"""Écrit contenus/missions.json (et la copie de l'app) : parcours d'anglais de 6e, unités 1 et 2.

Lancer depuis la racine du dépôt :  python3 pedagogie/outils/missions_6e.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]

DIFFICILE = [
    "Comprendre la scène|C'est normal au début. Tu as pu réécouter : c'est comme ça qu'on apprend.",
    "L'ordre des mots|En anglais, l'ordre des mots est important. Tu vas le revoir souvent.",
    "Écrire seul|Écrire seul, c'est le plus dur. Et tu l'as fait !",
    "Parler au micro|Parler fait un peu peur au début. Plus tu parles, plus c'est facile.",
    "Rien !|Super ! La prochaine mission sera un peu plus dure.",
]


def mot(m, ok, pourquoi):
    return {"mot": m, "ok": ok, "pourquoi": pourquoi}


def r(qui, en, fr):
    return {"qui": qui, "en": en, "fr": fr}


def q(question, options, reponse, rejouer=-1):
    return {"question": question, "options": options, "reponse": reponse, "rejouer": rejouer}


def aides(question, rejouer, texte_rejouer, modele, sens):
    return [question, {"rejouer": rejouer, "texte": texte_rejouer}, modele, sens]


def choix(gainde, options, reponse, a):
    return {"type": "choix", "gainde": gainde, "options": options, "reponse": reponse, "aides": a}


def ordre(gainde, tuiles, cible, dit, a):
    return {"type": "ordre", "gainde": gainde, "tuiles": tuiles, "cible": cible, "dit": dit, "aides": a}


def trou(gainde, avant, apres, accepte, dit, a):
    return {"type": "trou", "gainde": gainde, "avant": avant, "apres": apres, "accepte": accepte, "dit": dit, "aides": a}


def libre(gainde, cles, a):
    return {"type": "libre", "gainde": gainde, "cles": cles, "aides": a}


def tour(qui, en, fr, cles, modele, reponse):
    return {"qui": qui, "en": en, "fr": fr, "cles": cles, "modele": modele, "reponse": reponse}


def mission(id, titre, jesais, expressions, mots, scene, questions, marches, pourdevrai, carnet, histoire=""):
    return {
        "id": id, "titre": titre, "histoire": histoire or titre, "jesais": jesais, "expressions": expressions,
        "mots": mots, "scene": scene, "questions": questions, "marches": marches,
        "pourdevrai": pourdevrai, "carnet": carnet, "difficile": DIFFICILE,
    }


def ex(question, options, reponse, explication):
    return {"question": question, "options": options, "reponse": reponse, "explication": explication}


# ======================= UNITÉ 1 : HELLO! =======================

u1 = [
    mission(
        "6e-u1-m1", "Un lionceau dans la cour", "dire bonjour à un ami",
        ["Hello!", "Hi!", "How are you?", "I'm fine, thanks!"],
        {"consigne": "Quels mots vont avec l'image ?", "fond": "cour", "objets": ["🏫", "🌳", "⚽", "🎒"],
         "liste": [
             mot("school", True, "Oui ! « School », c'est l'école. On la voit derrière."),
             mot("tree", True, "Oui ! « Tree », c'est l'arbre de la cour."),
             mot("ball", True, "Oui ! « Ball », c'est le ballon."),
             mot("bag", True, "Oui ! « Bag », c'est le sac."),
             mot("girl", True, "Oui ! « Girl », c'est une fille. C'est Awa."),
             mot("fish", False, "« Fish », c'est le poisson. Il n'y a pas de poisson dans la cour. Regarde encore !"),
             mot("car", False, "« Car », c'est la voiture. Tu vois une voiture ? Non ! Regarde encore."),
             mot("bed", False, "« Bed », c'est le lit. On ne dort pas dans la cour ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Hello, Modou!", "Bonjour, Modou !"),
                       r("modou", "Hi, Awa! How are you?", "Salut, Awa ! Ça va ?"),
                       r("awa", "I'm fine, thanks!", "Ça va bien, merci !")],
         "gainde": "Hello ? Hi ? Ils disent quoi ? Moi aussi, je veux dire bonjour !"},
        [q("Comment Awa dit bonjour à Modou ?", ["Hello!", "Goodbye!", "Thank you!"], 0, 0),
         q("Modou demande « How are you? ». Ça veut dire…", ["Ça va ?", "Tu as quel âge ?", "Où vas-tu ?"], 0, 1)],
        [choix("Je veux dire bonjour à Awa. Je dis laquelle ?", ["Goodbye, Awa!", "Hi, Awa!"], 1,
               aides("Qu'est-ce que Modou a dit à Awa, au début ?", 1, "Écoute Modou :",
                     "Moi, je dis : « Hi, Gaïndé! »", "« Hi », c'est « Salut ». « Goodbye », c'est pour partir.")),
         ordre("« You are how? » C'est bien ça ?", ["are", "How", "you"], "How are you", "How are you?",
               aides("Quel mot Modou a-t-il dit en premier ?", 1, "Écoute l'ordre des mots :",
                     "Moi, je dis : « How are you? »", "En anglais : How (comment) + are + you (tu).")),
         trou("« I'm ___, thanks! » Il me manque un mot !", "I'm", ", thanks!", ["fine"], "I'm fine, thanks!",
              aides("Comment Awa a-t-elle répondu ?", 2, "Écoute Awa :",
                    "Moi, je dis : « I'm fine, thanks! »", "« Fine », c'est « bien ». Écris : fine.")),
         libre("Je veux dire bonjour à Modou. Comment je dis ?", ["hello|hi"],
               aides("Qu'est-ce qu'Awa a dit tout au début ?", 0, "Écoute le début :",
                     "Awa dit « Hello », Modou dit « Hi ».", "Écris « Hello, Modou! » ou « Hi, Modou! »."))],
        [tour("gainde", "Hello! How are you?", "Bonjour ! Ça va ?", ["fine|good|ok|great"], "I'm fine, thanks!",
              "Great! I'm fine too!"),
         tour("awa", "Hi! How are you today?", "Salut ! Ça va, aujourd'hui ?", ["fine|good|ok|great"],
              "I'm fine, thank you!", "Super! See you!")],
        ["Hello!", "Hi!", "How are you?", "I'm fine, thanks!"],
    ),
    mission(
        "6e-u1-m2", "Bonjour, Monsieur le Directeur !", "dire bonjour à un adulte",
        ["Good morning, Sir!", "Good afternoon, Madam!"],
        {"consigne": "C'est le matin. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["☀️", "📚", "🏫"],
         "liste": [
             mot("sun", True, "Oui ! « Sun », c'est le soleil du matin."),
             mot("books", True, "Oui ! « Books », ce sont les livres."),
             mot("school", True, "Oui ! « School », c'est l'école."),
             mot("teacher", True, "Oui ! « Teacher », c'est le prof. C'est Kocc Barma."),
             mot("moon", False, "« Moon », c'est la lune. On la voit la nuit, pas le matin. Regarde encore !"),
             mot("bed", False, "« Bed », c'est le lit. Il n'y a pas de lit à l'école ! Regarde encore."),
             mot("beach", False, "« Beach », c'est la plage. On est à l'école. Regarde encore !"),
         ]},
        {"fond": "classe", "persos": ["awa", "kocc", "gainde"],
         "repliques": [r("awa", "Good morning, Sir!", "Bonjour, Monsieur !"),
                       r("kocc", "Good morning, Awa! How are you?", "Bonjour, Awa ! Ça va ?"),
                       r("awa", "I'm fine, thank you, Sir.", "Ça va bien, merci, Monsieur.")],
         "gainde": "Awa ne dit pas « Hi » au prof ? Pourquoi ?"},
        [q("Awa dit bonjour au prof. Elle dit…", ["Hi, buddy!", "Good morning, Sir!", "Bye!"], 1, 0),
         q("« Sir », c'est pour parler à…", ["un homme adulte", "un ami", "un chat"], 0, 0)],
        [choix("C'est le matin. Je dis bonjour au directeur. Je dis laquelle ?", ["Hi, buddy!", "Good morning, Sir!"], 1,
               aides("Comment Awa parle-t-elle au prof ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Good morning, Sir! »", "À un adulte, on est poli : « Good morning ». « Hi, buddy », c'est pour un copain.")),
         ordre("« Morning good, Madam! » C'est ça ?", ["morning", "Madam", "Good"], "Good morning Madam",
               "Good morning, Madam!",
               aides("Quel mot vient en premier : « Good » ou « morning » ?", 0, "Écoute :",
                     "Moi, je dis : « Good morning, Madam! »", "On dit d'abord « Good », puis « morning ».")),
         trou("Il est 15 h. « Good ___, Sir! »", "Good", ", Sir!", ["afternoon"], "Good afternoon, Sir!",
              aides("Le matin, c'est « morning ». Et l'après-midi ?", -1, "",
                    "Moi, à 15 h, je dis : « Good afternoon! »", "« Afternoon », c'est l'après-midi. Écris : afternoon.")),
         libre("C'est le matin. Je dis bonjour à la directrice. Comment je dis ?", ["good morning", "madam|maam"],
               aides("Le matin, on dit « Good… » quoi ?", 0, "Écoute Awa :",
                     "Pour une femme, on dit « Madam ».", "Écris : « Good morning, Madam! »"))],
        [tour("kocc", "Good morning! How are you?", "Bonjour ! Ça va ?", ["good morning", "sir"],
              "Good morning, Sir! I'm fine, thank you.", "Very good! Thank you."),
         tour("kocc", "Good afternoon, class!", "Bonjour, la classe ! (l'après-midi)", ["good afternoon"],
              "Good afternoon, Sir!", "Well done!")],
        ["Good morning, Sir!", "Good afternoon, Madam!", "Thank you."],
    ),
    mission(
        "6e-u1-m3", "Gaïndé ne sait pas dire son nom", "dire mon nom, demander le nom d'un ami",
        ["My name is…", "What's your name?", "Nice to meet you!"],
        {"consigne": "Quels mots vont avec l'image ?", "fond": "cour", "objets": ["🏫"],
         "liste": [
             mot("girl", True, "Oui ! « Girl », c'est une fille. C'est Awa."),
             mot("boy", True, "Oui ! « Boy », c'est un garçon. C'est Modou."),
             mot("lion", True, "Oui ! « Lion », c'est Gaïndé."),
             mot("school", True, "Oui ! « School », c'est l'école."),
             mot("cat", False, "« Cat », c'est un chat. Gaïndé n'est pas un chat, c'est un lion ! Regarde encore."),
             mot("dog", False, "« Dog », c'est un chien. Tu vois un chien ? Non ! Regarde encore."),
             mot("fish", False, "« Fish », c'est le poisson. Il n'y en a pas ici. Regarde encore !"),
         ]},
        {"fond": "cour", "persos": ["awa", "gainde", "modou"],
         "repliques": [r("awa", "Hello! My name is Awa.", "Bonjour ! Je m'appelle Awa."),
                       r("modou", "Hi! My name is Modou.", "Salut ! Je m'appelle Modou."),
                       r("awa", "Nice to meet you, Modou!", "Enchantée, Modou !")],
         "gainde": "Ils disent quoi ?? Moi aussi, je veux dire mon nom…"},
        [q("Qu'est-ce qu'Awa dit juste avant son prénom ?", ["Nice to meet", "My name is", "Hello"], 1, 0),
         q("« Nice to meet you », ça veut dire…", ["Enchanté", "Au revoir", "Merci"], 0, 2)],
        [choix("J'hésite… Je dis laquelle ?", ["My name Gaïndé.", "My name is Gaïndé."], 1,
               aides("Awa a dit « My name… » et ensuite ? Il y a un petit mot avant le prénom.", 0, "Écoute encore Awa :",
                     "Moi, je dis : « My name is Kocc Barma. » Tu vois le petit mot « is » ?",
                     "En anglais, il faut « is » : My (mon) + name (nom) + is (est) + Gaïndé.")),
         ordre("« Name my is Gaïndé » ? C'est bien ça ?", ["name", "is", "My", "Gaïndé"], "My name is Gaïndé",
               "My name is Gaïndé.",
               aides("Quel mot Awa dit-elle en premier, juste après « Hello » ?", 0, "Écoute l'ordre des mots :",
                     "Moi, je dis : « My name is Kocc Barma. » Et Gaïndé ?",
                     "En wolof, on dit « Maa ngi tudd Gaïndé ». En anglais : My + name + is + Gaïndé.")),
         trou("« Hello! My ___ is Gaïndé. » Il me manque un mot !", "Hello! My", "is Gaïndé.", ["name"],
              "Hello! My name is Gaïndé.",
              aides("Quel mot veut dire « nom » dans la phrase de Modou ?", 1, "Écoute Modou :",
                    "Moi, je dis : « My name is Kocc Barma. » Le mot qui manque est entre « My » et « is ».",
                    "« Nom » se dit « name ». Écris : name.")),
         libre("Je veux demander son nom à Awa. Comment je dis ?", ["whats your name|what is your name|your name"],
               aides("On n'a pas encore entendu la question. Kocc Barma va t'aider.", -1, "",
                     "Pour demander le nom : « What's your name? »", "Écris : « What's your name? »"))],
        [tour("gainde", "Thank you! And you? What's your name?", "Merci ! Et toi ? Comment tu t'appelles ?",
              ["my name is|im|i am"], "My name is …", "Nice to meet you!"),
         tour("awa", "Hello! My name is Awa. What's your name?", "Bonjour ! Je m'appelle Awa. Comment tu t'appelles ?",
              ["my name is|im|i am"], "My name is …", "Nice to meet you!")],
        ["My name is…", "What's your name?", "Nice to meet you!"],
    ),
    mission(
        "6e-u1-m4", "Ça s'écrit comment ?", "épeler un mot",
        ["How do you spell it?", "M-O-D-O-U."],
        {"consigne": "En classe. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["🔤", "✏️", "📒"],
         "liste": [
             mot("letters", True, "Oui ! « Letters », ce sont les lettres : A, B, C…"),
             mot("pencil", True, "Oui ! « Pencil », c'est le crayon."),
             mot("book", True, "Oui ! « Book », c'est le cahier ou le livre."),
             mot("teacher", True, "Oui ! « Teacher », c'est le prof, Kocc Barma."),
             mot("banana", False, "« Banana », c'est la banane. On ne mange pas en classe ! Regarde encore."),
             mot("sea", False, "« Sea », c'est la mer. On est en classe. Regarde encore !"),
         ]},
        {"fond": "classe", "persos": ["kocc", "modou", "gainde"],
         "repliques": [r("kocc", "What's your name?", "Comment tu t'appelles ?"),
                       r("modou", "My name is Modou.", "Je m'appelle Modou."),
                       r("kocc", "How do you spell it?", "Ça s'écrit comment ?"),
                       r("modou", "M-O-D-O-U.", "M-O-D-O-U.")],
         "gainde": "Il dit des lettres ! Moi aussi, je veux épeler mon nom !"},
        [q("Que demande Kocc Barma à la fin ?", ["Ça s'écrit comment ?", "Tu as quel âge ?", "Où est ton sac ?"], 0, 2),
         q("Comment Modou épelle son nom ?", ["M-O-D-O-U", "M-A-D-O-U", "N-O-D-O-U"], 0, 3)],
        [choix("On me demande d'épeler mon nom. Je dis laquelle ?", ["G-A-I-N-D-E.", "Gaïndé is my name."], 0,
               aides("Comment Modou a-t-il répondu ?", 3, "Écoute Modou :",
                     "Moi, j'épelle : K-O-C-C.", "Épeler, c'est dire les lettres une par une.")),
         ordre("« Spell you do how it? » C'est ça ?", ["How", "spell", "do", "it", "you"], "How do you spell it",
               "How do you spell it?",
               aides("Quel mot vient en premier dans la question de Kocc Barma ?", 2, "Écoute la question :",
                     "Moi, je demande : « How do you spell it? »", "How (comment) + do you spell (épelles-tu) + it (ça).")),
         trou("« How do you ___ it? » Il me manque un mot !", "How do you", "it?", ["spell"], "How do you spell it?",
              aides("Quel mot veut dire « épeler » ?", 2, "Écoute Kocc Barma :",
                    "« How do you spell it? »", "« Épeler », c'est « spell ». Écris : spell.")),
         libre("Épelle le nom « AWA » pour moi, lettre par lettre.", ["a w a|awa"],
               aides("Quelles sont les lettres du nom Awa ?", -1, "",
                     "Je commence : A…", "Écris : A-W-A."))],
        [tour("kocc", "What's your name? How do you spell it?", "Comment tu t'appelles ? Ça s'écrit comment ?",
              [], "F-A-T-O-U.", "Thank you! Very good!")],
        ["How do you spell it?", "A, B, C… Z", "letter"],
    ),
    mission(
        "6e-u1-m5", "Tu as quel âge ?", "dire mon âge",
        ["How old are you?", "I'm eleven."],
        {"consigne": "C'est la fête d'Awa. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🎂", "🎈", "🎁", "🕯️"],
         "liste": [
             mot("cake", True, "Oui ! « Cake », c'est le gâteau."),
             mot("balloons", True, "Oui ! « Balloons », ce sont les ballons."),
             mot("present", True, "Oui ! « Present », c'est le cadeau."),
             mot("candles", True, "Oui ! « Candles », ce sont les bougies."),
             mot("fish", False, "« Fish », c'est le poisson. Il n'y a pas de poisson à la fête d'Awa. Regarde encore !"),
             mot("rain", False, "« Rain », c'est la pluie. Il ne pleut pas. Regarde encore !"),
             mot("car", False, "« Car », c'est la voiture. Tu vois une voiture ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "How old are you, Awa?", "Tu as quel âge, Awa ?"),
                       r("awa", "I'm eleven today!", "J'ai onze ans aujourd'hui !"),
                       r("modou", "Happy birthday! I'm twelve.", "Joyeux anniversaire ! Moi, j'ai douze ans.")],
         "gainde": "Onze quoi ? Onze gâteaux ? Moi aussi, je veux dire mon âge !"},
        [q("Que demande Modou ?", ["Tu as quel âge ?", "Comment tu t'appelles ?", "Ça va ?"], 0, 0),
         q("Awa a quel âge ?", ["10 ans", "11 ans", "12 ans"], 1, 1)],
        [choix("Awa m'a demandé mon âge ! Je dis laquelle ?", ["I have eleven years.", "I'm eleven."], 1,
               aides("Comment Awa dit-elle son âge ?", 1, "En français, on dit « J'ai 11 ans ». En anglais, c'est différent. Écoute Awa :",
                     "Moi, je dis : « I'm thirty. »", "En anglais, on « est » son âge : I'm (je suis) + eleven.")),
         ordre("« Old how you are? » C'est bien ça ?", ["old", "are", "How", "you"], "How old are you",
               "How old are you?",
               aides("Quel mot Modou dit-il en premier ?", 0, "Écoute Modou :",
                     "Moi, je demande : « How old are you? »", "How old (quel âge) + are you (tu as).")),
         trou("J'ai 10 ans. « I'm ___. »", "I'm", ".", ["ten", "10"], "I'm ten.",
              aides("Comment dit-on 10 en anglais ?", -1, "",
                    "One, two, three… nine, ten !", "10, c'est « ten ». Écris : ten.")),
         libre("Dis à Awa que tu as 12 ans.", ["im|i am", "twelve|12"],
               aides("Comment Modou a-t-il dit qu'il a 12 ans ?", 2, "Écoute Modou :",
                     "Modou dit : « I'm twelve. »", "Écris : « I'm twelve. »"))],
        [tour("gainde", "Thank you! And you? How old are you?", "Merci ! Et toi ? Tu as quel âge ?",
              ["im|i am|years"], "I'm eleven.", "Wow! Thank you!")],
        ["How old are you?", "I'm eleven.", "Happy birthday!", "one… twenty"],
    ),
    mission(
        "6e-u1-m6", "Tu es élève ?", "répondre par oui ou par non",
        ["Are you a pupil?", "Yes, I am.", "No, I'm not."],
        {"consigne": "Quels mots vont avec l'image ?", "fond": "classe", "objets": ["🎒", "📚", "🏫"],
         "liste": [
             mot("pupil", True, "Oui ! « Pupil », c'est un élève, comme Modou."),
             mot("teacher", True, "Oui ! « Teacher », c'est le prof, Kocc Barma."),
             mot("bag", True, "Oui ! « Bag », c'est le sac."),
             mot("books", True, "Oui ! « Books », ce sont les livres."),
             mot("doctor", False, "« Doctor », c'est le médecin. Il n'y a pas de médecin ici. Regarde encore !"),
             mot("plane", False, "« Plane », c'est l'avion. On est en classe ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["kocc", "modou", "gainde"],
         "repliques": [r("kocc", "Are you a pupil, Modou?", "Tu es élève, Modou ?"),
                       r("modou", "Yes, I am!", "Oui !"),
                       r("kocc", "Are you a teacher?", "Tu es prof ?"),
                       r("modou", "No, I'm not! Ha ha!", "Non ! Ha ha !")],
         "gainde": "Yes… No… Comment on répond, déjà ?"},
        [q("Modou est élève. Il répond…", ["Yes, I am.", "No, I'm not."], 0, 1),
         q("Modou est prof ?", ["Oui", "Non"], 1, 3)],
        [choix("« Are you a lion? » Je réponds quoi ?", ["Yes, I am!", "No, I'm not!"], 0,
               aides("Gaïndé est un lion ? Oui ou non ?", 1, "Pour dire oui, écoute Modou :",
                     "Moi : « Are you a teacher? » — « Yes, I am! »", "Gaïndé est un lion, donc : « Yes, I am! »")),
         ordre("« Am I yes. » C'est ça ?", ["I", "am", "Yes"], "Yes I am", "Yes, I am.",
               aides("Quel mot vient en premier : « Yes » ?", 1, "Écoute Modou :",
                     "« Yes, I am. »", "Yes (oui) + I am (je suis).")),
         trou("« Are you a teacher? » — « No, I'm ___! »", "No, I'm", "!", ["not"], "No, I'm not!",
              aides("Comment Modou dit-il non ?", 3, "Écoute Modou :",
                    "« No, I'm not! »", "« Not », c'est « pas ». Écris : not.")),
         libre("« Are you a fish? » Je réponds quoi ?", ["no"],
               aides("Gaïndé est un poisson ?", 3, "Pour dire non, écoute Modou :",
                     "« No, I'm not! »", "Écris : « No, I'm not! »"))],
        [tour("modou", "Are you a pupil?", "Tu es élève ?", ["yes"], "Yes, I am!", "Me too!"),
         tour("awa", "Are you a lion?", "Tu es un lion ?", ["no"], "No, I'm not!", "Ha ha! Gaïndé is a lion!")],
        ["Are you a pupil?", "Yes, I am.", "No, I'm not."],
    ),
    mission(
        "6e-u1-m7", "Au revoir, Gaïndé !", "dire au revoir",
        ["Goodbye!", "Bye!", "See you tomorrow!"],
        {"consigne": "C'est la fin de la journée. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🌇", "🚌", "🎒"],
         "liste": [
             mot("bus", True, "Oui ! « Bus », c'est le car pour rentrer."),
             mot("bag", True, "Oui ! « Bag », c'est le sac."),
             mot("boy", True, "Oui ! « Boy », c'est Modou."),
             mot("girl", True, "Oui ! « Girl », c'est Awa."),
             mot("bed", False, "« Bed », c'est le lit. On n'est pas encore à la maison ! Regarde encore."),
             mot("snow", False, "« Snow », c'est la neige. Il ne neige pas à Dakar ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Goodbye, Modou!", "Au revoir, Modou !"),
                       r("modou", "Bye, Awa! See you tomorrow!", "Salut, Awa ! À demain !"),
                       r("awa", "See you!", "À plus !")],
         "gainde": "Ils partent ? Comment on dit au revoir ?"},
        [q("Comment Awa dit au revoir ?", ["Goodbye!", "Hello!", "Thank you!"], 0, 0),
         q("« See you tomorrow » veut dire…", ["À demain", "Bonne nuit", "Bon appétit"], 0, 1)],
        [choix("Awa part. Je lui dis laquelle ?", ["Hello, Awa!", "Goodbye, Awa!"], 1,
               aides("Qu'est-ce qu'Awa a dit à Modou en partant ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Goodbye, Gaïndé! »", "« Hello », c'est pour arriver. « Goodbye », c'est pour partir.")),
         ordre("« Tomorrow you see! » C'est ça ?", ["you", "tomorrow", "See"], "See you tomorrow",
               "See you tomorrow!",
               aides("Quel mot Modou dit-il en premier ?", 1, "Écoute Modou :",
                     "« See you tomorrow! »", "See you (on se voit) + tomorrow (demain).")),
         trou("« Good___! » Il me manque la fin du mot !", "Good", "!", ["bye"], "Goodbye!",
              aides("Comment Awa dit-elle au revoir ?", 0, "Écoute Awa :",
                    "« Goodbye! »", "Il manque « bye ». Écris : bye.")),
         libre("Dis au revoir à Modou.", ["bye|goodbye|see you"],
               aides("Qu'est-ce qu'on dit quand on part ?", 1, "Écoute Modou :",
                     "« Bye, Modou! See you tomorrow! »", "Écris : « Goodbye, Modou! »"))],
        [tour("modou", "Goodbye! See you tomorrow!", "Au revoir ! À demain !", ["bye|goodbye|see you"],
              "Bye! See you tomorrow!", "See you!")],
        ["Goodbye!", "Bye!", "See you tomorrow!"],
    ),
]

unite1 = {
    "id": "6e-u1", "titre": "Hello!",
    "production": "Ma carte de présentation : dis bonjour, ton nom et ton âge.",
    "missions": u1,
    "revision": {
        "lignes": [
            {"fonction": "Dire bonjour", "en": "Hello! · Hi! · How are you? — I'm fine, thanks."},
            {"fonction": "Bonjour à un adulte", "en": "Good morning, Sir! · Good afternoon, Madam!"},
            {"fonction": "Dire mon nom", "en": "My name is… · What's your name?"},
            {"fonction": "Épeler", "en": "How do you spell it? — A-W-A."},
            {"fonction": "Dire mon âge", "en": "How old are you? — I'm eleven."},
            {"fonction": "Oui ou non", "en": "Are you a pupil? — Yes, I am. / No, I'm not."},
            {"fonction": "Dire au revoir", "en": "Goodbye! · Bye! · See you tomorrow!"},
        ],
        "mots": [
            {"en": "Hello", "fr": "Bonjour", "wo": "Salaamaalekum"},
            {"en": "Goodbye", "fr": "Au revoir", "wo": "Ba beneen"},
            {"en": "friend", "fr": "ami(e)", "wo": "xarit"},
            {"en": "name", "fr": "nom", "wo": "tur"},
            {"en": "eleven", "fr": "onze", "wo": "fukk ak benn"},
            {"en": "pupil", "fr": "élève", "wo": "ndongo"},
            {"en": "teacher", "fr": "prof", "wo": "jàngalekat"},
            {"en": "yes", "fr": "oui", "wo": "waaw"},
            {"en": "no", "fr": "non", "wo": "déedéet"},
        ],
        "pieges": [
            "I'm eleven. Pas « I have eleven years ».",
            "Good night = bonne nuit, pas bonsoir.",
            "Au prof, on dit « Good morning, Sir! », pas « Hi, buddy! ».",
        ],
    },
    "exercices": [
        ex("Il est 8 h. Tu vois le directeur. Tu dis : « Good ______, Sir! »", ["night", "morning", "evening", "bye"], 1,
           "Le matin : Good morning. Pour aller dormir : Good night."),
        ex("Ton ami te dit « How are you? ». Tu réponds :", ["I'm fine, thanks!", "My name is Awa.", "Goodbye!", "I'm eleven."], 0,
           "« How are you? » veut dire « Ça va ? ». On répond « I'm fine, thanks! »."),
        ex("Comment demander son nom à quelqu'un ?", ["How old are you?", "What's your name?", "How are you?", "Are you a pupil?"], 1,
           "« What's your name? » veut dire « Comment tu t'appelles ? »."),
        ex("Complète : « My ____ is Modou. »", ["name", "is", "am", "old"], 0, "My name is Modou = Je m'appelle Modou."),
        ex("Tu as 11 ans. Tu dis :", ["I have eleven years.", "I'm eleven.", "I eleven.", "My eleven."], 1,
           "En anglais, on dit « I'm eleven » : je « suis » onze."),
        ex("« How do you spell it? » veut dire :", ["Ça s'écrit comment ?", "Ça va ?", "Tu as quel âge ?", "Où est-il ?"], 0,
           "« Spell », c'est épeler. On répond lettre par lettre."),
        ex("« Are you a pupil? » Tu es élève. Tu réponds :", ["No, I'm not.", "Yes, I am.", "Yes, I'm not.", "No, I am."], 1,
           "Pour dire oui : « Yes, I am. »"),
        ex("Il est 15 h. Tu dis bonjour à la prof :", ["Good morning, Madam!", "Good afternoon, Madam!", "Good night, Madam!", "Hi, buddy!"], 1,
           "L'après-midi : Good afternoon."),
        ex("Tu pars. Tu dis :", ["Hello!", "Goodbye!", "Thank you!", "How are you?"], 1, "Pour partir : Goodbye! ou Bye!"),
        ex("« See you tomorrow! » veut dire :", ["À demain !", "Bonne nuit !", "Merci !", "Enchanté !"], 0,
           "Tomorrow, c'est demain."),
    ],
}

# ======================= UNITÉ 2 : MY CLASSROOM =======================

u2 = [
    mission(
        "6e-u2-m1", "C'est quoi, ce truc ?", "dire le nom des objets de la classe",
        ["What's this?", "It's a pen.", "It's a ruler."],
        {"consigne": "Dans la classe. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["✏️", "📏", "📕", "🎒"],
         "liste": [
             mot("pencil", True, "Oui ! « Pencil », c'est le crayon."),
             mot("ruler", True, "Oui ! « Ruler », c'est la règle."),
             mot("book", True, "Oui ! « Book », c'est le livre."),
             mot("bag", True, "Oui ! « Bag », c'est le sac."),
             mot("goat", False, "« Goat », c'est la chèvre. Pas de chèvre en classe ! Regarde encore."),
             mot("cup", False, "« Cup », c'est la tasse. Tu vois une tasse ? Non. Regarde encore !"),
         ]},
        {"fond": "classe", "persos": ["kocc", "awa", "gainde"],
         "repliques": [r("kocc", "What's this?", "Qu'est-ce que c'est ?"),
                       r("awa", "It's a pen.", "C'est un stylo."),
                       r("kocc", "And what's this?", "Et ça, qu'est-ce que c'est ?"),
                       r("awa", "It's a ruler.", "C'est une règle.")],
         "gainde": "Un pen, une ruler… Moi, je veux tout nommer !"},
        [q("Que demande Kocc Barma ?", ["Qu'est-ce que c'est ?", "Où est-il ?", "Tu as quel âge ?"], 0, 0),
         q("« It's a ruler » veut dire…", ["C'est une règle.", "C'est un stylo.", "C'est un sac."], 0, 3)],
        [choix("Kocc Barma montre un stylo. Je dis laquelle ?", ["It's a pen.", "It's a ruler."], 0,
               aides("Comment Awa appelle-t-elle le stylo ?", 1, "Écoute Awa :",
                     "« It's a pen. »", "« Pen », c'est le stylo. « Ruler », c'est la règle.")),
         ordre("« This what's? » C'est ça ?", ["this", "What's"], "Whats this", "What's this?",
               aides("Quel mot vient en premier dans la question ?", 0, "Écoute Kocc Barma :",
                     "« What's this? »", "What's (qu'est-ce que) + this (c'est).")),
         trou("« It's a ___. » (une règle)", "It's a", ".", ["ruler"], "It's a ruler.",
              aides("Comment dit-on « règle » ?", 3, "Écoute Awa :",
                    "« It's a ruler. »", "Règle = ruler. Écris : ruler.")),
         libre("Je montre un livre. Qu'est-ce que c'est ?", ["book"],
               aides("Comment dit-on « livre » ?", -1, "",
                     "« It's a … » + le mot.", "Écris : « It's a book. »"))],
        [tour("kocc", "What's this? (un crayon)", "Qu'est-ce que c'est ? (un crayon)", ["pencil"],
              "It's a pencil.", "Yes! Very good!")],
        ["What's this?", "It's a pen.", "ruler", "pencil", "book", "bag"],
    ),
    mission(
        "6e-u2-m2", "Le monde en couleurs", "dire la couleur d'un objet",
        ["What colour is it?", "It's red."],
        {"consigne": "Quels mots vont avec l'image ?", "fond": "classe", "objets": ["🔴", "🔵", "🟡", "🟢"],
         "liste": [
             mot("red", True, "Oui ! « Red », c'est rouge."),
             mot("blue", True, "Oui ! « Blue », c'est bleu."),
             mot("yellow", True, "Oui ! « Yellow », c'est jaune."),
             mot("green", True, "Oui ! « Green », c'est vert."),
             mot("pink", False, "« Pink », c'est rose. Tu vois du rose ? Non ! Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. Ce n'est pas une couleur ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "What colour is it?", "C'est de quelle couleur ?"),
                       r("awa", "It's red.", "C'est rouge."),
                       r("modou", "And this bag?", "Et ce sac ?"),
                       r("awa", "It's blue.", "Il est bleu.")],
         "gainde": "Rouge, bleu… Et moi, je suis de quelle couleur ?"},
        [q("Que demande Modou ?", ["C'est de quelle couleur ?", "C'est à qui ?", "Où est-il ?"], 0, 0),
         q("Le sac est…", ["rouge", "bleu", "vert"], 1, 3)],
        [choix("Le stylo est rouge. Je dis laquelle ?", ["It's red.", "It's green."], 0,
               aides("Comment dit-on « rouge » ?", 1, "Écoute Awa :",
                     "« It's red. »", "Red = rouge. Green = vert.")),
         ordre("« Colour what is it? » C'est ça ?", ["is", "What", "it", "colour"], "What colour is it",
               "What colour is it?",
               aides("Quel mot vient en premier ?", 0, "Écoute Modou :",
                     "« What colour is it? »", "What colour (quelle couleur) + is it (est-ce).")),
         trou("Le sac est jaune. « It's ___. »", "It's", ".", ["yellow"], "It's yellow.",
              aides("Comment dit-on « jaune » ?", -1, "",
                    "Red, blue, yellow, green…", "Jaune = yellow. Écris : yellow.")),
         libre("Le tableau est vert. Dis-le !", ["green"],
               aides("Comment dit-on « vert » ?", -1, "",
                     "« It's … »", "Écris : « It's green. »"))],
        [tour("modou", "What colour is your bag?", "Ton sac est de quelle couleur ?",
              ["red|blue|yellow|green|black|white|pink|brown|orange"], "It's blue.", "Cool!")],
        ["What colour is it?", "red", "blue", "yellow", "green"],
    ),
    mission(
        "6e-u2-m3", "Le sac d'Awa", "dire à qui est un objet",
        ["Whose bag is it?", "It's Awa's bag."],
        {"consigne": "Quels mots vont avec l'image ?", "fond": "classe", "objets": ["🎒", "👜", "📕"],
         "liste": [
             mot("bag", True, "Oui ! « Bag », c'est le sac."),
             mot("book", True, "Oui ! « Book », c'est le livre."),
             mot("girl", True, "Oui ! « Girl », c'est Awa."),
             mot("boy", True, "Oui ! « Boy », c'est Modou."),
             mot("horse", False, "« Horse », c'est le cheval. Pas de cheval en classe ! Regarde encore."),
             mot("sea", False, "« Sea », c'est la mer. Regarde encore !"),
         ]},
        {"fond": "classe", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Whose bag is it?", "C'est le sac de qui ?"),
                       r("awa", "It's my bag!", "C'est mon sac !"),
                       r("modou", "And this book?", "Et ce livre ?"),
                       r("awa", "It's Modou's book.", "C'est le livre de Modou.")],
         "gainde": "Le sac d'Awa… le livre de Modou… Et mon sac à moi ?"},
        [q("Que demande Modou ?", ["C'est le sac de qui ?", "C'est quoi ?", "Il est où ?"], 0, 0),
         q("Le livre est à…", ["Awa", "Modou", "Gaïndé"], 1, 3)],
        [choix("C'est le sac d'Awa. Je dis laquelle ?", ["It's Awa bag.", "It's Awa's bag."], 1,
               aides("Écoute bien : Modou's book. Il y a un petit « s ».", 3, "Écoute Awa :",
                     "« It's Modou's book. »", "Pour dire « de quelqu'un » : le nom + 's. Awa's bag = le sac d'Awa.")),
         ordre("« Bag whose is it? » C'est ça ?", ["is", "bag", "Whose", "it"], "Whose bag is it",
               "Whose bag is it?",
               aides("Quel mot vient en premier ?", 0, "Écoute Modou :",
                     "« Whose bag is it? »", "Whose (à qui) + bag + is it.")),
         trou("C'est le livre de Modou : « It's ___ book. »", "It's", "book.", ["modous", "modou s"], "It's Modou's book.",
              aides("Comment Awa le dit-elle ?", 3, "Écoute Awa :",
                    "« It's Modou's book. »", "Écris : Modou's (avec 's).")),
         libre("C'est la règle de Gaïndé. Dis-le !", ["gaindes|gainde s", "ruler"],
               aides("On met « 's » après le nom.", -1, "",
                     "« It's Awa's bag. »", "Écris : « It's Gaïndé's ruler. »"))],
        [tour("modou", "Whose pen is it? (le stylo d'Awa)", "C'est le stylo de qui ? (d'Awa)", ["awas|awa s"],
              "It's Awa's pen.", "Thank you!")],
        ["Whose bag is it?", "It's Awa's bag.", "It's my bag."],
    ),
    mission(
        "6e-u2-m4", "Une ombre dans la bibliothèque", "dire où se trouve un objet",
        ["Where is the book?", "It's on the table.", "It's under the chair."],
        {"consigne": "À la bibliothèque. Quels mots vont avec l'image ?", "fond": "bibliotheque",
         "objets": ["📚", "🪑", "🔦"],
         "liste": [
             mot("books", True, "Oui ! « Books », ce sont les livres."),
             mot("chair", True, "Oui ! « Chair », c'est la chaise."),
             mot("table", True, "Oui ! « Table », c'est la table."),
             mot("lamp", True, "Oui ! « Lamp », c'est la lampe."),
             mot("ball", False, "« Ball », c'est le ballon. On ne joue pas à la bibliothèque ! Regarde encore."),
             mot("tree", False, "« Tree », c'est l'arbre. On est dedans ! Regarde encore."),
         ]},
        {"fond": "bibliotheque", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Where is my book?", "Où est mon livre ?"),
                       r("modou", "It's on the table.", "Il est sur la table."),
                       r("awa", "And my pen?", "Et mon stylo ?"),
                       r("modou", "It's under the chair.", "Il est sous la chaise.")],
         "gainde": "Sur, sous… Où est passé mon goûter ?"},
        [q("Le livre est…", ["sur la table", "sous la chaise", "dans le sac"], 0, 1),
         q("Le stylo est…", ["sur la table", "sous la chaise", "dans le sac"], 1, 3)],
        [choix("Le livre est sur la table. Je dis laquelle ?", ["It's on the table.", "It's under the table."], 0,
               aides("« Sur », c'est « on » ou « under » ?", 1, "Écoute Modou :",
                     "« It's on the table. »", "On = sur. Under = sous.")),
         ordre("« Is where the bag? » C'est ça ?", ["the", "is", "Where", "bag"], "Where is the bag",
               "Where is the bag?",
               aides("Quel mot vient en premier ?", 0, "Écoute Awa :",
                     "« Where is the bag? »", "Where (où) + is + the bag.")),
         trou("Le stylo est sous la chaise : « It's ___ the chair. »", "It's", "the chair.", ["under"],
              "It's under the chair.",
              aides("Comment dit-on « sous » ?", 3, "Écoute Modou :",
                    "« It's under the chair. »", "Sous = under. Écris : under.")),
         libre("Le sac est dans la classe. Dis « Il est dans la classe. »", ["in", "classroom|class"],
               aides("« Dans », c'est « in ».", -1, "",
                     "« It's in the … »", "Écris : « It's in the classroom. »"))],
        [tour("awa", "Where is your bag?", "Où est ton sac ?", ["on|in|under|next to|behind"],
              "It's on the chair.", "Thank you!")],
        ["Where is…?", "on", "in", "under", "next to"],
    ),
    mission(
        "6e-u2-m5", "Gaïndé, chef de classe", "comprendre ce que le prof demande",
        ["Stand up!", "Sit down!", "Open your book!"],
        {"consigne": "Quels mots vont avec l'image ?", "fond": "classe", "objets": ["📖", "🪑", "🧑‍🏫"],
         "liste": [
             mot("book", True, "Oui ! « Book », c'est le livre."),
             mot("chair", True, "Oui ! « Chair », c'est la chaise."),
             mot("teacher", True, "Oui ! « Teacher », c'est le prof."),
             mot("board", True, "Oui ! « Board », c'est le tableau."),
             mot("kitchen", False, "« Kitchen », c'est la cuisine. On est en classe ! Regarde encore."),
             mot("moon", False, "« Moon », c'est la lune. Regarde encore !"),
         ]},
        {"fond": "classe", "persos": ["kocc", "modou", "gainde"],
         "repliques": [r("kocc", "Good morning! Stand up, please.", "Bonjour ! Levez-vous, s'il vous plaît."),
                       r("kocc", "Sit down.", "Asseyez-vous."),
                       r("kocc", "Open your book!", "Ouvrez votre livre !")],
         "gainde": "Debout ! Assis ! Debout ! C'est un jeu ?"},
        [q("« Stand up » veut dire…", ["Levez-vous", "Asseyez-vous", "Écrivez"], 0, 0),
         q("« Open your book » veut dire…", ["Fermez votre livre", "Ouvrez votre livre", "Lisez"], 1, 2)],
        [choix("Je veux que la classe s'assoie. Je dis laquelle ?", ["Stand up!", "Sit down!"], 1,
               aides("Qu'a dit Kocc Barma après « Stand up » ?", 1, "Écoute Kocc Barma :",
                     "« Sit down. »", "Stand up = levez-vous. Sit down = asseyez-vous.")),
         ordre("« Book your open! » C'est ça ?", ["your", "Open", "book"], "Open your book", "Open your book!",
               aides("Quel mot vient en premier ?", 2, "Écoute Kocc Barma :",
                     "« Open your book! »", "Open (ouvrez) + your book (votre livre).")),
         trou("« ___ up, please! » (levez-vous)", "", "up, please!", ["stand"], "Stand up, please!",
              aides("Comment dit-on « levez-vous » ?", 0, "Écoute Kocc Barma :",
                    "« Stand up, please. »", "Écris : stand.")),
         libre("Demande à la classe de s'asseoir, poliment.", ["sit down"],
               aides("Comment dit-on « asseyez-vous » ?", 1, "Écoute :",
                     "« Sit down, please. »", "Écris : « Sit down, please! »"))],
        [tour("kocc", "Gaïndé, you are the class leader! Say: stand up!", "Gaïndé, tu es chef de classe ! Dis : levez-vous !",
              ["stand up"], "Stand up, please!", "Very good, class leader!")],
        ["Stand up!", "Sit down!", "Open your book!", "please"],
    ),
    mission(
        "6e-u2-m6", "Qui est le premier ?", "dire premier, deuxième, troisième…",
        ["I'm the first!", "the second", "the third"],
        {"consigne": "La course dans la cour. Quels mots vont avec l'image ?", "fond": "cour", "objets": ["🥇", "🥈", "🥉"],
         "liste": [
             mot("first", True, "Oui ! « First », c'est premier."),
             mot("second", True, "Oui ! « Second », c'est deuxième."),
             mot("third", True, "Oui ! « Third », c'est troisième."),
             mot("run", True, "Oui ! « Run », c'est courir."),
             mot("sleep", False, "« Sleep », c'est dormir. Personne ne dort ici ! Regarde encore."),
             mot("rain", False, "« Rain », c'est la pluie. Il fait beau ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "I'm the first!", "Je suis la première !"),
                       r("modou", "I'm the second.", "Je suis le deuxième."),
                       r("awa", "Gaïndé, you are the third!", "Gaïndé, tu es le troisième !")],
         "gainde": "Troisième ? Mais je suis un lion ! Je veux être premier !"},
        [q("Qui est la première ?", ["Awa", "Modou", "Gaïndé"], 0, 0),
         q("« The second » veut dire…", ["le premier", "le deuxième", "le dernier"], 1, 1)],
        [choix("Je suis arrivé premier ! Je dis laquelle ?", ["I'm the first!", "I'm the third!"], 0,
               aides("Comment Awa dit-elle qu'elle est première ?", 0, "Écoute Awa :",
                     "« I'm the first! »", "First = premier. Third = troisième.")),
         ordre("« Second the I'm. » C'est ça ?", ["the", "second", "I'm"], "Im the second", "I'm the second.",
               aides("Quel mot vient en premier ?", 1, "Écoute Modou :",
                     "« I'm the second. »", "I'm (je suis) + the second (le deuxième).")),
         trou("Je suis troisième : « I'm the ___. »", "I'm the", ".", ["third"], "I'm the third.",
              aides("Comment dit-on « troisième » ?", 2, "Écoute Awa :",
                    "« You are the third! »", "Troisième = third. Écris : third.")),
         libre("Dis que tu es le deuxième.", ["second"],
               aides("Comment dit-on « deuxième » ?", 1, "Écoute Modou :",
                     "« I'm the second. »", "Écris : « I'm the second. »"))],
        [tour("modou", "Who is the first?", "Qui est le premier ?", ["first"], "I'm the first!", "Bravo!")],
        ["the first", "the second", "the third", "the tenth"],
    ),
]

unite2 = {
    "id": "6e-u2", "titre": "My classroom",
    "production": "Ma classe : décris 5 objets de ta classe (nom, couleur, place).",
    "missions": u2,
    "revision": {
        "lignes": [
            {"fonction": "Nommer un objet", "en": "What's this? — It's a pen."},
            {"fonction": "Dire la couleur", "en": "What colour is it? — It's red."},
            {"fonction": "Dire à qui", "en": "Whose bag is it? — It's Awa's bag."},
            {"fonction": "Dire où", "en": "Where is the book? — It's on / in / under the table."},
            {"fonction": "Les consignes", "en": "Stand up! · Sit down! · Open your book!"},
            {"fonction": "Le rang", "en": "the first · the second · the third"},
        ],
        "mots": [
            {"en": "pen", "fr": "stylo", "wo": "bindukaay"},
            {"en": "book", "fr": "livre", "wo": "téere"},
            {"en": "table", "fr": "table", "wo": "taabal"},
            {"en": "chair", "fr": "chaise", "wo": "siis"},
            {"en": "red", "fr": "rouge", "wo": "xonq"},
            {"en": "white", "fr": "blanc", "wo": "weex"},
            {"en": "black", "fr": "noir", "wo": "ñuul"},
        ],
        "pieges": [
            "Awa's bag (avec 's), pas « Awa bag ».",
            "On = sur, under = sous.",
            "What colour is it? Pas « What colour it is? ».",
        ],
    },
    "exercices": [
        ex("Qu'est-ce que c'est ? (une règle)", ["It's a pen.", "It's a ruler.", "It's a bag.", "It's a book."], 1, "Ruler = règle."),
        ex("Le sac est bleu. Tu dis :", ["It's red.", "It's blue.", "It's green.", "It's yellow."], 1, "Blue = bleu."),
        ex("C'est le livre de Modou :", ["It's Modou book.", "It's Modou's book.", "It's book Modou.", "It's of Modou book."], 1,
           "Pour dire « de quelqu'un » : nom + 's."),
        ex("Le livre est sur la table :", ["It's under the table.", "It's on the table.", "It's in the table.", "It's next the table."], 1,
           "On = sur."),
        ex("Le stylo est sous la chaise :", ["It's on the chair.", "It's under the chair.", "It's in the chair.", "It's the chair."], 1,
           "Under = sous."),
        ex("« Sit down! » veut dire :", ["Levez-vous !", "Asseyez-vous !", "Ouvrez !", "Écoutez !"], 1, "Sit down = asseyez-vous."),
        ex("Complète : « What ____ is it? » (la couleur)", ["colour", "name", "old", "time"], 0, "What colour is it? = c'est de quelle couleur ?"),
        ex("Tu arrives premier :", ["I'm the second.", "I'm the first.", "I'm the third.", "I'm one."], 1, "First = premier."),
        ex("« Open your book! » veut dire :", ["Fermez votre livre !", "Ouvrez votre livre !", "Prenez votre livre !", "Lisez !"], 1,
           "Open = ouvrir."),
        ex("Pour demander où est le sac :", ["Whose bag is it?", "Where is the bag?", "What's the bag?", "What colour is the bag?"], 1,
           "Where = où."),
    ],
}

data = {
    "version": 1,
    "parcours": [
        {"matiere": "anglais", "niveau": "6e", "saison": "Un lionceau à l'école", "unites": [unite1, unite2]},
    ],
}

for path in [ROOT / "contenus" / "missions.json", ROOT / "app" / "assets" / "missions.json"]:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
print("missions écrites :", sum(len(u["missions"]) for u in [unite1, unite2]))
