"""Parcours d'anglais de 3e, unités 1 à 3 (saison « Radio Jàng »)."""
from jang_lib import *  # noqa: F401,F403

NIVEAU = "3e"

# ======================= UNITÉ 1 : PROS AND CONS =======================

u1 = [
    mission(
        "3e-u1-m1", "Un téléphone pour Gaïndé ?", "dire ce qui est bien dans une chose",
        ["The advantage is that…", "It's useful because…"],
        {"consigne": "À la maison. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["📱", "📻", "🎵", "👩"],
         "liste": [
             mot("phone", True, "Oui ! « Phone », c'est le téléphone."),
             mot("radio", True, "Oui ! « Radio », c'est la radio, à côté du téléphone."),
             mot("music", True, "Oui ! « Music », c'est la musique. On l'écoute sur le téléphone."),
             mot("mum", True, "Oui ! « Mum », c'est la maman. On peut l'appeler avec le téléphone."),
             mot("useful", True, "Oui ! « Useful », c'est utile. Le téléphone sert à beaucoup de choses."),
             mot("useless", False, "« Useless », c'est inutile. Le téléphone n'est pas inutile ! Regarde encore."),
             mot("television", False, "« Television », c'est la télé. Il n'y a pas de télé ici. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Gaïndé wants a phone. Is it a good idea?", "Gaïndé veut un téléphone. C'est une bonne idée ?"),
                       r("awa", "Yes! The advantage is that he can call his mum.", "Oui ! L'avantage, c'est qu'il peut appeler sa maman."),
                       r("modou", "And it's useful because he can listen to the radio.", "Et c'est utile parce qu'il peut écouter la radio.")],
         "gainde": "Un seul avantage ? Moi, je dis que le téléphone a MILLE avantages ! Il fait même le thé ?"},
        [q("Quel avantage donne Awa ?", ["Gaïndé peut appeler sa maman.", "Le téléphone est joli.", "Le téléphone est cher."], 0, 1),
         q("« It's useful because… » veut dire…", ["C'est utile parce que…", "C'est cher parce que…", "C'est dangereux parce que…"], 0, 2)],
        [choix("Je veux dire pourquoi le téléphone est utile. Je dis laquelle ?",
               ["It's useful why I can call my mum.", "It's useful because I can call my mum."], 1,
               aides("Regarde ton carnet. Quel mot veut dire « parce que » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « It's useful because I can listen to music. »",
                     "« Because », c'est « parce que ». « Why », c'est « pourquoi ».")),
         ordre("« The advantage that is I can call Awa. » Je me mélange !",
               ["is", "The", "that", "advantage", "I", "call", "can", "Awa"], "The advantage is that I can call Awa",
               "The advantage is that I can call Awa.",
               aides("Par quels mots Awa commence-t-elle ?", 1, "Écoute Awa :",
                     "Moi, je dis : « The advantage is that I can call my friends. »",
                     "The advantage (l'avantage) + is that (c'est que) + la suite.")),
         trou("« The ___ is that I can listen to the radio. » Il me manque un mot !", "The",
              "is that I can listen to the radio.", ["advantage", "good thing"],
              "The advantage is that I can listen to the radio.",
              aides("Regarde ton carnet. Comment dit-on « l'avantage » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « The advantage is that it's fast. »", "« Avantage » se dit « advantage ». Écris : advantage.")),
         libre("Awa a un vélo. Moi, je dis seulement « Bike! Bike! ». Aide-moi : dis un avantage du vélo !",
               ["advantage|useful"],
               aides("Quels mots de ton carnet disent ce qui est bien ?", 1, "Écoute encore :",
                     "Moi, je dis : « The advantage is that it's fast. »",
                     "Commence par « The advantage is that… » ou « It's useful because… »."))],
        [tour("awa", "Do you have a phone? What's the advantage?", "Tu as un téléphone ? C'est quoi, l'avantage ?",
              ["advantage|useful"], "The advantage is that I can call my family.", "That's true! It's very useful."),
         tour("modou", "What's the advantage of the radio?", "C'est quoi, l'avantage de la radio ?",
              ["advantage|useful"], "It's useful because we can listen to the news.", "Yes! And to the football!")],
        ["The advantage is that…", "It's useful because…", "advantage", "useful"],
    ),
    mission(
        "3e-u1-m2", "Le problème, c'est…", "dire ce qui n'est pas bien dans une chose",
        ["The drawback is that…", "The problem is…"],
        {"consigne": "Au marché. Quels mots vont avec l'image ?", "fond": "marche", "objets": ["📱", "💸", "🏷️", "🌙"],
         "liste": [
             mot("phone", True, "Oui ! « Phone », c'est le téléphone, sur la table du vendeur."),
             mot("money", True, "Oui ! « Money », c'est l'argent. Il faut payer."),
             mot("price", True, "Oui ! « Price », c'est le prix. Il est écrit sur l'étiquette."),
             mot("expensive", True, "Oui ! « Expensive », c'est cher. Regarde le prix !"),
             mot("cheap", False, "« Cheap », c'est pas cher. Ce téléphone est cher ! Regarde encore le prix."),
             mot("free", False, "« Free », c'est gratuit. Ici, il faut payer ! Regarde encore."),
         ]},
        {"fond": "marche", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Look! A new phone for Gaïndé!", "Regarde ! Un nouveau téléphone pour Gaïndé !"),
                       r("awa", "The problem is the price. It's very expensive.", "Le problème, c'est le prix. Il est très cher."),
                       r("modou", "And the drawback is that he can play all night.", "Et l'inconvénient, c'est qu'il peut jouer toute la nuit.")],
         "gainde": "Un problème ? Quel problème ? Moi, je ne vois que des avantages !"},
        [q("Quel problème donne Awa ?", ["Le prix : c'est très cher.", "La couleur.", "Le téléphone est petit."], 0, 1),
         q("« The drawback is… » veut dire…", ["L'inconvénient, c'est…", "L'avantage, c'est…", "Le prix, c'est…"], 0, 2)],
        [choix("Le téléphone est trop cher. Je dis laquelle ?",
               ["The advantage is that it's expensive.", "The problem is that it's expensive."], 1,
               aides("Cher, c'est bien ou pas bien ? Quel mot de ton carnet va avec « pas bien » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « The problem is the price. »",
                     "« Advantage », c'est ce qui est bien. « Problem » et « drawback », c'est ce qui n'est pas bien.")),
         ordre("« The drawback that is it's dangerous. » C'est bien ça ?",
               ["that", "drawback", "is", "The", "it's", "dangerous"], "The drawback is that it's dangerous",
               "The drawback is that it's dangerous.",
               aides("Par quels mots Modou commence-t-il ?", 2, "Écoute Modou :",
                     "Moi, je dis : « The drawback is that it's expensive. »",
                     "The drawback (l'inconvénient) + is that (c'est que) + la suite.")),
         trou("« The ___ is that I can't sleep. » (ce qui n'est pas bien)", "The", "is that I can't sleep.",
              ["drawback", "problem", "disadvantage"], "The drawback is that I can't sleep.",
              aides("Regarde ton carnet. Quels mots disent ce qui n'est pas bien ?", 2, "Écoute Modou :",
                    "Moi, je dis : « The problem is that it's noisy. »", "Écris : drawback, ou problem.")),
         libre("Modou a un vélo. Moi, je dis : « It's perfect! » Mais il y a sûrement un problème… Dis-le !",
               ["drawback|problem|disadvantage"],
               aides("Quels mots de ton carnet disent ce qui n'est pas bien ?", 1, "Écoute Awa :",
                     "Moi, je dis : « The problem is that it's slow. »",
                     "Commence par « The problem is… » ou « The drawback is that… »."))],
        [tour("awa", "Gaïndé wants to watch TV all night. Is it a good idea?",
              "Gaïndé veut regarder la télé toute la nuit. C'est une bonne idée ?",
              ["problem|drawback|disadvantage"], "No! The problem is that he can't sleep.", "You're right! He needs to sleep.")],
        ["The drawback is that…", "The problem is…", "expensive", "dangerous"],
    ),
    mission(
        "3e-u1-m3", "Ville ou village ?", "dire le bien et le mal d'une chose",
        ["On the one hand…", "On the other hand…"],
        {"consigne": "En ville. Quels mots vont avec l'image ?", "fond": "marche", "objets": ["🚕", "🏢", "🛒", "🔊"],
         "liste": [
             mot("taxi", True, "Oui ! « Taxi », c'est le taxi jaune et noir."),
             mot("building", True, "Oui ! « Building », c'est le grand immeuble."),
             mot("shop", True, "Oui ! « Shop », c'est le magasin."),
             mot("noise", True, "Oui ! « Noise », c'est le bruit. En ville, il y a du bruit !"),
             mot("field", False, "« Field », c'est le champ. On le voit au village, pas en ville. Regarde encore !"),
             mot("well", False, "« Well », c'est le puits. Au village, oui. Ici, en ville, non. Regarde encore !"),
         ]},
        {"fond": "classe", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Is it better to live in the city or in a village?", "C'est mieux de vivre en ville ou au village ?"),
                       r("awa", "On the one hand, the city is convenient: there are shops.", "D'un côté, la ville est pratique : il y a des magasins."),
                       r("awa", "On the other hand, it's noisy and expensive.", "D'un autre côté, il y a du bruit et c'est cher."),
                       r("modou", "On the one hand, the village is quiet. On the other hand, it's far.",
                         "D'un côté, le village est calme. D'un autre côté, il est loin.")],
         "gainde": "Deux côtés ? Moi, je dis : la ville, c'est parfait, et c'est tout ! Pourquoi parler de l'autre côté ?"},
        [q("Pour Awa, le mal de la ville, c'est…", ["le bruit et le prix", "les magasins", "le calme"], 0, 2),
         q("« On the other hand » veut dire…", ["D'un autre côté", "Sur la table", "Pour finir"], 0, 2)],
        [choix("Je parle du village, avec le bien et le mal. Je dis laquelle ?",
               ["On the one hand, it's quiet. On the one hand, it's far.",
                "On the one hand, it's quiet. On the other hand, it's far."], 1,
               aides("Les deux côtés ont-ils le même nom ? Regarde ton carnet.", 3, "Écoute Modou :",
                     "Moi, je dis : « On the one hand… On the other hand… »",
                     "« One » pour le premier côté, « other » pour l'autre côté.")),
         ordre("« On the hand other, it's noisy. » C'est bien ça ?",
               ["other", "On", "hand", "the", "it's", "noisy"], "On the other hand it's noisy",
               "On the other hand, it's noisy.",
               aides("Quel mot vient juste avant « hand » ?", 2, "Écoute Awa :",
                     "Moi, je dis : « On the other hand, it's far. »",
                     "On + the + other + hand : d'un autre côté.")),
         trou("« On the one ___, the city is convenient. » Il me manque un mot !", "On the one",
              ", the city is convenient.", ["hand"], "On the one hand, the city is convenient.",
              aides("Quel mot veut dire « main », ou « côté » ici ?", 1, "Écoute Awa :",
                    "Moi, je dis : « On the one hand… »", "« Hand », c'est la main. Ici, ça veut dire « côté ». Écris : hand.")),
         libre("Moi, je dis : « The phone is PERFECT! » Personne ne me croit… Dis le bien ET le mal du téléphone !",
               ["one hand", "other hand"],
               aides("Quels mots de ton carnet montrent les deux côtés ?", 3, "Écoute Modou :",
                     "Moi, je dis : « On the one hand, it's useful. On the other hand, it's expensive. »",
                     "Un côté avec « On the one hand », l'autre avec « On the other hand »."))],
        [tour("modou", "City or village? What do you think?", "Ville ou village ? Tu en penses quoi ?",
              ["one hand", "other hand"], "On the one hand, the city is convenient. On the other hand, it's noisy.",
              "Good point! You can see the two sides.")],
        ["On the one hand…", "On the other hand…", "convenient", "noisy", "quiet"],
    ),
    mission(
        "3e-u1-m4", "Pour ou contre : la lutte à l'école ?", "dire mon avis à la fin",
        ["To sum up, I think…", "All in all…"],
        {"consigne": "Sur le terrain. Quels mots vont avec l'image ?", "fond": "terrain", "objets": ["🤼", "🏆", "👟", "📋"],
         "liste": [
             mot("wrestling", True, "Oui ! « Wrestling », c'est la lutte. Regarde les deux lutteurs."),
             mot("training", True, "Oui ! « Training », c'est l'entraînement, avec les chaussures de sport."),
             mot("team", True, "Oui ! « Team », c'est l'équipe qui gagne la coupe."),
             mot("timetable", True, "Oui ! « Timetable », c'est l'emploi du temps, sur la feuille."),
             mot("swimming", False, "« Swimming », c'est la natation. Il n'y a pas d'eau ici ! Regarde encore."),
             mot("library", False, "« Library », c'est la bibliothèque. On est sur le terrain ! Regarde encore."),
         ]},
        {"fond": "terrain", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Wrestling at school: for or against?", "La lutte à l'école : pour ou contre ?"),
                       r("modou", "On the one hand, it's good for the body. On the other hand, it can be dangerous.",
                         "D'un côté, c'est bon pour le corps. D'un autre côté, ça peut être dangereux."),
                       r("awa", "To sum up, I think it's a good idea, with a teacher.", "Pour finir, je pense que c'est une bonne idée, avec un prof."),
                       r("modou", "All in all, I'm for it!", "En résumé, je suis pour !")],
         "gainde": "« To sum up », c'est à la fin ? Moi, je résume tout au début, et après je crie !"},
        [q("Que pense Awa, à la fin ?", ["C'est une bonne idée, avec un prof.", "C'est trop dangereux.", "Elle ne sait pas."], 0, 2),
         q("« All in all » veut dire…", ["En résumé", "Tous ensemble", "Pour toujours"], 0, 3)],
        [choix("Je finis ma chronique sur la lutte. Je dis laquelle ?",
               ["On the one hand, I'm for wrestling at school.", "All in all, I'm for wrestling at school."], 1,
               aides("Pour finir, quels mots Modou dit-il ? Regarde ton carnet.", 3, "Écoute Modou :",
                     "Moi, je finis par : « All in all, I'm for it! »",
                     "« All in all » et « To sum up », c'est pour la fin. « On the one hand », c'est pour un côté.")),
         ordre("« Up sum to, I think it's a good idea. » C'est bien ça ?",
               ["sum", "I", "To", "think", "up", "it's", "a", "good", "idea"], "To sum up I think it's a good idea",
               "To sum up, I think it's a good idea.",
               aides("Par quels mots Awa commence-t-elle ?", 2, "Écoute Awa :",
                     "Moi, je dis : « To sum up, I think… »", "To sum up (pour finir) + I think (je pense) + ton avis.")),
         trou("« All in ___, I'm for it! » Il me manque un mot !", "All in", ", I'm for it!", ["all"],
              "All in all, I'm for it!",
              aides("Le mot qui manque est déjà dans la phrase…", 3, "Écoute Modou :",
                    "Moi, je dis : « All in all… »", "All in all = en résumé. Écris : all.")),
         libre("Ma chronique finit par « Wrestling! Wrestling! Wrestling! ». Ça ne convainc personne… Donne ton avis à la fin !",
               ["to sum up|all in all"],
               aides("Quels mots de ton carnet servent à finir ?", 2, "Écoute Awa :",
                     "Moi, je dis : « To sum up, I think it's a good idea. »",
                     "Commence par « To sum up, I think… » ou « All in all… », puis ton avis."))],
        [tour("awa", "Phones at school: for or against? Finish your radio show with your opinion.",
              "Le téléphone au collège : pour ou contre ? Finis ta chronique avec ton avis.",
              ["to sum up|all in all"], "To sum up, I think phones are useful, but not in class.",
              "Great! That's a real radio show!")],
        ["To sum up, I think…", "All in all…", "wrestling", "training", "team"],
    ),
]

unite1 = unite(
    "3e-u1", "Pros and cons",
    "Ta chronique radio d'une minute : « Pour ou contre le téléphone au collège ? ». Dis le bien, le mal, puis ton avis à la fin.",
    u1,
    lignes=[
        ("Dire ce qui est bien", "The advantage is that… · It's useful because…"),
        ("Dire ce qui n'est pas bien", "The drawback is that… · The problem is…"),
        ("Dire le bien et le mal", "On the one hand… · On the other hand…"),
        ("Dire mon avis à la fin", "To sum up, I think… · All in all…"),
    ],
    mots=[
        ("advantage", "avantage", "njariñ"),
        ("useful", "utile", "am njariñ"),
        ("useless", "inutile", "amul njariñ"),
        ("problem", "problème", "jafe-jafe"),
        ("expensive", "cher", "seer"),
        ("wrestling", "la lutte", "làmb"),
        ("village", "village", "dëkk"),
        ("school", "école", "lekool"),
        ("I think", "je pense", "dama xalaat ne"),
    ],
    pieges=[
        "On the other hand. Pas « In the other hand ».",
        "It's useful because… (parce que). Pas « It's useful why… ».",
        "Useful → useless (inutile). Pas « unuseful ».",
        "To sum up, c'est pour la fin, pas pour le début.",
    ],
    exercices=[
        ex("Tu dis ce qui est bien dans le vélo :", ["The advantage is that it's fast.", "The problem is that it's fast.",
                                                     "The drawback is that it's fast.", "To sum up, it's fast."], 0,
           "« Advantage », c'est ce qui est bien."),
        ex("Complète : « It's useful ______ I can call my mum. »", ["why", "because", "so", "but"], 1,
           "« Because » = parce que."),
        ex("« The drawback is… » veut dire :", ["L'inconvénient, c'est…", "L'avantage, c'est…", "Pour finir…", "D'un côté…"], 0,
           "Drawback = inconvénient : ce qui n'est pas bien."),
        ex("Le téléphone coûte 200 000 F. Tu dis :", ["It's useful.", "It's expensive.", "It's useless.", "It's convenient."], 1,
           "Expensive = cher."),
        ex("Complète : « On the one hand, it's useful. On the ______ hand, it's expensive. »", ["other", "one", "second", "two"], 0,
           "Pour l'autre côté : On the other hand."),
        ex("Quelle phrase est juste ?", ["In the other hand, the city is noisy.", "On the other hand, the city is noisy.",
                                         "At the other hand, the city is noisy.", "On other the hand, the city is noisy."], 1,
           "On dit « On the other hand », avec « on »."),
        ex("Tu finis ta chronique. Tu commences par :", ["On the one hand…", "To sum up, I think…", "The drawback is…",
                                                         "It's useful because…"], 1,
           "« To sum up » = pour finir, en résumé."),
        ex("« All in all » veut dire :", ["En résumé", "Tous ensemble", "Partout", "Pour toujours"], 0,
           "All in all = en résumé, à la fin."),
        ex("Le contraire de « useful » :", ["unuseful", "useless", "usefulness", "disuseful"], 1, "Useless = inutile."),
        ex("« Wrestling », c'est :", ["la lutte", "la natation", "l'entraînement", "l'équipe"], 0,
           "Wrestling = la lutte. Training = l'entraînement. Team = l'équipe."),
    ],
)

# ======================= UNITÉ 2 : FOOD AND HEALTH =======================

u2 = [
    mission(
        "3e-u2-m1", "Qu'y a-t-il dans mon assiette ?", "dire ce qu'il y a dans un aliment",
        ["It contains proteins.", "It's rich in vitamins."],
        {"consigne": "C'est l'heure du repas. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["🐟", "🍚", "🥕", "🥭"],
         "liste": [
             mot("fish", True, "Oui ! « Fish », c'est le poisson du thiéboudienne."),
             mot("rice", True, "Oui ! « Rice », c'est le riz."),
             mot("vegetables", True, "Oui ! « Vegetables », ce sont les légumes, comme la carotte."),
             mot("mango", True, "Oui ! « Mango », c'est la mangue, pour le dessert."),
             mot("meat", False, "« Meat », c'est la viande. Dans l'assiette, il y a du poisson, pas de viande. Regarde encore !"),
             mot("bread", False, "« Bread », c'est le pain. Tu vois du pain ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Today on Radio Jàng: thieboudienne! Fish contains proteins.",
                         "Aujourd'hui sur Radio Jàng : le thiéboudienne ! Le poisson contient des protéines."),
                       r("modou", "And the vegetables are rich in vitamins.", "Et les légumes sont riches en vitamines."),
                       r("awa", "Rice contains carbohydrates. It gives energy.", "Le riz contient des glucides. Il donne de l'énergie.")],
         "gainde": "Des protéines ? Combien de kilos dans un poisson ? Moi, je mange tout le bol pour être sûr !"},
        [q("Qu'est-ce qu'il y a dans le poisson ?", ["des protéines", "du sucre", "des glucides"], 0, 0),
         q("« Rich in vitamins » veut dire…", ["riche en vitamines", "pauvre en vitamines", "sans vitamines"], 0, 1)],
        [choix("Je parle de la mangue. Je dis laquelle ?", ["Mango is rich of vitamins.", "Mango is rich in vitamins."], 1,
               aides("Regarde ton carnet. Quel petit mot vient après « rich » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « Oranges are rich in vitamins. »", "On dit « rich in », comme « riche en ».")),
         ordre("« Peanuts fat contain and proteins. » C'est bien ça ?",
               ["fat", "Peanuts", "and", "contain", "proteins"], "Peanuts contain fat and proteins",
               "Peanuts contain fat and proteins.",
               aides("Qu'est-ce qui vient en premier : l'aliment ou ce qu'il contient ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Fish contains proteins. »", "L'aliment + contain(s) + ce qu'il y a dedans.")),
         trou("« Rice contains ___. It gives energy. » (des glucides)", "Rice contains", ". It gives energy.",
              ["carbohydrates", "carbs"], "Rice contains carbohydrates. It gives energy.",
              aides("Qu'est-ce qui donne de l'énergie, dans le riz ?", 2, "Écoute Awa :",
                    "Moi, je dis : « Bread contains carbohydrates. »", "Glucides = carbohydrates. Écris : carbohydrates.")),
         libre("Je dis : « Milk is very very good! » C'est tout… Dis-moi ce qu'il y a dans le lait !",
               ["contains|contain|rich in"],
               aides("Quels mots de ton carnet disent ce qu'il y a dans un aliment ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Milk contains proteins. »",
                     "Dis « Milk contains… » ou « Milk is rich in… »."))],
        [tour("modou", "What's in your favourite food?", "Qu'est-ce qu'il y a dans ton plat préféré ?",
              ["contains|contain|rich in"], "Thieboudienne contains fish. Fish is rich in proteins.",
              "Yummy! And it's good for you!")],
        ["It contains proteins.", "It's rich in vitamins.", "carbohydrates", "fat", "minerals"],
    ),
    mission(
        "3e-u2-m2", "Ça rend fort !", "dire ce qu'une chose fait au corps (Ça rend fort…)",
        ["Milk makes you strong.", "Sugar makes you thirsty."],
        {"consigne": "Après le sport. Quels mots vont avec l'image ?", "fond": "terrain", "objets": ["🥛", "🍬", "💪", "💧"],
         "liste": [
             mot("milk", True, "Oui ! « Milk », c'est le lait."),
             mot("sweets", True, "Oui ! « Sweets », ce sont les bonbons."),
             mot("strong", True, "Oui ! « Strong », c'est fort. Regarde le bras !"),
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("weak", False, "« Weak », c'est faible. Le bras est fort, pas faible ! Regarde encore."),
             mot("juice", False, "« Juice », c'est le jus. Il n'y a pas de jus ici. Regarde encore !"),
         ]},
        {"fond": "terrain", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "I'm so tired! I need sweets.", "Je suis trop fatigué ! Il me faut des bonbons."),
                       r("awa", "No! Sugar makes you thirsty. Drink water!", "Non ! Le sucre donne soif. Bois de l'eau !"),
                       r("modou", "OK. And milk?", "D'accord. Et le lait ?"),
                       r("awa", "Milk makes you strong.", "Le lait rend fort.")],
         "gainde": "Le lait rend fort ? Alors je bois dix litres, et je soulève le collège !"},
        [q("Pour Awa, le sucre…", ["donne soif", "rend fort", "fait dormir"], 0, 1),
         q("Le lait…", ["rend fort", "donne soif", "rend triste"], 0, 3)],
        [choix("Le lait rend fort. Je dis laquelle ?", ["Milk makes you to be strong.", "Milk makes you strong."], 1,
               aides("Awa dit « makes you » et ensuite ? Combien de mots ?", 3, "Écoute Awa :",
                     "Moi, je dis : « Sport makes you strong. »", "Makes you + un seul mot : makes you strong, makes you tired.")),
         ordre("« Makes thirsty sugar you. » C'est bien ça ?", ["thirsty", "makes", "Sugar", "you"], "Sugar makes you thirsty",
               "Sugar makes you thirsty.",
               aides("Par quoi commence la phrase : la chose ou ce qu'elle fait ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Salt makes you thirsty. »", "La chose + makes you + ce qu'elle fait au corps.")),
         trou("« Sport makes you ___! » Que fait le sport au corps ?", "Sport makes you", "!",
              ["strong", "tired", "happy", "healthy", "fit"], "Sport makes you strong!",
              aides("Regarde ton carnet. Comment dit-on « fort » ?", 3, "Écoute Awa :",
                    "Moi, je dis : « Milk makes you strong. »", "Écris : strong (fort), ou tired (fatigué).")),
         libre("Je veux dire ce que fait le sommeil au corps. Moi, je dis juste « Sleep! Good! »… Aide-moi !",
               ["makes you|make you"],
               aides("Quels mots de ton carnet disent ce qu'une chose fait au corps ?", 3, "Écoute Awa :",
                     "Moi, je dis : « Sleep makes you strong. »", "Dis « Sleep makes you… » + un mot."))],
        [tour("awa", "What does football do to your body?", "Qu'est-ce que le foot fait à ton corps ?",
              ["makes you|make you"], "Football makes you strong.", "True! And it makes you happy!"),
         tour("modou", "Is a big bottle of soda good for you?", "Une grande bouteille de soda, c'est bon pour toi ?",
              ["makes you|make you"], "No! Sugar makes you thirsty.", "Oh! So I drink water.")],
        ["Milk makes you strong.", "Sugar makes you thirsty.", "It makes you tired.", "strong", "thirsty"],
    ),
    mission(
        "3e-u2-m3", "Le paludisme, parlons-en", "parler d'une maladie et de ce qu'on sent",
        ["The symptoms are fever and headache.", "I have a fever.", "I have a headache."],
        {"consigne": "Modou est malade. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["🦟", "🌡️", "🛏️", "💊"],
         "liste": [
             mot("mosquito", True, "Oui ! « Mosquito », c'est le moustique. Il donne le paludisme."),
             mot("fever", True, "Oui ! « Fever », c'est la fièvre. Le thermomètre monte."),
             mot("bed", True, "Oui ! « Bed », c'est le lit. Modou se repose."),
             mot("medicine", True, "Oui ! « Medicine », c'est le médicament."),
             mot("fly", False, "« Fly », c'est la mouche. Ici, c'est un moustique, pas une mouche ! Regarde encore."),
             mot("flu", False, "« Flu », c'est la grippe. Ici, il y a un moustique : on parle du paludisme. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Modou, you look tired. Are you OK?", "Modou, tu as l'air fatigué. Ça va ?"),
                       r("modou", "No. I have a fever and a headache.", "Non. J'ai de la fièvre et mal à la tête."),
                       r("awa", "The symptoms of malaria are fever and headache. Go to the doctor!",
                         "Les signes du paludisme, ce sont la fièvre et le mal de tête. Va chez le médecin !"),
                       r("modou", "You're right. I'm going now.", "Tu as raison. J'y vais maintenant.")],
         "gainde": "Mal à la tête ? Moi, j'ai mal à la crinière, aux griffes, à la queue et aux moustaches ! C'est grave ?"},
        [q("Qu'est-ce que Modou sent ?", ["de la fièvre et mal à la tête", "mal au ventre", "rien du tout"], 0, 1),
         q("« Symptoms », ce sont…", ["les signes d'une maladie", "les médicaments", "les médecins"], 0, 2)],
        [choix("J'ai mal à la tête. Je dis laquelle ?", ["I am headache.", "I have a headache."], 1,
               aides("Regarde ton carnet. Comment Modou dit-il ce qu'il sent ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I have a fever. »", "On dit « I have a… » : I have a headache, I have a fever.")),
         ordre("« Are the symptoms fever and headache. » C'est bien ça ?",
               ["symptoms", "are", "The", "fever", "and", "headache"], "The symptoms are fever and headache",
               "The symptoms are fever and headache.",
               aides("Par quels mots Awa commence-t-elle ?", 2, "Écoute Awa :",
                     "Moi, je dis : « The symptoms are cough and tiredness. »",
                     "The symptoms (les signes) + are + les signes.")),
         trou("« I have a ___. » (J'ai de la fièvre.)", "I have a", ".", ["fever", "temperature", "high temperature"],
              "I have a fever.",
              aides("Regarde ton carnet. Comment dit-on « fièvre » ?", 1, "Écoute Modou :",
                    "Moi, je dis : « I have a fever. »", "Fièvre = fever. Écris : fever.")),
         libre("Chez le médecin, je dis : « I'm dying! I'm dying! » Aide-moi : dis que tu as de la fièvre et mal à la tête.",
               ["fever", "headache|head"],
               aides("Quels mots de ton carnet disent ce qu'on sent ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I have a fever and a headache. »", "Dis « I have a fever and a headache. »"))],
        [tour("kocc", "Hello! What's the problem? How do you feel?", "Bonjour ! Qu'est-ce qui ne va pas ? Comment tu te sens ?",
              ["fever|headache|cough|tired|sick|flu"], "I have a fever and a headache.",
              "Maybe it's malaria. Let's do a test."),
         tour("awa", "What are the symptoms of malaria?", "Quels sont les signes du paludisme ?",
              ["fever|headache"], "The symptoms are fever and headache.", "Exactly! You know it well.")],
        ["The symptoms are…", "I have a fever.", "I have a headache.", "malaria", "tiredness"],
    ),
    mission(
        "3e-u2-m4", "Le conseil santé de Radio Jàng", "dire « Attention ! » et donner un conseil",
        ["Be careful!", "Don't forget to…", "You must…"],
        {"consigne": "Le soir. Quels mots vont avec l'image ?", "fond": "nuit", "objets": ["🦟", "🛏️", "🧼", "💧"],
         "liste": [
             mot("mosquito", True, "Oui ! « Mosquito », c'est le moustique. Il sort le soir."),
             mot("mosquito net", True, "Oui ! « Mosquito net », c'est la moustiquaire, sur le lit."),
             mot("soap", True, "Oui ! « Soap », c'est le savon, pour se laver les mains."),
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("sun", False, "« Sun », c'est le soleil. Il fait nuit ! Regarde encore."),
             mot("sweets", False, "« Sweets », ce sont les bonbons. Il n'y en a pas ici. Regarde encore !"),
         ]},
        {"fond": "classe", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Hello! This is the health tip of Radio Jàng!", "Bonjour ! Voici le conseil santé de Radio Jàng !"),
                       r("modou", "Be careful! Mosquitoes give malaria.", "Attention ! Les moustiques donnent le paludisme."),
                       r("awa", "You must sleep under a mosquito net.", "Tu dois dormir sous une moustiquaire."),
                       r("modou", "And don't forget to wash your hands!", "Et n'oublie pas de te laver les mains !")],
         "gainde": "Moi aussi, je veux donner un conseil ! Je crie « YOU MUST! » très fort : comme ça, tout le monde obéit ?"},
        [q("Où faut-il dormir ?", ["sous une moustiquaire", "dans la cour", "sous la table"], 0, 2),
         q("« Don't forget to… » veut dire…", ["N'oublie pas de…", "Ne mange pas…", "Tu peux…"], 0, 3)],
        [choix("Une moto arrive très vite ! Je préviens Awa. Je dis laquelle ?", ["Don't forget, Awa!", "Be careful, Awa!"], 1,
               aides("Regarde ton carnet. Quand il y a un danger, qu'est-ce qu'on crie ?", 1, "Écoute Modou :",
                     "Moi, je crie : « Be careful! »",
                     "« Be careful! », c'est « Attention ! ». « Don't forget », c'est « N'oublie pas »."))
         , ordre("« Forget don't to wash your hands. » C'est bien ça ?",
                 ["forget", "to", "Don't", "wash", "your", "hands"], "Don't forget to wash your hands",
                 "Don't forget to wash your hands!",
                 aides("Par quel mot Modou commence-t-il ?", 3, "Écoute Modou :",
                       "Moi, je dis : « Don't forget to drink water! »", "Don't forget (n'oublie pas) + to + ce qu'il faut faire.")),
         trou("« You ___ sleep under a mosquito net. » (tu dois)", "You", "sleep under a mosquito net.",
              ["must", "should", "have to"], "You must sleep under a mosquito net.",
              aides("Regarde ton carnet. Comment dit-on « tu dois » ?", 2, "Écoute Awa :",
                    "Moi, je dis : « You must wash your hands. »", "Tu dois = you must. Écris : must.")),
         libre("Il fait très chaud. Moi, je dis à Modou : « DRINK! DRINK! DRINK! » Il a peur… Donne-lui un vrai conseil pour l'eau !",
               ["must|should|dont forget|have to", "water"],
               aides("Quels mots de ton carnet servent à donner un conseil ?", 2, "Écoute Awa :",
                     "Moi, je dis : « You must drink water. »", "Dis « You must drink water » ou « Don't forget to drink water »."))],
        [tour("modou", "It's very hot today. What's your advice?", "Il fait très chaud aujourd'hui. Tu me conseilles quoi ?",
              ["must|should|dont forget|be careful|have to"], "You must drink water. And be careful with the sun!",
              "Thanks! I'm taking my bottle.")],
        ["Be careful!", "Don't forget to…", "You must…", "mosquito net", "hygiene"],
    ),
]

unite2 = unite(
    "3e-u2", "Food and health",
    "Ton spot santé de 30 secondes pour Radio Jàng : un aliment, une maladie et un conseil.",
    u2,
    lignes=[
        ("Dire ce qu'il y a dans un aliment", "It contains proteins. · It's rich in vitamins."),
        ("Dire ce qu'une chose fait au corps", "Milk makes you strong. · Sugar makes you thirsty."),
        ("Parler d'une maladie", "The symptoms are fever and headache. · I have a fever."),
        ("Prévenir et conseiller", "Be careful! · Don't forget to… · You must…"),
    ],
    mots=[
        ("milk", "lait", "meew"),
        ("sugar", "sucre", "suukar"),
        ("fish", "poisson", "jën"),
        ("water", "eau", "ndox"),
        ("strong", "fort", "dëgër"),
        ("malaria", "paludisme", "sibiru"),
        ("mosquito", "moustique", "yoo"),
        ("head", "tête", "bopp"),
        ("medicine", "médicament", "garab"),
        ("doctor", "médecin", "doktoor"),
        ("sick", "malade", "feebar"),
    ],
    pieges=[
        "Rich in vitamins (riche en). Pas « rich of vitamins ».",
        "Milk makes you strong. Pas « makes you to be strong ».",
        "You must drink water. Pas « You must to drink ».",
        "J'ai mal à la tête : I have a headache. Pas « I am headache ».",
    ],
    exercices=[
        ex("Le poisson contient des protéines :", ["Fish contains proteins.", "Fish contain of proteins.", "Fish is proteins.",
                                                   "Fish has in proteins."], 0,
           "L'aliment + contains + ce qu'il y a dedans."),
        ex("Complète : « Mango is rich ______ vitamins. »", ["of", "in", "with", "on"], 1, "On dit « rich in », comme « riche en »."),
        ex("Le lait rend fort :", ["Milk makes you strong.", "Milk makes you to be strong.", "Milk makes strong you.",
                                   "Milk make you strong."], 0,
           "Milk makes you + strong."),
        ex("« Sugar makes you thirsty » veut dire :", ["Le sucre donne soif.", "Le sucre rend fort.", "Le sucre fait dormir.",
                                                       "Le sucre donne faim."], 0,
           "Thirsty = qui a soif."),
        ex("J'ai mal à la tête :", ["I have a headache.", "I am headache.", "I have a head.", "My head is ache."], 0,
           "Headache = mal de tête. On dit « I have a headache »."),
        ex("« The symptoms are fever and cough. » « Cough », c'est :", ["la toux", "la fièvre", "la fatigue", "le paludisme"], 0,
           "Cough = la toux. Fever = la fièvre."),
        ex("Le paludisme se dit :", ["flu", "malaria", "cholera", "diabetes"], 1,
           "Malaria = paludisme. Flu = grippe."),
        ex("Une moto arrive très vite. Tu cries :", ["Don't forget!", "Be careful!", "You must!", "All in all!"], 1,
           "Be careful! = Attention !"),
        ex("Complète : « You must ______ water. »", ["drink", "to drink", "drinking", "drinks"], 0,
           "You must + drink, sans « to »."),
        ex("« Don't forget to wash your hands » veut dire :", ["N'oublie pas de te laver les mains.", "Ne lave pas tes mains.",
                                                               "Tu dois manger.", "Attention à tes mains !"], 0,
           "Don't forget to… = N'oublie pas de…"),
    ],
)

# ======================= UNITÉ 3 : BREAKING NEWS =======================

u3 = [
    mission(
        "3e-u3-m1", "Flash spécial !", "annoncer une nouvelle",
        ["A library was opened.", "The road has been repaired.", "A school will be built."],
        {"consigne": "La fête de la bibliothèque. Quels mots vont avec l'image ?", "fond": "bibliotheque",
         "objets": ["📚", "🎀", "✂️", "📰"],
         "liste": [
             mot("library", True, "Oui ! « Library », c'est la bibliothèque. Elle est toute neuve."),
             mot("books", True, "Oui ! « Books », ce sont les livres."),
             mot("ribbon", True, "Oui ! « Ribbon », c'est le ruban. On le coupe pour ouvrir."),
             mot("newspaper", True, "Oui ! « Newspaper », c'est le journal. Il donne la nouvelle."),
             mot("hospital", False, "« Hospital », c'est l'hôpital. Ici, il y a des livres : c'est une bibliothèque ! Regarde encore."),
             mot("road", False, "« Road », c'est la route. On est dans la bibliothèque, pas sur la route. Regarde encore !"),
         ]},
        {"fond": "bibliotheque", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Breaking news! A new library was opened in our school.",
                         "Flash spécial ! Une nouvelle bibliothèque a été ouverte dans notre collège."),
                       r("modou", "And the road to the market has been repaired.", "Et la route du marché a été réparée."),
                       r("awa", "Next year, a football field will be built!", "L'année prochaine, un terrain de foot sera construit !"),
                       r("modou", "Great news for Radio Jàng!", "Super nouvelles pour Radio Jàng !")],
         "gainde": "« Was opened »… « has been repaired »… Moi, je veux crier les nouvelles : « BREAKING NEWS! BREAKING! » C'est tout ?"},
        [q("Qu'est-ce qui a été ouvert ?", ["une bibliothèque", "un marché", "un hôpital"], 0, 0),
         q("« A football field will be built » veut dire…", ["Un terrain de foot sera construit.", "Un terrain de foot a été cassé.",
                                                              "Un terrain de foot est fermé."], 0, 2)],
        [choix("La route est réparée. J'annonce la nouvelle. Je dis laquelle ?",
               ["The road has repaired.", "The road has been repaired."], 1,
               aides("Une route ne se répare pas toute seule ! Quel petit mot manque ? Regarde ton carnet.", 1, "Écoute Modou :",
                     "Moi, je dis : « The school has been painted. »",
                     "On ne dit pas qui a réparé : has been + repaired.")),
         ordre("« Opened a new was library. » C'est bien ça ?", ["opened", "A", "new", "was", "library"],
               "A new library was opened", "A new library was opened.",
               aides("Par quoi commence la nouvelle : la chose, ou ce qui lui arrive ?", 0, "Écoute Awa :",
                     "Moi, je dis : « A new market was opened. »", "La chose + was opened (a été ouverte).")),
         trou("« A new school will be ___ next year. » (construite)", "A new school will be", "next year.",
              ["built", "opened", "constructed"], "A new school will be built next year.",
              aides("Regarde ton carnet. Comment dit-on « construit » ?", 2, "Écoute Awa :",
                    "Moi, je dis : « A hospital will be built. »", "Construit = built. Écris : built.")),
         libre("Moi, je crie seulement « BREAKING NEWS! ». Mais quelle nouvelle ? Annonce une nouvelle de ton quartier !",
               ["was|were|has been|have been|will be"],
               aides("Quels mots de ton carnet servent à annoncer une nouvelle ?", 1, "Écoute Modou :",
                     "Moi, je dis : « Breaking news! The market has been cleaned. »",
                     "Dis la chose + was…, has been… ou will be…"))],
        [tour("awa", "You're on Radio Jàng! What's the news in your school?", "Tu es sur Radio Jàng ! Quelle est la nouvelle dans ton collège ?",
              ["was|were|has been|have been|will be"], "Breaking news! The classrooms have been painted.",
              "Wow! Thank you for the news!")],
        ["Breaking news!", "… was opened.", "… has been repaired.", "… will be built.", "news"],
    ),
    mission(
        "3e-u3-m2", "Il a dit que…", "répéter ce qu'une personne a dit",
        ["He said that…", "He explained that…"],
        {"consigne": "Une interview pour la radio. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🎤", "📻", "📝", "🧑‍🏫"],
         "liste": [
             mot("microphone", True, "Oui ! « Microphone », c'est le micro."),
             mot("radio", True, "Oui ! « Radio », c'est la radio."),
             mot("notebook", True, "Oui ! « Notebook », c'est le carnet. On écrit ce que la personne dit."),
             mot("interview", True, "Oui ! « Interview », c'est l'interview : on pose des questions au directeur."),
             mot("singer", False, "« Singer », c'est le chanteur. Ici, on ne chante pas : on fait une interview. Regarde encore !"),
             mot("television", False, "« Television », c'est la télé. Ici, c'est la radio : on écoute, on ne regarde pas !"),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "What did the headmaster say?", "Qu'est-ce que le directeur a dit ?"),
                       r("awa", "He said that he was proud of our radio.", "Il a dit qu'il était fier de notre radio."),
                       r("modou", "Really? Anything else?", "C'est vrai ? Autre chose ?"),
                       r("awa", "He explained that the library opens on Monday.", "Il a expliqué que la bibliothèque ouvre lundi.")],
         "gainde": "Le directeur a dit « I am proud ». Alors je répète : « He said that I am proud »… Attends, c'est qui, le fier ?"},
        [q("Qu'a dit le directeur ?", ["Il est fier de la radio.", "La radio est fermée.", "Il n'aime pas la radio."], 0, 1),
         q("« He explained that… » veut dire…", ["Il a expliqué que…", "Il a demandé si…", "Il a oublié que…"], 0, 3)],
        [choix("Le directeur a dit : « I am proud. » Je le répète. Je dis laquelle ?",
               ["He said that I am proud.", "He said that he was proud."], 1,
               aides("Qui est fier : toi, ou le directeur ?", 1, "Écoute Awa :",
                     "Moi, je dis : « She said that she was tired. »",
                     "On répète la phrase d'un autre : « I » devient « he » ou « she ».")),
         ordre("« That said he loved he the radio. » Je me mélange !",
               ["said", "the", "He", "radio", "that", "loved", "he"], "He said that he loved the radio",
               "He said that he loved the radio.",
               aides("Par quels mots Awa commence-t-elle ?", 1, "Écoute Awa :",
                     "Moi, je dis : « He said that he was happy. »", "He said that (il a dit que) + la phrase.")),
         trou("Kocc Barma : « The test is easy. » → « He ___ that the test was easy. »", "He", "that the test was easy.",
              ["said", "explained"], "He said that the test was easy.",
              aides("Regarde ton carnet. Quel mot veut dire « a dit » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « She said that… »", "A dit = said. Écris : said.")),
         libre("Awa a dit : « I love music. » Moi, je répète : « Awa music love! » … Aide-moi à le dire pour la radio !",
               ["she said|she explained|she told", "music"],
               aides("Quels mots de ton carnet servent à répéter ce qu'une personne a dit ?", 1, "Écoute Awa :",
                     "Moi, je dis : « She said that she loved music. »", "Commence par « She said that… »."))],
        [tour("modou", "I wasn't there! What did Kocc Barma say? (Il a dit : « The radio is great. »)",
              "Je n'étais pas là ! Qu'a dit Kocc Barma ? (Il a dit : « The radio is great. »)",
              ["he said|he explained|he told"], "He said that the radio was great.", "Cool! Thanks for telling me.")],
        ["He said that…", "She explained that…", "interview", "reporter"],
    ),
    mission(
        "3e-u3-m3", "Elle m'a demandé si…", "répéter la question d'une personne",
        ["She asked me if…", "She asked where…"],
        {"consigne": "Au marché, avec le micro. Quels mots vont avec l'image ?", "fond": "marche",
         "objets": ["🎤", "🧺", "🍅", "❓"],
         "liste": [
             mot("microphone", True, "Oui ! « Microphone », c'est le micro de Radio Jàng."),
             mot("basket", True, "Oui ! « Basket », c'est le panier."),
             mot("tomatoes", True, "Oui ! « Tomatoes », ce sont les tomates."),
             mot("question", True, "Oui ! « Question », c'est la question. Le point d'interrogation, là."),
             mot("beach", False, "« Beach », c'est la plage. On est au marché ! Regarde encore."),
             mot("classroom", False, "« Classroom », c'est la salle de classe. Ici, c'est le marché. Regarde encore !"),
         ]},
        {"fond": "marche", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "So, Modou, what did the seller ask you?", "Alors, Modou, qu'est-ce que la vendeuse t'a demandé ?"),
                       r("modou", "She asked me if I was a reporter.", "Elle m'a demandé si j'étais reporter."),
                       r("awa", "And then?", "Et ensuite ?"),
                       r("modou", "She asked where our radio was.", "Elle a demandé où était notre radio.")],
         "gainde": "Elle a demandé « Where is your radio? ». Alors je répète : « She asked where is your radio »… Ça sonne bizarre, non ?"},
        [q("La vendeuse a demandé si Modou…", ["était reporter", "avait faim", "était malade"], 0, 1),
         q("« She asked where… » veut dire…", ["Elle a demandé où…", "Elle a dit que…", "Elle a demandé si…"], 0, 3)],
        [choix("La vendeuse m'a demandé : « Are you hungry? » Je répète sa question. Je dis laquelle ?",
               ["She asked me that I was hungry.", "She asked me if I was hungry."], 1,
               aides("Regarde ton carnet. Pour une question « oui ou non », quel petit mot Modou dit-il ?", 1, "Écoute Modou :",
                     "Moi, je dis : « He asked me if I was ready. »",
                     "« If », c'est « si ». She asked me if… = Elle m'a demandé si…")),
         ordre("« She asked where was the radio. » C'est bien ça ?",
               ["the", "asked", "She", "was", "where", "radio"], "She asked where the radio was",
               "She asked where the radio was.",
               aides("Écoute la fin de la phrase de Modou : « was » vient où ?", 3, "Écoute Modou :",
                     "Moi, je dis : « He asked where the market was. »",
                     "She asked where + la chose + was. Le « was » va à la fin.")),
         trou("« Are you OK? » → « She asked me ___ I was OK. »", "She asked me", "I was OK.", ["if", "whether"],
              "She asked me if I was OK.",
              aides("Quel petit mot veut dire « si » ?", 1, "Écoute Modou :",
                    "Moi, je dis : « She asked me if I was a reporter. »", "Si = if. Écris : if.")),
         libre("Kocc Barma m'a demandé : « Where is your book? » Moi, je dis : « He asked book where? » Aide-moi !",
               ["asked", "where"],
               aides("Quels mots de ton carnet servent à répéter une question ?", 3, "Écoute Modou :",
                     "Moi, je dis : « He asked me where my book was. »", "Commence par « He asked me where… »."))],
        [tour("awa", "What did the doctor ask you? (Il a demandé : « Do you have a fever? »)",
              "Qu'est-ce que le médecin t'a demandé ? (Il a demandé : « Do you have a fever? »)",
              ["asked", "if|whether"], "He asked me if I had a fever.", "And do you? I hope you're OK!")],
        ["She asked me if…", "She asked where…", "question", "seller"],
    ),
    mission(
        "3e-u3-m4", "Il nous a dit de…", "répéter ce qu'une personne a demandé de faire",
        ["He told us to…", "He told us not to…"],
        {"consigne": "En classe. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["🧑‍🏫", "📖", "📵", "🤫"],
         "liste": [
             mot("teacher", True, "Oui ! « Teacher », c'est le prof, Kocc Barma."),
             mot("book", True, "Oui ! « Book », c'est le livre."),
             mot("phone", True, "Oui ! « Phone », c'est le téléphone. Il est barré : pas de téléphone !"),
             mot("quiet", True, "Oui ! « Quiet », c'est le calme. Chut !"),
             mot("ball", False, "« Ball », c'est le ballon. On ne joue pas au ballon en classe ! Regarde encore."),
             mot("bed", False, "« Bed », c'est le lit. On ne dort pas en classe ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Sorry, I'm late! What did Kocc Barma say?", "Pardon, je suis en retard ! Qu'est-ce que Kocc Barma a dit ?"),
                       r("awa", "He told us to open our books at page ten.", "Il nous a dit d'ouvrir nos livres à la page dix."),
                       r("modou", "OK. Can I use my phone?", "D'accord. Je peux utiliser mon téléphone ?"),
                       r("awa", "No! He told us not to use our phones in class.", "Non ! Il nous a dit de ne pas utiliser nos téléphones en classe.")],
         "gainde": "« He told us not to… » Je mets le « not » où ? Au début ? À la fin ? Partout ?"},
        [q("Kocc Barma a dit d'ouvrir…", ["les livres", "les fenêtres", "les sacs"], 0, 1),
         q("Le téléphone en classe ?", ["Non, pas en classe.", "Oui, toujours.", "Oui, pour jouer."], 0, 3)],
        [choix("Kocc Barma a dit : « Don't run! » Je le répète. Je dis laquelle ?",
               ["He told us don't run.", "He told us not to run."], 1,
               aides("Regarde ton carnet. Comment Awa dit-elle « de ne pas » ?", 3, "Écoute Awa :",
                     "Moi, je dis : « She told us not to shout. »",
                     "« Don't run! » devient « He told us not to run. » : not + to.")),
         ordre("« Told us he to sit down. » C'est bien ça ?", ["us", "told", "He", "to", "sit", "down"],
               "He told us to sit down", "He told us to sit down.",
               aides("Par quels mots Awa commence-t-elle ?", 1, "Écoute Awa :",
                     "Moi, je dis : « He told us to stand up. »", "He told us (il nous a dit) + to + ce qu'il faut faire.")),
         trou("Kocc Barma : « Be quiet! » → « He told us ___ be quiet. »", "He told us", "be quiet.", ["to"],
              "He told us to be quiet.",
              aides("Quel petit mot vient après « told us » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « He told us to open our books. »", "Écris : to.")),
         libre("Le médecin a dit : « Drink water! » Moi, je dis à Modou : « Doctor water drink! » Aide-moi à bien le répéter !",
               ["told|asked|said", "to drink"],
               aides("Quels mots de ton carnet servent à répéter ce qu'il faut faire ?", 1, "Écoute Awa :",
                     "Moi, je dis : « He told me to drink water. »", "Commence par « He told me to… »."))],
        [tour("modou", "I was late again! What did the headmaster tell us? (Il a dit : « Don't be late! »)",
              "J'étais encore en retard ! Qu'est-ce que le directeur nous a dit ? (Il a dit : « Don't be late! »)",
              ["told|asked|said", "not to"], "He told us not to be late.", "Oops! OK, I'll come early tomorrow.")],
        ["He told us to…", "He told us not to…", "headmaster"],
    ),
    mission(
        "3e-u3-m5", "Depuis quand ?", "dire quand et depuis quand",
        ["for two years", "since 2020", "three days ago", "during the holidays"],
        {"consigne": "L'interview de Doudou. Quels mots vont avec l'image ?", "fond": "cour", "objets": ["🥁", "📅", "⏰", "🎤"],
         "liste": [
             mot("drum", True, "Oui ! « Drum », c'est le tambour. Le tama de Doudou est un drum."),
             mot("calendar", True, "Oui ! « Calendar », c'est le calendrier."),
             mot("clock", True, "Oui ! « Clock », c'est l'horloge."),
             mot("microphone", True, "Oui ! « Microphone », c'est le micro d'Awa."),
             mot("guitar", False, "« Guitar », c'est la guitare. Doudou joue du tama, un tambour ! Regarde encore."),
             mot("piano", False, "« Piano », c'est le piano. Il n'y a pas de piano ici. Regarde encore !"),
         ]},
        {"fond": "cour", "persos": ["awa", "doudou", "gainde"],
         "repliques": [r("awa", "Doudou, how long have you played the tama?", "Doudou, depuis combien de temps tu joues du tama ?"),
                       r("doudou", "I've played the tama for ten years, since 2016.", "Je joue du tama depuis dix ans, depuis 2016."),
                       r("awa", "And your new song?", "Et ta nouvelle chanson ?"),
                       r("doudou", "I wrote it during the holidays. I finished it three days ago.",
                         "Je l'ai écrite pendant les vacances. Je l'ai finie il y a trois jours.")],
         "gainde": "« For », « since », « ago »… Moi, je mets tout ensemble : « I'm a lion since for two years ago ! » C'est bon ?"},
        [q("Doudou joue du tama depuis…", ["dix ans", "trois jours", "deux ans"], 0, 1),
         q("« Three days ago » veut dire…", ["Il y a trois jours", "Dans trois jours", "Pendant trois jours"], 0, 3)],
        [choix("J'habite à Dakar depuis 2024. Je dis laquelle ?",
               ["I've lived in Dakar for 2024.", "I've lived in Dakar since 2024."], 1,
               aides("Regarde ton carnet. Avec une date (2016), Doudou dit « for » ou « since » ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « I've lived here since 2019. »",
                     "« Since » + une date : since 2020. « For » + une durée : for two years.")),
         ordre("« Ago I finished the song three days. » C'est bien ça ?",
               ["ago", "I", "the", "finished", "song", "three", "days"], "I finished the song three days ago",
               "I finished the song three days ago.",
               aides("Où Doudou met-il « ago » : au début ou à la fin ?", 3, "Écoute Doudou :",
                     "Moi, je dis : « I came here two years ago. »", "« Ago » va après la durée : three days ago = il y a trois jours.")),
         trou("« We go to the village ___ the holidays. » (pendant)", "We go to the village", "the holidays.",
              ["during", "in", "for"], "We go to the village during the holidays.",
              aides("Regarde ton carnet. Comment dit-on « pendant » ?", 3, "Écoute Doudou :",
                    "Moi, je dis : « I wrote it during the holidays. »", "Pendant = during. Écris : during.")),
         libre("Je dis : « I'm at school since always and forever! » Personne ne comprend… Dis depuis combien de temps tu es au collège !",
               ["for|since"],
               aides("Quels mots de ton carnet disent « depuis » ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « I've been at this school for three years. »",
                     "Dis « for » + une durée, ou « since » + une date."))],
        [tour("doudou", "How long have you lived in your house?", "Depuis combien de temps tu habites dans ta maison ?",
              ["for|since"], "I've lived in my house for five years.", "Oh, that's a long time!"),
         tour("awa", "When did you start this mission?", "Tu as commencé cette mission quand ?",
              ["ago"], "I started it ten minutes ago.", "Well done! You're quick!")],
        ["for two years", "since 2020", "three days ago", "during the holidays"],
    ),
    mission(
        "3e-u3-m6", "Le titre parfait", "trouver les mots de la même famille",
        ["happy → happiness → unhappy", "safe → safety", "useful → useless"],
        {"consigne": "On écrit le journal. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["📰", "✏️", "🔤", "📻"],
         "liste": [
             mot("newspaper", True, "Oui ! « Newspaper », c'est le journal."),
             mot("headline", True, "Oui ! « Headline », c'est le titre, écrit en gros en haut du journal."),
             mot("pencil", True, "Oui ! « Pencil », c'est le crayon."),
             mot("letters", True, "Oui ! « Letters », ce sont les lettres : A, B, C…"),
             mot("drum", False, "« Drum », c'est le tambour. Il n'y en a pas ici. Regarde encore !"),
             mot("bed", False, "« Bed », c'est le lit. On travaille, on ne dort pas ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Headline: The road is now safe!", "Titre : La route est maintenant sûre !"),
                       r("awa", "Better: Safety on the road!", "Mieux : La sécurité sur la route !"),
                       r("modou", "And for the library: Happiness in our school!", "Et pour la bibliothèque : Le bonheur dans notre collège !"),
                       r("awa", "Yes! Nobody is unhappy today.", "Oui ! Personne n'est malheureux aujourd'hui.")],
         "gainde": "Happy, happiness, unhappy… Et si j'ajoute encore des bouts ? « Unhappinessfulless » ! Ça veut dire quoi ?"},
        [q("« Safety », c'est…", ["la sécurité", "sûr", "dangereux"], 0, 1),
         q("« Unhappy » veut dire…", ["malheureux", "très heureux", "le bonheur"], 0, 3)],
        [choix("Je veux le titre « Le bonheur au collège ! ». Je dis laquelle ?", ["Happy at school!", "Happiness at school!"], 1,
               aides("Regarde ton carnet. Quel mot veut dire « le bonheur » ?", 2, "Écoute Modou :",
                     "Moi, j'écris : « sad → sadness (la tristesse) »",
                     "« -ness » fait un nom : happy (heureux) → happiness (le bonheur).")),
         ordre("« The new road safe is and useful. » C'est bien ça ?",
               ["safe", "The", "useful", "new", "and", "is", "road"], "The new road is safe and useful",
               "The new road is safe and useful.",
               aides("Par quoi commence la phrase : la chose, ou ce qu'elle est ?", 0, "Écoute Modou :",
                     "Moi, je dis : « The library is new and useful. »", "The new road + is + safe and useful.")),
         trou("Le contraire de « useful », c'est « unuseful » ? « The phone doesn't work. It's ___! »",
              "The phone doesn't work. It's", "!", ["useless"], "The phone doesn't work. It's useless!",
              aides("Regarde ton carnet : -ful, -less. Quel bout de mot veut dire « sans » ?", -1, "",
                    "Moi, je dis : « careful → careless »", "« -ful » = plein de. « -less » = sans. Useful → useless (inutile).")),
         libre("Je dis « Modou is not-not-happy ». Ça ne va pas… Fais une phrase avec le contraire de « happy » !",
               ["unhappy"],
               aides("Quel petit bout de mot dit « le contraire » ? Regarde ton carnet.", 3, "Écoute Awa :",
                     "Moi, je dis : « Modou is unhappy today. »", "« un- » fait le contraire : happy → unhappy."))],
        [tour("awa", "Give me a headline for our radio with « safety »!", "Donne-moi un titre pour la radio avec « safety » !",
              ["safety"], "Safety first at school!", "Perfect! That's our headline!"),
         tour("modou", "I lost my phone… How do I feel? Happy or…?", "J'ai perdu mon téléphone… Je me sens comment ? Heureux ou… ?",
              ["unhappy|sad"], "You're unhappy!", "Yes, very unhappy! Help me find it!")],
        ["happy → happiness → unhappy", "safe → safety", "useful → useless", "headline"],
    ),
]

unite3 = unite(
    "3e-u3", "Breaking news",
    "Le journal de Radio Jàng : fais une interview, puis raconte ce que la personne a dit.",
    u3,
    lignes=[
        ("Annoncer une nouvelle", "A library was opened. · The road has been repaired. · A school will be built."),
        ("Répéter ce qu'on a dit", "He said that… · He explained that…"),
        ("Répéter une question", "She asked me if… · She asked where…"),
        ("Répéter ce qu'il faut faire", "He told us to… · He told us not to…"),
        ("Dire quand et depuis quand", "for two years · since 2020 · three days ago · during the holidays"),
        ("Les mots de la même famille", "happy → happiness → unhappy · safe → safety · useful → useless"),
    ],
    mots=[
        ("news", "nouvelles", "xibaar"),
        ("radio", "radio", "rajo"),
        ("reporter", "journaliste", "taskatu xibaar"),
        ("question", "question", "laaj"),
        ("to say", "dire", "wax"),
        ("road", "route", "yoon"),
        ("year", "année", "at"),
        ("day", "jour", "bés"),
        ("happy", "heureux", "bég"),
        ("holidays", "vacances", "vakaas"),
    ],
    pieges=[
        "Since + une date (since 2020). For + une durée (for two years). Pas « since two years ».",
        "She asked me if I was ready. Pas « She asked me that… ».",
        "He told us not to run. Pas « He told us don't run ».",
        "She asked where the radio was. Pas « where was the radio ».",
    ],
    exercices=[
        ex("La route est réparée. Tu annonces :", ["The road has been repaired.", "The road has repaired.",
                                                    "The road is repair.", "The road was repair."], 0,
           "On ne dit pas qui a réparé : has been repaired."),
        ex("« A school will be built » parle…", ["de plus tard", "d'hier", "de maintenant", "d'il y a longtemps"], 0,
           "Will be built = sera construite, plus tard."),
        ex("Awa dit : « I'm tired. » Tu répètes :", ["She said that she was tired.", "She said that I am tired.",
                                                    "She said me that she was tired.", "She told that she tired."], 0,
           "She said that + she was…"),
        ex("« He explained that… » veut dire :", ["Il a expliqué que…", "Il a demandé si…", "Il nous a dit de…",
                                                  "Il a oublié que…"], 0,
           "Explained = a expliqué."),
        ex("Modou demande : « Are you ready? » Tu répètes :", ["He asked me if I was ready.", "He asked me that I was ready.",
                                                               "He asked me was I ready if.", "He said me if I was ready."], 0,
           "Pour une question « oui ou non » : asked me if…"),
        ex("Elle a demandé où était la radio :", ["She asked where the radio was.", "She asked where was the radio.",
                                                  "She asked if where the radio.", "She said where the radio was."], 0,
           "She asked where + la chose + was."),
        ex("Kocc Barma dit : « Don't run! » Tu répètes :", ["He told us not to run.", "He told us don't run.",
                                                           "He told us to not running.", "He said us not run."], 0,
           "He told us not to + ce qu'il ne faut pas faire."),
        ex("Complète : « I've lived here ______ 2020. »", ["for", "since", "ago", "during"], 1,
           "Since + une date."),
        ex("Il y a trois jours :", ["three days ago", "since three days", "for three days ago", "during three days"], 0,
           "Ago = il y a. On le met après la durée."),
        ex("Le nom de « safe » (sûr), c'est :", ["safety", "safely", "unsafe", "safeful"], 0,
           "Safety = la sécurité. Unsafe = pas sûr."),
    ],
)

UNITES = [unite1, unite2, unite3]

# ======================= ÉPISODES : RADIO JÀNG =======================

EPISODES = [
    episode("Radio Jàng, c'est parti… et ça s'entend !", "3e-u1-m2", [
        case("classe", [perso("awa", 0.05), perso("modou", 0.35), perso("gainde", 0.65, 95, "saute")],
             [bulle("Welcome to Radio Jàng!", "Bienvenue sur Radio Jàng ! (le premier jour de la radio du collège)", 0.02, 0.04),
              bulle("And here is our star: Gaïndé!", "Et voici notre star : Gaïndé !", 0.3, 0.3)]),
        case("classe", [perso("gainde", 0.35, 115, "saute")],
             [bulle("Radio Jàng is useful because… EVERYBODY can hear me!",
                    "Radio Jàng est utile parce que… TOUT LE MONDE m'entend ! (il rugit dans le micro : ROAAAR !)", 0.05, 0.05)]),
        case("cour", [perso("kocc", 0.1, 100, "tangue"), perso("bouc", 0.55, 80, "saute")],
             [bulle("The problem is… everybody can hear him!",
                    "Le problème, c'est que… tout le monde l'entend ! (le thé de Kocc Barma vole partout)", 0.02, 0.05),
              bulle("Bêêê!", "Bêêê ! (le bouc saute sur le mur)", 0.5, 0.35)]),
        case("classe", [perso("awa", 0.05), perso("gainde", 0.38, 95, "balance"), perso("modou", 0.7, 90, "danse")],
             [bulle("Gaïndé, the drawback of Radio Jàng is… you!", "Gaïndé, l'inconvénient de Radio Jàng, c'est… toi !", 0.02, 0.04),
              bulle("Thank you, Awa!", "Merci, Awa ! (il croit que c'est un compliment et fait une révérence)", 0.3, 0.35),
              bulle("Ha ha ha!", "Ha ha ha !", 0.65, 0.08)]),
    ], ["The advantage is that…", "It's useful because…", "The problem is…", "The drawback is…"]),

    episode("La troisième main de Gaïndé", "3e-u1-m4", [
        case("classe", [perso("awa", 0.05), perso("gainde", 0.5, 100)],
             [bulle("Today on Radio Jàng: wrestling at school. Gaïndé?", "Aujourd'hui sur Radio Jàng : la lutte à l'école. Gaïndé ?", 0.02, 0.04),
              bulle("On the one hand…", "D'un côté… (il lève une patte)", 0.45, 0.35)]),
        case("classe", [perso("gainde", 0.35, 110, "tangue")],
             [bulle("On the other hand…", "D'un autre côté… (il lève l'autre patte)", 0.05, 0.05),
              bulle("…and on the third hand…", "…et d'un troisième côté… (il lève un pied et tombe sur le dos)", 0.3, 0.4)]),
        case("nuit", [perso("modou", 0.05, 90, "immobile"), perso("gainde", 0.5, 100)],
             [bulle("To sum up, I think… on the one hand… on the other hand…",
                    "Pour finir, je pense… d'un côté… d'un autre côté… (il parle encore. Il fait nuit.)", 0.35, 0.04),
              bulle("Zzz…", "Zzz… (Modou dort sur la table)", 0.05, 0.35)]),
        case("nuit", [perso("kocc", 0.05, 95), perso("gainde", 0.38, 100, "saute"), perso("doudou", 0.7, 85)],
             [bulle("All in all, Gaïndé?", "En résumé, Gaïndé ?", 0.02, 0.04),
              bulle("All in all… I'm FOR wrestling!", "En résumé… je suis POUR la lutte ! (il fait une prise de lutte à Kocc Barma)", 0.3, 0.3),
              bulle("BOOM!", "BOUM ! (Kocc Barma tombe dans le tama de Doudou)", 0.62, 0.05)]),
    ], ["On the one hand…", "On the other hand…", "To sum up, I think…", "All in all…"]),

    episode("Le lion qui a bu la mer", "3e-u2-m2", [
        case("maison", [perso("awa", 0.05), perso("gainde", 0.5, 100)],
             [bulle("Today on Radio Jàng: fish contains proteins!", "Aujourd'hui sur Radio Jàng : le poisson contient des protéines !", 0.02, 0.04),
              bulle("Proteins? I love proteins!", "Des protéines ? J'adore les protéines ! (le plat de poisson du studio disparaît)", 0.4, 0.35)]),
        case("maison", [perso("modou", 0.05), perso("gainde", 0.5, 105, "saute")],
             [bulle("And milk makes you strong.", "Et le lait rend fort.", 0.02, 0.04),
              bulle("Strong? Give me ALL the milk!", "Fort ? Donne-moi TOUT le lait ! (il boit trois bidons de lait)", 0.4, 0.3)]),
        case("cour", [perso("gainde", 0.15, 115, "saute"), perso("kocc", 0.6, 85, "tangue")],
             [bulle("Look! Milk makes you STRONG!", "Regarde ! Le lait rend FORT ! (il soulève Kocc Barma avec une patte)", 0.02, 0.04),
              bulle("Gaïndé! Nooo!", "Gaïndé ! Nooon !", 0.55, 0.3)]),
        case("plage", [perso("awa", 0.05), perso("gainde", 0.38, 110), perso("poisson", 0.72, 70, "saute")],
             [bulle("Oh no! He ate the sugar too. Sugar makes you thirsty!", "Oh non ! Il a mangé le sucre aussi. Le sucre donne soif !", 0.02, 0.04),
              bulle("I'm SO thirsty!", "J'ai TELLEMENT soif ! (il boit la mer)", 0.32, 0.32),
              bulle("Hey!", "Hé ! (le poisson n'a plus d'eau)", 0.65, 0.1)]),
    ], ["It contains proteins.", "It's rich in…", "Milk makes you strong.", "Sugar makes you thirsty."]),

    episode("Kocc Barma en moustiquaire", "3e-u2-m4", [
        case("classe", [perso("gainde", 0.15, 105, "saute"), perso("awa", 0.62)],
             [bulle("Health tip of Radio Jàng! Be careful! Mosquitoes!", "Le conseil santé de Radio Jàng ! Attention ! Les moustiques !", 0.02, 0.04),
              bulle("Good, Gaïndé!", "Bien, Gaïndé !", 0.55, 0.35)]),
        case("classe", [perso("gainde", 0.05, 100, "saute"), perso("kocc", 0.55, 95)],
             [bulle("Be careful, Sir! A mosquito!", "Attention, Monsieur ! Un moustique ! (il tape sur le nez de Kocc Barma avec son livre)", 0.02, 0.04),
              bulle("Ouch!", "Aïe !", 0.55, 0.3)]),
        case("classe", [perso("kocc", 0.05, 95, "tangue"), perso("modou", 0.55)],
             [bulle("I have a headache…", "J'ai mal à la tête… (il a une grosse bosse)", 0.02, 0.04),
              bulle("Fever? Headache? The symptoms of malaria!", "Fièvre ? Mal de tête ? Les signes du paludisme !", 0.45, 0.3)]),
        case("nuit", [perso("gainde", 0.05, 100), perso("kocc", 0.38, 90, "immobile"), perso("awa", 0.7)],
             [bulle("You must sleep under a mosquito net, Sir!",
                    "Vous devez dormir sous une moustiquaire, Monsieur ! (il a roulé Kocc Barma dans la moustiquaire, comme un nem)", 0.02, 0.04),
              bulle("Mmmf!", "Mmmf !", 0.38, 0.35),
              bulle("Gaïndé! It's not malaria. It's YOU!", "Gaïndé ! Ce n'est pas le paludisme. C'est TOI !", 0.6, 0.08)]),
    ], ["The symptoms are…", "I have a headache.", "Be careful!", "You must…"]),

    episode("La route est contente !", "3e-u3-m2", [
        case("cour", [perso("kocc", 0.05, 95), perso("gainde", 0.55, 95)],
             [bulle("The road has been repaired. I'm happy!", "La route a été réparée. Je suis content !", 0.02, 0.04),
              bulle("Repaired… road… happy…", "Réparée… route… content… (il écrit dans son carnet, très vite)", 0.45, 0.35)]),
        case("classe", [perso("gainde", 0.1, 110, "saute"), perso("awa", 0.62)],
             [bulle("Breaking news! Kocc Barma said that… the road was happy!",
                    "Flash spécial ! Kocc Barma a dit que… la route était contente !", 0.02, 0.04),
              bulle("What?!", "Quoi ?!", 0.6, 0.35)]),
        case("marche", [perso("modou", 0.05, 90, "danse"), perso("doudou", 0.4, 90, "danse2"), perso("mouton", 0.72, 75, "saute")],
             [bulle("Breaking news! The road is happy!", "Flash spécial ! La route est contente !", 0.02, 0.04),
              bulle("Let's dance for the happy road!", "Dansons pour la route contente ! (tout le quartier danse sur la route, même le mouton)", 0.38, 0.3)]),
        case("cour", [perso("kocc", 0.05, 100), perso("gainde", 0.55, 95, "balance")],
             [bulle("I said that I was happy! Not the road!", "J'ai dit que MOI, j'étais content ! Pas la route !", 0.02, 0.04),
              bulle("Breaking news! Kocc Barma is not a road!", "Flash spécial ! Kocc Barma n'est pas une route !", 0.4, 0.38)]),
    ], ["Breaking news!", "… has been repaired.", "He said that…", "I said that…"]),

    episode("Gaïndé ne crie pas… TRÈS FORT", "3e-u3-m4", [
        case("classe", [perso("kocc", 0.05, 95), perso("awa", 0.38), perso("gainde", 0.68, 90)],
             [bulle("Radio Jàng is good. But please, don't shout!", "Radio Jàng, c'est bien. Mais s'il vous plaît, ne criez pas !", 0.02, 0.04),
              bulle("OK, Sir!", "D'accord, Monsieur !", 0.35, 0.35)]),
        case("classe", [perso("modou", 0.05, 85, "tangue"), perso("gainde", 0.5, 110, "saute")],
             [bulle("Sorry, I'm late! What did Kocc Barma tell us?", "Pardon, je suis en retard ! Qu'est-ce que Kocc Barma nous a dit ?", 0.02, 0.04),
              bulle("HE TOLD US NOT TO SHOUT!!!", "IL NOUS A DIT DE NE PAS CRIER !!! (au micro. Modou s'envole.)", 0.4, 0.3)]),
        case("cour", [perso("kocc", 0.05, 100, "tangue"), perso("gainde", 0.55, 95)],
             [bulle("Gaïndé! I told you not to shout!", "Gaïndé ! Je t'ai dit de ne pas crier ! (ses quatre touffes sont toutes droites)", 0.02, 0.04),
              bulle("No, Sir! You told US. I am ME!", "Non, Monsieur ! Vous avez dit « nous ». Moi, c'est MOI !", 0.4, 0.38)]),
        case("cour", [perso("awa", 0.05), perso("kocc", 0.38, 100, "saute"), perso("gainde", 0.7, 90)],
             [bulle("Sir, the headmaster asked me if you were OK.", "Monsieur, le directeur m'a demandé si vous alliez bien.", 0.02, 0.04),
              bulle("WHAT? I CAN'T HEAR YOU!", "QUOI ? JE NE T'ENTENDS PAS ! (maintenant, c'est Kocc Barma qui crie le plus fort)", 0.3, 0.3),
              bulle("Sir… please, don't shout!", "Monsieur… s'il vous plaît, ne criez pas !", 0.6, 0.08)]),
    ], ["He told us not to…", "She asked me if…", "What did he tell us?"]),

    episode("Unhappinessfulless", "3e-u3-m6", [
        case("classe", [perso("awa", 0.05), perso("gainde", 0.5, 100, "saute")],
             [bulle("We need a headline. The new road is safe.", "Il nous faut un titre. La nouvelle route est sûre.", 0.02, 0.04),
              bulle("Easy! I'm the headline champion!", "Facile ! Je suis le champion des titres !", 0.42, 0.35)]),
        case("classe", [perso("gainde", 0.05, 105, "saute"), perso("kocc", 0.55, 95)],
             [bulle("Headline: UN-SAFE-TY-FUL-LESS-NESS!", "Titre : IN-SÉCU-RI-TÉ-PLEIN-SANS-NESS ! (le mot fait toute la feuille)", 0.02, 0.04),
              bulle("What does it mean?", "Ça veut dire quoi ?", 0.55, 0.32),
              bulle("I don't know… but it's beautiful!", "Je ne sais pas… mais c'est beau !", 0.05, 0.45)]),
        case("cour", [perso("doudou", 0.05, 90), perso("gainde", 0.5, 100, "balance")],
             [bulle("Gaïndé, how long have you been here?", "Gaïndé, tu es là depuis combien de temps ?", 0.02, 0.04),
              bulle("Since eight o'clock! For ten hours!", "Depuis huit heures ! Depuis dix heures de temps ! (il a des feuilles collées sur la crinière)", 0.4, 0.35)]),
        case("nuit", [perso("awa", 0.05), perso("gainde", 0.38, 95, "immobile"), perso("modou", 0.7, 90, "danse")],
             [bulle("Gaïndé, the news finished three hours ago!", "Gaïndé, le journal est fini depuis trois heures !", 0.02, 0.04),
              bulle("Oh… I'm unhappy.", "Oh… je suis malheureux.", 0.32, 0.36),
              bulle("Headline: Unhappy lion, happy radio!", "Titre : Lion malheureux, radio heureuse !", 0.6, 0.08)]),
    ], ["for ten hours", "since eight o'clock", "three hours ago", "safe → safety", "happy → unhappy"]),
]
