"""Parcours d'anglais de 3e, unités 4 à 6 (saison « Radio Jàng », suite et fin)."""
from jang_lib import *  # noqa: F401,F403

NIVEAU = "3e"

# ======================= UNITÉ 4 : WISHES AND REGRETS =======================

u4 = [
    mission(
        "3e-u4-m1", "Si seulement…", "dire ce que je voudrais avoir maintenant",
        ["I wish I had a bike.", "If only I were taller!"],
        {"consigne": "Dans la cour. Quels mots vont avec l'image ?", "fond": "cour", "objets": ["🚲", "🏀", "📱", "🌳"],
         "liste": [
             mot("bike", True, "Oui ! « Bike », c'est le vélo."),
             mot("basketball", True, "Oui ! « Basketball », c'est le basket. On voit le ballon."),
             mot("phone", True, "Oui ! « Phone », c'est le téléphone."),
             mot("tree", True, "Oui ! « Tree », c'est l'arbre de la cour."),
             mot("car", False, "« Car », c'est la voiture. Il n'y a pas de voiture dans la cour. Regarde encore !"),
             mot("plane", False, "« Plane », c'est l'avion. Tu vois un avion ? Non ! Regarde encore."),
             mot("horse", False, "« Horse », c'est le cheval. Il n'y a pas de cheval ici. Regarde encore !"),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Look at that bike! I wish I had a bike.", "Regarde ce vélo ! J'aimerais avoir un vélo."),
                       r("awa", "And look at the basketball team. If only I were taller!",
                         "Et regarde l'équipe de basket. Si seulement j'étais plus grande !"),
                       r("modou", "I wish I had a phone, too.", "J'aimerais aussi avoir un téléphone.")],
         "gainde": "« I wish »… C'est pour dire un vœu ? Moi, j'ai mille vœux pour la radio !"},
        [q("Qu'est-ce que Modou voudrait avoir ?", ["un vélo", "un ballon", "un chat"], 0, 0),
         q("Awa dit « If only I were taller! ». Elle voudrait…", ["être plus grande", "être plus forte", "avoir un vélo"], 0, 1)],
        [choix("À la radio, je dis mon vœu. Je dis laquelle ?", ["I wish I have a bike.", "I wish I had a bike."], 1,
               aides("Regarde ton carnet. Modou dit « I wish I… » quoi ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I wish I had a big book. »",
                     "Après « I wish I », on dit « had », pas « have ». C'est un vœu, pas la vraie vie.")),
         ordre("« I wish had I a phone. » Ça sonne bizarre…", ["had", "a phone", "I wish", "I"], "I wish I had a phone",
               "I wish I had a phone.",
               aides("Par quoi commence un vœu ?", 2, "Écoute Modou :",
                     "Moi, je dis : « I wish I had a phone. »", "I wish (j'aimerais) + I had (avoir) + a phone.")),
         trou("Je suis petit. « If only I ___ taller! »", "If only I", "taller!", ["were", "was"], "If only I were taller!",
              aides("Comment Awa dit-elle son vœu ?", 1, "Écoute Awa :",
                    "Moi, je dis : « If only I were taller! »", "Il manque « were ». Écris : were.")),
         libre("Je n'ai pas de vélo. Je veux dire mon vœu. Comment je dis ?", ["wish|if only", "had", "bike"],
               aides("Regarde ton carnet : comment Modou dit-il son vœu ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I wish I had a bike. »", "Écris : « I wish I had a bike. »"))],
        [tour("modou", "Radio Jàng! What's your wish today?", "Radio Jàng ! C'est quoi, ton vœu aujourd'hui ?",
              ["wish|if only", "had|were|was|could"], "I wish I had a new phone.", "Me too! Great wish!"),
         tour("awa", "Tell me a wish about you. If only I were…?", "Dis-moi un vœu sur toi. Si seulement j'étais… ?",
              ["if only|wish", "were|was"], "If only I were taller!", "Ha ha! Me too!")],
        ["I wish I had a bike.", "If only I were taller!", "I wish I had…"],
    ),
    mission(
        "3e-u4-m2", "Pourvu qu'il pleuve", "dire ce que je voudrais pour demain",
        ["I wish it would rain.", "I wish you would stop."],
        {"consigne": "Il fait très chaud. Quels mots vont avec l'image ?", "fond": "cour", "objets": ["☀️", "🌾", "💧", "🥵"],
         "liste": [
             mot("sun", True, "Oui ! « Sun », c'est le soleil. Il est très fort."),
             mot("hot", True, "Oui ! « Hot », c'est chaud. Tout le monde a chaud."),
             mot("field", True, "Oui ! « Field », c'est le champ."),
             mot("water", True, "Oui ! « Water », c'est l'eau. Il en reste un peu."),
             mot("rain", False, "« Rain », c'est la pluie. Il ne pleut pas encore : tout est sec ! Regarde encore."),
             mot("snow", False, "« Snow », c'est la neige. Avec ce soleil ? Non ! Regarde encore."),
             mot("moon", False, "« Moon », c'est la lune. C'est le jour, pas la nuit. Regarde encore !"),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "It's so hot today! I wish it would rain.", "Il fait si chaud aujourd'hui ! Pourvu qu'il pleuve."),
                       r("awa", "Yes, the fields need water.", "Oui, les champs ont besoin d'eau."),
                       r("gainde", "La la laaa!", "La la laaa ! (il chante très fort)"),
                       r("awa", "Gaïndé, please! I wish you would stop singing!",
                         "Gaïndé, s'il te plaît ! J'aimerais que tu arrêtes de chanter !")],
         "gainde": "Awa veut que j'arrête ? Mais ma voix est parfaite pour la radio !"},
        [q("Qu'est-ce que Modou voudrait ?", ["qu'il pleuve", "qu'il fasse plus chaud", "aller à la mer"], 0, 0),
         q("Awa dit « I wish you would stop ». Elle veut que Gaïndé…", ["arrête de chanter", "chante plus fort", "parte"], 0, 3)],
        [choix("Il fait trop chaud. Je dis laquelle ?", ["I wish it rains.", "I wish it would rain."], 1,
               aides("Regarde ton carnet : après « I wish it… », quel petit mot vient ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I wish it would rain. »",
                     "Pour plus tard, on dit « I wish it would… ». « Would », c'est comme « -rait » en français.")),
         ordre("« I wish would you stop. » C'est bon ?", ["would", "I wish", "stop", "you"], "I wish you would stop",
               "I wish you would stop.",
               aides("Qui doit arrêter ? Ce mot vient avant « would ».", 3, "Écoute Awa :",
                     "Moi, je dis : « I wish you would stop. »", "I wish (j'aimerais) + you would stop (que tu arrêtes).")),
         trou("Le bus est en retard ! « I wish the bus ___ come! »", "I wish the bus", "come!", ["would"],
              "I wish the bus would come!",
              aides("Quel petit mot Modou met-il après « I wish it » ?", 0, "Écoute Modou :",
                    "« I wish it would rain. »", "Il manque « would ». Écris : would.")),
         libre("Modou parle trop fort. Je veux qu'il arrête. Je lui dis quoi ?", ["wish", "would stop"],
               aides("Comment Awa parle-t-elle à Gaïndé ?", 3, "Écoute Awa :",
                     "Moi, je dis : « Modou, I wish you would stop! »", "Écris : « I wish you would stop! »"))],
        [tour("awa", "The football match is tomorrow. What do you wish?", "Le match de foot, c'est demain. Tu voudrais quoi ?",
              ["wish", "would|wouldnt"], "I wish our team would win!", "Yes! Me too!"),
         tour("modou", "Gaïndé sings all night. What do you say to him?", "Gaïndé chante toute la nuit. Tu lui dis quoi ?",
              ["wish", "would stop"], "Gaïndé, I wish you would stop!", "Ha ha! Poor Gaïndé!")],
        ["I wish it would rain.", "I wish you would stop.", "I wish… would…"],
    ),
    mission(
        "3e-u4-m3", "Gaïndé regrette", "dire ce que je regrette",
        ["I wish I hadn't said that.", "I wish I hadn't eaten all the cake."],
        {"consigne": "À la radio du collège. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["🎙️", "🎧", "📻"],
         "liste": [
             mot("microphone", True, "Oui ! « Microphone », c'est le micro. On parle dedans."),
             mot("headphones", True, "Oui ! « Headphones », c'est le casque pour écouter."),
             mot("radio", True, "Oui ! « Radio », c'est la radio du collège."),
             mot("table", True, "Oui ! « Table », c'est la table. Le micro est dessus."),
             mot("television", False, "« Television », c'est la télé. À la radio, on écoute, on ne regarde pas ! Regarde encore."),
             mot("guitar", False, "« Guitar », c'est la guitare. Il n'y a pas de guitare ici. Regarde encore !"),
             mot("camera", False, "« Camera », c'est l'appareil photo. Tu en vois un ? Non ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["gainde", "modou", "awa"],
         "repliques": [r("gainde", "Good morning, Radio Jàng! Modou's football team is very bad!",
                         "Bonjour, Radio Jàng ! L'équipe de foot de Modou est très nulle !"),
                       r("modou", "What?! Gaïndé! Everybody is listening!", "Quoi ?! Gaïndé ! Tout le monde écoute !"),
                       r("gainde", "Oh no… I wish I hadn't said that.", "Oh non… Je regrette d'avoir dit ça."),
                       r("awa", "And I wish I hadn't given you the microphone!", "Et moi, je regrette de t'avoir donné le micro !")],
         "gainde": "J'ai dit une bêtise à la radio. Comment on dit qu'on regrette, déjà ?"},
        [q("Pourquoi Modou n'est pas content ?", ["Gaïndé dit que son équipe est nulle.", "Gaïndé a cassé le micro.",
                                                   "Gaïndé est en retard."], 0, 0),
         q("« I wish I hadn't said that » veut dire…", ["Je regrette d'avoir dit ça.", "Je veux dire ça.", "J'ai oublié ça."], 0, 2)],
        [choix("Je regrette ma phrase. Je dis laquelle ?", ["I wish I didn't say that.", "I wish I hadn't said that."], 1,
               aides("Regarde ton carnet : qu'est-ce que Gaïndé dit dans la scène ?", 2, "Écoute Gaïndé :",
                     "Moi, je dis : « I wish I hadn't said that. »",
                     "Pour un regret : « I wish I hadn't… » + ce que j'ai fait.")),
         ordre("« I wish said I hadn't that. » C'est ça ?", ["said", "I wish", "that", "I hadn't"], "I wish I hadnt said that",
               "I wish I hadn't said that.",
               aides("Le regret commence par « I wish ». Et ensuite ?", 2, "Écoute Gaïndé :",
                     "Moi, je dis : « I wish I hadn't said that. »", "I wish + I hadn't (je n'aurais pas) + said that (dit ça).")),
         trou("J'ai mangé tout le gâteau ! « I wish I hadn't ___ all the cake. »", "I wish I hadn't", "all the cake.",
              ["eaten"], "I wish I hadn't eaten all the cake.",
              aides("Manger, c'est « eat ». Après « hadn't », le mot change un peu. Tu le connais ?", 3,
                    "Écoute Awa : « given », c'est « give » qui a changé.",
                    "Moi, je dis : « I have eaten. » C'est le même mot.", "Il manque « eaten ». Écris : eaten.")),
         libre("J'ai crié sur Awa. Je le regrette. Je lui dis quoi ?", ["wish i hadnt|wish i had not"],
               aides("Comment commence un regret ?", 2, "Écoute Gaïndé :",
                     "Moi, je dis : « Sorry, Awa. I wish I hadn't shouted. »", "Écris : « I wish I hadn't shouted. »"))],
        [tour("modou", "You laughed at my team on the radio! What do you say now?",
              "Tu t'es moqué de mon équipe à la radio ! Tu dis quoi maintenant ?",
              ["wish i hadnt|wish i had not"], "Sorry, Modou. I wish I hadn't said that.", "OK, OK. It's fine!"),
         tour("awa", "Tell me something you regret.", "Dis-moi une chose que tu regrettes.",
              ["wish i hadnt|wish i had not|wish i had"], "I wish I hadn't eaten all the cake.", "Ha ha! Me too!")],
        ["I wish I hadn't said that.", "I wish I hadn't eaten all the cake.", "Sorry!"],
    ),
    mission(
        "3e-u4-m4", "Le courrier du cœur", "écrire pour demander de l'aide",
        ["Dear Awa,", "I have a problem…", "What should I do?"],
        {"consigne": "Le courrier de Radio Jàng. Quels mots vont avec l'image ?", "fond": "bibliotheque",
         "objets": ["✉️", "📝", "🖊️"],
         "liste": [
             mot("letter", True, "Oui ! « Letter », c'est la lettre."),
             mot("envelope", True, "Oui ! « Envelope », c'est l'enveloppe de la lettre."),
             mot("paper", True, "Oui ! « Paper », c'est le papier."),
             mot("pen", True, "Oui ! « Pen », c'est le stylo pour écrire."),
             mot("ball", False, "« Ball », c'est le ballon. On ne joue pas, on écrit ! Regarde encore."),
             mot("computer", False, "« Computer », c'est l'ordinateur. Il n'y en a pas ici : on écrit à la main. Regarde encore !"),
         ]},
        {"fond": "bibliotheque", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Dear Awa, I have a problem. My friends want me to smoke.",
                         "Chère Awa, j'ai un problème. Mes amis veulent que je fume."),
                       r("awa", "I don't want to. What should I do? Ibou.",
                         "Je ne veux pas. Qu'est-ce que je dois faire ? Ibou."),
                       r("modou", "Poor Ibou! It's peer pressure.", "Pauvre Ibou ! Ses amis le poussent."),
                       r("awa", "Ibou, you should resist. Say no!", "Ibou, tu dois résister. Dis non !")],
         "gainde": "Une lettre pour demander de l'aide ? Moi aussi, j'en écris une ! Mais je commence comment ?"},
        [q("Comment commence la lettre d'Ibou ?", ["Dear Awa,", "Goodbye Awa,", "Hey you,"], 0, 0),
         q("« What should I do? » veut dire…", ["Qu'est-ce que je dois faire ?", "Où est-ce que je vais ?",
                                                "Qu'est-ce que tu fais ?"], 0, 1)],
        [choix("J'écris à Awa pour demander de l'aide. Je commence par laquelle ?",
               ["Awa! Problem! Help! Help!", "Dear Awa, I have a problem."], 1,
               aides("Regarde ton carnet : comment Ibou commence-t-il sa lettre ?", 0, "Écoute le début :",
                     "Moi, j'écris : « Dear Awa, I have a problem. »",
                     "Une lettre commence par « Dear » + le nom. « Dear », c'est « Cher » ou « Chère ».")),
         ordre("« What I should do? » C'est ça ?", ["I", "should", "do", "What"], "What should I do", "What should I do?",
               aides("Dans la question, « should » vient avant ou après « I » ?", 1, "Écoute la fin de la lettre :",
                     "Moi, j'écris : « What should I do? »", "What (quoi) + should I do (dois-je faire).")),
         trou("Le premier mot de ma lettre : « ___ Awa, I have a problem. »", "", "Awa, I have a problem.", ["dear"],
              "Dear Awa, I have a problem.",
              aides("Quel mot vient avant le nom, en haut de la lettre ?", 0, "Écoute :",
                    "« Dear Awa, … »", "Il manque « Dear ». Écris : Dear.")),
         libre("Écris le début de ma lettre : « Chère Awa, j'ai un problème. »", ["dear awa", "problem"],
               aides("Comment Ibou commence-t-il ?", 0, "Écoute :",
                     "Moi, j'écris : « Dear Awa, I have a problem. »", "Écris : « Dear Awa, I have a problem. »"))],
        [tour("awa", "Write to Radio Jàng! Tell me your problem and ask for help.",
              "Écris à Radio Jàng ! Dis-moi ton problème et demande de l'aide.",
              ["dear", "problem", "what should i do"],
              "Dear Awa, I have a problem. I can't wake up early. What should I do?",
              "Thank you for your letter! You should go to bed early.")],
        ["Dear Awa,", "I have a problem.", "What should I do?", "peer pressure", "to resist"],
    ),
]

unite4 = unite(
    "3e-u4", "Wishes and regrets",
    "Mes vœux : écris une lettre à toi, dans 5 ans. Dis ce que tu voudrais, et ce que tu regrettes.",
    u4,
    lignes=[
        ("Dire ce que je voudrais avoir", "I wish I had a bike. · If only I were taller!"),
        ("Dire ce que je voudrais pour demain", "I wish it would rain. · I wish you would stop."),
        ("Dire ce que je regrette", "I wish I hadn't said that. · I wish I hadn't eaten all the cake."),
        ("Écrire pour demander de l'aide", "Dear Awa, · I have a problem. · What should I do?"),
    ],
    mots=[
        ("bike", "vélo", "welo"),
        ("rain", "pluie", "taw"),
        ("tall", "grand", "gudd"),
        ("tomorrow", "demain", "ëllëg"),
        ("problem", "problème", "jafe-jafe"),
        ("help", "aide", "ndimbal"),
        ("letter", "lettre", "bataaxal"),
        ("friend", "ami(e)", "xarit"),
        ("family", "famille", "njaboot"),
        ("relatives", "les parents, la famille", "mbokk"),
        ("marriage", "mariage", "séy"),
        ("to regret", "regretter", "réccu"),
    ],
    pieges=[
        "I wish I had a bike. Pas « I wish I have a bike ».",
        "I wish I hadn't said that. Pas « I wish I didn't say that ».",
        "What should I do? Pas « What I should do? ».",
    ],
    exercices=[
        ex("Tu n'as pas de vélo. Tu dis :", ["I wish I have a bike.", "I wish I had a bike.", "I wish I having a bike.",
                                             "I wish a bike I had."], 1, "Pour un vœu : I wish I had…"),
        ex("« If only I were taller! » veut dire :", ["Si seulement j'étais plus grand !", "Je suis très grand !",
                                                      "Avant, j'étais grand.", "Je veux être petit."], 0,
           "« If only », c'est « si seulement ». « Taller », c'est « plus grand »."),
        ex("Il fait chaud. Tu voudrais de la pluie :", ["I wish it rains.", "I wish it would rain.", "I wish rain it.",
                                                        "I wish it raining."], 1,
           "Pour plus tard : I wish it would…"),
        ex("Ton petit frère fait du bruit. Tu dis :", ["I wish you stop.", "I wish you would stop.", "I wish you stopping.",
                                                       "I wish would you stop."], 1,
           "I wish you would stop = j'aimerais que tu arrêtes."),
        ex("Tu regrettes ta phrase. Tu dis :", ["I wish I didn't say that.", "I wish I hadn't said that.",
                                                "I wish I don't say that.", "I wish I not said that."], 1,
           "Pour un regret : I wish I hadn't + said, eaten…"),
        ex("Complète : « I wish I hadn't ____ all the cake. »", ["eat", "eaten", "eating", "eats"], 1,
           "Après « hadn't » : eaten, said, given…"),
        ex("Une lettre pour demander de l'aide commence par :", ["Dear Awa,", "Goodbye Awa,", "Thanks Awa,", "Sorry Awa,"], 0,
           "Une lettre commence par « Dear » + le nom."),
        ex("« What should I do? » veut dire :", ["Qu'est-ce que je dois faire ?", "Qu'est-ce que tu fais ?",
                                                 "Où dois-je aller ?", "Qui dois-je appeler ?"], 0,
           "« Should », c'est « devoir », pour un conseil."),
        ex("Remets en ordre : should / What / do / I", ["What should I do?", "What I should do?", "Should what I do?",
                                                         "What do I should?"], 0,
           "Dans la question : What + should + I + do."),
        ex("« Peer pressure », c'est quand…", ["tes amis te poussent à faire une chose", "tu es malade",
                                               "tu reçois une lettre", "il pleut beaucoup"], 0,
           "« Peer pressure » : tes amis te poussent. Tu peux résister : « to resist »."),
    ],
)

# ======================= UNITÉ 5 : TELLING STORIES =======================

u5 = [
    mission(
        "3e-u5-m1", "Quand on était en 6e…", "dire ce que je faisais avant",
        ["We used to play in the street.", "I used to…"],
        {"consigne": "Dans le quartier. Quels mots vont avec l'image ?", "fond": "cour", "objets": ["⚽", "🏘️", "👦", "🧦"],
         "liste": [
             mot("ball", True, "Oui ! « Ball », c'est le ballon."),
             mot("street", True, "Oui ! « Street », c'est la rue du quartier."),
             mot("houses", True, "Oui ! « Houses », ce sont les maisons."),
             mot("children", True, "Oui ! « Children », ce sont les enfants."),
             mot("beach", False, "« Beach », c'est la plage. Il n'y a pas de sable ni de mer ici. Regarde encore !"),
             mot("classroom", False, "« Classroom », c'est la salle de classe. On est dehors ! Regarde encore."),
             mot("bus", False, "« Bus », c'est le car. Tu vois un car ? Non ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "kocc", "gainde"],
         "repliques": [r("awa", "Kocc Barma, when you were in 6e, what did you use to do?",
                         "Kocc Barma, quand tu étais en 6e, qu'est-ce que tu faisais ?"),
                       r("kocc", "We used to play football in the street.", "On jouait au foot dans la rue."),
                       r("kocc", "We used to make a ball with old socks!", "On faisait un ballon avec de vieilles chaussettes !"),
                       r("awa", "Wow! Today we have real balls.", "Waouh ! Aujourd'hui, on a de vrais ballons.")],
         "gainde": "Kocc Barma a été en 6e ? Je croyais qu'il était né avec ses lunettes !"},
        [q("Qu'est-ce que Kocc Barma faisait en 6e ?", ["Il jouait au foot dans la rue.", "Il parlait à la radio.",
                                                         "Il dormait en classe."], 0, 1),
         q("Avec quoi faisaient-ils le ballon ?", ["de vieilles chaussettes", "du papier", "des mangues"], 0, 2)],
        [choix("En 6e, je jouais dans la rue. Je dis laquelle ?",
               ["I am used to play in the street.", "I used to play in the street."], 1,
               aides("Regarde ton carnet : qu'est-ce que Kocc Barma dit pour « avant » ?", 1, "Écoute Kocc Barma :",
                     "Moi, je dis : « I used to play football. »",
                     "Pour une chose qu'on faisait avant, et plus maintenant : « I used to… ».")),
         ordre("« We to used play in the street. » C'est ça ?", ["play", "We", "in the street", "used to"],
               "We used to play in the street", "We used to play in the street.",
               aides("Qu'est-ce qui vient juste après « We » ?", 1, "Écoute Kocc Barma :",
                     "Moi, je dis : « We used to play in the street. »", "We + used to (avant, on…) + play + in the street.")),
         trou("Avant, j'habitais à Thiès. « I ___ to live in Thiès. »", "I", "to live in Thiès.", ["used"],
              "I used to live in Thiès.",
              aides("Quel mot Kocc Barma dit-il avant « to play » ?", 1, "Écoute :",
                    "« We used to play… »", "Il manque « used ». Écris : used.")),
         libre("Dis ce que tu faisais quand tu étais petit.", ["used to"],
               aides("Quels petits mots disent « avant, je… » ?", 1, "Écoute Kocc Barma :",
                     "Moi, je dis : « When I was little, I used to sleep a lot. »",
                     "Écris : « I used to… » + ce que tu faisais."))],
        [tour("awa", "Radio Jàng interview! When you were in 6e, what did you use to do?",
              "Interview de Radio Jàng ! Quand tu étais en 6e, qu'est-ce que tu faisais ?",
              ["used to"], "I used to play football with my friends.", "That's nice! Thank you!"),
         tour("modou", "What did you use to eat when you were little?", "Qu'est-ce que tu mangeais quand tu étais petit ?",
              ["used to"], "I used to eat a lot of mangoes.", "Me too! I used to love mangoes!")],
        ["We used to play in the street.", "I used to…", "When I was in 6e,…"],
    ),
    mission(
        "3e-u5-m2", "Tous les jours", "dire ce que je fais d'habitude",
        ["I usually walk to school.", "I'm used to getting up early."],
        {"consigne": "C'est le matin. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["⏰", "🌅", "🎒", "🍞"],
         "liste": [
             mot("alarm clock", True, "Oui ! « Alarm clock », c'est le réveil. Il sonne !"),
             mot("morning", True, "Oui ! « Morning », c'est le matin. Le soleil se lève."),
             mot("bag", True, "Oui ! « Bag », c'est le sac pour l'école."),
             mot("bread", True, "Oui ! « Bread », c'est le pain du petit-déjeuner."),
             mot("moon", False, "« Moon », c'est la lune. C'est la nuit. Là, c'est le matin ! Regarde encore."),
             mot("beach", False, "« Beach », c'est la plage. On est à la maison. Regarde encore !"),
         ]},
        {"fond": "cour", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Modou, how do you come to school?", "Modou, comment tu viens au collège ?"),
                       r("modou", "I usually walk to school. It takes thirty minutes.",
                         "D'habitude, je viens à pied. Ça prend trente minutes."),
                       r("awa", "Thirty minutes! You get up early!", "Trente minutes ! Tu te lèves tôt !"),
                       r("modou", "Yes, at six. I'm used to getting up early.", "Oui, à six heures. J'ai l'habitude de me lever tôt.")],
         "gainde": "« Used to »… comme Kocc Barma ? Mais Modou parle d'aujourd'hui, pas d'avant !"},
        [q("Comment Modou vient-il au collège, d'habitude ?", ["à pied", "en bus", "à vélo"], 0, 1),
         q("« I'm used to getting up early » veut dire…", ["J'ai l'habitude de me lever tôt.", "Avant, je me levais tôt.",
                                                            "Je ne me lève jamais tôt."], 0, 3)],
        [choix("Je me lève tôt tous les jours. Je dis laquelle ?",
               ["I'm used to get up early.", "I'm used to getting up early."], 1,
               aides("Regarde ton carnet : après « I'm used to », Modou dit « get » ou « getting » ?", 3, "Écoute Modou :",
                     "Moi, je dis : « I'm used to getting up early. »",
                     "Après « I'm used to », le mot finit par « -ing » : getting, walking.")),
         ordre("« I walk usually to school. » Hmm…", ["walk", "usually", "to school", "I"], "I usually walk to school",
               "I usually walk to school.",
               aides("Où Modou met-il « usually » : avant ou après « walk » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I usually walk to school. »", "I + usually (d'habitude) + walk (marche) + to school.")),
         trou("Je marche tous les jours. « I'm used to ___ to school. »", "I'm used to", "to school.", ["walking"],
              "I'm used to walking to school.",
              aides("Après « I'm used to », le mot finit comment ?", 3, "Écoute la fin de Modou :",
                    "« I'm used to getting up early. »", "Marcher, c'est « walk ». Ici, on dit « walking ».")),
         libre("Dis comment tu viens au collège, d'habitude.", ["usually"],
               aides("Quel mot veut dire « d'habitude » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I usually take the bus. »", "Écris : « I usually… » + comment tu viens."))],
        [tour("awa", "What time do you usually get up?", "Tu te lèves à quelle heure, d'habitude ?",
              ["usually|used to"], "I usually get up at six.", "Wow, early!"),
         tour("modou", "You come to school on foot? Is it hard for you?", "Tu viens à pied ? C'est dur pour toi ?",
              ["used to|usually"], "No, I'm used to walking.", "Me too! I'm used to it.")],
        ["I usually walk to school.", "I'm used to getting up early.", "I'm used to walking."],
    ),
    mission(
        "3e-u5-m3", "Pendant que je marchais…", "raconter deux choses qui arrivent en même temps",
        ["While I was walking, I saw an accident.", "While I was eating, I heard the news."],
        {"consigne": "Dans la rue, près du marché. Quels mots vont avec l'image ?", "fond": "marche",
         "objets": ["🚕", "🛵", "🐐", "🚶"],
         "liste": [
             mot("taxi", True, "Oui ! « Taxi », c'est le taxi jaune et noir."),
             mot("motorbike", True, "Oui ! « Motorbike », c'est la moto."),
             mot("goat", True, "Oui ! « Goat », c'est la chèvre, au bord de la rue."),
             mot("street", True, "Oui ! « Street », c'est la rue."),
             mot("sea", False, "« Sea », c'est la mer. On est en ville, près du marché. Regarde encore !"),
             mot("plane", False, "« Plane », c'est l'avion. Tu vois un avion ? Non ! Regarde encore."),
             mot("library", False, "« Library », c'est la bibliothèque. On est dehors ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "This morning, while I was walking to school, I saw an accident.",
                         "Ce matin, pendant que je marchais vers le collège, j'ai vu un accident."),
                       r("awa", "Oh no! Was anybody hurt?", "Oh non ! Quelqu'un a été blessé ?"),
                       r("modou", "No. A taxi hit a motorbike, but nobody was hurt.",
                         "Non. Un taxi a touché une moto, mais personne n'a été blessé."),
                       r("awa", "Phew! While I was eating breakfast, I heard it on the radio.",
                         "Ouf ! Pendant que je prenais mon petit-déjeuner, je l'ai entendu à la radio.")],
         "gainde": "Deux choses en même temps ? Facile ! Moi, je peux manger ET dormir en même temps !"},
        [q("Qu'est-ce que Modou faisait ?", ["Il marchait vers le collège.", "Il dormait.", "Il jouait au foot."], 0, 0),
         q("Quand Awa a entendu la nouvelle, elle…", ["prenait son petit-déjeuner", "marchait", "dormait"], 0, 3)],
        [choix("Je raconte ma matinée. Je dis laquelle ?",
               ["While I walked, I was seeing a goat.", "While I was walking, I saw a goat."], 1,
               aides("Regarde ton carnet : qu'est-ce que Modou faisait, et qu'est-ce qui est arrivé ?", 0, "Écoute Modou :",
                     "Moi, je dis : « While I was reading, I heard a noise. »",
                     "La chose longue : « I was walking ». La chose courte qui arrive : « I saw ».")),
         ordre("« While walking I was, I saw a goat. » C'est ça ?", ["walking", "I saw a goat", "While", "I was"],
               "While I was walking I saw a goat", "While I was walking, I saw a goat.",
               aides("Par quel mot Modou commence-t-il son histoire ?", 0, "Écoute Modou :",
                     "Moi, je dis : « While I was walking, I saw a goat. »",
                     "While (pendant que) + I was walking (je marchais) + I saw (j'ai vu).")),
         trou("« While I was ___, I heard the news. » (manger)", "While I was", ", I heard the news.",
              ["eating", "having breakfast", "eating breakfast"], "While I was eating, I heard the news.",
              aides("Awa faisait quoi quand elle a entendu la nouvelle ?", 3, "Écoute Awa :",
                    "« While I was eating breakfast… »", "Manger, c'est « eat ». Ici : eating.")),
         libre("Raconte : pendant que tu dormais, tu as entendu un bruit.", ["while|when", "sleeping", "heard"],
               aides("Quelle chose est longue : dormir ou entendre ?", 0, "Écoute Modou :",
                     "Moi, je dis : « While I was sleeping, I heard a noise. »",
                     "Écris : « While I was sleeping, I heard… »"))],
        [tour("modou", "Tell the radio! What happened while you were walking to school?",
              "Raconte à la radio ! Qu'est-ce qui s'est passé pendant que tu marchais vers le collège ?",
              ["while|when", "was"], "While I was walking, I saw a big sheep.", "Ha ha! Great story!")],
        ["While I was walking, I saw an accident.", "While I was eating, I heard the news.", "while"],
    ),
    mission(
        "3e-u5-m4", "La Tabaski de grand-père", "raconter une fête",
        ["Every year, we…", "On the big day…"],
        {"consigne": "C'est la Tabaski. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["🐑", "👗", "🍖", "🕌"],
         "liste": [
             mot("sheep", True, "Oui ! « Sheep », c'est le mouton de la Tabaski."),
             mot("new clothes", True, "Oui ! « New clothes », ce sont les habits neufs."),
             mot("meat", True, "Oui ! « Meat », c'est la viande."),
             mot("mosque", True, "Oui ! « Mosque », c'est la mosquée."),
             mot("Christmas tree", False, "« Christmas tree », c'est le sapin de Noël. Là, c'est la Tabaski ! Regarde encore."),
             mot("snow", False, "« Snow », c'est la neige. Il ne neige pas au Sénégal ! Regarde encore."),
             mot("school", False, "« School », c'est l'école. Le jour de la fête, on n'y va pas ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Modou, tell us about Tabaski at your grandfather's house.",
                         "Modou, raconte-nous la Tabaski chez ton grand-père."),
                       r("modou", "Every year, we go to his village. We buy a big sheep.",
                         "Chaque année, on va dans son village. On achète un gros mouton."),
                       r("modou", "On the big day, we wear new clothes and we pray.",
                         "Le grand jour, on met des habits neufs et on prie."),
                       r("modou", "Then we eat the meat with all the guests!", "Ensuite, on mange la viande avec tous les invités !")],
         "gainde": "Un gros mouton… Miam. Euh, non ! Je veux dire : bonjour, Monsieur le mouton !"},
        [q("Quand vont-ils au village ?", ["chaque année", "chaque semaine", "jamais"], 0, 1),
         q("Qu'est-ce qu'ils font le grand jour ?", ["Ils mettent des habits neufs et ils prient.", "Ils vont à la plage.",
                                                     "Ils vont à l'école."], 0, 2)],
        [choix("Je raconte la Korité. Je commence par laquelle ?", ["Every years, we visit our family.",
                                                                     "Every year, we visit our family."], 1,
               aides("Regarde ton carnet : Modou dit « Every year » ou « Every years » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « Every year, we visit my grandmother. »",
                     "Après « every », le mot reste sans « s » : every year, every day.")),
         ordre("« The big day on, we pray. » C'est bizarre…", ["the big day", "we pray", "On"], "On the big day we pray",
               "On the big day, we pray.",
               aides("Quel petit mot vient avant « the big day » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « On the big day, we pray. »", "On the big day (le grand jour) + we pray (on prie).")),
         trou("« ___ the big day, we wear new clothes. »", "", "the big day, we wear new clothes.", ["on"],
              "On the big day, we wear new clothes.",
              aides("Quel petit mot Modou met-il avant « the big day » ?", 2, "Écoute Modou :",
                    "« On the big day… »", "Il manque « On ». Écris : On.")),
         libre("Raconte une fête chez toi. Dis ce que vous faites chaque année.", ["every year"],
               aides("Comment Modou dit-il « chaque année » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « Every year, we visit my grandmother at Korité. »", "Écris : « Every year, we… »"))],
        [tour("awa", "Radio Jàng! Tell us about your favourite celebration. What do you do on the big day?",
              "Radio Jàng ! Parle-nous de ta fête préférée. Que faites-vous le grand jour ?",
              ["on the big day|every year|we"], "On the big day, we wear new clothes and we visit our family.",
              "Wonderful! Thank you!")],
        ["Every year, we…", "On the big day…", "guests", "new clothes"],
    ),
    mission(
        "3e-u5-m5", "Gaïndé chez le coiffeur", "dire ce qu'une autre personne fait pour moi (coiffeur…)",
        ["I had my hair cut.", "He had his phone repaired."],
        {"consigne": "Chez le coiffeur. Quels mots vont avec l'image ?", "fond": "marche", "objets": ["💈", "✂️", "🪞", "💇"],
         "liste": [
             mot("scissors", True, "Oui ! « Scissors », ce sont les ciseaux."),
             mot("mirror", True, "Oui ! « Mirror », c'est le miroir."),
             mot("barber", True, "Oui ! « Barber », c'est le coiffeur pour hommes."),
             mot("hair", True, "Oui ! « Hair », ce sont les cheveux."),
             mot("fish", False, "« Fish », c'est le poisson. On est chez le coiffeur, pas chez le vendeur de poisson ! Regarde encore."),
             mot("book", False, "« Book », c'est le livre. Tu vois un livre ? Non ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Modou! Nice hair! Did you cut it?", "Modou ! Jolie coiffure ! Tu les as coupés toi-même ?"),
                       r("modou", "No! I had my hair cut at the barber's.", "Non ! Je me suis fait couper les cheveux chez le coiffeur."),
                       r("awa", "Cool! And does your phone work again?", "Super ! Et ton téléphone marche à nouveau ?"),
                       r("modou", "Yes, I had my phone repaired at the market.", "Oui, j'ai fait réparer mon téléphone au marché.")],
         "gainde": "Modou n'a pas coupé ses cheveux lui-même ? Alors pourquoi il dit « I had my hair cut » ?"},
        [q("Qui a coupé les cheveux de Modou ?", ["le coiffeur", "Modou lui-même", "Awa"], 0, 1),
         q("Qu'est-ce que Modou a fait réparer ?", ["son téléphone", "son vélo", "sa radio"], 0, 3)],
        [choix("Le coiffeur m'a coupé la crinière. Je dis laquelle ?", ["I cut my hair.", "I had my hair cut."], 1,
               aides("Regarde ton carnet : qui coupe ? Toi ou le coiffeur ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I had my hair cut on Saturday. »",
                     "« I cut my hair » : je coupe moi-même. « I had my hair cut » : une autre personne le fait pour moi.")),
         ordre("« He his phone had repaired. » C'est ça ?", ["repaired", "He had", "his phone"], "He had his phone repaired",
               "He had his phone repaired.",
               aides("Où va « repaired » : au milieu ou à la fin ?", 3, "Écoute Modou :",
                     "Moi, je dis : « He had his phone repaired. »", "He had + his phone (la chose) + repaired (réparé).")),
         trou("Le réparateur a réparé mon vélo : « I had my bike ___. »", "I had my bike", ".",
              ["repaired", "fixed", "mended"], "I had my bike repaired.",
              aides("Quel mot Modou dit-il pour son téléphone ?", 3, "Écoute Modou :",
                    "« I had my phone repaired. »", "Il manque « repaired ». Écris : repaired.")),
         libre("Je suis allé chez le coiffeur. Comment je le dis à Awa ?", ["had", "hair cut"],
               aides("Qui a coupé ? Comment Modou le dit-il ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I had my hair cut. »", "Écris : « I had my hair cut. »"))],
        [tour("awa", "Oh, nice hair! Did you cut it yourself?", "Oh, jolie coiffure ! Tu les as coupés toi-même ?",
              ["had", "cut"], "No, I had my hair cut at the barber's.", "It looks great!"),
         tour("modou", "Your bike looks new! What happened?", "Ton vélo a l'air neuf ! Qu'est-ce qui s'est passé ?",
              ["had", "repaired|fixed|mended|painted"], "I had my bike repaired.", "Cool! Mine needs it too!")],
        ["I had my hair cut.", "He had his phone repaired.", "barber", "I had my… repaired."],
    ),
]

unite5 = unite(
    "3e-u5", "Telling stories",
    "Un souvenir : raconte un souvenir ou une fête en 8 à 10 phrases.",
    u5,
    lignes=[
        ("Dire ce que je faisais avant", "We used to play in the street. · I used to…"),
        ("Dire ce que je fais d'habitude", "I usually walk to school. · I'm used to getting up early."),
        ("Raconter deux choses en même temps", "While I was walking, I saw an accident."),
        ("Raconter une fête", "Every year, we… · On the big day…"),
        ("Dire ce qu'une autre personne fait pour moi", "I had my hair cut. · He had his phone repaired."),
    ],
    mots=[
        ("sheep", "mouton", "xar"),
        ("guest", "invité", "gan"),
        ("baptism", "baptême", "ngénte"),
        ("celebration", "fête", "xew"),
        ("new clothes", "habits neufs", "yére yu bees"),
        ("to pray", "prier", "julli"),
        ("village", "village", "dëkk"),
        ("street", "rue", "mbedd"),
        ("hair", "cheveux", "kawar"),
        ("morning", "matin", "suba"),
    ],
    pieges=[
        "Avant : « I used to play ». D'habitude : « I'm used to playing ». Ne mélange pas.",
        "Every year, pas « every years ».",
        "I had my hair cut : le coiffeur l'a fait. « I cut my hair » : je l'ai fait moi-même.",
    ],
    exercices=[
        ex("Avant, tu jouais dans la rue. Tu dis :", ["I used to play in the street.", "I'm used to play in the street.",
                                                      "I use to playing in the street.", "I used playing in the street."], 0,
           "Pour une chose qu'on faisait avant : I used to + play."),
        ex("« I'm used to getting up early » veut dire :", ["J'ai l'habitude de me lever tôt.", "Avant, je me levais tôt.",
                                                            "Je vais me lever tôt.", "Je déteste me lever tôt."], 0,
           "I'm used to… = j'ai l'habitude de…"),
        ex("Complète : « I'm used to ____ to school. »", ["walk", "walking", "walked", "walks"], 1,
           "Après « I'm used to », le mot finit par -ing."),
        ex("« I usually take the bus » veut dire :", ["D'habitude, je prends le bus.", "Je ne prends jamais le bus.",
                                                      "Hier, j'ai pris le bus.", "Je veux prendre le bus."], 0,
           "Usually = d'habitude."),
        ex("Deux choses en même temps. Tu dis :", ["While I was walking, I saw a goat.", "While I walking, I see a goat.",
                                                   "While I was walk, I saw a goat.", "While I am walking, I was seeing a goat."], 0,
           "La chose longue : I was walking. La chose courte : I saw."),
        ex("« While » veut dire :", ["pendant que", "parce que", "après", "jamais"], 0,
           "While I was eating = pendant que je mangeais."),
        ex("Complète : « ____ year, we go to the village. »", ["Every", "All", "Every the", "On"], 0,
           "Every year = chaque année."),
        ex("« On the big day » veut dire :", ["le grand jour", "le grand repas", "la grande maison", "chaque jour"], 0,
           "On the big day, we pray = le grand jour, on prie."),
        ex("Le coiffeur t'a coupé les cheveux. Tu dis :", ["I cut my hair.", "I had my hair cut.", "I had cut my hair.",
                                                           "My hair cut me."], 1,
           "Une autre personne le fait pour moi : I had my hair cut."),
        ex("« He had his phone repaired » veut dire :", ["Il a fait réparer son téléphone.",
                                                         "Il a réparé son téléphone lui-même.",
                                                         "Il a cassé son téléphone.", "Il a acheté un téléphone."], 0,
           "He had his phone repaired : une autre personne l'a réparé pour lui."),
    ],
)

# ======================= UNITÉ 6 : LET'S DEBATE! =======================

u6 = [
    mission(
        "3e-u6-m1", "Catastrophes naturelles", "dire mon avis avec force",
        ["In my opinion…", "I strongly believe…"],
        {"consigne": "Il a beaucoup plu. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["🌧️", "🌊", "🏠", "☔"],
         "liste": [
             mot("rain", True, "Oui ! « Rain », c'est la pluie. Il pleut fort."),
             mot("flood", True, "Oui ! « Flood », c'est l'inondation : il y a de l'eau partout."),
             mot("water", True, "Oui ! « Water », c'est l'eau, dans la rue et dans la maison."),
             mot("umbrella", True, "Oui ! « Umbrella », c'est le parapluie."),
             mot("drought", False, "« Drought », c'est la sécheresse : quand il ne pleut pas. Ici, il y a trop d'eau ! Regarde encore."),
             mot("desert", False, "« Desert », c'est le désert : du sable, mais pas d'eau. Regarde encore !"),
             mot("sun", False, "« Sun », c'est le soleil. On ne le voit pas : il pleut ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Today on Radio Jàng: floods in our town.", "Aujourd'hui sur Radio Jàng : les inondations dans notre ville."),
                       r("modou", "In my opinion, people throw too much rubbish in the street.",
                         "À mon avis, les gens jettent trop d'ordures dans la rue."),
                       r("awa", "I agree. And I strongly believe we must plant more trees.",
                         "Je suis d'accord. Et je crois vraiment qu'on doit planter plus d'arbres.")],
         "gainde": "Un avis ? Moi, j'en ai plein ! Mais comment on le dit fort, en anglais ?"},
        [q("Qu'est-ce que Modou pense ?", ["Les gens jettent trop d'ordures.", "Il faut plus de pluie.",
                                           "Les arbres sont dangereux."], 0, 1),
         q("« I strongly believe » veut dire…", ["Je crois vraiment", "Je ne sais pas", "Je crois un peu"], 0, 2)],
        [choix("Je donne mon avis à la radio. Je dis laquelle ?",
               ["According to me, floods are dangerous.", "In my opinion, floods are dangerous."], 1,
               aides("Regarde ton carnet : comment Modou commence-t-il son avis ?", 1, "Écoute Modou :",
                     "Moi, je dis : « In my opinion, the radio is great. »",
                     "En anglais, on dit « In my opinion ». « According to me », c'est du français traduit mot à mot.")),
         ordre("« Strongly I believe we must act. » C'est ça ?", ["believe", "we must act", "I", "strongly"],
               "I strongly believe we must act", "I strongly believe we must act.",
               aides("Où Awa met-elle « strongly » ?", 2, "Écoute Awa :",
                     "Moi, je dis : « I strongly believe we must act. »",
                     "I + strongly (vraiment) + believe (crois) + we must act (on doit agir).")),
         trou("« In my ___, we must plant trees. »", "In my", ", we must plant trees.", ["opinion"],
              "In my opinion, we must plant trees.",
              aides("Quel mot Modou dit-il après « In my » ?", 1, "Écoute Modou :",
                    "« In my opinion… »", "Il manque « opinion » (avis). Écris : opinion.")),
         libre("Dis ton avis avec force : on doit nettoyer les rues.", ["strongly believe|in my opinion", "clean"],
               aides("Comment Awa dit-elle son avis avec force ?", 2, "Écoute Awa :",
                     "Moi, je dis : « I strongly believe we must clean the streets. »",
                     "Écris : « I strongly believe we must clean the streets. »"))],
        [tour("awa", "Radio Jàng asks you: what should people do against floods?",
              "Radio Jàng te demande : que doivent faire les gens contre les inondations ?",
              ["in my opinion|strongly believe"], "In my opinion, we must stop throwing rubbish in the street.",
              "Thank you! That's a strong opinion!")],
        ["In my opinion…", "I strongly believe…", "flood", "drought", "storm"],
    ),
    mission(
        "3e-u6-m2", "L'émigration", "répondre à quelqu'un qui ne pense pas comme moi",
        ["I see your point, but…", "I disagree because…"],
        {"consigne": "Sur la plage. Quels mots vont avec l'image ?", "fond": "plage", "objets": ["🛶", "🌊", "🧳", "✈️"],
         "liste": [
             mot("boat", True, "Oui ! « Boat », c'est le bateau. Ici, c'est une pirogue."),
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("suitcase", True, "Oui ! « Suitcase », c'est la valise, pour voyager."),
             mot("plane", True, "Oui ! « Plane », c'est l'avion, dans le ciel."),
             mot("snow", False, "« Snow », c'est la neige. Il n'y a pas de neige sur la plage ! Regarde encore."),
             mot("desert", False, "« Desert », c'est le désert. Ici, il y a la mer ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "In my opinion, young people should go to Europe. There are more opportunities.",
                         "À mon avis, les jeunes devraient aller en Europe. Il y a plus de chances."),
                       r("awa", "I see your point, but the trip by boat is a big risk.",
                         "Je comprends ton idée, mais le voyage en pirogue est un grand risque."),
                       r("modou", "Maybe. But here, there is no work.", "Peut-être. Mais ici, il n'y a pas de travail."),
                       r("awa", "I disagree because there are opportunities here, too.",
                         "Je ne suis pas d'accord, parce qu'il y a des chances ici aussi.")],
         "gainde": "Awa n'est pas d'accord, mais elle reste gentille. Moi, quand je ne suis pas d'accord… je rugis !"},
        [q("Est-ce qu'Awa est d'accord avec Modou ?", ["Non, mais elle reste polie.", "Oui, totalement.", "Elle ne dit rien."], 0, 1),
         q("« I disagree because… » veut dire…", ["Je ne suis pas d'accord parce que…", "Je suis d'accord parce que…",
                                                   "Je ne sais pas pourquoi…"], 0, 3)],
        [choix("Modou ne pense pas comme moi. Je lui réponds laquelle ?",
               ["You are wrong! Stop talking!", "I see your point, but I think differently."], 1,
               aides("Regarde ton carnet : comment Awa répond-elle à Modou ?", 1, "Écoute Awa :",
                     "Moi, je dis : « I see your point, but… »",
                     "On peut ne pas être d'accord et rester poli. « I see your point », c'est « je comprends ton idée ».")),
         ordre("« I because disagree it's dangerous. » C'est ça ?", ["disagree", "it's dangerous", "I", "because"],
               "I disagree because its dangerous", "I disagree because it's dangerous.",
               aides("Qu'est-ce qui vient juste après « I » ?", 3, "Écoute Awa :",
                     "Moi, je dis : « I disagree because it's dangerous. »",
                     "I disagree (je ne suis pas d'accord) + because (parce que) + la raison.")),
         trou("« I see your ___, but it's a big risk. »", "I see your", ", but it's a big risk.", ["point"],
              "I see your point, but it's a big risk.",
              aides("Quel mot Awa dit-elle après « I see your » ?", 1, "Écoute Awa :",
                    "« I see your point, but… »", "Il manque « point ». Écris : point.")),
         libre("Modou dit : « Football is boring. » Tu n'es pas d'accord. Réponds-lui gentiment.",
               ["i see your point|i disagree|i dont agree"],
               aides("Comment Awa commence-t-elle pour rester polie ?", 1, "Écoute Awa :",
                     "Moi, je dis : « I see your point, but I disagree because football is fun. »",
                     "Écris : « I see your point, but… »"))],
        [tour("modou", "In my opinion, school is useless. What do you think?", "À mon avis, l'école ne sert à rien. Tu en penses quoi ?",
              ["i see your point|i disagree|i dont agree"],
              "I see your point, but I disagree because school gives us skills.", "Hmm… OK, maybe you're right.")],
        ["I see your point, but…", "I disagree because…", "risk", "opportunity", "to emigrate"],
    ),
    mission(
        "3e-u6-m3", "Le chômage des jeunes", "proposer une solution",
        ["We could…", "The government should…"],
        {"consigne": "Un atelier au marché. Quels mots vont avec l'image ?", "fond": "marche", "objets": ["🔧", "🧵", "🧑‍🔧", "🪚"],
         "liste": [
             mot("workshop", True, "Oui ! « Workshop », c'est l'atelier où on travaille."),
             mot("tools", True, "Oui ! « Tools », ce sont les outils."),
             mot("worker", True, "Oui ! « Worker », c'est le travailleur."),
             mot("market", True, "Oui ! « Market », c'est le marché autour."),
             mot("holiday", False, "« Holiday », ce sont les vacances. Ici, les gens travaillent ! Regarde encore."),
             mot("sheep", False, "« Sheep », c'est le mouton. Tu vois un mouton ? Non ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Many young people have no job. What can we do?", "Beaucoup de jeunes n'ont pas de travail. Que peut-on faire ?"),
                       r("modou", "We could open a training centre in our town.", "On pourrait ouvrir un centre de formation dans notre ville."),
                       r("awa", "Yes! And the government should help young people learn skills.",
                         "Oui ! Et le gouvernement devrait aider les jeunes à apprendre un métier."),
                       r("modou", "Then companies could hire them.", "Ensuite, les entreprises pourraient les embaucher.")],
         "gainde": "Une solution ? Facile : je donne des ordres à tout le monde ! Mais comment on propose, gentiment ?"},
        [q("Qu'est-ce que Modou propose ?", ["ouvrir un centre de formation", "partir en Europe", "fermer l'école"], 0, 1),
         q("« The government should… » veut dire…", ["Le gouvernement devrait…", "Le gouvernement a fait…",
                                                      "Le gouvernement ne veut pas…"], 0, 2)],
        [choix("Je propose une idée. Je dis laquelle ?", ["We could to open a workshop.", "We could open a workshop."], 1,
               aides("Regarde ton carnet : après « We could », Modou met « to » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « We could open a library. »",
                     "Après « could » ou « should », pas de « to » : we could open.")),
         ordre("« The government help should young people. » C'est ça ?",
               ["should", "young people", "The government", "help"],
               "The government should help young people", "The government should help young people.",
               aides("Où Awa met-elle « should » ?", 2, "Écoute Awa :",
                     "Moi, je dis : « The government should help young people. »",
                     "The government + should (devrait) + help (aider) + young people.")),
         trou("« We ___ hire young people. » (on pourrait)", "We", "hire young people.", ["could", "should"],
              "We could hire young people.",
              aides("Comment Modou dit-il « on pourrait » ?", 1, "Écoute Modou :",
                    "« We could open a training centre. »", "Il manque « could ». Écris : could.")),
         libre("Propose une solution : le gouvernement devrait créer des emplois.", ["should|could", "job|jobs|work"],
               aides("Comment Awa propose-t-elle une idée pour le gouvernement ?", 2, "Écoute Awa :",
                     "Moi, je dis : « The government should create jobs. »", "Écris : « The government should create jobs. »"))],
        [tour("awa", "Radio Jàng! Young people have no job. What's your solution?",
              "Radio Jàng ! Les jeunes n'ont pas de travail. Quelle est ta solution ?",
              ["could|should"], "We could teach young people new skills.", "Great idea! Thank you!")],
        ["We could…", "The government should…", "unemployment", "skills", "training", "to hire"],
    ),
    mission(
        "3e-u6-m4", "Le débat de Radio Jàng", "donner la parole dans un débat",
        ["What do you think, Awa?", "Can I add something?", "Let's move on."],
        {"consigne": "Le studio de Radio Jàng. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["🎙️", "🪑", "⏰", "🙋"],
         "liste": [
             mot("microphone", True, "Oui ! « Microphone », c'est le micro."),
             mot("chair", True, "Oui ! « Chair », c'est la chaise."),
             mot("clock", True, "Oui ! « Clock », c'est l'horloge. Le débat ne doit pas être trop long !"),
             mot("hand", True, "Oui ! « Hand », c'est la main levée : quelqu'un veut parler."),
             mot("bed", False, "« Bed », c'est le lit. On ne dort pas pendant le débat ! Regarde encore."),
             mot("guitar", False, "« Guitar », c'est la guitare. Il n'y en a pas ici. Regarde encore !"),
         ]},
        {"fond": "classe", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Welcome to the Radio Jàng debate! What do you think, Modou?",
                         "Bienvenue au débat de Radio Jàng ! Qu'en penses-tu, Modou ?"),
                       r("modou", "In my opinion, phones are useful at school.", "À mon avis, les téléphones sont utiles au collège."),
                       r("gainde", "Can I add something? Phones can also be dangerous!",
                         "Je peux ajouter quelque chose ? Les téléphones peuvent aussi être dangereux !"),
                       r("awa", "Thank you, Gaïndé. Let's move on to the next question.",
                         "Merci, Gaïndé. Passons à la question suivante.")],
         "gainde": "J'ai demandé la parole poliment ! Mais quand c'est moi qui anime, je dis quoi ?"},
        [q("Comment Awa donne-t-elle la parole à Modou ?", ["What do you think, Modou?", "Let's move on, Modou.",
                                                             "Can I add something, Modou?"], 0, 0),
         q("« Let's move on » veut dire…", ["Passons à la suite.", "Arrêtons tout.", "Recommençons."], 0, 3)],
        [choix("J'anime le débat. Je donne la parole à Awa. Je dis laquelle ?", ["Awa, talk now. Quick!", "What do you think, Awa?"], 1,
               aides("Regarde ton carnet : comment Awa donne-t-elle la parole à Modou ?", 0, "Écoute Awa :",
                     "Moi, je dis : « What do you think, Modou? »",
                     "Pour donner la parole poliment, on pose une question : « What do you think…? »")),
         ordre("« What you do think, Awa? » C'est ça ?", ["you", "think", "What", "do", "Awa"], "What do you think Awa",
               "What do you think, Awa?",
               aides("Quel petit mot vient juste après « What » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « What do you think, Awa? »", "What + do + you think (tu penses) + le prénom.")),
         trou("« Let's ___ on to the next question. »", "Let's", "on to the next question.", ["move"],
              "Let's move on to the next question.",
              aides("Quel mot Awa dit-elle après « Let's » ?", 3, "Écoute Awa :",
                    "« Let's move on… »", "Il manque « move ». Écris : move.")),
         libre("Je veux parler, moi aussi, pendant le débat. Je demande comment, poliment ?",
               ["can i add|could i add|may i add|can i say"],
               aides("Comment Gaïndé a-t-il demandé la parole, dans la scène ?", 2, "Écoute :",
                     "Moi, je dis : « Can I add something? »", "Écris : « Can I add something? »"))],
        [tour("awa", "You are the host now! Give the floor to Modou.", "C'est toi qui animes ! Donne la parole à Modou.",
              ["what do you think|what about you"], "What do you think, Modou?", "Perfect! You are a real host!"),
         tour("modou", "…and that's why football is the best sport in the world, and…",
              "…et c'est pour ça que le foot est le meilleur sport du monde, et…",
              ["move on"], "Thank you, Modou. Let's move on.", "Oh… OK. Sorry!")],
        ["What do you think, Awa?", "Can I add something?", "Let's move on.", "debate"],
    ),
    mission(
        "3e-u6-m5", "Lettre au maire", "écrire une lettre à un adulte important (le maire…)",
        ["Dear Sir,", "I am writing to…", "Yours faithfully,"],
        {"consigne": "On écrit au maire. Quels mots vont avec l'image ?", "fond": "bibliotheque",
         "objets": ["✉️", "🏛️", "🖊️", "📄"],
         "liste": [
             mot("letter", True, "Oui ! « Letter », c'est la lettre."),
             mot("town hall", True, "Oui ! « Town hall », c'est la mairie. C'est là que travaille le maire."),
             mot("pen", True, "Oui ! « Pen », c'est le stylo."),
             mot("paper", True, "Oui ! « Paper », c'est la feuille de papier."),
             mot("football", False, "« Football », c'est le foot. On ne joue pas, on écrit ! Regarde encore."),
             mot("sheep", False, "« Sheep », c'est le mouton. Il n'y a pas de mouton ici. Regarde encore !"),
         ]},
        {"fond": "bibliotheque", "persos": ["awa", "kocc", "gainde"],
         "repliques": [r("awa", "Dear Sir, I am writing to ask for a basketball court.",
                         "Monsieur, je vous écris pour demander un terrain de basket."),
                       r("awa", "Our school has no sports ground. Thank you for your help.",
                         "Notre collège n'a pas de terrain de sport. Merci pour votre aide."),
                       r("awa", "Yours faithfully, Awa Diop.", "Je vous prie d'agréer mes salutations, Awa Diop."),
                       r("kocc", "Very good, Awa! It's a perfect letter for the mayor.", "Très bien, Awa ! C'est une lettre parfaite pour le maire.")],
         "gainde": "Moi, j'aurais écrit : « Salut le maire ! Bisous ! ». Ce n'est pas bien ?"},
        [q("Pourquoi Awa écrit-elle au maire ?", ["pour demander un terrain de basket", "pour dire bonjour",
                                                  "pour inviter le maire à manger"], 0, 0),
         q("Comment Awa finit-elle sa lettre ?", ["Yours faithfully,", "Take care!", "See you!"], 0, 2)],
        [choix("J'écris au maire. Je commence par laquelle ?", ["Hi Mayor! Guess what…", "Dear Sir, I am writing to…"], 1,
               aides("Regarde ton carnet : comment Awa commence-t-elle ?", 0, "Écoute Awa :",
                     "Moi, j'écris : « Dear Sir, I am writing to ask… »",
                     "Au maire, on écrit poliment : « Dear Sir » ou « Dear Madam ». « Hi », c'est pour un ami.")),
         ordre("« I writing am to ask for help. » C'est ça ?", ["writing", "to ask for help", "I", "am"],
               "I am writing to ask for help", "I am writing to ask for help.",
               aides("Qu'est-ce qui vient juste après « I » ?", 0, "Écoute Awa :",
                     "Moi, j'écris : « I am writing to ask for help. »",
                     "I am writing (je vous écris) + to ask for (pour demander) + help.")),
         trou("La fin de ma lettre au maire : « Yours ___, Gaïndé »", "Yours", ", Gaïndé", ["faithfully", "sincerely"],
              "Yours faithfully, Gaïndé",
              aides("Comment Awa finit-elle sa lettre ?", 2, "Écoute la fin :",
                    "« Yours faithfully, Awa Diop. »", "Il manque « faithfully ». Écris : faithfully.")),
         libre("Écris le début de ma lettre au maire : je veux demander une bibliothèque.",
               ["dear sir|dear madam|dear mayor", "i am writing|im writing"],
               aides("Comment commence une lettre au maire ?", 0, "Écoute Awa :",
                     "Moi, j'écris : « Dear Sir, I am writing to ask for a library. »",
                     "Écris : « Dear Sir, I am writing to ask for… »"))],
        [tour("kocc", "Write a short letter to the mayor. Ask for something for your school.",
              "Écris une petite lettre au maire. Demande une chose pour ton collège.",
              ["dear", "i am writing|im writing", "yours faithfully|yours sincerely"],
              "Dear Sir, I am writing to ask for new computers for our school. Yours faithfully, Fatou.",
              "Excellent! The mayor will be happy to read it.")],
        ["Dear Sir, / Dear Madam,", "I am writing to…", "Yours faithfully,", "mayor"],
    ),
    mission(
        "3e-u6-m6", "Raconte-moi le débat !", "écrire une lettre à un ami",
        ["Hi Modou!", "Guess what…", "Take care!"],
        {"consigne": "Modou est malade. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["🛏️", "✉️", "📱", "🤒"],
         "liste": [
             mot("bed", True, "Oui ! « Bed », c'est le lit. Modou est couché."),
             mot("letter", True, "Oui ! « Letter », c'est la lettre d'Awa."),
             mot("phone", True, "Oui ! « Phone », c'est le téléphone."),
             mot("sick", True, "Oui ! « Sick », c'est malade. Modou a de la fièvre."),
             mot("town hall", False, "« Town hall », c'est la mairie. On est chez Modou ! Regarde encore."),
             mot("ball", False, "« Ball », c'est le ballon. Modou est malade, il ne joue pas. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Hi Modou! How are you? I hope you feel better.", "Salut Modou ! Comment ça va ? J'espère que tu vas mieux."),
                       r("awa", "Guess what… Gaïndé won the debate!", "Devine quoi… Gaïndé a gagné le débat !"),
                       r("awa", "See you soon. Take care! Awa", "À bientôt. Prends soin de toi ! Awa"),
                       r("modou", "Gaïndé won?! Wow!", "Gaïndé a gagné ?! Waouh !")],
         "gainde": "À Modou, Awa écrit « Hi » et « Take care ». Pas de « Yours faithfully » ? C'est plus simple !"},
        [q("Quelle nouvelle Awa annonce à Modou ?", ["Gaïndé a gagné le débat.", "Le maire est venu.",
                                                     "Il n'y a plus d'école."], 0, 1),
         q("« Take care! » veut dire…", ["Prends soin de toi !", "Fais attention à la voiture !", "Prends ça !"], 0, 2)],
        [choix("J'écris à mon ami Modou. Je commence par laquelle ?",
               ["Dear Sir, I am writing to inform you…", "Hi Modou! Guess what…"], 1,
               aides("Regarde ton carnet : comment Awa écrit-elle à Modou ?", 0, "Écoute Awa :",
                     "Moi, j'écris : « Hi Modou! How are you? »",
                     "À un ami, on écrit simplement : « Hi » + le prénom. « Dear Sir », c'est pour le maire.")),
         ordre("« What guess… won we the debate! » C'est ça ?", ["the debate", "Guess what", "won", "we"],
               "Guess what we won the debate", "Guess what… we won the debate!",
               aides("Par quels mots Awa annonce-t-elle la nouvelle ?", 1, "Écoute Awa :",
                     "Moi, j'écris : « Guess what… we won the debate! »",
                     "Guess what (devine quoi) + la nouvelle : we won the debate.")),
         trou("La fin de ma lettre à Modou : « ___ care! Gaïndé »", "", "care! Gaïndé", ["take"], "Take care! Gaïndé",
              aides("Comment Awa finit-elle sa lettre ?", 2, "Écoute la fin :",
                    "« Take care! Awa »", "Il manque « Take ». Écris : Take.")),
         libre("Écris à Modou pour lui annoncer une nouvelle : la radio a un nouveau micro.",
               ["hi modou|hello modou|dear modou", "guess what"],
               aides("Comment Awa annonce-t-elle la nouvelle ?", 1, "Écoute Awa :",
                     "Moi, j'écris : « Hi Modou! Guess what… the radio has a new microphone! »",
                     "Écris : « Hi Modou! Guess what… »"))],
        [tour("modou", "I'm sick at home. Write me a short letter with news from school!",
              "Je suis malade à la maison. Écris-moi une petite lettre avec des nouvelles du collège !",
              ["hi|hello|dear", "guess what", "take care"], "Hi Modou! Guess what… we have a new teacher! Take care!",
              "Thank you! Your letter makes me happy!")],
        ["Hi Modou!", "Guess what…", "Take care!", "See you soon!"],
    ),
]

unite6 = unite(
    "3e-u6", "Let's debate!",
    "Un mini-débat de Radio Jàng, enregistré, ou une lettre au maire.",
    u6,
    lignes=[
        ("Dire mon avis avec force", "In my opinion… · I strongly believe…"),
        ("Répondre à quelqu'un qui ne pense pas comme moi", "I see your point, but… · I disagree because…"),
        ("Proposer une solution", "We could… · The government should…"),
        ("Donner la parole dans un débat", "What do you think, Awa? · Can I add something? · Let's move on."),
        ("Écrire à un adulte important", "Dear Sir, · I am writing to… · Yours faithfully,"),
        ("Écrire à un ami", "Hi Modou! · Guess what… · Take care!"),
    ],
    mots=[
        ("rain", "pluie", "taw"),
        ("wind", "vent", "ngelaw"),
        ("sea", "mer", "géej"),
        ("country", "pays", "réew"),
        ("to travel", "voyager", "tukki"),
        ("job, work", "travail", "liggéey"),
        ("money", "argent", "xaalis"),
        ("young people", "les jeunes", "ndaw ñi"),
        ("opinion", "avis, idée", "xalaat"),
        ("mayor", "maire", "meer"),
        ("letter", "lettre", "bataaxal"),
    ],
    pieges=[
        "In my opinion… Pas « According to me… ».",
        "We could open… Pas « We could to open… ».",
        "Au maire : « Dear Sir » et « Yours faithfully ». À un ami : « Hi » et « Take care! ».",
    ],
    exercices=[
        ex("Tu donnes ton avis :", ["According to me, …", "In my opinion, …", "For me opinion, …", "In my opinions, …"], 1,
           "On dit « In my opinion ». « According to me », c'est du français traduit."),
        ex("« I strongly believe » veut dire :", ["Je crois vraiment", "Je crois un peu", "Je ne crois pas", "Je crois peut-être"], 0,
           "Strongly = avec force, vraiment."),
        ex("Ton ami ne pense pas comme toi. Tu réponds poliment :", ["You are wrong! Stop!", "I see your point, but…",
                                                                     "Shut up!", "No, no, no!"], 1,
           "« I see your point, but… » : je comprends ton idée, mais…"),
        ex("Complète : « I ____ because it's dangerous. »", ["disagree", "disagrees", "disagreeing", "am disagree"], 0,
           "I disagree = je ne suis pas d'accord."),
        ex("Tu proposes une idée :", ["We could to open a workshop.", "We could open a workshop.",
                                      "We could opening a workshop.", "We could opened a workshop."], 1,
           "Après « could », pas de « to » : we could open."),
        ex("« The government should help us » veut dire :", ["Le gouvernement devrait nous aider.",
                                                              "Le gouvernement nous a aidés.",
                                                              "Le gouvernement ne nous aide pas.",
                                                              "Le gouvernement va partir."], 0,
           "Should = devrait."),
        ex("Tu animes le débat. Tu donnes la parole à Awa :", ["What do you think, Awa?", "What you think, Awa?",
                                                               "Awa, talk!", "Let's move on, Awa."], 0,
           "What do you think, Awa? = Qu'en penses-tu, Awa ?"),
        ex("« Let's move on » veut dire :", ["Passons à la suite.", "Bougeons-nous.", "Partons d'ici.", "Arrêtons de parler."], 0,
           "Dans un débat, « Let's move on » : on passe à la question suivante."),
        ex("Une lettre au maire finit par :", ["Take care!", "Yours faithfully,", "See you!", "Bye bye!"], 1,
           "À un adulte important : Yours faithfully."),
        ex("Tu écris à ton ami pour lui annoncer une nouvelle :", ["Dear Sir, I am writing to…", "Hi Modou! Guess what…",
                                                                   "Yours faithfully, Modou", "To sum up, Modou…"], 1,
           "À un ami : Hi + le prénom. Guess what… = devine quoi…"),
    ],
)

UNITES = [unite4, unite5, unite6]

# ======================= LES HISTOIRES =======================

EPISODES = [
    episode("Pourvu qu'il pleuve… sur Gaïndé", "3e-u4-m2", [
        case("classe", [perso("modou", 0.05, 90), perso("awa", 0.6, 90)],
             [bulle("Radio Jàng! Your wishes! I wish I had a bike.", "Radio Jàng ! Vos vœux ! J'aimerais avoir un vélo.", 0.02, 0.04),
              bulle("If only I were taller!", "Si seulement j'étais plus grande !", 0.5, 0.32)]),
        case("classe", [perso("gainde", 0.3, 100, "saute"), perso("awa", 0.65, 90)],
             [bulle("I wish I had a bike, a phone, a TV, a car, a plane…",
                    "J'aimerais avoir un vélo, un téléphone, une télé, une voiture, un avion… (il ne s'arrête plus)", 0.02, 0.04),
              bulle("Gaïndé! I wish you would stop!", "Gaïndé ! J'aimerais que tu arrêtes !", 0.5, 0.35)]),
        case("cour", [perso("gainde", 0.1, 100), perso("modou", 0.6, 90)],
             [bulle("It's so hot! I wish it would rain!", "Il fait si chaud ! Pourvu qu'il pleuve ! (il lève les bras au ciel)", 0.02, 0.05),
              bulle("OK!", "D'accord ! (Modou monte sur le mur avec un grand seau d'eau)", 0.58, 0.1)]),
        case("cour", [perso("gainde", 0.1, 100, "immobile"), perso("modou", 0.6, 90, "danse")],
             [bulle("Modou! I wish you would stop!", "Modou ! J'aimerais que tu arrêtes ! (il est trempé, sa crinière coule)", 0.02, 0.04),
              bulle("But you said: I wish it would rain!", "Mais tu as dit : pourvu qu'il pleuve !", 0.45, 0.3),
              bulle("If only I were a fish…", "Si seulement j'étais un poisson…", 0.05, 0.5)]),
    ], ["I wish I had…", "If only I were…!", "I wish it would rain.", "I wish you would stop."]),

    episode("Chère Awa, le lion chante la nuit", "3e-u4-m4", [
        case("classe", [perso("awa", 0.05, 90), perso("gainde", 0.55, 100, "saute")],
             [bulle("Gaïndé, please read the letters on the radio.", "Gaïndé, lis les lettres à la radio, s'il te plaît.", 0.02, 0.04),
              bulle("OK! I love letters!", "D'accord ! J'adore les lettres !", 0.5, 0.32)]),
        case("classe", [perso("gainde", 0.35, 105)],
             [bulle("Dear Awa, I have a problem. My friend is a lion. He sings all night!",
                    "Chère Awa, j'ai un problème. Mon ami est un lion. Il chante toute la nuit !", 0.02, 0.04),
              bulle("What should I do? Modou.", "Qu'est-ce que je dois faire ? Modou.", 0.4, 0.4)]),
        case("classe", [perso("gainde", 0.05, 100, "saute"), perso("modou", 0.6, 90)],
             [bulle("Modou! Your friend is terrible! Say goodbye to him!",
                    "Modou ! Ton ami est terrible ! Dis-lui au revoir ! (il crie dans le micro)", 0.02, 0.04),
              bulle("Gaïndé… the lion is YOU.", "Gaïndé… le lion, c'est TOI.", 0.5, 0.35)]),
        case("classe", [perso("gainde", 0.05, 100, "balance"), perso("awa", 0.38, 90), perso("modou", 0.68, 90)],
             [bulle("Oh no! I wish I hadn't said that!", "Oh non ! Je regrette d'avoir dit ça ! (il pleure… en chantant très fort)", 0.02, 0.04),
              bulle("Dear Awa… I have a new problem!", "Chère Awa… J'ai un nouveau problème ! (Modou se bouche les oreilles)", 0.45, 0.4)]),
    ], ["Dear Awa,", "I have a problem.", "What should I do?", "I wish I hadn't said that."]),

    episode("Gaïndé se lève très tôt… à 10 heures", "3e-u5-m2", [
        case("classe", [perso("awa", 0.05, 90), perso("kocc", 0.6, 100)],
             [bulle("Kocc Barma, in 6e, what did you use to do?", "Kocc Barma, en 6e, qu'est-ce que tu faisais ?", 0.02, 0.04),
              bulle("We used to play football in the street.", "On jouait au foot dans la rue.", 0.45, 0.32)]),
        case("classe", [perso("gainde", 0.3, 100, "saute"), perso("awa", 0.65, 90)],
             [bulle("Me! Me! I used to be a king! I used to eat ten sheep a day!",
                    "Moi ! Moi ! Avant, j'étais un roi ! Je mangeais dix moutons par jour !", 0.02, 0.04),
              bulle("Gaïndé… you were a baby!", "Gaïndé… tu étais un bébé !", 0.5, 0.38)]),
        case("classe", [perso("modou", 0.05, 90), perso("gainde", 0.55, 100)],
             [bulle("I usually get up at six.", "D'habitude, je me lève à six heures.", 0.02, 0.04),
              bulle("Me too! I'm used to getting up early!", "Moi aussi ! J'ai l'habitude de me lever tôt !", 0.45, 0.32)]),
        case("classe", [perso("awa", 0.05, 90), perso("gainde", 0.35, 100, "immobile"), perso("modou", 0.68, 90, "danse")],
             [bulle("Gaïndé! It's ten o'clock! The radio!", "Gaïndé ! Il est dix heures ! La radio !", 0.02, 0.04),
              bulle("Zzz… I'm used to getting up early… zzz…",
                    "Zzz… J'ai l'habitude de me lever tôt… zzz… (il dort sur le micro)", 0.25, 0.4),
              bulle("Ha ha! Very early!", "Ha ha ! Très tôt !", 0.6, 0.1)]),
    ], ["What did you use to do?", "We used to…", "I usually…", "I'm used to getting up early."]),

    episode("Le mouton qui aimait le papier", "3e-u5-m4", [
        case("classe", [perso("awa", 0.05, 90), perso("gainde", 0.38, 100), perso("mouton", 0.7, 85)],
             [bulle("Gaïndé, tell us about Tabaski!", "Gaïndé, raconte-nous la Tabaski !", 0.02, 0.04),
              bulle("Every year, we buy a big sheep.", "Chaque année, on achète un gros mouton. (il montre le mouton, très fier)", 0.3, 0.35)]),
        case("classe", [perso("gainde", 0.1, 100), perso("mouton", 0.6, 85)],
             [bulle("On the big day, we wear new clothes, and we…",
                    "Le grand jour, on met des habits neufs, et on… (derrière lui, le mouton mange sa feuille)", 0.02, 0.04)]),
        case("classe", [perso("gainde", 0.1, 100), perso("modou", 0.65, 90)],
             [bulle("…and we… and we… Where is my paper?", "…et on… et on… Où est ma feuille ?", 0.02, 0.04),
              bulle("While you were talking, the sheep was eating your paper!",
                    "Pendant que tu parlais, le mouton mangeait ta feuille !", 0.4, 0.35)]),
        case("classe", [perso("gainde", 0.05, 95), perso("mouton", 0.38, 90, "danse"), perso("awa", 0.68, 90)],
             [bulle("Bêêê!", "Bêêê ! (il a maintenant le micro dans la bouche)", 0.35, 0.1),
              bulle("On the big day… the sheep is on the radio!", "Le grand jour… le mouton passe à la radio !", 0.02, 0.4),
              bulle("Every year, the same story!", "Chaque année, la même histoire !", 0.55, 0.45)]),
    ], ["Every year, we…", "On the big day…", "While you were talking, the sheep was eating…"]),

    episode("Quatre touffes pour Gaïndé", "3e-u5-m5", [
        case("maison", [perso("gainde", 0.35, 105, "balance")],
             [bulle("My hair is too long! I can't see!", "Ma crinière est trop longue ! Je ne vois rien ! (il prend des ciseaux)", 0.05, 0.05)]),
        case("cour", [perso("awa", 0.05, 90), perso("gainde", 0.35, 100), perso("modou", 0.68, 90, "danse")],
             [bulle("Gaïndé! Did you have your hair cut?", "Gaïndé ! Tu t'es fait couper les cheveux ?", 0.02, 0.04),
              bulle("No. I cut my hair. Alone!", "Non. Je me suis coupé les cheveux. Tout seul ! (sa crinière est en zigzag)", 0.28, 0.38),
              bulle("Ha ha ha!", "Ha ha ha !", 0.62, 0.08)]),
        case("cour", [perso("kocc", 0.05, 100), perso("gainde", 0.55, 100)],
             [bulle("Gaïndé… next time, go to the barber's. Have your hair cut!",
                    "Gaïndé… la prochaine fois, va chez le coiffeur. Fais-toi couper les cheveux !", 0.02, 0.04),
              bulle("OK!", "D'accord !", 0.55, 0.35)]),
        case("classe", [perso("gainde", 0.05, 100, "saute"), perso("kocc", 0.38, 100), perso("modou", 0.68, 90)],
             [bulle("Look! I had my hair cut at the barber's!",
                    "Regardez ! Je me suis fait couper les cheveux chez le coiffeur ! (il a quatre touffes sur la tête, comme Kocc Barma)", 0.02, 0.04),
              bulle("Hmm… very nice.", "Hmm… très joli.", 0.35, 0.38),
              bulle("Now we have two Kocc Barmas!", "Maintenant, on a deux Kocc Barma !", 0.55, 0.1)]),
    ], ["Did you have your hair cut?", "I had my hair cut.", "I cut my hair."]),

    episode("Les lions dorment-ils toute la journée ?", "3e-u6-m2", [
        case("classe", [perso("awa", 0.35, 95)],
             [bulle("Radio Jàng debate! Today's question: do lions sleep all day?",
                    "Débat de Radio Jàng ! La question du jour : est-ce que les lions dorment toute la journée ?", 0.05, 0.05)]),
        case("classe", [perso("modou", 0.05, 90), perso("gainde", 0.55, 100, "saute")],
             [bulle("In my opinion, yes. Lions sleep all day.", "À mon avis, oui. Les lions dorment toute la journée.", 0.02, 0.04),
              bulle("I disagree because lions work a lot! I strongly believe it!",
                    "Je ne suis pas d'accord, parce que les lions travaillent beaucoup ! J'en suis sûr !", 0.4, 0.35)]),
        case("classe", [perso("awa", 0.05, 90), perso("gainde", 0.55, 100)],
             [bulle("I see your point, Gaïndé, but… what do lions do?", "Je comprends ton idée, Gaïndé, mais… que font les lions ?", 0.02, 0.04),
              bulle("They… they… hmm…", "Ils… ils… hmm… (il bâille très fort)", 0.5, 0.38)]),
        case("classe", [perso("modou", 0.05, 90, "danse"), perso("gainde", 0.35, 100, "immobile"), perso("awa", 0.68, 90)],
             [bulle("Zzz…", "Zzz… (il dort sur la table, au milieu du débat)", 0.35, 0.15),
              bulle("I see your point, Gaïndé!", "Je comprends ton idée, Gaïndé !", 0.02, 0.4),
              bulle("Ha ha ha!", "Ha ha ha !", 0.6, 0.45)]),
    ], ["In my opinion…", "I strongly believe…", "I disagree because…", "I see your point, but…"]),

    episode("Le mouton anime le débat", "3e-u6-m4", [
        case("classe", [perso("gainde", 0.05, 100, "saute"), perso("awa", 0.6, 90)],
             [bulle("Welcome to the Radio Jàng debate! What do you think, Awa?",
                    "Bienvenue au débat de Radio Jàng ! Qu'en penses-tu, Awa ?", 0.02, 0.04),
              bulle("We could open a training centre, and the government should…",
                    "On pourrait ouvrir un centre de formation, et le gouvernement devrait…", 0.4, 0.38)]),
        case("classe", [perso("gainde", 0.05, 100), perso("awa", 0.38, 90), perso("modou", 0.68, 90)],
             [bulle("Thank you! Let's move on!", "Merci ! Passons à la suite ! (Awa n'a pas fini sa phrase)", 0.02, 0.04),
              bulle("Can I add something?", "Je peux ajouter quelque chose ?", 0.55, 0.15),
              bulle("No! Let's move on!", "Non ! Passons à la suite !", 0.05, 0.45)]),
        case("classe", [perso("gainde", 0.05, 100), perso("mouton", 0.55, 90)],
             [bulle("What do you think, Sir?", "Qu'en pensez-vous, Monsieur ? (il tend le micro au mouton)", 0.02, 0.04),
              bulle("Bêêê!", "Bêêê !", 0.55, 0.3),
              bulle("Great idea! Let's move on!", "Super idée ! Passons à la suite !", 0.05, 0.45)]),
        case("classe", [perso("modou", 0.05, 90), perso("mouton", 0.38, 95, "danse"), perso("gainde", 0.68, 95)],
             [bulle("We could hire the sheep!", "On pourrait embaucher le mouton !", 0.02, 0.04),
              bulle("Can I add something?", "Je peux ajouter quelque chose ?", 0.55, 0.15),
              bulle("Bêêê!", "Bêêê ! (Traduction : non ! Passons à la suite !)", 0.3, 0.45)]),
    ], ["What do you think, Awa?", "Let's move on!", "Can I add something?", "We could…"]),

    episode("La grande émission de Radio Jàng", "3e-u6-m6", [
        case("classe", [perso("awa", 0.05, 90), perso("gainde", 0.55, 100, "saute")],
             [bulle("Tomorrow is our last radio day! Please write to the mayor and to Modou.",
                    "Demain, c'est notre dernière émission ! Écris au maire et à Modou, s'il te plaît.", 0.02, 0.04),
              bulle("OK! Two letters!", "D'accord ! Deux lettres !", 0.5, 0.4)]),
        case("bibliotheque", [perso("gainde", 0.35, 105)],
             [bulle("Hi Mayor! Guess what… come to our radio! Take care! Gaïndé",
                    "Salut le maire ! Devine quoi… viens à notre radio ! Prends soin de toi ! Gaïndé", 0.02, 0.04),
              bulle("Dear Sir Modou, I am writing to invite you. Yours faithfully, Gaïndé.",
                    "Monsieur Modou, je vous écris pour vous inviter. Salutations distinguées, Gaïndé. (il a mélangé les deux lettres)",
                    0.3, 0.42)]),
        case("maison", [perso("modou", 0.35, 100, "balance")],
             [bulle("Dear Sir Modou?! Yours faithfully?! Ha ha ha!", "Monsieur Modou ?! Salutations distinguées ?! Ha ha ha !", 0.05, 0.05)]),
        case("cour", [perso("kocc", 0.05, 100), perso("gainde", 0.55, 100)],
             [bulle("Gaïndé, a letter from the mayor!", "Gaïndé, une lettre du maire !", 0.02, 0.04),
              bulle("Hi Gaïndé! Guess what… I'm coming! Take care! The Mayor",
                    "Salut Gaïndé ! Devine quoi… je viens ! Prends soin de toi ! Le maire (le maire a répondu comme Gaïndé !)", 0.05, 0.3),
              bulle("Yes!", "Ouiii !", 0.6, 0.5)]),
        case("classe", [perso("gainde", 0.05, 100, "danse"), perso("doudou", 0.38, 95, "danse2"), perso("awa", 0.68, 90, "danse")],
             [bulle("Goodbye, everybody! Yours faithfully, Radio Jàng!", "Au revoir, tout le monde ! Salutations distinguées, Radio Jàng !", 0.02, 0.04),
              bulle("Gaïndé! Just say: Take care!", "Gaïndé ! Dis juste : prends soin de toi !", 0.5, 0.3),
              bulle("Tam-tam-tam!", "Tam-tam-tam ! (Doudou joue du tama. Tout le collège danse, et le maire aussi. Fin de la saison !)", 0.3, 0.5)]),
    ], ["Dear Sir,", "I am writing to…", "Yours faithfully,", "Hi Modou!", "Guess what…", "Take care!"]),
]
