"""Parcours d'anglais de 4e, unités 4 à 6 (saison « La pirogue de Kayar », suite et fin)."""
from jang_lib import *  # noqa: F401,F403

NIVEAU = "4e"

# ======================= UNITÉ 4 : CLIMATE =======================

u4 = [
    mission(
        "4e-u4-m1", "Kayar, ses chèvres et son vent", "dire le temps qu'il fait",
        ["What's the weather like?", "It's windy.", "It's dry.", "It's rainy.", "The rainy season starts in July."],
        {"consigne": "La plage de Kayar. Quels mots vont avec l'image ?", "fond": "plage", "objets": ["🌬️", "🐐", "☀️", "🛶"],
         "liste": [
             mot("wind", True, "Oui ! « Wind », c'est le vent. Il souffle fort ici."),
             mot("goat", True, "Oui ! « Goat », c'est la chèvre. À Kayar, il y en a partout !"),
             mot("sun", True, "Oui ! « Sun », c'est le soleil."),
             mot("boat", True, "Oui ! « Boat », c'est le bateau. Ici, c'est une pirogue."),
             mot("sand", True, "Oui ! « Sand », c'est le sable de la plage."),
             mot("snow", False, "« Snow », c'est la neige. Il ne neige jamais à Kayar ! Regarde encore."),
             mot("cloud", False, "« Cloud », c'est le nuage. Le ciel est tout bleu : pas de nuage. Regarde encore !"),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "What's the weather like in Kayar?", "Quel temps fait-il à Kayar ?"),
                       r("modou", "It's windy and dry. It's the dry season.", "Il y a du vent et c'est sec. C'est la saison sèche."),
                       r("awa", "When does the rainy season start?", "Quand commence la saison des pluies ?"),
                       r("modou", "The rainy season starts in July.", "La saison des pluies commence en juillet.")],
         "gainde": "Le vent a volé mon sandwich… et une chèvre l'a mangé ! Comment on dit le temps qu'il fait ?"},
        [q("Quel temps fait-il à Kayar ?", ["Il y a du vent et c'est sec.", "Il pleut beaucoup.", "Il neige."], 0, 1),
         q("La saison des pluies commence…", ["en juillet", "en mai", "en décembre"], 0, 3)],
        [choix("Le vent souffle très fort. Je parle à l'oncle de Modou. Je dis laquelle ?",
               ["Wind! Big wind, old man!", "It's very windy today."], 1,
               aides("Comment Modou parle du vent ?", 1, "Écoute Modou :",
                     "Moi, je dis : « It's very windy today. »",
                     "« Windy », c'est « avec du vent ». Et « old man » (le vieux), ce n'est pas poli avec un adulte.")),
         ordre("« Starts the rainy season in July. » C'est bien ça ?",
               ["starts", "The", "July", "rainy", "in", "season"], "The rainy season starts in July",
               "The rainy season starts in July.",
               aides("Quels mots Modou dit en premier ?", 3, "Écoute Modou :",
                     "Moi, je dis : « The rainy season starts in July. »",
                     "The rainy season (la saison des pluies) + starts (commence) + in July (en juillet).")),
         trou("Il n'y a pas d'eau, tout est sec. « It's very ___. »", "It's very", ".", ["dry"], "It's very dry.",
              aides("Comment Modou dit « sec » ?", 1, "Écoute Modou :",
                    "Moi, je dis : « It's dry. It's the dry season. »", "« Sec », c'est « dry ». Écris : dry.")),
         libre("Il pleut à Kayar. Comment je le dis ?", ["rainy|raining|rains"],
               aides("« Windy », c'est pour le vent. Et pour la pluie ?", 3, "Écoute la fin :",
                     "Moi, je dis : « It's rainy today. »", "La pluie, c'est « rain ». Écris : « It's rainy. »"))],
        [tour("awa", "What's the weather like today in your town?", "Quel temps fait-il aujourd'hui dans ta ville ?",
              ["windy|dry|rainy|raining|sunny|hot|cold|cloudy|warm"], "It's hot and dry.",
              "Thank you! In Kayar, it's very windy today!"),
         tour("modou", "When does the rainy season start in Senegal?", "Quand commence la saison des pluies au Sénégal ?",
              ["june|july|august"], "The rainy season starts in July.", "Yes! Then the farmers are happy.")],
        ["What's the weather like?", "It's windy.", "It's dry.", "It's rainy.", "the rainy season · the dry season"],
    ),
    mission(
        "4e-u4-m2", "Il n'a pas plu depuis trois mois", "dire depuis combien de temps",
        ["It hasn't rained for three months.", "It hasn't rained since May."],
        {"consigne": "Un champ à Kayar. Quels mots vont avec l'image ?", "fond": "terrain",
         "objets": ["☀️", "🌾", "🐐", "🪣"],
         "liste": [
             mot("sun", True, "Oui ! « Sun », c'est le soleil. Il chauffe fort."),
             mot("field", True, "Oui ! « Field », c'est le champ. Il est tout sec."),
             mot("goat", True, "Oui ! « Goat », c'est la chèvre. Elle cherche de l'herbe."),
             mot("bucket", True, "Oui ! « Bucket », c'est le seau. Il est vide."),
             mot("rain", False, "« Rain », c'est la pluie. Justement : il ne pleut pas ! Regarde encore."),
             mot("umbrella", False, "« Umbrella », c'est le parapluie. Personne n'en a besoin ici ! Regarde encore."),
             mot("river", False, "« River », c'est la rivière. Tu vois de l'eau ? Non ! Regarde encore."),
         ]},
        {"fond": "terrain", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Look at the field! It's so dry!", "Regarde le champ ! Il est tellement sec !"),
                       r("modou", "Yes. It hasn't rained for three months.",
                         "Oui. Il n'a pas plu depuis trois mois."),
                       r("awa", "Three months?", "Trois mois ?"),
                       r("modou", "Yes. It hasn't rained since May. The farmers are waiting for the rain.",
                         "Oui. Il n'a pas plu depuis mai. Les paysans attendent la pluie.")],
         "gainde": "Moi, je n'ai pas mangé depuis… dix minutes ! Comment on dit « depuis » ?"},
        [q("Depuis combien de temps il n'a pas plu ?", ["trois mois", "trois jours", "trois ans"], 0, 1),
         q("Il n'a pas plu depuis…", ["mai", "juillet", "hier"], 0, 3)],
        [choix("Je veux parler de la pluie. Je dis laquelle ?",
               ["It hasn't rained since three months.", "It hasn't rained for three months."], 1,
               aides("« Trois mois », c'est une durée ou un jour de départ ?", 1, "Écoute Modou :",
                     "Moi, je dis : « It hasn't rained for three months. »",
                     "Astuce : « for » + une durée (trois mois). « since » + le départ (mai).")),
         ordre("« Rained it hasn't since May. » C'est ça ?",
               ["since", "rained", "It", "May", "hasn't"], "It hasnt rained since May", "It hasn't rained since May.",
               aides("Quel mot Modou dit en premier ?", 3, "Écoute Modou :",
                     "Moi, je dis : « It hasn't rained since May. »",
                     "It hasn't rained (il n'a pas plu) + since May (depuis mai).")),
         trou("« It hasn't rained ___ two weeks. »", "It hasn't rained", "two weeks.", ["for"],
              "It hasn't rained for two weeks.",
              aides("Deux semaines, c'est une durée. Tu mets « for » ou « since » ?", 1, "Écoute : « for three months ».",
                    "Moi, je dis : « for two weeks », « for three months ».", "Avec une durée, on dit « for ». Écris : for.")),
         libre("Dis : « Il n'a pas plu depuis janvier. »", ["hasnt rained|has not rained", "since january"],
               aides("Janvier, c'est un départ. Tu mets « for » ou « since » ?", 3, "Écoute : « since May ».",
                     "Moi, je dis : « It hasn't rained since June. »",
                     "Écris : « It hasn't rained since January. »"))],
        [tour("modou", "Is it dry in your town too?", "C'est sec chez toi aussi ?",
              ["hasnt rained|has not rained|hasnt rain", "for|since"], "Yes. It hasn't rained for two months.",
              "Oh no! Like in Kayar!")],
        ["It hasn't rained for three months.", "It hasn't rained since May.", "for two weeks", "since Monday"],
    ),
    mission(
        "4e-u4-m3", "Il y a deux ans…", "dire il y a combien de temps",
        ["The flood happened two years ago.", "I arrived three days ago."],
        {"consigne": "Modou montre une vieille photo. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🏠", "🌊", "📷", "🛶"],
         "liste": [
             mot("house", True, "Oui ! « House », c'est la maison de Modou."),
             mot("photo", True, "Oui ! « Photo », c'est la photo."),
             mot("flood", True, "Oui ! « Flood », c'est l'inondation. Sur la photo, l'eau est partout."),
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("fire", False, "« Fire », c'est le feu. Sur la photo, c'est de l'eau, pas du feu ! Regarde encore."),
             mot("desert", False, "« Desert », c'est le désert : du sable, mais pas d'eau. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Look at this photo. The flood happened two years ago.",
                         "Regarde cette photo. L'inondation, c'était il y a deux ans."),
                       r("awa", "Two years ago? Your house was under water!", "Il y a deux ans ? Ta maison était sous l'eau !"),
                       r("modou", "Yes! And my uncle's pirogue was in the street!",
                         "Oui ! Et la pirogue de mon oncle était dans la rue !"),
                       r("awa", "Wow! I arrived in Kayar three days ago. It's dry now!",
                         "Waouh ! Moi, je suis arrivée à Kayar il y a trois jours. Maintenant, c'est sec !")],
         "gainde": "Il y a deux ans, moi, j'étais un bébé lion ! Comment on dit « il y a » ?"},
        [q("L'inondation, c'était quand ?", ["il y a deux ans", "il y a deux jours", "dans deux ans"], 0, 0),
         q("Où était la pirogue de l'oncle ?", ["dans la rue", "dans la mer", "sur le toit"], 0, 2)],
        [choix("Je parle de l'inondation. Je dis laquelle ?",
               ["The flood happened ago two years.", "The flood happened two years ago."], 1,
               aides("Où Modou met le mot « ago » : avant ou après « two years » ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I came to Kayar two days ago. »",
                     "Astuce : « ago » vient après le temps. Two years ago = il y a deux ans.")),
         ordre("« Ago I three days arrived. » C'est ça ?",
               ["ago", "I", "three", "arrived", "days"], "I arrived three days ago", "I arrived three days ago.",
               aides("Qui est arrivé ? Commence par ce mot.", 3, "Écoute Awa :",
                     "Moi, je dis : « I arrived two days ago. »",
                     "I arrived (je suis arrivé) + three days ago (il y a trois jours).")),
         trou("« The flood happened two years ___. »", "The flood happened two years", ".", ["ago"],
              "The flood happened two years ago.",
              aides("Quel mot veut dire « il y a » dans la phrase de Modou ?", 0, "Écoute Modou :",
                    "Moi, je dis : « three days ago », « two years ago ».", "« Il y a », ici, c'est « ago ». Écris : ago.")),
         libre("Dis : « Je suis arrivé à Kayar il y a une semaine. »", ["arrived|came", "a week ago|one week ago"],
               aides("Comment Awa dit « je suis arrivée » ?", 3, "Écoute Awa :",
                     "Moi, je dis : « I arrived three days ago. »",
                     "Une semaine, c'est « a week ». Écris : « I arrived in Kayar a week ago. »"))],
        [tour("modou", "When did you come to your school?", "Tu es arrivé dans ton école quand ?",
              ["ago"], "I came to my school two years ago.", "Oh! And I came three years ago.")],
        ["The flood happened two years ago.", "I arrived three days ago.", "two years ago"],
    ),
    mission(
        "4e-u4-m4", "Une bouteille dans le filet", "dire qui a fait quelque chose",
        ["The beach was polluted by plastic.", "This net was made by my uncle."],
        {"consigne": "Sur la plage, après la pêche. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🍾", "🥤", "🕸️", "🐟"],
         "liste": [
             mot("bottle", True, "Oui ! « Bottle », c'est la bouteille."),
             mot("plastic", True, "Oui ! « Plastic », c'est le plastique. Il y en a beaucoup ici."),
             mot("net", True, "Oui ! « Net », c'est le filet du pêcheur."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson. Il est dans le filet."),
             mot("rubbish", True, "Oui ! « Rubbish », ce sont les déchets."),
             mot("flowers", False, "« Flowers », ce sont les fleurs. Il n'y a pas de fleurs : il y a des déchets. Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. Personne ne mange de gâteau ici ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["modou", "awa", "kocc"],
         "repliques": [r("modou", "Look! There are bottles in the net!", "Regarde ! Il y a des bouteilles dans le filet !"),
                       r("awa", "Oh no. The beach was polluted by plastic.", "Oh non. La plage a été polluée par le plastique."),
                       r("kocc", "Was this net made by your uncle?", "Ce filet a été fait par ton oncle ?"),
                       r("modou", "Yes, it was made by my uncle. Now it's full of rubbish!",
                         "Oui, il a été fait par mon oncle. Maintenant, il est plein de déchets !")],
         "gainde": "Qui a mis ces bouteilles ici ? Pas moi ! Je le jure !"},
        [q("Qu'est-ce qui a pollué la plage ?", ["le plastique", "les poissons", "le vent"], 0, 1),
         q("Qui a fait le filet ?", ["l'oncle de Modou", "Awa", "Kocc Barma"], 0, 3)],
        [choix("Je parle de la plage sale. Je dis laquelle ?",
               ["The plastic was polluted by the beach.", "The beach was polluted by plastic."], 1,
               aides("Qu'est-ce qui est sale : la plage ou le plastique ?", 1, "Écoute Awa :",
                     "Moi, je dis : « The beach was polluted by plastic. »",
                     "La plage (the beach) a été salie (was polluted) par (by) le plastique.")),
         ordre("« By my uncle this net was made. » C'est bien ça ?",
               ["was", "my", "This", "by", "made", "uncle", "net"], "This net was made by my uncle",
               "This net was made by my uncle.",
               aides("Par quoi Modou commence : le filet ou l'oncle ?", 3, "Écoute Modou :",
                     "Moi, je dis : « This tama was made by Doudou. »",
                     "This net (ce filet) + was made (a été fait) + by my uncle (par mon oncle).")),
         trou("« The beach was polluted ___ plastic. »", "The beach was polluted", "plastic.", ["by"],
              "The beach was polluted by plastic.",
              aides("Quel petit mot veut dire « par » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « made by my uncle », « polluted by plastic ».", "« Par », c'est « by ». Écris : by.")),
         libre("Dis : « La pirogue a été faite par le grand-père de Modou. »",
               ["was made by|was built by", "grandfather|grandad|grandpa"],
               aides("Tu te rappelles comment Modou parle du filet ?", 3, "Écoute Modou :",
                     "Moi, je dis : « This net was made by my uncle. »",
                     "Grand-père, c'est « grandfather ». Écris : « The pirogue was made by Modou's grandfather. »"))],
        [tour("kocc", "This tama is beautiful! Was it made by Doudou?", "Ce tama est beau ! Il a été fait par Doudou ?",
              ["made by|was made"], "Yes, it was made by Doudou.", "Wow! Doudou is very good!"),
         tour("awa", "Why is the beach so dirty?", "Pourquoi la plage est si sale ?",
              ["polluted|by plastic|by rubbish"], "The beach was polluted by plastic.", "Yes. Let's clean it!")],
        ["The beach was polluted by plastic.", "This net was made by my uncle.", "plastic", "rubbish", "bottle"],
    ),
    mission(
        "4e-u4-m5", "Où est le poisson ?", "dire « je suis d'accord » ou « je ne suis pas d'accord »",
        ["I agree with you.", "I don't think so.", "That's true, but…"],
        {"consigne": "En mer, sur la pirogue. Quels mots vont avec l'image ?", "fond": "mer",
         "objets": ["🛶", "🌊", "🐟", "🕸️"],
         "liste": [
             mot("boat", True, "Oui ! « Boat », c'est le bateau : la pirogue."),
             mot("wave", True, "Oui ! « Wave », c'est la vague."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson. Il n'y en a qu'un !"),
             mot("net", True, "Oui ! « Net », c'est le filet."),
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("tree", False, "« Tree », c'est l'arbre. Il n'y a pas d'arbre en pleine mer ! Regarde encore."),
             mot("car", False, "« Car », c'est la voiture. Une voiture sur la mer ? Non ! Regarde encore."),
         ]},
        {"fond": "mer", "persos": ["modou", "awa", "kocc"],
         "repliques": [r("modou", "There aren't many fish today. The sea is too hot.",
                         "Il n'y a pas beaucoup de poissons aujourd'hui. La mer est trop chaude."),
                       r("awa", "That's true, but there's a lot of plastic too.",
                         "C'est vrai, mais il y a aussi beaucoup de plastique."),
                       r("modou", "I agree with you.", "Je suis d'accord avec toi."),
                       r("kocc", "Maybe the fish are on holiday!", "Peut-être que les poissons sont en vacances !"),
                       r("awa", "Ha ha! I don't think so!", "Ha ha ! Je ne crois pas !")],
         "gainde": "Moi, je sais où sont les poissons : ils ont peur de moi !"},
        [q("Awa est d'accord avec Modou ?", ["Oui, mais elle ajoute une idée.", "Non, pas du tout.", "Elle ne dit rien."], 0, 1),
         q("Kocc Barma dit que les poissons sont en vacances. Awa répond…", ["Je ne crois pas.", "Je suis d'accord.", "C'est vrai."], 0, 4)],
        [choix("Kocc Barma dit une chose fausse. Je lui réponds laquelle ?",
               ["You're wrong! Stupid!", "I don't think so."], 1,
               aides("Comment Awa dit « non » sans être méchante ?", 4, "Écoute Awa :",
                     "Moi, je dis : « I don't think so. »",
                     "« I don't think so », c'est « je ne crois pas ». C'est poli. « Stupid », ça fait mal.")),
         ordre("« With you agree I. » C'est ça ?", ["you", "agree", "with", "I"], "I agree with you", "I agree with you.",
               aides("Qui est d'accord ? Commence par ce mot.", 2, "Écoute Modou :",
                     "Moi, je dis : « I agree with you. »", "I agree (je suis d'accord) + with you (avec toi).")),
         trou("« That's ___, but there's a lot of plastic. »", "That's", ", but there's a lot of plastic.",
              ["true", "right"], "That's true, but there's a lot of plastic.",
              aides("Quel mot veut dire « vrai » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « That's true, but… »", "« Vrai », c'est « true ». Écris : true.")),
         libre("Modou dit : « Thiof is the best fish! » Je suis d'accord. Je dis quoi ?", ["agree|true|right"],
               aides("Comment Modou dit « je suis d'accord » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « I agree with you. »", "Écris : « I agree with you! »"))],
        [tour("modou", "Football is the best sport in the world!", "Le foot, c'est le meilleur sport du monde !",
              ["agree|dont think so|true|right|disagree"], "I agree with you!", "Yes! Let's play on the beach!"),
         tour("gainde", "Lions are better fishermen than people!", "Les lions pêchent mieux que les gens !",
              ["agree|dont think so|true|right|disagree"], "I don't think so!", "Grrr… OK, OK. Maybe you're right.")],
        ["I agree with you.", "I don't think so.", "That's true, but…"],
    ),
]

unite4 = unite(
    "4e-u4", "Climate",
    "La météo de Kayar : dis le temps qu'il fait à Kayar, comme à la radio. Tu peux parler ou écrire.",
    u4,
    lignes=[
        ("Dire le temps qu'il fait", "It's windy. · It's dry. · It's rainy. · The rainy season starts in July."),
        ("Dire depuis combien de temps", "It hasn't rained for three months. · It hasn't rained since May."),
        ("Dire il y a combien de temps", "The flood happened two years ago. · I arrived three days ago."),
        ("Dire qui a fait quelque chose", "The beach was polluted by plastic. · This net was made by my uncle."),
        ("Dire si je suis d'accord", "I agree with you. · I don't think so. · That's true, but…"),
    ],
    mots=[
        ("wind", "vent", "ngelaw"),
        ("rain", "pluie", "taw"),
        ("rainy season", "saison des pluies", "nawet"),
        ("dry season", "saison sèche", "noor"),
        ("hot", "chaud", "tàng"),
        ("sun", "soleil", "jant"),
        ("sea", "mer", "géej"),
        ("sand", "sable", "suuf"),
        ("water", "eau", "ndox"),
        ("fish", "poisson", "jën"),
    ],
    pieges=[
        "It hasn't rained for three months. Pas « since three months ».",
        "Two years ago = il y a deux ans. Pas « ago two years ».",
        "I agree with you. Pas « I am agree ».",
    ],
    exercices=[
        ex("Il y a beaucoup de vent. Tu dis :", ["It's windy.", "It's rainy.", "It's snowy.", "It's wet."], 0,
           "Windy = avec du vent. Rainy = avec de la pluie."),
        ex("La saison des pluies commence en juillet :",
           ["The dry season starts in July.", "The rainy season starts in July.", "The rainy season stops in July.",
            "The rain season start July."], 1,
           "Rainy season = saison des pluies. Dry season = saison sèche."),
        ex("Complète : « It hasn't rained ____ three months. »", ["since", "for", "ago", "by"], 1,
           "Avec une durée (trois mois), on dit « for »."),
        ex("Complète : « It hasn't rained ____ May. »", ["for", "since", "ago", "by"], 1,
           "Avec le moment du départ (mai), on dit « since »."),
        ex("L'inondation, c'était il y a deux ans :",
           ["The flood happened ago two years.", "The flood happened since two years.",
            "The flood happened two years ago.", "The flood happened for two years."], 2,
           "« Ago » vient après le temps : two years ago."),
        ex("« I arrived three days ago. » veut dire :",
           ["Je suis arrivé il y a trois jours.", "J'arrive dans trois jours.", "Je reste trois jours.",
            "Je pars dans trois jours."], 0, "Ago = il y a."),
        ex("La plage a été polluée par le plastique :",
           ["The beach polluted the plastic.", "The beach was polluted by plastic.",
            "The plastic was polluted by the beach.", "The beach is pollute plastic."], 1,
           "Was polluted by = a été polluée par."),
        ex("Complète : « This net was made ____ my uncle. »", ["by", "for", "of", "since"], 0, "By = par."),
        ex("Tu es d'accord avec ton ami. Tu dis :", ["I am agree.", "I agree with you.", "I don't think so.", "You are agree."], 1,
           "On dit « I agree », sans « am »."),
        ex("Tu n'es pas d'accord, mais tu restes poli :", ["You're stupid!", "I don't think so.", "I agree with you.", "Shut up!"], 1,
           "« I don't think so » = je ne crois pas. C'est poli."),
    ],
)

# ======================= UNITÉ 5 : MIGRATION AND JOBS =======================

u5 = [
    mission(
        "4e-u5-m1", "Le héros de Kayar", "parler d'un métier",
        ["He works as a fisherman.", "She works as a nurse.", "He has to get up early."],
        {"consigne": "Le matin, sur la plage de Kayar. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🛶", "🎣", "🕸️", "🌅"],
         "liste": [
             mot("fisherman", True, "Oui ! « Fisherman », c'est le pêcheur, comme l'oncle de Modou."),
             mot("boat", True, "Oui ! « Boat », c'est le bateau : la pirogue."),
             mot("net", True, "Oui ! « Net », c'est le filet."),
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("morning", True, "Oui ! « Morning », c'est le matin. Le soleil se lève."),
             mot("nurse", False, "« Nurse », c'est l'infirmière. Elle travaille à l'hôpital, pas sur la plage. Regarde encore !"),
             mot("office", False, "« Office », c'est le bureau. Il n'y a pas de bureau sur la plage ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "What does your uncle do?", "Il fait quoi, ton oncle ?"),
                       r("modou", "He works as a fisherman. He's the hero of Kayar!",
                         "Il travaille comme pêcheur. C'est le héros de Kayar !"),
                       r("awa", "Does he have to get up early?", "Il doit se lever tôt ?"),
                       r("modou", "Yes! He has to get up at five. And my aunt works as a nurse.",
                         "Oui ! Il doit se lever à cinq heures. Et ma tante travaille comme infirmière.")],
         "gainde": "Se lever à cinq heures ?! Moi, à cinq heures, je ronfle !"},
        [q("L'oncle de Modou est…", ["pêcheur", "infirmier", "prof"], 0, 1),
         q("L'oncle doit se lever à…", ["cinq heures", "dix heures", "midi"], 0, 3)],
        [choix("L'oncle de Modou est pêcheur. Je dis laquelle ?",
               ["He works like a fish.", "He works as a fisherman."], 1,
               aides("Comment Modou parle du travail de son oncle ?", 1, "Écoute Modou :",
                     "Moi, je dis : « He works as a fisherman. »",
                     "« Works as », c'est « travaille comme ». « Fisherman », c'est le pêcheur. « Fish », c'est le poisson !")),
         ordre("« Early he has get up to. » C'est ça ?", ["to", "He", "early", "has", "get", "up"],
               "He has to get up early", "He has to get up early.",
               aides("Qui doit se lever ? Commence par ce mot.", 3, "Écoute Modou :",
                     "Moi, je dis : « I have to get up early. »",
                     "He has to (il doit) + get up (se lever) + early (tôt).")),
         trou("« My aunt works ___ a nurse. »", "My aunt works", "a nurse.", ["as"], "My aunt works as a nurse.",
              aides("Quel petit mot veut dire « comme » ?", 3, "Écoute la fin de Modou :",
                    "Moi, je dis : « He works as a fisherman. »", "« Comme », ici, c'est « as ». Écris : as.")),
         libre("Ma maman est prof. Comment je le dis ?", ["works as|is|shes", "teacher"],
               aides("Comment Modou parle du métier de sa tante ?", 3, "Écoute Modou :",
                     "Moi, je dis : « My aunt works as a nurse. »",
                     "Prof, c'est « teacher ». Écris : « My mum works as a teacher. »"))],
        [tour("awa", "Tell me about a job in your family.", "Parle-moi d'un métier dans ta famille.",
              ["works as|is a|is an|has to"], "My uncle works as a mechanic.", "Great! That's a good job!"),
         tour("modou", "Does a fisherman have to get up early?", "Un pêcheur doit se lever tôt ?",
              ["yes|has to"], "Yes, he has to get up early.", "Yes! At five o'clock! Poor Gaïndé!")],
        ["He works as a fisherman.", "He has to get up early.", "nurse", "mechanic", "tailor"],
    ),
    mission(
        "4e-u5-m2", "Partir ou rester ?", "dire « si… alors… »",
        ["If I find a job, I'll stay.", "If I go abroad, I'll miss my family."],
        {"consigne": "Quelqu'un prépare un voyage. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🧳", "✈️", "🛂", "🛶"],
         "liste": [
             mot("suitcase", True, "Oui ! « Suitcase », c'est la valise."),
             mot("plane", True, "Oui ! « Plane », c'est l'avion."),
             mot("passport", True, "Oui ! « Passport », c'est le passeport, pour partir à l'étranger."),
             mot("boat", True, "Oui ! « Boat », c'est le bateau : la pirogue."),
             mot("snow", False, "« Snow », c'est la neige. Il n'y a pas de neige à Kayar ! Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. On ne met pas de gâteau dans une valise ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["awa", "doudou", "modou"],
         "repliques": [r("awa", "Doudou, do you want to go abroad?", "Doudou, tu veux partir à l'étranger ?"),
                       r("doudou", "I don't know. If I find a job here, I'll stay.",
                         "Je ne sais pas. Si je trouve un travail ici, je resterai."),
                       r("modou", "And if you go abroad, you'll miss Kayar!", "Et si tu pars à l'étranger, Kayar va te manquer !"),
                       r("doudou", "That's true. If I stay, I'll play the tama every day!",
                         "C'est vrai. Si je reste, je jouerai du tama tous les jours !")],
         "gainde": "Si je trouve un poisson, je le mange ! C'est comme ça, « si… alors » ?"},
        [q("Doudou reste si…", ["il trouve un travail ici", "il pleut", "il a faim"], 0, 1),
         q("Si Doudou part, qu'est-ce qui va lui manquer ?", ["Kayar", "son avion", "la neige"], 0, 2)],
        [choix("Je parle comme Doudou. Je dis laquelle ?",
               ["If I find a job, I stay will.", "If I find a job, I'll stay."], 1,
               aides("Comment Doudou finit sa phrase ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « If I find a job, I'll stay. »",
                     "If (si) + I find a job (je trouve un travail) + I'll stay (je resterai).")),
         ordre("« Stay I'll, a job if I find. » C'est ça ?", ["stay", "If", "a", "I'll", "find", "job", "I"],
               "If I find a job Ill stay", "If I find a job, I'll stay.",
               aides("Quel mot Doudou dit en premier ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « If I find a job, I'll stay. »",
                     "If (si) + I find a job (je trouve un travail) + I'll stay (je resterai).")),
         trou("« ___ I stay, I'll play the tama every day! »", "", "I stay, I'll play the tama every day!", ["if"],
              "If I stay, I'll play the tama every day!",
              aides("Quel mot veut dire « si » ?", 3, "Écoute Doudou :",
                    "Moi, je dis : « If I stay, I'll be happy. »", "« Si », c'est « if ». Écris : if.")),
         libre("Dis : « S'il pleut, je resterai à la maison. »", ["if it rains", "ill stay|i will stay"],
               aides("Comment Doudou dit « je resterai » ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « If it's windy, I'll stay at home. »",
                     "« S'il pleut », c'est « If it rains ». Écris : « If it rains, I'll stay at home. »"))],
        [tour("doudou", "And you? Do you want to go abroad?", "Et toi ? Tu veux partir à l'étranger ?",
              ["if"], "If I find a good job here, I'll stay.", "Good idea! Senegal needs you!")],
        ["If I find a job, I'll stay.", "If I go abroad, I'll miss my family.", "abroad", "to leave", "to stay"],
    ),
    mission(
        "4e-u5-m3", "Mon futur métier", "dire ce que je vais faire plus tard",
        ["I'm going to be a mechanic.", "Next year, I will…"],
        {"consigne": "Des métiers. Quels mots vont avec l'image ?", "fond": "classe",
         "objets": ["👩‍⚕️", "🔧", "🧵", "📰"],
         "liste": [
             mot("nurse", True, "Oui ! « Nurse », c'est l'infirmière."),
             mot("mechanic", True, "Oui ! « Mechanic », c'est le mécanicien. Il a une clé."),
             mot("tailor", True, "Oui ! « Tailor », c'est le tailleur. Il coud avec du fil."),
             mot("journalist", True, "Oui ! « Journalist », c'est le journaliste. Il écrit le journal."),
             mot("kitchen", False, "« Kitchen », c'est la cuisine. C'est un endroit, pas un métier. Regarde encore !"),
             mot("fish", False, "« Fish », c'est le poisson. Ce n'est pas un métier ! Le pêcheur, c'est « fisherman ». Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "What are you going to do later, Modou?", "Tu vas faire quoi plus tard, Modou ?"),
                       r("modou", "I'm going to be a mechanic, like my cousin.", "Je vais être mécanicien, comme mon cousin."),
                       r("awa", "I'm going to be a journalist. Next year, I will visit a radio in Dakar.",
                         "Moi, je vais être journaliste. L'année prochaine, je visiterai une radio à Dakar.")],
         "gainde": "Moi, plus tard, je vais être… le roi des sandwichs ! C'est un métier ?"},
        [q("Modou va être…", ["mécanicien", "journaliste", "pêcheur"], 0, 1),
         q("Awa va être…", ["journaliste", "infirmière", "tailleur"], 0, 2)],
        [choix("Je veux dire mon futur métier. Je dis laquelle ?",
               ["Later, I go to be a nurse.", "Later, I'm going to be a nurse."], 1,
               aides("Comment Modou commence sa phrase ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I'm going to be a teacher. »",
                     "« I'm going to be », c'est « je vais être ». Il faut « I'm » au début.")),
         ordre("« Be going I'm a journalist to. » C'est ça ?", ["going", "a", "I'm", "be", "journalist", "to"],
               "Im going to be a journalist", "I'm going to be a journalist.",
               aides("Quels mots Awa dit en premier ?", 2, "Écoute Awa :",
                     "Moi, je dis : « I'm going to be a teacher. »",
                     "I'm going to be (je vais être) + a journalist (journaliste).")),
         trou("« Next year, I ___ visit Dakar. »", "Next year, I", "visit Dakar.", ["will"], "Next year, I will visit Dakar.",
              aides("Quel mot montre que c'est pour plus tard ?", 2, "Écoute Awa :",
                    "Moi, je dis : « Next year, I will go to Dakar. »", "Pour plus tard, on peut dire « will ». Écris : will.")),
         libre("Quel métier tu vas faire plus tard ? Dis-le-moi !", ["going to be|will be|want to be|gonna be"],
               aides("Comment Modou parle de son futur métier ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I'm going to be a teacher. »",
                     "Écris : « I'm going to be a… » et ton métier."))],
        [tour("awa", "What are you going to do later?", "Tu vas faire quoi plus tard ?",
              ["going to|will|want to"], "I'm going to be a nurse.", "Super! I'm going to be a journalist."),
         tour("modou", "What will you do next year?", "Tu feras quoi l'année prochaine ?",
              ["will|going to"], "Next year, I will be in 3e.", "Me too! Cool!")],
        ["I'm going to be a mechanic.", "Next year, I will…", "journalist", "engineer", "tailor"],
    ),
    mission(
        "4e-u5-m4", "Peut-être…", "dire « peut-être » ou « c'est sûr »",
        ["I may go abroad.", "I will certainly stay."],
        {"consigne": "Le soir, sur la plage. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🌅", "🛶", "✈️", "🧳"],
         "liste": [
             mot("sunset", True, "Oui ! « Sunset », c'est le coucher du soleil."),
             mot("boat", True, "Oui ! « Boat », c'est le bateau : la pirogue."),
             mot("plane", True, "Oui ! « Plane », c'est l'avion, dans le ciel."),
             mot("suitcase", True, "Oui ! « Suitcase », c'est la valise."),
             mot("snow", False, "« Snow », c'est la neige. Pas à Kayar ! Regarde encore."),
             mot("bus", False, "« Bus », c'est le car. Tu vois un car sur la plage ? Non ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "kocc"],
         "repliques": [r("kocc", "Modou, will you go abroad one day?", "Modou, tu partiras à l'étranger un jour ?"),
                       r("modou", "I may go abroad. I don't know.", "Je partirai peut-être. Je ne sais pas."),
                       r("kocc", "And you, Awa?", "Et toi, Awa ?"),
                       r("awa", "I will certainly stay in Senegal. I love it here!",
                         "Moi, je resterai sûrement au Sénégal. J'adore être ici !")],
         "gainde": "Peut-être… sûrement… Moi, c'est sûr : je vais manger ce soir !"},
        [q("Modou est sûr de partir ?", ["Non, c'est « peut-être ».", "Oui, c'est sûr.", "Il part demain."], 0, 1),
         q("Awa va…", ["sûrement rester au Sénégal", "peut-être partir", "partir demain"], 0, 3)],
        [choix("Kocc Barma me demande : « Will you come to school tomorrow? » Je viens, c'est sûr. Je dis laquelle ?",
               ["Maybe. I don't care!", "I will certainly come, Sir."], 1,
               aides("Tu es sûr de venir. Comment Awa dit « c'est sûr » ?", 3, "Écoute Awa :",
                     "Moi, je dis : « I will certainly come. »",
                     "« Certainly », c'est « sûrement, c'est sûr ». Et « I don't care » (je m'en fiche), c'est impoli avec le prof !")),
         ordre("« Abroad may I go. » C'est ça ?", ["go", "may", "abroad", "I"], "I may go abroad", "I may go abroad.",
               aides("Qui parle ? Commence par ce mot.", 1, "Écoute Modou :",
                     "Moi, je dis : « I may go to Dakar. »",
                     "I may (je vais peut-être) + go abroad (partir à l'étranger).")),
         trou("C'est sûr ! « I will ___ stay in Senegal. »", "I will", "stay in Senegal.",
              ["certainly", "surely", "definitely"], "I will certainly stay in Senegal.",
              aides("Quel mot veut dire « sûrement » ?", 3, "Écoute Awa :",
                    "Moi, je dis : « I will certainly stay. »", "« Sûrement », c'est « certainly ». Écris : certainly.")),
         libre("Je ne suis pas sûr d'aller à la plage demain. Comment je dis ?", ["may|might|maybe"],
               aides("Comment Modou dit « peut-être » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I may go to the market tomorrow. »",
                     "Écris : « I may go to the beach tomorrow. »"))],
        [tour("kocc", "Will you go abroad one day?", "Tu partiras à l'étranger un jour ?",
              ["may|might|maybe|certainly|will"], "I may go abroad. I don't know.", "OK. You have time to think!"),
         tour("awa", "Will you come to the beach on Saturday?", "Tu viendras à la plage samedi ?",
              ["will|may|might|maybe|certainly"], "Yes, I will certainly come!", "Great! See you on Saturday!")],
        ["I may go abroad.", "I will certainly stay.", "maybe", "certainly"],
    ),
    mission(
        "4e-u5-m5", "La famille des mots", "trouver les mots de la même famille",
        ["teach → teacher → teaching", "fish → fisherman → fishing", "employ → unemployment"],
        {"consigne": "En classe. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["📖", "🧑‍🏫", "✏️", "🔤"],
         "liste": [
             mot("teacher", True, "Oui ! « Teacher », c'est le prof : Kocc Barma."),
             mot("book", True, "Oui ! « Book », c'est le livre."),
             mot("pencil", True, "Oui ! « Pencil », c'est le crayon."),
             mot("words", True, "Oui ! « Words », ce sont les mots."),
             mot("boat", False, "« Boat », c'est le bateau. Il n'y a pas de bateau en classe ! Regarde encore."),
             mot("goat", False, "« Goat », c'est la chèvre. Même à Kayar, pas de chèvre en classe ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["kocc", "awa", "modou"],
         "repliques": [r("kocc", "Look: teach, teacher, teaching. It's a word family!",
                         "Regardez : teach, teacher, teaching. C'est une famille de mots !"),
                       r("awa", "So: farm, farmer, farming!", "Alors : farm, farmer, farming !"),
                       r("modou", "And fish, fisherman, fishing! Like my uncle!", "Et fish, fisherman, fishing ! Comme mon oncle !"),
                       r("kocc", "Very good! And: employ, employment, unemployment.",
                         "Très bien ! Et : employ (employer), employment (l'emploi), unemployment (le chômage).")],
         "gainde": "Une famille de mots ? Ils ont un papa et une maman, les mots ?"},
        [q("« Teacher », c'est…", ["la personne qui enseigne", "l'école", "le livre"], 0, 0),
         q("Quel mot est dans la famille de « fish » ?", ["fisherman", "farmer", "teacher"], 0, 2)],
        [choix("La personne qui travaille à la ferme (farm), c'est… Je dis laquelle ?", ["a farmman", "a farmer"], 1,
               aides("Comment Awa dit la personne de la ferme ?", 1, "Écoute Awa :",
                     "Moi, je dis : teach → teacher. Alors farm → ?",
                     "Souvent, on ajoute « -er » pour la personne : farm → farmer.")),
         ordre("« Problem unemployment big is a. » C'est ça ?", ["problem", "is", "Unemployment", "big", "a"],
               "Unemployment is a big problem", "Unemployment is a big problem.",
               aides("Le mot le plus long commence la phrase. C'est lequel ?", 3, "Écoute Kocc Barma :",
                     "Moi, je dis : « Unemployment is a big problem. »",
                     "Unemployment (le chômage) + is a big problem (est un gros problème).")),
         trou("« My mum teaches. She is a ___. »", "My mum teaches. She is a", ".", ["teacher"],
              "My mum teaches. She is a teacher.",
              aides("teach → … ? Quelle est la personne ?", 0, "Écoute Kocc Barma :",
                    "Moi, je dis : farm → farmer. Et teach → ?", "La personne qui enseigne, c'est « teacher ». Écris : teacher.")),
         libre("Le contraire de « happy » (content) ? Mets un petit morceau devant !", ["unhappy"],
               aides("employment → unemployment. Quel petit morceau Kocc Barma a mis devant ?", 3, "Écoute Kocc Barma :",
                     "Moi, je dis : kind → unkind.", "« un- » devant le mot veut dire « pas ». Écris : unhappy."))],
        [tour("kocc", "A person who fishes is a…?", "Une personne qui pêche, c'est un… ?",
              ["fisherman"], "A fisherman!", "Yes! Like Modou's uncle!"),
         tour("kocc", "A person who farms is a…?", "Une personne qui cultive la ferme, c'est un… ?",
              ["farmer"], "A farmer!", "Well done!")],
        ["teach → teacher → teaching", "farm → farmer → farming", "fish → fisherman → fishing",
         "employ → unemployment", "happy → unhappy"],
    ),
    mission(
        "4e-u5-m6", "Lettre à un ami", "écrire une lettre à un ami",
        ["Dear Modou,", "How are you?", "Take care.", "Love, Awa"],
        {"consigne": "Awa écrit une lettre. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["✉️", "✏️", "📄", "📮"],
         "liste": [
             mot("letter", True, "Oui ! « Letter », c'est la lettre."),
             mot("pen", True, "Oui ! « Pen », c'est le stylo."),
             mot("paper", True, "Oui ! « Paper », c'est le papier."),
             mot("envelope", True, "Oui ! « Envelope », c'est l'enveloppe."),
             mot("phone", False, "« Phone », c'est le téléphone. Awa écrit une lettre, pas un SMS ! Regarde encore."),
             mot("ball", False, "« Ball », c'est le ballon. Pas de ballon ici ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Dear Fatou, How are you?", "Chère Fatou, comment vas-tu ?"),
                       r("awa", "I'm in Kayar with Modou and Gaïndé. It's great!",
                         "Je suis à Kayar avec Modou et Gaïndé. C'est super !"),
                       r("modou", "Don't forget the end!", "N'oublie pas la fin !"),
                       r("awa", "Take care. Love, Awa.", "Prends soin de toi. Bisous, Awa.")],
         "gainde": "Une lettre ! Moi aussi, je veux écrire à ma maman lionne !"},
        [q("Comment Awa commence sa lettre ?", ["Dear Fatou,", "Goodbye, Fatou,", "Hey you!"], 0, 0),
         q("« Take care » veut dire…", ["Prends soin de toi", "Prends ton sac", "Viens vite"], 0, 3)],
        [choix("Je commence ma lettre à Modou. J'écris laquelle ?", ["Hey you! Give me news!", "Dear Modou, How are you?"], 1,
               aides("Comment Awa commence sa lettre ?", 0, "Écoute Awa :",
                     "Moi, j'écris : « Dear Awa, How are you? »",
                     "« Dear », c'est « cher, chère ». « Hey you! Give me news! », c'est trop brusque dans une lettre.")),
         ordre("« Are how you Modou dear. » C'est ça ?", ["you", "Dear", "How", "Modou", "are"],
               "Dear Modou How are you", "Dear Modou, How are you?",
               aides("Quel mot commence une lettre ?", 0, "Écoute Awa :",
                     "Moi, j'écris : « Dear Fatou, How are you? »",
                     "Dear Modou (cher Modou) + How are you? (comment vas-tu ?).")),
         trou("À la fin de ma lettre : « Take ___. Love, Gaïndé. »", "Take", ". Love, Gaïndé.", ["care"],
              "Take care. Love, Gaïndé.",
              aides("Comment Awa finit sa lettre ?", 3, "Écoute Awa :",
                    "Moi, j'écris : « Take care. Love, Kocc. »", "« Prends soin de toi », c'est « Take care ». Écris : care.")),
         libre("Écris le début d'une lettre à Awa.", ["dear awa"],
               aides("Quel mot Awa met avant le nom ?", 0, "Écoute Awa :",
                     "Moi, j'écris : « Dear Fatou, How are you? »", "Écris : « Dear Awa, How are you? »"))],
        [tour("modou", "I'm in Dakar now. Write me a short letter: the start and the end!",
              "Je suis à Dakar maintenant. Écris-moi une petite lettre : le début et la fin !",
              ["dear", "take care|love|bye|see you|best wishes"],
              "Dear Modou, How are you? I'm fine. Take care!", "Thank you for your letter! I'm fine too!")],
        ["Dear Modou,", "How are you?", "Take care.", "Love, Awa"],
    ),
]

unite5 = unite(
    "4e-u5", "Migration and jobs",
    "Mon projet pour plus tard : écris une lettre à un ami. Parle du métier que tu veux faire.",
    u5,
    lignes=[
        ("Parler d'un métier", "He works as a fisherman. · He has to get up early."),
        ("Dire « si… alors… »", "If I find a job, I'll stay. · If I go abroad, I'll miss my family."),
        ("Dire ce que je vais faire plus tard", "I'm going to be a mechanic. · Next year, I will…"),
        ("Dire « peut-être » ou « c'est sûr »", "I may go abroad. · I will certainly stay."),
        ("Trouver les mots de la même famille", "teach → teacher · fish → fisherman · employ → unemployment · happy → unhappy"),
        ("Écrire une lettre à un ami", "Dear Modou, · How are you? · Take care. · Love, Awa"),
    ],
    mots=[
        ("work", "travail", "liggéey"),
        ("farmer", "cultivateur", "beykat"),
        ("trader", "commerçant", "jaaykat"),
        ("teacher", "prof", "jàngalekat"),
        ("letter", "lettre", "bataaxal"),
        ("friend", "ami(e)", "xarit"),
        ("to leave", "partir", "dem"),
        ("abroad", "à l'étranger", "bitim-réew"),
        ("family", "famille", "njaboot"),
        ("tomorrow", "demain", "ëllëg"),
    ],
    pieges=[
        "He works as a fisherman. Pas « He works like a fisherman ».",
        "If I find a job, I'll stay. Pas « If I will find a job ».",
        "I'm going to be a nurse. Pas « I go to be a nurse ».",
        "Dans une lettre à un ami : « Dear Modou, ». Pas « Hey you! ».",
    ],
    exercices=[
        ex("Ton oncle est pêcheur :", ["He works as a fisherman.", "He works as a fish.", "He work fisherman.", "He is fishing a man."], 0,
           "Works as = travaille comme. Fisherman = pêcheur."),
        ex("« She has to get up early. » veut dire :",
           ["Elle doit se lever tôt.", "Elle aime se lever tôt.", "Elle s'est levée tard.", "Elle va dormir tôt."], 0,
           "Has to = doit."),
        ex("Complète : « If I find a job, I ____ stay. »", ["will", "am", "did", "was"], 0,
           "Pour plus tard : I will stay (je resterai)."),
        ex("Si je pars à l'étranger, ma famille va me manquer :",
           ["If I go abroad, I'll miss my family.", "If I will go abroad, I miss my family.",
            "If I go abroad, I missed my family.", "I go abroad if, I'll miss my family."], 0,
           "Juste après « If », on ne met pas « will »."),
        ex("Plus tard, tu vas être infirmière :",
           ["I go to be a nurse.", "I'm going to be a nurse.", "I'm going be a nurse.", "I going to be a nurse."], 1,
           "I'm going to be = je vais être."),
        ex("Tu n'es pas sûr de partir. Tu dis :", ["I will certainly go.", "I may go.", "I go every day.", "I went."], 1,
           "May = peut-être."),
        ex("« I will certainly stay. » veut dire :",
           ["Je resterai sûrement.", "Je resterai peut-être.", "Je ne reste pas.", "Je suis resté."], 0,
           "Certainly = sûrement, c'est sûr."),
        ex("La personne qui travaille à la ferme (farm), c'est :", ["a farmer", "a farming", "a farmment", "an unfarm"], 0,
           "Pour la personne, on ajoute souvent « -er »."),
        ex("Le contraire de « happy » :", ["happier", "unhappy", "happiness", "happyer"], 1,
           "« un- » devant le mot veut dire « pas »."),
        ex("Comment commencer une lettre à ton ami Modou ?", ["Hey you, Modou!", "Dear Modou,", "Goodbye, Modou,", "Thank you, Modou,"], 1,
           "Dans une lettre, on commence par « Dear… » (cher…)."),
    ],
)

# ======================= UNITÉ 6 : SPORTS, LEISURE, EDUCATION AND HEALTH =======================

u6 = [
    mission(
        "4e-u6-m1", "Debout à cinq heures !", "dire ce que j'aime faire quand je suis libre",
        ["In my free time, …", "I enjoy swimming.", "I'm fond of reading."],
        {"consigne": "Cinq heures du matin, sur la plage. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🏊", "⚽", "📖", "🌅"],
         "liste": [
             mot("swimming", True, "Oui ! « Swimming », c'est nager. Quelqu'un nage dans la mer."),
             mot("football", True, "Oui ! « Football », c'est le foot. On joue sur le sable."),
             mot("book", True, "Oui ! « Book », c'est le livre."),
             mot("sunrise", True, "Oui ! « Sunrise », c'est le lever du soleil. Il est très tôt !"),
             mot("television", False, "« Television », c'est la télé. Il n'y a pas de télé sur la plage ! Regarde encore."),
             mot("bed", False, "« Bed », c'est le lit. Gaïndé en rêve, mais il n'y a pas de lit ici ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Get up, Gaïndé! It's five o'clock!", "Debout, Gaïndé ! Il est cinq heures !"),
                       r("awa", "In my free time, I enjoy swimming in the morning.",
                         "Quand je suis libre, j'aime nager le matin."),
                       r("modou", "And I'm fond of football. On the beach!", "Et moi, j'adore le foot. Sur la plage !")],
         "gainde": "Moi, quand je suis libre, j'aime… dormir ! Comment on dit ça ?"},
        [q("Qu'est-ce qu'Awa aime faire ?", ["nager", "lire", "dormir"], 0, 1),
         q("Modou adore…", ["le foot", "la lutte", "la musique"], 0, 2)],
        [choix("Je dis que j'aime nager. Je dis laquelle ?", ["I enjoy swim.", "I enjoy swimming."], 1,
               aides("Écoute bien la fin du mot après « enjoy ».", 1, "Écoute Awa :",
                     "Moi, je dis : « I enjoy reading. »",
                     "Astuce : après « enjoy », le mot finit par « -ing » : swimming, reading.")),
         ordre("« Of reading fond I'm. » C'est ça ?", ["fond", "reading", "I'm", "of"], "Im fond of reading",
               "I'm fond of reading.",
               aides("Comment Modou dit « j'adore » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « I'm fond of music. »", "I'm fond of (j'adore) + reading (lire).")),
         trou("J'aime danser : « In my free time, I enjoy ___. »", "In my free time, I enjoy", ".", ["dancing"],
              "In my free time, I enjoy dancing.",
              aides("Après « enjoy », le mot finit comment ?", 1, "Écoute Awa : « I enjoy swimming ».",
                    "Moi, je dis : « I enjoy singing. »", "Danser, c'est « dance ». Avec « -ing » : dancing.")),
         libre("Qu'est-ce que tu aimes faire quand tu es libre ? Dis-le-moi !", ["enjoy|fond of|like|love"],
               aides("Comment Awa le dit ?", 1, "Écoute Awa :",
                     "Moi, je dis : « In my free time, I enjoy reading. »",
                     "Écris : « I enjoy… » et un mot en « -ing »."))],
        [tour("awa", "What do you enjoy doing in your free time?", "Qu'est-ce que tu aimes faire quand tu es libre ?",
              ["enjoy|fond of|like|love"], "I enjoy playing football.", "Cool! Me too!")],
        ["In my free time, …", "I enjoy swimming.", "I'm fond of reading."],
    ),
    mission(
        "4e-u6-m2", "La lutte, c'est notre sport", "parler d'une tradition de chez moi",
        ["Wrestling is very popular in Senegal.", "It's our tradition."],
        {"consigne": "Un combat de lutte sur la plage. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🤼", "🥁", "👥", "🏆"],
         "liste": [
             mot("wrestling", True, "Oui ! « Wrestling », c'est la lutte."),
             mot("drum", True, "Oui ! « Drum », c'est le tambour. Ici, c'est un tama."),
             mot("people", True, "Oui ! « People », ce sont les gens. Ils regardent le combat."),
             mot("sand", True, "Oui ! « Sand », c'est le sable de la plage."),
             mot("tennis", False, "« Tennis », c'est le tennis. Tu vois une raquette ? Non ! Regarde encore."),
             mot("snow", False, "« Snow », c'est la neige. Pas de neige à Kayar ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["modou", "doudou", "gainde"],
         "repliques": [r("modou", "Look! A wrestling match on the beach!", "Regarde ! Un combat de lutte sur la plage !"),
                       r("doudou", "Wrestling is very popular in Senegal.", "La lutte est très populaire au Sénégal."),
                       r("modou", "It's our tradition. The griots sing and play the tama.",
                         "C'est notre tradition. Les griots chantent et jouent du tama."),
                       r("doudou", "Like me! Boum, boum!", "Comme moi ! Boum, boum !")],
         "gainde": "La lutte ? Moi, je suis un lion ! Je veux lutter !"},
        [q("La lutte au Sénégal, c'est…", ["très populaire", "un sport nouveau", "interdit"], 0, 1),
         q("Que font les griots ?", ["Ils chantent et jouent du tama.", "Ils dorment.", "Ils pêchent."], 0, 2)],
        [choix("Un touriste demande : « What is wrestling? » Je réponds laquelle ?",
               ["Wrestling? Everybody knows that, stupid!", "Wrestling is very popular in Senegal."], 1,
               aides("Comment Doudou parle de la lutte ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « Wrestling is very popular in Senegal. »",
                     "« Popular », c'est « populaire, tout le monde aime ». Et « stupid », c'est très impoli !")),
         ordre("« Tradition our it's. » C'est ça ?", ["our", "It's", "tradition"], "Its our tradition", "It's our tradition.",
               aides("Comment Modou commence sa phrase ?", 2, "Écoute Modou :",
                     "Moi, je dis : « It's our tradition. »", "It's (c'est) + our tradition (notre tradition).")),
         trou("« Wrestling is very ___ in Senegal. »", "Wrestling is very", "in Senegal.", ["popular"],
              "Wrestling is very popular in Senegal.",
              aides("Quel mot dit que tout le monde aime la lutte ?", 1, "Écoute Doudou :",
                    "Moi, je dis : « Football is very popular too. »", "« Populaire », c'est « popular ». Écris : popular.")),
         libre("Parle d'une autre tradition : le thiéboudienne, la Tabaski… Dis qu'elle est très populaire au Sénégal.",
               ["popular", "senegal"],
               aides("Comment Doudou parle de la lutte ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « Thiéboudienne is very popular in Senegal. »",
                     "Écris : « … is very popular in Senegal. »"))],
        [tour("kocc", "Tell me about a tradition from your town.", "Parle-moi d'une tradition de ta ville.",
              ["popular|tradition"], "Wrestling is very popular in my town. It's our tradition.", "Wonderful! Thank you!")],
        ["Wrestling is very popular in Senegal.", "It's our tradition.", "wrestling", "griot", "festival"],
    ),
    mission(
        "4e-u6-m3", "L'école de Kayar", "parler de mon école",
        ["My favourite subject is English.", "We study maths and French."],
        {"consigne": "Une classe de l'école de Kayar. Quels mots vont avec l'image ?", "fond": "classe",
         "objets": ["📐", "🗺️", "🔬", "📚"],
         "liste": [
             mot("maths", True, "Oui ! « Maths », ce sont les maths. Il y a une équerre."),
             mot("map", True, "Oui ! « Map », c'est la carte, pour la géographie."),
             mot("science", True, "Oui ! « Science », ce sont les sciences."),
             mot("books", True, "Oui ! « Books », ce sont les livres."),
             mot("net", False, "« Net », c'est le filet de pêche. Pas de filet en classe ! Regarde encore."),
             mot("beach", False, "« Beach », c'est la plage. Aujourd'hui, on est en classe ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["kocc", "modou", "awa"],
         "repliques": [r("kocc", "Modou, what's your favourite subject?", "Modou, quelle est ta matière préférée ?"),
                       r("modou", "My favourite subject is P.E.! I love football.",
                         "Ma matière préférée, c'est le sport ! J'adore le foot."),
                       r("kocc", "And you, Awa?", "Et toi, Awa ?"),
                       r("awa", "My favourite subject is English. We study English, maths and French.",
                         "Ma matière préférée, c'est l'anglais. On étudie l'anglais, les maths et le français.")],
         "gainde": "Ma matière préférée ? La récré ! Et la cantine !"},
        [q("La matière préférée de Modou, c'est…", ["le sport", "l'anglais", "les maths"], 0, 1),
         q("La matière préférée d'Awa, c'est…", ["l'anglais", "le sport", "la musique"], 0, 3)],
        [choix("Je dis que j'aime les maths. Je dis laquelle ?",
               ["My subject favourite is maths.", "My favourite subject is maths."], 1,
               aides("Où Awa met le mot « favourite » ?", 3, "Écoute Awa :",
                     "Moi, je dis : « My favourite subject is history. »",
                     "En anglais, « favourite » vient avant « subject » : my favourite subject.")),
         ordre("« Study maths we French and. » C'est ça ?", ["maths", "We", "and", "study", "French"],
               "We study maths and French", "We study maths and French.",
               aides("Qui étudie ? Commence par ce mot.", 3, "Écoute la fin d'Awa :",
                     "Moi, je dis : « We study English and science. »",
                     "We study (nous étudions) + maths and French (les maths et le français).")),
         trou("« My favourite ___ is English. »", "My favourite", "is English.", ["subject"], "My favourite subject is English.",
              aides("Quel mot veut dire « matière » ?", 1, "Écoute Modou :",
                    "Moi, je dis : « My favourite subject is maths. »", "« Matière », c'est « subject ». Écris : subject.")),
         libre("Quelle est ta matière préférée ? Dis-le-moi !", ["favourite subject|favorite subject|i like|i love"],
               aides("Comment Awa le dit ?", 3, "Écoute Awa :",
                     "Moi, je dis : « My favourite subject is science. »",
                     "Écris : « My favourite subject is… » et ta matière."))],
        [tour("kocc", "What do you study at school?", "Qu'est-ce que tu étudies à l'école ?",
              ["study|have|learn"], "We study English, maths and French.", "Very good! Lots of subjects!"),
         tour("awa", "What's your favourite subject?", "Quelle est ta matière préférée ?",
              ["english|maths|math|french|science|history|geography|pe|p e|sport|art|music|physics|biology|wolof|arabic"],
              "My favourite subject is English.", "Me too! English is great!")],
        ["My favourite subject is…", "We study maths and French.", "subject", "exam", "P.E."],
    ),
    mission(
        "4e-u6-m4", "Le sport, c'est la santé", "dire ce qui est bon ou mauvais pour la santé",
        ["Playing football is good for your health.", "Eating too much sugar is bad for you."],
        {"consigne": "Sur le terrain de foot. Quels mots vont avec l'image ?", "fond": "terrain",
         "objets": ["⚽", "🍉", "💧", "👟"],
         "liste": [
             mot("football", True, "Oui ! « Football », c'est le foot."),
             mot("fruit", True, "Oui ! « Fruit », c'est un fruit. Ici, une pastèque."),
             mot("water", True, "Oui ! « Water », c'est l'eau. On boit après le sport."),
             mot("shoes", True, "Oui ! « Shoes », ce sont les chaussures."),
             mot("cigarette", False, "« Cigarette », c'est la cigarette. Il n'y en a pas ici, heureusement ! Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. Il n'y a pas de gâteau, il y a un fruit ! Regarde encore."),
         ]},
        {"fond": "terrain", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Come on! Playing football is good for your health!",
                         "Allez ! Jouer au foot, c'est bon pour la santé !"),
                       r("awa", "And drinking water is good for you.", "Et boire de l'eau, c'est bon pour toi."),
                       r("modou", "But eating too much sugar is bad for you!", "Mais manger trop de sucre, c'est mauvais pour toi !")],
         "gainde": "Trop de sucre ? Euh… je cache vite mes trois beignets…"},
        [q("Qu'est-ce qui est bon pour la santé ?", ["jouer au foot", "manger trop de sucre", "dormir sur le terrain"], 0, 0),
         q("Manger trop de sucre, c'est…", ["mauvais pour toi", "bon pour toi", "très drôle"], 0, 2)],
        [choix("Je parle du foot. Je dis laquelle ?",
               ["Play football is good for your health.", "Playing football is good for your health."], 1,
               aides("Comment Modou commence sa phrase ?", 0, "Écoute Modou :",
                     "Moi, je dis : « Swimming is good for your health. »",
                     "Astuce : au début de la phrase, on dit « Playing », avec « -ing ».")),
         ordre("« Sugar is bad eating too much for you. » C'est ça ?",
               ["too", "is", "Eating", "sugar", "bad", "you", "much", "for"],
               "Eating too much sugar is bad for you", "Eating too much sugar is bad for you.",
               aides("Quel mot Modou dit en premier ?", 2, "Écoute Modou :",
                     "Moi, je dis : « Eating too much sugar is bad for you. »",
                     "Eating too much sugar (manger trop de sucre) + is bad for you (c'est mauvais pour toi).")),
         trou("« Drinking water is ___ for you. »", "Drinking water is", "for you.", ["good", "great"],
              "Drinking water is good for you.",
              aides("Boire de l'eau, c'est bon ou mauvais ?", 1, "Écoute Awa :",
                    "Moi, je dis : « Sleeping well is good for you. »", "« Bon », c'est « good ». Écris : good.")),
         libre("Dis que dormir, c'est bon pour la santé.", ["sleeping|sleep", "good for"],
               aides("Comment Modou parle du foot ?", 0, "Écoute Modou :",
                     "Moi, je dis : « Swimming is good for your health. »",
                     "Dormir, c'est « sleep ». Écris : « Sleeping is good for your health. »"))],
        [tour("modou", "What is good for your health?", "Qu'est-ce qui est bon pour la santé ?",
              ["good for"], "Playing football is good for your health.", "Yes! Let's play!"),
         tour("awa", "And what is bad for you?", "Et qu'est-ce qui est mauvais pour toi ?",
              ["bad for"], "Eating too much sugar is bad for you.", "That's true! Sorry, Gaïndé!")],
        ["… is good for your health.", "… is bad for you.", "healthy", "exercise", "sleep"],
    ),
    mission(
        "4e-u6-m5", "Mon premier discours", "parler devant la classe",
        ["Good morning, everybody.", "Today, I'm going to talk about…", "Thank you for listening."],
        {"consigne": "Awa parle devant la classe. Quels mots vont avec l'image ?", "fond": "classe",
         "objets": ["🎤", "👥", "📄", "🏫"],
         "liste": [
             mot("microphone", True, "Oui ! « Microphone », c'est le micro."),
             mot("class", True, "Oui ! « Class », c'est la classe. Tout le monde écoute."),
             mot("paper", True, "Oui ! « Paper », c'est la feuille. Awa a écrit son discours dessus."),
             mot("school", True, "Oui ! « School », c'est l'école."),
             mot("boat", False, "« Boat », c'est le bateau. On n'est pas en mer aujourd'hui ! Regarde encore."),
             mot("bed", False, "« Bed », c'est le lit. On ne dort pas pendant un discours ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["awa", "kocc", "gainde"],
         "repliques": [r("awa", "Good morning, everybody.", "Bonjour à tous."),
                       r("awa", "Today, I'm going to talk about Kayar and its fishermen.",
                         "Aujourd'hui, je vais vous parler de Kayar et de ses pêcheurs."),
                       r("awa", "… Thank you for listening!", "… Merci de m'avoir écoutée !"),
                       r("kocc", "Well done, Awa! A great speech!", "Bravo, Awa ! Un très beau discours !")],
         "gainde": "Parler devant toute la classe ? J'ai les pattes qui tremblent !"},
        [q("Comment Awa commence ?", ["Good morning, everybody.", "Hey, guys!", "Goodbye!"], 0, 0),
         q("Awa parle de…", ["Kayar et ses pêcheurs", "la lutte", "son chat"], 0, 1)],
        [choix("Je commence mon discours devant la classe. Je dis laquelle ?",
               ["Yo guys! Listen to me!", "Good morning, everybody."], 1,
               aides("Comment Awa commence son discours ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Good morning, everybody. »",
                     "Devant la classe, on est poli : « Good morning, everybody ». « Yo guys! », c'est pour les copains dans la rue.")),
         ordre("« About going to I'm talk today wrestling. » C'est ça ?",
               ["talk", "Today", "going", "about", "I'm", "wrestling", "to"],
               "Today Im going to talk about wrestling", "Today, I'm going to talk about wrestling.",
               aides("Quel mot Awa dit en premier ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Today, I'm going to talk about football. »",
                     "Today (aujourd'hui) + I'm going to talk about (je vais parler de) + wrestling (la lutte).")),
         trou("À la fin : « Thank you for ___! »", "Thank you for", "!", ["listening"], "Thank you for listening!",
              aides("Comment Awa finit son discours ?", 2, "Écoute Awa :",
                    "Moi, je dis : « Thank you for listening! »", "Écouter, c'est « listen ». Avec « -ing » : listening.")),
         libre("Commence ton discours : dis bonjour à tous, puis dis de quoi tu vas parler.",
               ["everybody|everyone", "talk about|speak about"],
               aides("Comment Awa commence ?", 0, "Écoute le début :",
                     "Moi, je dis : « Good morning, everybody. Today, I'm going to talk about music. »",
                     "Écris : « Good morning, everybody. Today, I'm going to talk about… »"))],
        [tour("kocc", "It's your turn! Start your speech, please.", "C'est ton tour ! Commence ton discours, s'il te plaît.",
              ["good morning|good afternoon|good evening|hello|hi", "talk about|speak about"],
              "Good morning, everybody. Today, I'm going to talk about football.", "A very good start!"),
         tour("kocc", "And how do you finish?", "Et comment tu finis ?",
              ["thank you|thanks"], "Thank you for listening!", "Bravo! Everybody is clapping!")],
        ["Good morning, everybody.", "Today, I'm going to talk about…", "Thank you for listening."],
    ),
]

unite6 = unite(
    "4e-u6", "Sports, leisure, education and health",
    "Mon loisir préféré : fais un petit discours devant la classe pour parler de ton loisir.",
    u6,
    lignes=[
        ("Dire ce que j'aime faire quand je suis libre", "In my free time, … · I enjoy swimming. · I'm fond of reading."),
        ("Parler d'une tradition", "Wrestling is very popular in Senegal. · It's our tradition."),
        ("Parler de mon école", "My favourite subject is English. · We study maths and French."),
        ("Dire ce qui est bon ou mauvais pour la santé",
         "Playing football is good for your health. · Eating too much sugar is bad for you."),
        ("Parler devant la classe", "Good morning, everybody. · Today, I'm going to talk about… · Thank you for listening."),
    ],
    mots=[
        ("wrestling", "lutte", "làmb"),
        ("griot", "griot", "gewël"),
        ("to dance", "danser", "fecc"),
        ("to swim", "nager", "féey"),
        ("song", "chanson", "woy"),
        ("school", "école", "lekkool"),
        ("book", "livre", "téere"),
        ("health", "santé", "wér-gi-yaram"),
        ("to sleep", "dormir", "nelaw"),
        ("sugar", "sucre", "suukar"),
    ],
    pieges=[
        "I enjoy swimming. Pas « I enjoy swim ».",
        "My favourite subject. Pas « my subject favourite ».",
        "Playing football is good. Pas « Play football is good ».",
        "Thank you for listening. Pas « Thank you for listen ».",
    ],
    exercices=[
        ex("Tu aimes nager :", ["I enjoy swim.", "I enjoy swimming.", "I enjoy to swimming.", "I enjoying swim."], 1,
           "Après « enjoy », on met « -ing » : swimming."),
        ex("« I'm fond of reading. » veut dire :", ["J'adore lire.", "Je déteste lire.", "Je lis vite.", "J'ai trouvé un livre."], 0,
           "Fond of = j'aime beaucoup."),
        ex("La lutte est très populaire au Sénégal :",
           ["Wrestling is very popular in Senegal.", "Wrestling very popular is in Senegal.", "Senegal is very wrestling.",
            "Wrestling are popular Senegal."], 0, "Wrestling = la lutte. Popular = populaire."),
        ex("Complète : « It's ____ tradition. » (notre)", ["our", "we", "us", "ours"], 0, "Our = notre."),
        ex("Ta matière préférée, c'est l'anglais :",
           ["My subject favourite is English.", "My favourite subject is English.", "My favourite English is subject.",
            "Favourite my subject is English."], 1, "« Favourite » vient avant « subject »."),
        ex("« We study maths and French. » veut dire :",
           ["Nous étudions les maths et le français.", "Nous aimons les maths.", "Nous avons un examen.", "Nous parlons français."], 0,
           "Study = étudier."),
        ex("Jouer au foot, c'est bon pour la santé :",
           ["Play football is good for your health.", "Playing football is good for your health.",
            "Playing football is bad for your health.", "Football playing good health."], 1,
           "Au début de la phrase : « Playing », avec « -ing »."),
        ex("Complète : « Eating too much sugar is ____ for you. »", ["good", "bad", "fond", "popular"], 1,
           "Trop de sucre, c'est mauvais : bad."),
        ex("Tu commences ton discours devant la classe :", ["Yo guys!", "Good morning, everybody.", "Goodbye, everybody.", "Hey you!"], 1,
           "Devant la classe, on est poli : « Good morning, everybody. »"),
        ex("Tu finis ton discours :", ["Thank you for listening.", "Thank you for listen.", "Go away now.", "Today, I'm going to talk about."], 0,
           "Pour finir : « Thank you for listening. »"),
    ],
)

UNITES = [unite4, unite5, unite6]

# ======================= LES ÉPISODES =======================

EPISODES = [
    # Unité 4, après les missions 1 et 2 : le temps qu'il fait + depuis combien de temps.
    episode("La pluie du bouc", "4e-u4-m2", [
        case("terrain", [perso("awa", 0.05, 90), perso("modou", 0.6, 90)],
             [bulle("It hasn't rained for three months.", "Il n'a pas plu depuis trois mois.", 0.03, 0.04),
              bulle("It hasn't rained since May. The farmers are waiting for the rain.", "Il n'a pas plu depuis mai. Les paysans attendent la pluie.", 0.45, 0.32)]),
        case("terrain", [perso("gainde", 0.05, 100, "danse"), perso("doudou", 0.6, 90, "balance")],
             [bulle("No problem! Rain, rain, come to Kayar!", "Pas de problème ! Pluie, pluie, viens à Kayar ! (il fait la danse de la pluie)", 0.03, 0.04),
              bulle("Boum, boum, boum!", "Boum, boum, boum ! (Doudou joue du tama)", 0.5, 0.32)]),
        case("terrain", [perso("gainde", 0.05, 95, "saute"), perso("kocc", 0.6, 95)],
             [bulle("Look! A cloud! It's rainy!", "Regarde ! Un nuage ! Il pleut !", 0.03, 0.04),
              bulle("No, Gaïndé. It's windy. It's sand!", "Non, Gaïndé. C'est le vent. C'est du sable ! (tout le monde est plein de sable)", 0.45, 0.32)]),
        case("terrain", [perso("bouc", 0.05, 80), perso("gainde", 0.35, 95, "danse"), perso("modou", 0.68, 90)],
             [bulle("ATCHOUM!", "ATCHOUM ! (le bouc éternue sur Gaïndé)", 0.02, 0.03),
              bulle("It's rainy! Thank you, Sir!", "Il pleut ! Merci, Monsieur ! (il remercie le bouc)", 0.3, 0.25),
              bulle("Gaïndé… that's not rain!", "Gaïndé… ce n'est pas de la pluie !", 0.55, 0.47)]),
    ], ["It's windy.", "It's rainy.", "It hasn't rained for three months.", "It hasn't rained since May."]),

    # Unité 4, après les missions 3 et 4 : il y a + qui a fait quelque chose.
    episode("Le sandwich de trois jours", "4e-u4-m4", [
        case("mer", [perso("modou", 0.05, 90), perso("gainde", 0.6, 95, "saute")],
             [bulle("Look! The net is full!", "Regarde ! Le filet est plein !", 0.03, 0.04),
              bulle("A big fish! Lunch!", "Un gros poisson ! Le déjeuner !", 0.5, 0.32)]),
        case("mer", [perso("awa", 0.05, 90), perso("gainde", 0.6, 95)],
             [bulle("No fish… bottles! The sea was polluted by plastic.", "Pas de poisson… des bouteilles ! La mer a été polluée par le plastique.", 0.03, 0.04),
              bulle("Wait… my sandwich!", "Attends… mon sandwich ! (il sort un vieux sandwich tout mouillé du filet)", 0.5, 0.32)]),
        case("mer", [perso("gainde", 0.05, 100, "danse"), perso("kocc", 0.6, 95)],
             [bulle("This sandwich was made by my mum! I lost it three days ago!", "Ce sandwich a été fait par ma maman ! Je l'ai perdu il y a trois jours !", 0.03, 0.04),
              bulle("Three days ago? In the sea?!", "Il y a trois jours ? Dans la mer ?!", 0.45, 0.34)]),
        case("mer", [perso("gainde", 0.05, 95), perso("poisson", 0.4, 60, "saute"), perso("awa", 0.68, 90)],
             [bulle("Mmm! A fish sandwich!", "Mmm ! Un sandwich au poisson ! (un petit poisson sort du sandwich)", 0.02, 0.03),
              bulle("Bye bye!", "Salut ! (le poisson saute dans la mer)", 0.3, 0.3),
              bulle("Yuck!", "Beurk !", 0.6, 0.47)]),
    ], ["three days ago", "The sea was polluted by plastic.", "This sandwich was made by my mum."]),

    # Unité 4, après la mission 5 : d'accord, pas d'accord.
    episode("D'accord avec tout le monde", "4e-u4-m5", [
        case("mer", [perso("modou", 0.05, 90), perso("pirogue", 0.3, 130, "tangue"), perso("awa", 0.68, 90)],
             [bulle("The fish are on the left!", "Les poissons sont à gauche !", 0.02, 0.03),
              bulle("I don't think so. They're on the right!", "Je ne crois pas. Ils sont à droite !", 0.5, 0.35)]),
        case("mer", [perso("gainde", 0.3, 100, "tangue")],
             [bulle("I agree with you! … And I agree with you!", "Je suis d'accord avec toi ! … Et je suis d'accord avec toi ! (il court à gauche, puis à droite : la pirogue tangue très fort)", 0.05, 0.05)]),
        case("mer", [perso("kocc", 0.05, 95), perso("gainde", 0.6, 95, "saute")],
             [bulle("Gaïndé, stop! Sit down!", "Gaïndé, arrête ! Assieds-toi !", 0.03, 0.04),
              bulle("That's true, but… AAAH!", "C'est vrai, mais… AAAH ! (PLOUF ! Il tombe dans la mer)", 0.5, 0.32)]),
        case("mer", [perso("gainde", 0.05, 95, "balance"), perso("poisson", 0.6, 70)],
             [bulle("Look! I'm a fish now!", "Regardez ! Maintenant, je suis un poisson !", 0.03, 0.04),
              bulle("I don't think so.", "Je ne crois pas.", 0.5, 0.35)]),
    ], ["I agree with you.", "I don't think so.", "That's true, but…"]),

    # Unité 5, après les missions 1 et 2 : un métier + si… alors…
    episode("Le pêcheur qui dort", "4e-u5-m2", [
        case("plage", [perso("modou", 0.05, 90), perso("gainde", 0.6, 95, "saute")],
             [bulle("My uncle works as a fisherman. He has to get up at five.", "Mon oncle travaille comme pêcheur. Il doit se lever à cinq heures.", 0.03, 0.04),
              bulle("Easy! If I get up at five, I'll be a fisherman too!", "Facile ! Si je me lève à cinq heures, je serai pêcheur aussi !", 0.45, 0.32)]),
        case("nuit", [perso("kocc", 0.05, 95), perso("gainde", 0.55, 95, "immobile")],
             [bulle("Gaïndé! It's five o'clock!", "Gaïndé ! Il est cinq heures !", 0.03, 0.04),
              bulle("Zzz… If I get up, I'll be tired… Zzz…", "Zzz… Si je me lève, je serai fatigué… Zzz…", 0.45, 0.34)]),
        case("mer", [perso("modou", 0.05, 90), perso("pirogue", 0.35, 130, "tangue")],
             [bulle("Where is Gaïndé?", "Où est Gaïndé ?", 0.03, 0.04),
              bulle("He's in the pirogue… sleeping!", "Il est dans la pirogue… il dort ! (Gaïndé ronfle, la bouche grande ouverte)", 0.4, 0.3)]),
        case("mer", [perso("gainde", 0.05, 100, "immobile"), perso("poisson", 0.38, 60, "saute"), perso("modou", 0.68, 90, "danse")],
             [bulle("Mmm… If I sleep, the fish will come to me!", "Mmm… Si je dors, les poissons viendront à moi ! (un poisson saute droit dans sa bouche)", 0.02, 0.03),
              bulle("Ha ha! He works as a fisherman… with his mouth!", "Ha ha ! Il travaille comme pêcheur… avec sa bouche !", 0.5, 0.42)]),
    ], ["He works as a fisherman.", "He has to get up at five.", "If I get up at five, I'll be a fisherman."]),

    # Unité 5, après les missions 3 et 4 : plus tard + peut-être / c'est sûr.
    episode("Kocc Barma part à l'étranger", "4e-u5-m4", [
        case("plage", [perso("awa", 0.05, 90), perso("modou", 0.6, 90)],
             [bulle("I'm going to be a journalist.", "Moi, je vais être journaliste.", 0.03, 0.04),
              bulle("I'm going to be a mechanic.", "Moi, je vais être mécanicien.", 0.5, 0.32)]),
        case("plage", [perso("gainde", 0.3, 105, "saute")],
             [bulle("And I'm going to be… a nurse! A tailor! A mechanic!", "Et moi, je vais être… infirmier ! Tailleur ! Mécanicien ! (il a un pansement sur le nez, une aiguille et une clé)", 0.05, 0.05)]),
        case("plage", [perso("gainde", 0.05, 95, "danse"), perso("kocc", 0.6, 95)],
             [bulle("Next year, I will certainly be a tailor!", "L'année prochaine, je serai sûrement tailleur ! (il coud, il coud, il coud…)", 0.03, 0.04),
              bulle("Gaïndé… where is my boubou?", "Gaïndé… où est mon boubou ?", 0.5, 0.34)]),
        case("mer", [perso("pirogue", 0.05, 130, "tangue"), perso("kocc", 0.4, 90, "balance"), perso("gainde", 0.68, 90)],
             [bulle("I may go abroad… today!", "Je vais peut-être partir à l'étranger… aujourd'hui ! (Gaïndé a cousu son boubou à la voile de la pirogue)", 0.25, 0.03),
              bulle("Sorry! I will certainly be a good mechanic!", "Pardon ! Je serai sûrement un bon mécanicien !", 0.5, 0.45)]),
    ], ["I'm going to be a journalist.", "Next year, I will…", "I may go abroad.", "I will certainly…"]),

    # Unité 5, après les missions 5 et 6 : la famille des mots + la lettre.
    episode("La lettre dans la bouteille", "4e-u5-m6", [
        case("maison", [perso("gainde", 0.05, 95), perso("kocc", 0.6, 95)],
             [bulle("Dear Mum, How are you? I'm fine in Kayar.", "Chère maman, comment vas-tu ? Je vais bien à Kayar.", 0.03, 0.04),
              bulle("Very good, Gaïndé!", "Très bien, Gaïndé !", 0.5, 0.34)]),
        case("maison", [perso("gainde", 0.3, 105, "danse")],
             [bulle("Fish, fisherman, fishing… and me: fish-eater!", "Fish, fisherman, fishing… et moi : fish-eater (mangeur de poissons) ! (il dessine un poisson dans une assiette)", 0.05, 0.05)]),
        case("plage", [perso("gainde", 0.05, 95, "saute"), perso("awa", 0.6, 90)],
             [bulle("Take care. Love, Gaïndé.", "Prends soin de toi. Bisous, Gaïndé. (il met la lettre dans une bouteille et la jette à la mer)", 0.03, 0.04),
              bulle("Gaïndé! Not in the sea!", "Gaïndé ! Pas dans la mer !", 0.5, 0.34)]),
        case("mer", [perso("poisson", 0.05, 75), perso("gainde", 0.6, 95)],
             [bulle("Dear Gaïndé, a fish-eater? I'm very unhappy! Love, Fish.", "Cher Gaïndé, un mangeur de poissons ? Je ne suis pas content du tout ! Bisous, Poisson.", 0.03, 0.04),
              bulle("Oops…", "Oups…", 0.55, 0.38)]),
    ], ["fish → fisherman → fishing", "unhappy", "Dear Mum,", "How are you?", "Take care. Love, Gaïndé."]),

    # Unité 6, après les missions 1 et 2 : les loisirs + une tradition.
    episode("Le lion contre le bouc", "4e-u6-m2", [
        case("plage", [perso("doudou", 0.05, 90, "balance"), perso("gainde", 0.6, 100, "saute")],
             [bulle("Wrestling is very popular in Senegal!", "La lutte est très populaire au Sénégal !", 0.03, 0.04),
              bulle("I'm fond of wrestling! I'm a lion!", "J'adore la lutte ! Je suis un lion !", 0.5, 0.32)]),
        case("plage", [perso("gainde", 0.05, 100, "danse"), perso("doudou", 0.6, 90, "balance")],
             [bulle("Look! I enjoy dancing too!", "Regardez ! J'aime aussi danser ! (il fait la danse des lutteurs pendant une heure, du sable partout)", 0.03, 0.04),
              bulle("Boum, boum! It's our tradition!", "Boum, boum ! C'est notre tradition !", 0.5, 0.34)]),
        case("plage", [perso("gainde", 0.05, 95), perso("bouc", 0.6, 85)],
             [bulle("Who is that? A goat?!", "C'est qui, lui ? Une chèvre ?! (l'adversaire de Gaïndé arrive : c'est le bouc)", 0.03, 0.04),
              bulle("Bêêê!", "Bêêê !", 0.55, 0.36)]),
        case("plage", [perso("bouc", 0.05, 85, "saute"), perso("gainde", 0.35, 90, "immobile"), perso("modou", 0.68, 90, "danse")],
             [bulle("Ha ha! The goat enjoys wrestling too!", "Ha ha ! Le bouc aussi aime la lutte ! (le bouc a poussé Gaïndé avec ses cornes)", 0.5, 0.03),
              bulle("In my free time… I enjoy sleeping.", "Quand je suis libre… j'aime dormir. (Gaïndé, la tête dans le sable)", 0.15, 0.45)]),
    ], ["I'm fond of wrestling.", "I enjoy dancing.", "Wrestling is very popular in Senegal.", "It's our tradition."]),

    # Unité 6, après les missions 3 et 4 : l'école + la santé.
    episode("Le ballon Gaïndé", "4e-u6-m4", [
        case("classe", [perso("kocc", 0.05, 95), perso("gainde", 0.6, 95)],
             [bulle("Gaïndé, what's your favourite subject?", "Gaïndé, quelle est ta matière préférée ?", 0.03, 0.04),
              bulle("My favourite subject is… lunch!", "Ma matière préférée, c'est… le déjeuner !", 0.5, 0.34)]),
        case("classe", [perso("kocc", 0.05, 95), perso("gainde", 0.6, 95, "saute")],
             [bulle("Lunch is not a subject! We study maths, English, French…", "Le déjeuner, ce n'est pas une matière ! On étudie les maths, l'anglais, le français…", 0.03, 0.04),
              bulle("OK… my favourite subject is P.E.!", "D'accord… ma matière préférée, c'est le sport !", 0.5, 0.36)]),
        case("terrain", [perso("modou", 0.05, 90), perso("gainde", 0.6, 95, "danse")],
             [bulle("Playing football is good for your health!", "Jouer au foot, c'est bon pour la santé !", 0.03, 0.04),
              bulle("And eating is good for my health!", "Et manger, c'est bon pour MA santé ! (il mange dix beignets d'un coup)", 0.45, 0.32)]),
        case("terrain", [perso("modou", 0.05, 90, "saute"), perso("gainde", 0.38, 90, "balance"), perso("awa", 0.68, 90)],
             [bulle("GOAL!", "BUT ! (Gaïndé est tout rond. Modou croit que c'est le ballon et tire dedans)", 0.02, 0.03),
              bulle("Eating too much is bad for you, Gaïndé!", "Manger trop, c'est mauvais pour toi, Gaïndé !", 0.45, 0.45)]),
    ], ["My favourite subject is…", "We study maths, English, French.", "Playing football is good for your health.",
        "Eating too much is bad for you."]),

    # Unité 6, après la mission 5 : le discours. Fin de la saison : la grande fête sur la plage de Kayar.
    episode("La grande fête de Kayar", "4e-u6-m5", [
        case("nuit", [perso("modou", 0.05, 90), perso("doudou", 0.6, 90, "balance")],
             [bulle("Big party on the beach! Gaïndé, it's your speech!", "Grande fête sur la plage ! Gaïndé, c'est ton discours !", 0.03, 0.04),
              bulle("Boum, boum!", "Boum, boum !", 0.55, 0.36)]),
        case("nuit", [perso("gainde", 0.05, 95, "tangue"), perso("kocc", 0.6, 95)],
             [bulle("G-g-good morning, everybody!", "B-b-bonjour à tous ! (« Good morning », c'est pour le matin… Ses pattes tremblent.)", 0.03, 0.04),
              bulle("Gaïndé… it's night!", "Gaïndé… c'est la nuit !", 0.5, 0.36)]),
        case("nuit", [perso("gainde", 0.3, 105, "saute")],
             [bulle("Good evening, everybody! Today, I'm going to talk about… about… fish! Thank you for listening!",
                    "Bonsoir à tous ! Aujourd'hui, je vais vous parler de… de… poisson ! Merci de m'avoir écouté ! (il a tout oublié : son discours a duré trois secondes)",
                    0.05, 0.05)]),
        case("nuit", [perso("awa", 0.02, 90, "danse"), perso("modou", 0.35, 90, "danse2"), perso("doudou", 0.68, 90, "balance")],
             [bulle("Three seconds! The best speech in Kayar!", "Trois secondes ! Le meilleur discours de Kayar !", 0.02, 0.03),
              bulle("Thank you, Gaïndé!", "Merci, Gaïndé ! (tout le monde applaudit)", 0.3, 0.27),
              bulle("Boum, boum, boum!", "Boum, boum, boum !", 0.55, 0.47)]),
        case("plage", [perso("gainde", 0.05, 95, "danse"), perso("pirogue", 0.35, 130, "danse2"), perso("poisson", 0.7, 60, "saute")],
             [bulle("Dancing is good for your health!", "Danser, c'est bon pour la santé ! (Gaïndé, la pirogue et le poisson dansent jusqu'au matin)", 0.03, 0.04),
              bulle("Good morning, everybody! See you in 3e!", "Bonjour à tous ! (cette fois, c'est vraiment le matin) Rendez-vous en 3e !", 0.4, 0.4)]),
    ], ["Good morning, everybody.", "Today, I'm going to talk about…", "Thank you for listening.", "… is good for your health."]),
]
