"""Parcours d'anglais de 4e, unités 1 à 3 (saison « La pirogue de Kayar »)."""
from jang_lib import *  # noqa: F401,F403

NIVEAU = "4e"

# ======================= UNITÉ 1 : WHO AM I? =======================

u1 = [
    mission(
        "4e-u1-m1", "L'oncle de Modou a une pirogue", "bien me présenter",
        ["I was born in Kébémer.", "I come from…", "I live with…"],
        {"consigne": "La plage de Kayar. Quels mots vont avec l'image ?", "fond": "plage", "objets": ["🛶", "🐟", "🌊", "🎣"],
         "liste": [
             mot("boat", True, "Oui ! « Boat », c'est le bateau. Ici, c'est une pirogue."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("sea", True, "Oui ! « Sea », c'est la mer, avec les vagues."),
             mot("sand", True, "Oui ! « Sand », c'est le sable de la plage."),
             mot("fisherman", True, "Oui ! « Fisherman », c'est le pêcheur, comme l'oncle de Modou."),
             mot("desert", False, "« Desert », c'est le désert : du sable, mais pas d'eau. Ici, il y a la mer ! Regarde encore."),
             mot("train", False, "« Train », c'est le train. Il n'y a pas de train sur la plage. Regarde encore !"),
             mot("snow", False, "« Snow », c'est la neige. Il ne neige pas à Kayar ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Modou, tell me about you. Where were you born?", "Modou, parle-moi de toi. Tu es né où ?"),
                       r("modou", "I was born in Kébémer. I come from a family of fishermen.", "Je suis né à Kébémer. Je viens d'une famille de pêcheurs."),
                       r("awa", "And who do you live with?", "Et tu vis avec qui ?"),
                       r("modou", "I live with my mum in Dakar. My uncle lives here, in Kayar. He has got a pirogue!", "Je vis avec ma maman à Dakar. Mon oncle vit ici, à Kayar. Il a une pirogue !")],
         "gainde": "Une pirogue ! Je vais rencontrer l'oncle de Modou. Comment je me présente à un adulte ?"},
        [q("Modou est né où ?", ["à Dakar", "à Kébémer", "à Kayar"], 1, 1),
         q("Modou vit avec qui ?", ["avec sa maman", "avec son oncle", "avec Awa"], 0, 3)],
        [choix("Je me présente à l'oncle de Modou. C'est un adulte. Je dis laquelle ?",
               ["Yo, man! Lion here. Born in the bush!", "Hello! I'm Gaïndé. I was born in Niokolo-Koba."], 1,
               aides("L'oncle est un adulte. On lui parle comment : comme à un copain, ou poliment ?", 1, "Écoute comment Modou dit où il est né :",
                     "Moi, je dis : « Hello! I'm Kocc Barma. I was born in Kayar. »",
                     "« Yo, man! », c'est pour un copain. À un adulte, on dit « Hello! » et une vraie phrase.")),
         ordre("« Born I was in Niokolo-Koba. » C'est bien ça ?", ["born", "in", "I", "Niokolo-Koba", "was"],
               "I was born in Niokolo-Koba", "I was born in Niokolo-Koba.",
               aides("Par quel mot Modou commence-t-il sa phrase ?", 1, "Écoute bien l'ordre des mots :",
                     "Moi, je dis : « I was born in Kayar. »",
                     "« I was born in… », c'est « Je suis né à… ». On dit toujours les mots dans cet ordre.")),
         trou("Je vis avec ma grand-mère. « I live ___ my grandmother. »", "I live", "my grandmother.", ["with"],
              "I live with my grandmother.",
              aides("Qu'est-ce que Modou dit pour sa maman ? « I live … my mum. »", 3, "Écoute Modou :",
                    "Moi, je dis : « I live with my wife. »", "« With », c'est « avec ». Écris : with.")),
         libre("L'oncle de Modou me demande où je suis né. Je dis juste « Bush. » ? C'est un peu court, non ?", ["born"],
               aides("Comment Modou dit-il où il est né ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I was born in Kayar. »", "Écris : « I was born in Niokolo-Koba. »"))],
        [tour("awa", "Hello! Where were you born?", "Bonjour ! Tu es né(e) où ?", ["born|from"],
              "I was born in Thiès.", "Thiès? Nice! I was born in Dakar."),
         tour("modou", "And who do you live with?", "Et tu vis avec qui ?", ["with"],
              "I live with my mum and my brother.", "Cool! I live with my mum too.")],
        ["I was born in…", "I come from…", "I live with…", "fisherman"],
    ),
    mission(
        "4e-u1-m2", "La fiche d'inscription", "remplir une fiche avec mon nom, ma date de naissance…",
        ["Surname?", "First name?", "Date of birth?", "Could you spell that?"],
        {"consigne": "Avant de monter dans la pirogue, on remplit une fiche. Quels mots vont avec l'image ?",
         "fond": "plage", "objets": ["📋", "🖊️", "🦺", "🛶"],
         "liste": [
             mot("form", True, "Oui ! « Form », c'est la fiche à remplir."),
             mot("pen", True, "Oui ! « Pen », c'est le stylo pour écrire."),
             mot("life jacket", True, "Oui ! « Life jacket », c'est le gilet de sauvetage. Il est orange."),
             mot("boat", True, "Oui ! « Boat », c'est le bateau, la pirogue."),
             mot("ball", False, "« Ball », c'est le ballon. On ne joue pas, on remplit une fiche ! Regarde encore."),
             mot("bed", False, "« Bed », c'est le lit. Il n'y a pas de lit sur la plage. Regarde encore !"),
         ]},
        {"fond": "plage", "persos": ["kocc", "modou", "gainde"],
         "repliques": [r("kocc", "Good morning! Surname?", "Bonjour ! Ton nom de famille ?"),
                       r("modou", "Ndiaye.", "Ndiaye."),
                       r("kocc", "Could you spell that, please?", "Tu peux l'épeler, s'il te plaît ?"),
                       r("modou", "N-D-I-A-Y-E. First name: Modou. Date of birth: the third of March, 2013.",
                         "N-D-I-A-Y-E. Prénom : Modou. Date de naissance : le 3 mars 2013.")],
         "gainde": "Surname, first name… J'ai deux noms, moi ? Et ma date de naissance, c'est quoi ?"},
        [q("« Surname », c'est…", ["le prénom", "le nom de famille", "le surnom"], 1, 0),
         q("Modou est né quand ?", ["le 3 mars 2013", "le 13 mai 2003", "le 3 mai 2013"], 0, 3)],
        [choix("Je remplis la fiche d'Awa. Je lui demande son nom de famille. Je dis laquelle ?",
               ["Hey! Your surname! Quick!", "Surname, please?"], 1,
               aides("Kocc Barma est-il pressé et fâché quand il parle à Modou ?", 0, "Écoute Kocc Barma :",
                     "Moi, je dis : « Good morning! Surname, please? »",
                     "« Hey! Quick! », c'est sec et pas poli. Avec « please », c'est gentil.")),
         ordre("« Spell that, you! » C'est poli, non ? Aide-moi à demander gentiment.",
               ["spell", "please", "Could", "that", "you"], "Could you spell that please", "Could you spell that, please?",
               aides("Pour demander gentiment, Kocc Barma commence par quel mot ?", 2, "Écoute Kocc Barma :",
                     "Moi, je dis : « Could you spell that, please? »",
                     "« Could you… ? », c'est « Tu peux… ? ». C'est poli.")),
         trou("« Date of ___? » Je dis « Date of born » ?", "Date of", "?", ["birth"], "Date of birth?",
              aides("Écoute la fin de Modou. Quel mot vient après « Date of » ?", 3, "Écoute Modou :",
                    "Moi, je demande : « Date of birth? »", "« Birth », c'est la naissance. Écris : birth.")),
         libre("Je demande son prénom à Awa : « Give me your little name! » Hmm… Ce n'est pas ça. Aide-moi !",
               ["first name"],
               aides("Dans la fiche, comment dit-on « prénom » ?", 3, "Écoute Modou :",
                     "Moi, je dis : « First name, please? »", "Prénom = first name. Écris : « What's your first name, please? »"))],
        [tour("kocc", "Good morning! Surname and first name, please?", "Bonjour ! Ton nom et ton prénom, s'il te plaît ?", [],
              "Sow. Fatou Sow.", "Thank you. Could you spell that, please?"),
         tour("kocc", "And your date of birth?", "Et ta date de naissance ?", [],
              "The fifth of May, 2013.", "Thank you! Here is your life jacket.")],
        ["Surname?", "First name?", "Date of birth?", "Could you spell that, please?"],
    ),
    mission(
        "4e-u1-m3", "L'arbre de la famille de Modou", "présenter l'arbre de ma famille",
        ["My grandfather has got five children.", "She's married to…"],
        {"consigne": "Modou dessine sa famille. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["👴", "👵", "👨‍👩‍👧‍👦", "🌳"],
         "liste": [
             mot("grandfather", True, "Oui ! « Grandfather », c'est le grand-père."),
             mot("grandmother", True, "Oui ! « Grandmother », c'est la grand-mère."),
             mot("children", True, "Oui ! « Children », ce sont les enfants."),
             mot("tree", True, "Oui ! « Tree », c'est l'arbre. Ici, c'est l'arbre de la famille."),
             mot("family", True, "Oui ! « Family », c'est la famille."),
             mot("goat", False, "« Goat », c'est la chèvre. Elle n'est pas dans la famille de Modou ! Regarde encore."),
             mot("teacher", False, "« Teacher », c'est le prof. Il n'y a pas de prof sur le dessin. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Look! This is my family tree. My grandfather has got five children.",
                         "Regarde ! C'est l'arbre de ma famille. Mon grand-père a cinq enfants."),
                       r("awa", "Who is this lady?", "Qui est cette dame ?"),
                       r("modou", "That's my aunt Fatou. She's married to my uncle Ibou, the fisherman.",
                         "C'est ma tante Fatou. Elle est mariée à mon oncle Ibou, le pêcheur."),
                       r("awa", "And Ibou has got the pirogue!", "Et c'est Ibou qui a la pirogue !")],
         "gainde": "Un arbre avec des gens dedans ? Je veux faire le mien ! Mais comment je présente ma famille ?"},
        [q("Combien d'enfants a le grand-père de Modou ?", ["trois", "cinq", "dix"], 1, 0),
         q("Fatou est mariée à qui ?", ["à Ibou", "à Modou", "au grand-père"], 0, 2)],
        [choix("Je présente mon grand-père à Kocc Barma, devant la classe. Je dis laquelle ?",
               ["My grandpa got loads of kids, man!", "My grandfather has got five children."], 1,
               aides("Devant la classe, on parle comme dans la rue, ou avec de belles phrases ?", 0, "Écoute Modou :",
                     "Moi, je dis : « My grandfather has got eight children. »",
                     "« Loads of kids, man! », c'est pour les copains. Devant la classe, on dit « has got five children ».")),
         ordre("« My grandfather five children has got. » C'est ça ?", ["has", "five", "My", "children", "got", "grandfather"],
               "My grandfather has got five children", "My grandfather has got five children.",
               aides("Quels mots viennent juste après « My grandfather » ?", 0, "Écoute Modou :",
                     "Moi, je dis : « My grandmother has got three children. »",
                     "On dit : qui (My grandfather) + has got + combien (five children).")),
         trou("« She's married ___ Ibou. » Je dis « married with » ?", "She's married", "Ibou.", ["to"],
              "She's married to Ibou.",
              aides("Écoute Modou. Quel petit mot vient après « married » ?", 2, "Écoute Modou :",
                    "Moi, je dis : « My wife is married to me! »",
                    "En anglais, on dit « married to », pas « married with ». Écris : to.")),
         libre("Je présente le grand-père d'Awa : il a quatre enfants. Je dis « Awa's grandpa, four kids. » ? C'est un peu court…",
               ["grandfather|grandpa", "four|4"],
               aides("Comment Modou présente-t-il son grand-père ?", 0, "Écoute Modou :",
                     "Moi, je dis : « My grandfather has got five children. »",
                     "Écris : « Awa's grandfather has got four children. »"))],
        [tour("modou", "How many children has your grandfather got?", "Ton grand-père a combien d'enfants ?", ["has|got|have"],
              "He has got six children.", "Six! That's a big family!"),
         tour("awa", "Who is your aunt married to?", "Ta tante est mariée à qui ?", ["married to"],
              "She's married to Moussa.", "Oh, I know Moussa! He's very nice.")],
        ["My grandfather has got five children.", "She's married to…", "aunt", "uncle", "family tree"],
    ),
    mission(
        "4e-u1-m4", "La photo du port", "décrire une image",
        ["In this picture, I can see…", "On the left…", "In the background…"],
        {"consigne": "Awa a pris une photo du port. Quels mots vont avec l'image ?", "fond": "mer", "objets": ["🛶", "🛶", "🌅", "🐟"],
         "liste": [
             mot("boats", True, "Oui ! « Boats », ce sont les bateaux : les pirogues."),
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("sky", True, "Oui ! « Sky », c'est le ciel, au fond."),
             mot("sun", True, "Oui ! « Sun », c'est le soleil."),
             mot("mountain", False, "« Mountain », c'est la montagne. Il n'y a pas de montagne à Kayar ! Regarde encore."),
             mot("car", False, "« Car », c'est la voiture. On ne voit pas de voiture sur la mer. Regarde encore !"),
             mot("tree", False, "« Tree », c'est l'arbre. Tu vois un arbre dans la mer ? Non ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Look at my photo. In this picture, I can see a lot of pirogues.",
                         "Regarde ma photo. Sur cette image, je vois beaucoup de pirogues."),
                       r("modou", "On the left, I can see my uncle's pirogue!", "À gauche, je vois la pirogue de mon oncle !"),
                       r("awa", "In the background, there's the sea and the sky.", "Au fond, il y a la mer et le ciel."),
                       r("modou", "And in the foreground… a big nose. Gaïndé!", "Et devant… un gros nez. Gaïndé !")],
         "gainde": "Mon nez est sur la photo ? Moi aussi, je veux montrer une photo à la classe !"},
        [q("Où est la pirogue de l'oncle ?", ["à gauche", "à droite", "au fond"], 0, 1),
         q("Qu'est-ce qu'on voit au fond ?", ["Gaïndé", "la mer et le ciel", "la maison"], 1, 2)],
        [choix("Je montre la photo à la classe. Je dis laquelle ?",
               ["Pirogues. Sea. Finished!", "In this picture, I can see pirogues and the sea."], 1,
               aides("Comment Awa commence-t-elle, quand elle montre sa photo ?", 0, "Écoute Awa :",
                     "Moi, je dis : « In this picture, I can see a goat. »",
                     "« Pirogues. Sea. Finished! », c'est trop court et pas gentil pour la classe. On fait une vraie phrase.")),
         ordre("« In this picture see I can a goat. » C'est bien ça ?", ["can", "this", "a", "see", "In", "goat", "picture", "I"],
               "In this picture I can see a goat", "In this picture, I can see a goat.",
               aides("Awa commence par « In this picture ». Et ensuite ?", 0, "Écoute Awa :",
                     "Moi, je dis : « In this picture, I can see a boat. »",
                     "In this picture (sur cette image) + I can see (je vois) + ce qu'on voit.")),
         trou("« ___ the left, there's a goat. » Je dis « In the left » ?", "", "the left, there's a goat.", ["on"],
              "On the left, there's a goat.",
              aides("Écoute Modou. Quel petit mot dit-il avant « the left » ?", 1, "Écoute Modou :",
                    "Moi, je dis : « On the right, I can see Awa. »",
                    "On dit « on the left » (à gauche) et « on the right » (à droite). Écris : on.")),
         libre("Je dis ce qu'il y a au fond de la photo : le ciel. « Behind behind, sky! » C'est bon ?",
               ["background", "sky"],
               aides("Comment Awa dit-elle « au fond » ?", 2, "Écoute Awa :",
                     "Moi, je dis : « In the background, I can see the sea. »",
                     "Au fond = in the background. Écris : « In the background, I can see the sky. »"))],
        [tour("awa", "Look at my photo! What can you see on the right?", "Regarde ma photo ! Qu'est-ce que tu vois à droite ?",
              ["see|there"], "On the right, I can see a fisherman.", "Yes! That's Modou's uncle!"),
         tour("kocc", "Now look at your class photo. What can you see in the background?",
              "Maintenant, regarde ta photo de classe. Qu'est-ce que tu vois au fond ?", ["see|there"],
              "In the background, I can see the board.", "Very good description!")],
        ["In this picture, I can see…", "On the left / On the right", "In the middle", "In the background", "In the foreground"],
    ),
]

unite1 = unite(
    "4e-u1", "Who am I?",
    "Mon arbre de famille : dessine l'arbre de ta famille et présente-le, à l'oral ou à l'écrit.",
    u1,
    lignes=[
        ("Bien me présenter", "I was born in Kébémer. · I come from… · I live with…"),
        ("Remplir une fiche", "Surname? · First name? · Date of birth? · Could you spell that?"),
        ("Présenter ma famille", "My grandfather has got five children. · She's married to…"),
        ("Décrire une image", "In this picture, I can see… · On the left… · In the background…"),
    ],
    mots=[
        ("surname", "nom de famille", "sant"),
        ("first name", "prénom", "tur"),
        ("child", "enfant", "doom"),
        ("husband", "mari", "jëkkër"),
        ("wife", "épouse", "jabar"),
        ("married", "marié(e)", "séy"),
        ("grandfather", "grand-père", "maam bu góor"),
        ("picture", "image, photo", "nataal"),
        ("sea", "mer", "géej"),
        ("pirogue", "pirogue", "gaal"),
    ],
    pieges=[
        "I was born in 2013. Pas « I am born in 2013 ».",
        "She's married to Ibou. Pas « married with Ibou ».",
        "Surname = nom de famille. Ce n'est pas le surnom !",
        "On the left (à gauche). Pas « in the left ».",
    ],
    exercices=[
        ex("Tu dis où tu es né :", ["I was born in Thiès.", "I am born in Thiès.", "I born in Thiès.", "I was birth in Thiès."], 0,
           "On dit « I was born in… » pour dire où on est né."),
        ex("« Surname » veut dire :", ["prénom", "nom de famille", "surnom", "date de naissance"], 1,
           "Surname = nom de famille. First name = prénom."),
        ex("Tu veux qu'on épelle un nom. Tu demandes poliment :",
           ["Spell!", "Could you spell that, please?", "You spell, now!", "Spell it, you!"], 1,
           "« Could you… please? » est poli. Les autres sont trop secs."),
        ex("Complète la fiche : « Date of ____ »", ["born", "birth", "birthday", "bear"], 1,
           "Date of birth = date de naissance."),
        ex("« She's married ____ my uncle. »", ["with", "to", "at", "for"], 1,
           "En anglais, on dit « married to »."),
        ex("Mon grand-père a cinq enfants :",
           ["My grandfather has got five children.", "My grandfather have five childs.",
            "My grandfather is five children.", "My grandfather got five child."], 0,
           "« Has got » = a. Un enfant = a child, des enfants = children."),
        ex("Au fond de la photo, il y a la mer :",
           ["In the background, there's the sea.", "In the foreground, there's the sea.",
            "On the left, there's the sea.", "In the middle, there's the sea."], 0,
           "Au fond = in the background. Devant = in the foreground."),
        ex("« On the left » veut dire :", ["à droite", "à gauche", "au milieu", "devant"], 1,
           "Left = gauche. Right = droite."),
        ex("Tu dis que tu vis avec ta tante :",
           ["I live with my aunt.", "I live at my aunt.", "I live of my aunt.", "I living with my aunt."], 0,
           "« With » veut dire « avec » : I live with…"),
        ex("Tu montres ta photo à la classe. Tu commences par :",
           ["In this picture, I can see…", "Look, look, look!", "Photo. Finished.", "I can't see."], 0,
           "Pour décrire une image : « In this picture, I can see… »"),
    ],
)

# ======================= UNITÉ 2 : FEELINGS AND ADVICE =======================

u2 = [
    mission(
        "4e-u2-m1", "Le mal de mer de Gaïndé", "consoler quelqu'un",
        ["I'm sorry to hear that.", "Poor you!", "I hope you feel better."],
        {"consigne": "En pirogue, Gaïndé ne se sent pas bien. Quels mots vont avec l'image ?", "fond": "mer",
         "objets": ["🛶", "🌊", "🤢", "🥪"],
         "liste": [
             mot("waves", True, "Oui ! « Waves », ce sont les vagues. La pirogue bouge beaucoup."),
             mot("boat", True, "Oui ! « Boat », c'est le bateau, la pirogue."),
             mot("sick", True, "Oui ! « Sick », c'est malade. Gaïndé est tout vert !"),
             mot("sandwich", True, "Oui ! « Sandwich », c'est le sandwich de Gaïndé."),
             mot("happy", False, "« Happy », c'est content. Gaïndé n'a pas l'air content ! Regarde encore."),
             mot("desert", False, "« Desert », c'est le désert. Ici, il y a beaucoup d'eau ! Regarde encore."),
         ]},
        {"fond": "mer", "persos": ["gainde", "awa", "modou"],
         "repliques": [r("gainde", "I feel sick… The pirogue is dancing!", "Je me sens mal… La pirogue danse !"),
                       r("awa", "Oh, poor you!", "Oh, mon pauvre !"),
                       r("gainde", "And my sandwich fell in the sea.", "Et mon sandwich est tombé dans la mer."),
                       r("awa", "I'm sorry to hear that. I hope you feel better soon.", "Je suis désolée. J'espère que tu vas vite aller mieux.")],
         "gainde": "Awa est gentille avec moi. Comment on dit ces mots gentils, quand un ami a un problème ?"},
        [q("Qu'est-ce que Gaïndé a perdu ?", ["son chapeau", "son sandwich", "son livre"], 1, 2),
         q("« I hope you feel better » veut dire…", ["J'espère que tu vas mieux.", "Tu es malade.", "Mange ton sandwich."], 0, 3)],
        [choix("Maintenant, c'est Modou qui a le mal de mer. Je lui dis laquelle ?", ["Ha ha! You're all green!", "Oh, poor you!"], 1,
               aides("Quand Gaïndé était malade, Awa s'est-elle moquée de lui ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Oh, poor you, Gaïndé! »",
                     "Rire d'un ami malade, ce n'est pas gentil. « Poor you! », c'est « Mon pauvre ! ».")),
         ordre("« You feel better I hope. » C'est ça ?", ["feel", "I", "better", "you", "hope"], "I hope you feel better",
               "I hope you feel better.",
               aides("Par quels mots Awa commence-t-elle sa dernière phrase ?", 3, "Écoute Awa :",
                     "Moi, je dis : « I hope you feel better. »",
                     "I hope (j'espère) + you feel better (tu vas mieux).")),
         trou("« I'm sorry to ___ that. » Je dis « sorry to listen that » ?", "I'm sorry to", "that.", ["hear"],
              "I'm sorry to hear that.",
              aides("Écoute Awa. Quel mot vient après « sorry to » ?", 3, "Écoute Awa :",
                    "Moi, je dis : « I'm sorry to hear that. »",
                    "« Hear », c'est entendre. « I'm sorry to hear that » = je suis désolé de l'apprendre. Écris : hear.")),
         libre("Modou a perdu son ballon dans la mer. Je lui dis « Not my problem! » ? Aide-moi à le consoler.",
               ["sorry|poor you|hope"],
               aides("Qu'est-ce qu'Awa a dit à Gaïndé pour son sandwich ?", 3, "Écoute Awa :",
                     "Moi, je dis : « Oh, poor you! I'm sorry to hear that. »",
                     "Écris : « I'm sorry to hear that, Modou. »"))],
        [tour("modou", "I've got a headache today.", "J'ai mal à la tête aujourd'hui.", ["sorry|poor you|hope"],
              "Poor you! I hope you feel better.", "Thanks. You're a good friend."),
         tour("awa", "My grandmother is ill.", "Ma grand-mère est malade.", ["sorry|poor|hope"],
              "I'm sorry to hear that. I hope she feels better soon.", "Thank you. That's kind.")],
        ["I'm sorry to hear that.", "Poor you!", "I hope you feel better.", "sick"],
    ),
    mission(
        "4e-u2-m2", "Tu devrais…", "donner un conseil",
        ["You should…", "You'd better…", "If I were you…"],
        {"consigne": "Gaïndé a encore le mal de mer. Quels mots vont avec l'image ?", "fond": "mer", "objets": ["🛶", "💧", "🌅", "🦁"],
         "liste": [
             mot("water", True, "Oui ! « Water », c'est l'eau. Gaïndé doit boire un peu."),
             mot("sky", True, "Oui ! « Sky », c'est le ciel."),
             mot("lion", True, "Oui ! « Lion », c'est Gaïndé, tout vert."),
             mot("boat", True, "Oui ! « Boat », c'est la pirogue."),
             mot("bus", False, "« Bus », c'est le car. On est sur la mer ! Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. Gaïndé ne veut pas manger ! Regarde encore."),
         ]},
        {"fond": "mer", "persos": ["gainde", "awa", "modou"],
         "repliques": [r("gainde", "I feel sick. What can I do?", "Je me sens mal. Qu'est-ce que je peux faire ?"),
                       r("awa", "You should look at the sky, not at the water.", "Tu devrais regarder le ciel, pas l'eau."),
                       r("modou", "You'd better sit down.", "Tu ferais mieux de t'asseoir."),
                       r("awa", "And if I were you, I'd drink some water.", "Et à ta place, je boirais un peu d'eau.")],
         "gainde": "Tout le monde me donne des idées ! Comment on donne un conseil, en anglais ?"},
        [q("Awa dit à Gaïndé de regarder…", ["l'eau", "le ciel", "son sandwich"], 1, 1),
         q("« If I were you », ça veut dire…", ["à ta place", "avec toi", "comme moi"], 0, 3)],
        [choix("Awa est très fatiguée. Je lui donne un conseil. Je dis laquelle ?",
               ["You should have a rest.", "Go to bed, lazy girl!"], 0,
               aides("Awa a donné un conseil à Gaïndé. Elle a été gentille ou méchante ?", 1, "Écoute Awa :",
                     "Moi, je dis : « You should drink some water. »",
                     "« Lazy girl », c'est « fainéante » : c'est méchant. « You should… », c'est « Tu devrais… ».")),
         ordre("« You drink should some water. » C'est ça ?", ["drink", "should", "water", "You", "some"],
               "You should drink some water", "You should drink some water.",
               aides("Awa dit « You should… ». Quel mot vient juste après ?", 1, "Écoute Awa :",
                     "Moi, je dis : « You should look at the sky. »",
                     "You should (tu devrais) + ce qu'il faut faire (drink some water).")),
         trou("« You'd ___ sit down. » Il me manque un mot !", "You'd", "sit down.", ["better"], "You'd better sit down.",
              aides("Écoute Modou. Qu'est-ce qu'il dit entre « You'd » et « sit down » ?", 2, "Écoute Modou :",
                    "Moi, je dis : « You'd better sit down. »",
                    "« You'd better », c'est « Tu ferais mieux de ». Écris : better.")),
         libre("Modou a très faim. Je lui dis « Eat! Eat! Eat! » ? C'est un ordre, pas un conseil… Aide-moi !",
               ["should|better|if i were you"],
               aides("Comment Awa et Modou donnent-ils des conseils ?", 1, "Écoute Awa :",
                     "Moi, je dis : « You should eat some rice. »",
                     "Écris : « You should eat something. » ou « If I were you, I'd eat. »"))],
        [tour("modou", "I'm always late for school. What should I do?", "Je suis toujours en retard à l'école. Je fais quoi ?",
              ["should|better|if i were you"], "You should get up early.", "Good idea! I'll try."),
         tour("awa", "I'm so tired today.", "Je suis très fatiguée aujourd'hui.", ["should|better|if i were you"],
              "If I were you, I'd go to bed early.", "You're right. Thanks!")],
        ["You should…", "You'd better…", "If I were you, I'd…"],
    ),
    mission(
        "4e-u2-m3", "Tu aurais dû écouter !", "dire à quelqu'un qu'il n'aurait pas dû",
        ["You shouldn't have done that!", "Why didn't you…?"],
        {"consigne": "Les sardines pour la pêche ont disparu ! Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🐟", "🪣", "🦁", "🛶"],
         "liste": [
             mot("sardines", True, "Oui ! « Sardines », ce sont les sardines. Il n'en reste plus beaucoup…"),
             mot("bucket", True, "Oui ! « Bucket », c'est le seau. Il est vide !"),
             mot("lion", True, "Oui ! « Lion », c'est Gaïndé. Il a un gros ventre…"),
             mot("pirogue", True, "Oui ! « Pirogue », c'est la pirogue de l'oncle."),
             mot("bread", False, "« Bread », c'est le pain. Tu vois du pain ? Non. Regarde encore !"),
             mot("chair", False, "« Chair », c'est la chaise. Il n'y a pas de chaise sur la plage. Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("modou", "Gaïndé! You ate the sardines for the fishing!", "Gaïndé ! Tu as mangé les sardines pour la pêche !"),
                       r("awa", "You shouldn't have done that!", "Tu n'aurais pas dû faire ça !"),
                       r("modou", "Why didn't you ask?", "Pourquoi tu n'as pas demandé ?"),
                       r("gainde", "Sorry… I was hungry.", "Pardon… J'avais faim.")],
         "gainde": "Oups. Ils ne sont pas contents. Mais comment on dit « tu n'aurais pas dû » sans être méchant ?"},
        [q("Qu'est-ce que Gaïndé a fait ?", ["Il a mangé les sardines.", "Il a cassé la pirogue.", "Il a perdu le filet."], 0, 0),
         q("« Why didn't you ask? » veut dire…", ["Pourquoi tu n'as pas demandé ?", "Tu as demandé ?", "Qui a demandé ?"], 0, 2)],
        [choix("Modou s'est réveillé trop tard. La pirogue est partie sans lui. Je lui dis laquelle ?",
               ["You're useless, Modou!", "Why didn't you get up early?"], 1,
               aides("Modou a-t-il dit « Tu es nul ! » à Gaïndé, pour les sardines ?", 2, "Écoute Modou :",
                     "Moi, je dis : « Why didn't you ask? »",
                     "« Useless », c'est « nul » : ça fait mal. « Why didn't you… ? », c'est « Pourquoi tu n'as pas… ? ».")),
         ordre("« You have shouldn't that done. » C'est ça ?", ["done", "You", "that", "have", "shouldn't"],
               "You shouldn't have done that", "You shouldn't have done that!",
               aides("Awa dit « You shouldn't… ». Et après ?", 1, "Écoute Awa :",
                     "Moi, je dis : « You shouldn't have done that! »",
                     "You shouldn't have done that = Tu n'aurais pas dû faire ça.")),
         trou("« Why ___ you ask? » Il me manque un mot !", "Why", "you ask?", ["didn't", "didnt", "did not"],
              "Why didn't you ask?",
              aides("Écoute Modou. Quel mot vient après « Why » ?", 2, "Écoute Modou :",
                    "Moi, je dis : « Why didn't you ask? »",
                    "« Why didn't you… ? » = Pourquoi tu n'as pas… ? Écris : didn't.")),
         libre("Awa est montée sur la pirogue sans gilet. Je lui crie « You're crazy! » ? C'est trop dur. Aide-moi !",
               ["why didnt you|why did not you|shouldnt have|should not have|should have"],
               aides("Comment Modou parle-t-il à Gaïndé, pour les sardines ?", 2, "Écoute Modou :",
                     "Moi, je dis : « Why didn't you take your life jacket? »",
                     "Écris : « Why didn't you take your life jacket? »"))],
        [tour("modou", "I didn't do my homework. Now the teacher is angry!", "Je n'ai pas fait mes devoirs. Maintenant, le prof est fâché !",
              ["why didnt|why did not|shouldnt|should not|should have"], "Why didn't you do it yesterday?",
              "I know… I went to the beach."),
         tour("awa", "I ate ten mangoes. Now I feel sick!", "J'ai mangé dix mangues. Maintenant, j'ai mal au ventre !",
              ["shouldnt|should not|why didnt|why did not"], "You shouldn't have done that!", "You're right. Only two next time!")],
        ["You shouldn't have done that!", "Why didn't you…?", "life jacket"],
    ),
    mission(
        "4e-u2-m4", "Je regrette…", "dire que je regrette",
        ["I'm sorry I didn't come.", "I regret…"],
        {"consigne": "Hier soir, il y avait une fête pour la nouvelle pirogue. Quels mots vont avec l'image ?", "fond": "nuit",
         "objets": ["🥁", "🛶", "🎉", "🌙"],
         "liste": [
             mot("drum", True, "Oui ! « Drum », c'est le tambour, le tama de Doudou."),
             mot("party", True, "Oui ! « Party », c'est la fête."),
             mot("moon", True, "Oui ! « Moon », c'est la lune. C'est la nuit."),
             mot("pirogue", True, "Oui ! « Pirogue », c'est la nouvelle pirogue."),
             mot("sun", False, "« Sun », c'est le soleil. Mais c'est la nuit ! Regarde encore."),
             mot("school", False, "« School », c'est l'école. La fête n'est pas à l'école. Regarde encore !"),
         ]},
        {"fond": "plage", "persos": ["doudou", "modou", "gainde"],
         "repliques": [r("doudou", "Modou, I'm sorry I didn't come to the party.", "Modou, je suis désolé de ne pas être venu à la fête."),
                       r("modou", "Oh, Doudou! Why?", "Oh, Doudou ! Pourquoi ?"),
                       r("doudou", "I fell asleep. I regret sleeping so much!", "Je me suis endormi. Je regrette d'avoir tant dormi !"),
                       r("modou", "It's OK. Come and play the tama tonight!", "Ce n'est pas grave. Viens jouer du tama ce soir !")],
         "gainde": "Doudou est triste de ne pas être venu. Comment on dit « je regrette » ?"},
        [q("Pourquoi Doudou n'est pas venu ?", ["Il était malade.", "Il s'est endormi.", "Il était à Dakar."], 1, 2),
         q("Modou est fâché ?", ["Oui, très fâché.", "Non, ce n'est pas grave."], 1, 3)],
        [choix("Je ne suis pas venu au match de Modou. Je lui dis laquelle ?",
               ["I'm sorry I didn't come.", "Whatever! I didn't come. So what?"], 0,
               aides("Doudou dit-il « Et alors ? » à Modou ?", 0, "Écoute Doudou :",
                     "Moi, je dis : « I'm sorry I didn't come to your party. »",
                     "« So what? », c'est « Et alors ? » : ce n'est pas gentil. « I'm sorry… », c'est « Je suis désolé… ».")),
         ordre("« I'm sorry I come didn't. » C'est ça ?", ["didn't", "sorry", "come", "I'm", "I"],
               "I'm sorry I didn't come", "I'm sorry I didn't come.",
               aides("Écoute Doudou. Quel mot vient juste avant « come » ?", 0, "Écoute Doudou :",
                     "Moi, je dis : « I'm sorry I didn't come. »",
                     "I'm sorry (je suis désolé) + I didn't come (je ne suis pas venu).")),
         trou("J'ai mangé tout le poisson. Je le regrette. « I ___ eating all the fish. »", "I", "eating all the fish.", ["regret"],
              "I regret eating all the fish.",
              aides("Quel mot Doudou dit-il pour « je regrette » ?", 2, "Écoute Doudou :",
                    "Moi, je dis : « I regret sleeping so much! »",
                    "« Regret » = regretter. Écris : regret.")),
         libre("Je ne suis pas venu à l'anniversaire d'Awa. Je dis « Lol, I forgot! » ? Aide-moi à dire que je regrette.",
               ["sorry|regret"],
               aides("Comment Doudou commence-t-il, avec Modou ?", 0, "Écoute Doudou :",
                     "Moi, je dis : « I'm sorry I didn't come to the party. »",
                     "Écris : « I'm sorry I didn't come, Awa. »"))],
        [tour("awa", "You didn't come to my birthday party!", "Tu n'es pas venu(e) à ma fête d'anniversaire !", ["sorry|regret"],
              "I'm sorry I didn't come. I was ill.", "It's OK. Next time!"),
         tour("modou", "You didn't do your homework?", "Tu n'as pas fait tes devoirs ?", ["sorry|regret"],
              "I regret it. I'm sorry.", "Do it tonight! I can help you.")],
        ["I'm sorry I didn't come.", "I regret…", "party"],
    ),
    mission(
        "4e-u2-m5", "Thiof ou yaboye ?", "dire ce que je préfère",
        ["I prefer thiof to yaboye.", "I'd rather eat…"],
        {"consigne": "Au marché aux poissons de Kayar. Quels mots vont avec l'image ?", "fond": "marche",
         "objets": ["🐟", "🐠", "🍚", "⚖️"],
         "liste": [
             mot("thiof", True, "Oui ! « Thiof », c'est le thiof, un gros poisson."),
             mot("sardines", True, "Oui ! « Sardines », ce sont les sardines."),
             mot("rice", True, "Oui ! « Rice », c'est le riz, pour le thiéboudienne."),
             mot("market", True, "Oui ! « Market », c'est le marché."),
             mot("chicken", False, "« Chicken », c'est le poulet. Ici, on vend du poisson ! Regarde encore."),
             mot("ice cream", False, "« Ice cream », c'est la glace. Tu en vois ? Non. Regarde encore !"),
         ]},
        {"fond": "marche", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Which do you prefer, thiof or yaboye?", "Tu préfères lequel, le thiof ou le yaboye ?"),
                       r("modou", "I prefer thiof to yaboye. It's delicious!", "Je préfère le thiof au yaboye. C'est délicieux !"),
                       r("awa", "I'd rather eat sardines. They're cheap!", "Moi, je préfère manger des sardines. Elles ne sont pas chères !")],
         "gainde": "Thiof, yaboye, sardines… Moi, je préfère tout ! Comment on dit ce qu'on préfère ?"},
        [q("Modou préfère…", ["le yaboye", "le thiof", "les sardines"], 1, 1),
         q("Awa préfère manger…", ["des sardines", "du thiof", "du riz"], 0, 2)],
        [choix("La tante de Modou me donne du yaboye. Moi, je préfère le thiof. Je dis laquelle ?",
               ["Yaboye? Yuck! Disgusting!", "Thank you! But I'd rather eat thiof, please."], 1,
               aides("Si quelqu'un te donne à manger, tu dis « Beurk ! » ?", 2, "Écoute Awa :",
                     "Moi, je dis : « I'd rather eat sardines, please. »",
                     "« Yuck! Disgusting! », c'est « Beurk ! C'est dégoûtant ! » : c'est impoli. « I'd rather… », c'est « Je préfère… ».")),
         ordre("« I prefer yaboye thiof to. » C'est ça ?", ["thiof", "to", "I", "yaboye", "prefer"],
               "I prefer thiof to yaboye", "I prefer thiof to yaboye.",
               aides("Écoute Modou. Quel petit mot vient entre les deux poissons ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I prefer books to football. »",
                     "I prefer + ce que j'aime le plus + to + l'autre chose.")),
         trou("« I'd ___ eat rice. » Je dis « I'd better eat rice » ?", "I'd", "eat rice.", ["rather"], "I'd rather eat rice.",
              aides("Écoute Awa. Quel mot vient après « I'd » ?", 2, "Écoute Awa :",
                    "Moi, je dis : « I'd rather eat sardines. »",
                    "« I'd better », c'est un conseil. « I'd rather », c'est « je préfère ». Écris : rather.")),
         libre("Je veux dire que je préfère les sardines au thiof. Je dis « Thiof? Bad! » ? Aide-moi !",
               ["prefer|rather|like", "sardine|sardines"],
               aides("Comment Modou dit-il qu'il préfère le thiof ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I prefer yaboye to sardines. »",
                     "Écris : « I prefer sardines to thiof. »"))],
        [tour("modou", "Which do you prefer: tea or juice?", "Tu préfères quoi : le thé ou le jus ?", ["prefer|rather|like"],
              "I prefer juice to tea.", "Me too! Juice is great."),
         tour("awa", "Shall we eat fish or chicken tonight?", "On mange du poisson ou du poulet ce soir ?", ["prefer|rather|like"],
              "I'd rather eat fish.", "OK! Fish from Kayar!")],
        ["I prefer… to…", "I'd rather eat…", "Which do you prefer?", "thiof", "yaboye", "sardine"],
    ),
]

unite2 = unite(
    "4e-u2", "Feelings and advice",
    "Le courrier des lecteurs : un ami t'écrit. Il a un problème. Réponds-lui : console-le et donne-lui un conseil.",
    u2,
    lignes=[
        ("Consoler", "I'm sorry to hear that. · Poor you! · I hope you feel better."),
        ("Donner un conseil", "You should… · You'd better… · If I were you…"),
        ("Dire « tu n'aurais pas dû »", "You shouldn't have done that! · Why didn't you…?"),
        ("Dire que je regrette", "I'm sorry I didn't come. · I regret…"),
        ("Dire ce que je préfère", "I prefer thiof to yaboye. · I'd rather eat…"),
    ],
    mots=[
        ("fish", "poisson", "jën"),
        ("sick", "malade", "feebar"),
        ("to forget", "oublier", "fàtte"),
        ("to break", "casser", "toj"),
        ("to fight", "se battre", "xeex"),
        ("to be late", "être en retard", "yéex"),
        ("angry", "fâché", "mer"),
        ("ashamed", "qui a honte", "rus"),
        ("sorry", "désolé, pardon", "baal ma"),
        ("water", "eau", "ndox"),
    ],
    pieges=[
        "I'm sorry to hear that. Pas « I'm sorry to listen that ».",
        "You should go. Pas « You should to go ». Pareil : You'd better go.",
        "I prefer thiof to yaboye. Pas « I prefer thiof than yaboye ».",
        "I'd better = je ferais mieux (un conseil). I'd rather = je préfère.",
    ],
    exercices=[
        ex("Ton ami est malade. Tu lui dis :", ["Ha ha! You're sick!", "I hope you feel better.", "I prefer thiof.", "Why didn't you come?"], 1,
           "« I hope you feel better » = j'espère que tu vas mieux."),
        ex("Complète : « I'm sorry to ____ that. »", ["listen", "hear", "say", "see"], 1,
           "On dit « I'm sorry to hear that »."),
        ex("Modou est fatigué. Tu lui conseilles de dormir :",
           ["You should sleep.", "You should to sleep.", "You sleep must.", "You'd better to sleep."], 0,
           "Après « should », on met le verbe tout de suite, sans « to »."),
        ex("« If I were you… » veut dire :", ["À ta place…", "Si tu étais moi…", "Quand je serai grand…", "Parce que je suis toi…"], 0,
           "« If I were you, I'd… » = à ta place, je…"),
        ex("Awa a mangé dix mangues. Elle a mal au ventre. Tu dis :",
           ["You shouldn't have done that!", "You should do that!", "Poor me!", "I prefer mangoes."], 0,
           "« You shouldn't have done that! » = Tu n'aurais pas dû faire ça !"),
        ex("« Why didn't you ask? » veut dire :",
           ["Pourquoi tu n'as pas demandé ?", "Pourquoi tu demandes ?", "Tu vas demander ?", "Qui a demandé ?"], 0,
           "« Why didn't you… ? » = Pourquoi tu n'as pas… ?"),
        ex("Tu n'es pas venu à la fête. Tu dis :",
           ["I'm sorry I didn't come.", "I'm sorry I don't came.", "I sorry not come.", "I'm sorry I didn't came."], 0,
           "On dit « I didn't come », pas « I didn't came »."),
        ex("Complète : « I prefer thiof ____ yaboye. »", ["than", "to", "of", "that"], 1,
           "On dit « prefer… to… »."),
        ex("« I'd rather eat rice. » veut dire :",
           ["Je préfère manger du riz.", "Je dois manger du riz.", "J'ai mangé du riz.", "Je ne mange pas de riz."], 0,
           "« I'd rather » = je préfère."),
        ex("« You'd better sit down. » veut dire :",
           ["Tu ferais mieux de t'asseoir.", "Tu es mieux assis.", "Tu t'es assis.", "Tu t'assois toujours."], 0,
           "« You'd better… » = tu ferais mieux de… C'est un conseil."),
    ],
)

# ======================= UNITÉ 3 : PUBLIC PLACES =======================

u3 = [
    mission(
        "4e-u3-m1", "Perdu à la gare routière", "demander le chemin et le montrer",
        ["How can I get to the hospital?", "Go straight on, then turn left."],
        {"consigne": "À la gare routière de Kayar. Quels mots vont avec l'image ?", "fond": "marche",
         "objets": ["🚌", "🏥", "🏦", "🚕"],
         "liste": [
             mot("bus", True, "Oui ! « Bus », c'est le car rapide."),
             mot("hospital", True, "Oui ! « Hospital », c'est l'hôpital."),
             mot("bank", True, "Oui ! « Bank », c'est la banque."),
             mot("taxi", True, "Oui ! « Taxi », c'est le taxi jaune et noir."),
             mot("beach", False, "« Beach », c'est la plage. Ici, on est en ville, à la gare. Regarde encore !"),
             mot("plane", False, "« Plane », c'est l'avion. Il n'y a pas d'avion à la gare routière. Regarde encore."),
         ]},
        {"fond": "marche", "persos": ["awa", "doudou", "gainde"],
         "repliques": [r("awa", "Excuse me, how can I get to the hospital?", "Pardon, comment je peux aller à l'hôpital ?"),
                       r("doudou", "Go straight on, then turn left.", "Va tout droit, puis tourne à gauche."),
                       r("awa", "Is it far?", "C'est loin ?"),
                       r("doudou", "No. It's opposite the bank.", "Non. C'est en face de la banque.")],
         "gainde": "Moi, je suis perdu ! Comment je demande mon chemin à un monsieur ?"},
        [q("Awa veut aller où ?", ["à la banque", "à l'hôpital", "à la plage"], 1, 0),
         q("Après « tout droit », Awa tourne…", ["à gauche", "à droite", "deux fois"], 0, 1)],
        [choix("Je cherche la pharmacie. Je parle à un vieux monsieur. Je dis laquelle ?",
               ["Hey, old man! Pharmacy, where?", "Excuse me, how can I get to the pharmacy?"], 1,
               aides("Comment Awa commence-t-elle, quand elle parle au monsieur ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Excuse me, how can I get to the bank? »",
                     "« Hey, old man! », c'est impoli. On commence par « Excuse me » (pardon).")),
         ordre("« How I can get to the pharmacy? » C'est ça ?", ["get", "How", "the", "can", "pharmacy", "I", "to"],
               "How can I get to the pharmacy", "How can I get to the pharmacy?",
               aides("Écoute Awa. Quel mot vient juste après « How » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « How can I get to the post office? »",
                     "How can I get to… ? = Comment je peux aller à… ?")),
         trou("« Go straight ___, then turn left. » Il me manque un mot !", "Go straight", ", then turn left.", ["on"],
              "Go straight on, then turn left.",
              aides("Écoute Doudou. Quel petit mot vient après « straight » ?", 1, "Écoute Doudou :",
                    "Moi, je dis : « Go straight on, then turn right. »",
                    "« Go straight on » = va tout droit. Écris : on.")),
         libre("Un monsieur cherche la banque. Je lui dis « Go, go, go! » ? Aide-moi : tout droit, puis à droite.",
               ["straight", "right"],
               aides("Comment Doudou montre-t-il le chemin à Awa ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « Go straight on, then turn left. »",
                     "Écris : « Go straight on, then turn right. »"))],
        [tour("doudou", "Excuse me, how can I get to the post office?", "Pardon, comment je peux aller à la poste ?",
              ["straight|turn|left|right|opposite|next to"], "Go straight on, then turn right.", "Thank you very much!"),
         tour("kocc", "You want to go to the hospital. Ask me the way!", "Tu veux aller à l'hôpital. Demande-moi le chemin !",
              ["how can i get|how do i get|where is|wheres", "hospital"], "Excuse me, how can I get to the hospital?",
              "Go straight on, then turn left. It's opposite the bank.")],
        ["How can I get to…?", "Go straight on.", "Turn left. / Turn right.", "opposite", "hospital", "bank"],
    ),
    mission(
        "4e-u3-m2", "Interdit aux lions !", "dire ce qu'on doit faire et ce qui est interdit",
        ["You must…", "You mustn't…", "No smoking."],
        {"consigne": "Au port de Kayar, il y a des panneaux. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["⚠️", "🚭", "🦺", "🌊"],
         "liste": [
             mot("danger", True, "Oui ! « Danger », c'est le danger. Le panneau est jaune."),
             mot("sign", True, "Oui ! « Sign », c'est le panneau."),
             mot("life jacket", True, "Oui ! « Life jacket », c'est le gilet de sauvetage."),
             mot("waves", True, "Oui ! « Waves », ce sont les vagues. Elles sont grosses !"),
             mot("cinema", False, "« Cinema », c'est le cinéma. On est au port ! Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. Tu vois un gâteau ? Non. Regarde encore !"),
         ]},
        {"fond": "plage", "persos": ["modou", "kocc", "gainde"],
         "repliques": [r("modou", "Look at this sign: « Danger! No swimming. »", "Regarde ce panneau : « Danger ! Baignade interdite. »"),
                       r("kocc", "Yes. You mustn't swim here. The waves are very big.", "Oui. Il ne faut pas nager ici. Les vagues sont très grosses."),
                       r("modou", "And this one: « No smoking. »", "Et celui-là : « Interdit de fumer. »"),
                       r("kocc", "And on the pirogue, you must wear a life jacket.", "Et sur la pirogue, tu dois mettre un gilet de sauvetage.")],
         "gainde": "Il y a beaucoup de panneaux ! Il y en a un « Interdit aux lions » ?"},
        [q("Ici, on peut nager ?", ["Oui", "Non"], 1, 1),
         q("Sur la pirogue, on doit…", ["mettre un gilet", "fumer", "nager"], 0, 3)],
        [choix("Un monsieur fume près des pirogues. Je lui dis laquelle ?",
               ["Excuse me, you mustn't smoke here.", "Hey you! Stop smoking or I bite you!"], 0,
               aides("Comment Kocc Barma dit-il ce qui est interdit ? Il menace ?", 1, "Écoute Kocc Barma :",
                     "Moi, je dis : « Excuse me, you mustn't swim here. »",
                     "« Or I bite you! », c'est « Ou je te mords ! » : c'est méchant. « You mustn't… », c'est « Il ne faut pas… ».")),
         ordre("« You a life jacket must wear. » C'est ça ?", ["wear", "life", "You", "a", "must", "jacket"],
               "You must wear a life jacket", "You must wear a life jacket.",
               aides("Écoute Kocc Barma. Quel mot vient après « You » ?", 3, "Écoute Kocc Barma :",
                     "Moi, je dis : « You must wear a life jacket. »",
                     "You must (tu dois) + ce qu'il faut faire.")),
         trou("C'est dangereux ! « You ___ swim here. » Je dis « You must swim here » ?", "You", "swim here.",
              ["mustn't", "mustnt", "must not"], "You mustn't swim here.",
              aides("Il faut nager ou il ne faut pas nager ? Écoute Kocc Barma.", 1, "Écoute Kocc Barma :",
                    "Moi, je dis : « You mustn't swim here. »",
                    "« Must » = il faut. « Mustn't » = il ne faut pas. Écris : mustn't.")),
         libre("Je fais un panneau « Interdit de fumer » pour la pirogue. J'écris « Don't smoke, you! » ? Aide-moi !",
               ["no smoking"],
               aides("Qu'est-ce qui est écrit sur le deuxième panneau ?", 2, "Écoute Modou :",
                     "Moi, j'écris : « No swimming. »", "Sur un panneau, on écrit « No » + le mot. Écris : « No smoking. »"))],
        [tour("kocc", "We are in the library. What mustn't you do?", "On est à la bibliothèque. Qu'est-ce qui est interdit ?",
              ["mustnt|must not|no"], "You mustn't shout.", "Yes! Shhh…"),
         tour("modou", "I want to go on the pirogue. What must I do?", "Je veux monter dans la pirogue. Je dois faire quoi ?",
              ["must"], "You must wear a life jacket.", "OK! Where is my life jacket?")],
        ["You must…", "You mustn't…", "No smoking.", "No swimming.", "danger", "sign"],
    ),
    mission(
        "4e-u3-m3", "Et si on allait à la plage ?", "proposer une idée (Et si on… ?)",
        ["Let's…", "Why don't we…?", "Shall we…?"],
        {"consigne": "Il fait chaud à Kayar. Quels mots vont avec l'image ?", "fond": "plage", "objets": ["☀️", "⚽", "🏖️", "🌊"],
         "liste": [
             mot("sun", True, "Oui ! « Sun », c'est le soleil. Il fait chaud !"),
             mot("ball", True, "Oui ! « Ball », c'est le ballon."),
             mot("beach", True, "Oui ! « Beach », c'est la plage."),
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("rain", False, "« Rain », c'est la pluie. Il fait beau ! Regarde encore."),
             mot("homework", False, "« Homework », ce sont les devoirs. Pas de devoirs sur la plage ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "It's hot! Let's go to the beach!", "Il fait chaud ! Allons à la plage !"),
                       r("awa", "Good idea! Why don't we play football on the sand?", "Bonne idée ! Et si on jouait au foot sur le sable ?"),
                       r("modou", "Yes! Shall we ask Kocc Barma too?", "Oui ! On demande aussi à Kocc Barma ?")],
         "gainde": "Ils font des propositions ! Moi aussi, j'ai des idées. Comment je les dis ?"},
        [q("Modou propose d'aller…", ["à la plage", "au marché", "à l'école"], 0, 0),
         q("Awa propose de…", ["nager", "jouer au foot", "dormir"], 1, 1)],
        [choix("Je veux proposer à Kocc Barma de venir à la plage. Je dis laquelle ?",
               ["Kocc! Beach! You come now!", "Shall we go to the beach, Sir?"], 1,
               aides("Kocc Barma est le prof. On lui donne un ordre, ou on lui propose gentiment ?", 2, "Écoute Modou :",
                     "Moi, je dis : « Shall we go to the market, Sir? »",
                     "« You come now! », c'est un ordre. « Shall we… ? », c'est « On… ? » : une idée polie.")),
         ordre("« Why we don't play football? » C'est ça ?", ["don't", "football", "Why", "play", "we"],
               "Why don't we play football", "Why don't we play football?",
               aides("Écoute Awa. Quel mot vient après « Why » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Why don't we read a book? »",
                     "Why don't we… ? = Et si on… ?")),
         trou("Je propose d'aller à la plage. « ___ we go to the beach? »", "", "we go to the beach?", ["shall", "should", "can"],
              "Shall we go to the beach?",
              aides("Écoute Modou. Par quel mot commence sa question ?", 2, "Écoute Modou :",
                    "Moi, je dis : « Shall we ask Awa? »",
                    "« Shall we… ? » = On… ? Écris : shall.")),
         libre("Je veux proposer à Awa de manger du thiof ce soir. Je dis « Thiof! Me! Tonight! » ? Aide-moi !",
               ["lets|let us|why dont we|why not|shall we"],
               aides("Comment Modou propose-t-il d'aller à la plage ?", 0, "Écoute Modou :",
                     "Moi, je dis : « Let's eat rice tonight! »",
                     "Écris : « Let's eat thiof tonight! »"))],
        [tour("modou", "I'm bored. What can we do?", "Je m'ennuie. Qu'est-ce qu'on peut faire ?",
              ["lets|let us|why dont we|why not|shall we|we can"], "Let's play football!", "Good idea! Let's go!"),
         tour("awa", "It's Saturday! Any ideas?", "C'est samedi ! Tu as une idée ?",
              ["lets|let us|why dont we|why not|shall we|we can"], "Why don't we go to the market?", "Yes! Let's buy some thiof!")],
        ["Let's…", "Why don't we…?", "Shall we…?", "Good idea!"],
    ),
    mission(
        "4e-u3-m4", "Asseyez-vous !", "demander poliment de faire quelque chose",
        ["Sit down, please.", "Don't run!"],
        {"consigne": "On monte dans la pirogue. Quels mots vont avec l'image ?", "fond": "mer", "objets": ["🛶", "🪢", "🦺", "🌊"],
         "liste": [
             mot("rope", True, "Oui ! « Rope », c'est la corde."),
             mot("life jacket", True, "Oui ! « Life jacket », c'est le gilet de sauvetage."),
             mot("pirogue", True, "Oui ! « Pirogue », c'est la pirogue."),
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("chair", False, "« Chair », c'est la chaise. Dans la pirogue, on s'assoit sur le bois ! Regarde encore."),
             mot("road", False, "« Road », c'est la route. Il n'y a pas de route sur la mer ! Regarde encore."),
         ]},
        {"fond": "mer", "persos": ["kocc", "modou", "gainde"],
         "repliques": [r("kocc", "Modou, sit down, please.", "Modou, assieds-toi, s'il te plaît."),
                       r("kocc", "And don't run on the pirogue!", "Et ne cours pas sur la pirogue !"),
                       r("modou", "Sorry, Sir!", "Pardon, Monsieur !"),
                       r("kocc", "Hold the rope, please.", "Tiens la corde, s'il te plaît.")],
         "gainde": "Kocc Barma donne des ordres, mais il reste gentil. Comment il fait ?"},
        [q("Kocc Barma demande à Modou de…", ["se lever", "s'asseoir", "nager"], 1, 0),
         q("« Don't run! » veut dire…", ["Ne cours pas !", "Cours vite !", "Viens ici !"], 0, 1)],
        [choix("Je veux qu'Awa me donne le filet. Je dis laquelle ?", ["Give me the net, please.", "NET! NOW!"], 0,
               aides("Kocc Barma crie-t-il « NOW! » ? Quel petit mot met-il à la fin ?", 3, "Écoute Kocc Barma :",
                     "Moi, je dis : « Give me the rope, please. »",
                     "« NOW! », en criant, c'est impoli. Avec « please », c'est gentil.")),
         ordre("« Run don't on the pirogue! » C'est ça ?", ["run", "Don't", "the", "on", "pirogue"],
               "Don't run on the pirogue", "Don't run on the pirogue!",
               aides("Écoute Kocc Barma. Quel mot vient en premier ?", 1, "Écoute Kocc Barma :",
                     "Moi, je dis : « Don't run in the classroom! »",
                     "Pour dire « ne… pas » : Don't + ce qu'il ne faut pas faire.")),
         trou("« ___ down, please. » Il me manque un mot !", "", "down, please.", ["sit"], "Sit down, please.",
              aides("Écoute Kocc Barma au début. Qu'est-ce qu'il dit à Modou ?", 0, "Écoute Kocc Barma :",
                    "Moi, je dis : « Sit down, please. »", "« Sit down » = assieds-toi. Écris : sit.")),
         libre("Je veux que Modou ferme la porte. Je crie « DOOR! » ? Aide-moi à demander poliment.",
               ["close|shut", "please"],
               aides("Quel petit mot Kocc Barma met-il toujours à la fin ?", 3, "Écoute Kocc Barma :",
                     "Moi, je dis : « Close the window, please. »",
                     "Écris : « Close the door, please. »"))],
        [tour("kocc", "Look! Gaïndé is running on the pirogue. Tell him!", "Regarde ! Gaïndé court sur la pirogue. Dis-lui !",
              ["dont run|do not run|stop"], "Don't run, Gaïndé, please!", "Thank you! He's sitting down now."),
         tour("awa", "Your friend is standing in the pirogue. Ask him to sit down.", "Ton ami est debout dans la pirogue. Demande-lui de s'asseoir.",
              ["sit down"], "Sit down, please.", "Good! Now we can go.")],
        ["Sit down, please.", "Don't run!", "Hold the rope, please.", "please"],
    ),
    mission(
        "4e-u3-m5", "Le message du chauffeur", "répéter ce qu'une personne a dit",
        ["He said the bus was late.", "She told us to wait."],
        {"consigne": "À la gare routière, tout le monde attend le car. Quels mots vont avec l'image ?", "fond": "marche",
         "objets": ["🚌", "⏰", "🧳", "📱"],
         "liste": [
             mot("bus", True, "Oui ! « Bus », c'est le car rapide."),
             mot("clock", True, "Oui ! « Clock », c'est l'horloge. On attend longtemps…"),
             mot("bag", True, "Oui ! « Bag », c'est le sac."),
             mot("phone", True, "Oui ! « Phone », c'est le téléphone."),
             mot("pirogue", False, "« Pirogue », c'est la pirogue. On n'est pas sur la plage, on est à la gare ! Regarde encore."),
             mot("bed", False, "« Bed », c'est le lit. On attend debout ! Regarde encore."),
         ]},
        {"fond": "marche", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Awa, what did the driver say?", "Awa, qu'est-ce que le chauffeur a dit ?"),
                       r("awa", "He said the bus was late.", "Il a dit que le car était en retard."),
                       r("modou", "And the lady at the ticket office?", "Et la dame du guichet ?"),
                       r("awa", "She told us to wait here.", "Elle nous a dit d'attendre ici.")],
         "gainde": "Je n'ai pas entendu le chauffeur. Comment on répète ce qu'une personne a dit ?"},
        [q("Le chauffeur a dit que le car…", ["était en retard", "était plein", "était cassé"], 0, 1),
         q("La dame a dit…", ["de partir", "d'attendre ici", "de courir"], 1, 3)],
        [choix("Kocc Barma me demande ce que le chauffeur a dit. Je dis laquelle ?",
               ["Driver guy? Bus late, blah blah.", "He said the bus was late."], 1,
               aides("Kocc Barma est le prof. Comment Awa répète-t-elle le message ?", 1, "Écoute Awa :",
                     "Moi, je dis : « He said the bus was full. »",
                     "« Blah blah », ce n'est pas sérieux. « He said… », c'est « Il a dit… ».")),
         ordre("« She us told to wait. » C'est ça ?", ["us", "wait", "She", "to", "told"],
               "She told us to wait", "She told us to wait.",
               aides("Écoute Awa. Quel mot vient juste après « She » ?", 3, "Écoute Awa :",
                     "Moi, je dis : « He told us to sit down. »",
                     "She told us (elle nous a dit) + to wait (d'attendre).")),
         trou("« He ___ the bus was full. » Je dis « He say » ?", "He", "the bus was full.", ["said"],
              "He said the bus was full.",
              aides("Écoute Awa. Quel mot dit-elle après « He » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « He said the bus was late. »",
                    "Pour une chose déjà dite : « said ». Écris : said.")),
         libre("Le chauffeur a dit : « Le car est cassé ». Je répète à Kocc Barma : « Bus, kaput! » ? Aide-moi !",
               ["said|says|told", "broken"],
               aides("Comment Awa répète-t-elle les mots du chauffeur ?", 1, "Écoute Awa :",
                     "Moi, je dis : « He said the bus was late. »",
                     "Cassé = broken. Écris : « He said the bus was broken. »"))],
        [tour("kocc", "What did Awa say? (Awa a dit : « Je suis fatiguée. »)", "Qu'est-ce qu'Awa a dit ?",
              ["said|says", "tired"], "She said she was tired.", "Poor Awa! Let's sit down."),
         tour("modou", "What did the driver tell us? (Il a dit : « Attendez ! »)", "Qu'est-ce que le chauffeur nous a dit ?",
              ["told|said|says", "wait"], "He told us to wait.", "Wait again?! OK…")],
        ["He said the bus was late.", "She told us to wait.", "driver"],
    ),
    mission(
        "4e-u3-m6", "Le SMS à maman", "envoyer un message par SMS",
        ["Bus late.", "Driver says wait 1h.", "C U l8r!"],
        {"consigne": "Modou écrit un SMS à sa maman. Quels mots vont avec l'image ?", "fond": "marche", "objets": ["📱", "🚌", "⏳", "👩"],
         "liste": [
             mot("phone", True, "Oui ! « Phone », c'est le téléphone de Modou."),
             mot("message", True, "Oui ! « Message », c'est le SMS."),
             mot("bus", True, "Oui ! « Bus », c'est le car rapide en retard."),
             mot("mum", True, "Oui ! « Mum », c'est la maman de Modou. Elle va lire le SMS."),
             mot("letter", False, "« Letter », c'est une lettre sur du papier. Modou écrit sur son téléphone ! Regarde encore."),
             mot("radio", False, "« Radio », c'est la radio. Modou n'écoute pas la radio. Regarde encore !"),
         ]},
        {"fond": "marche", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "I must text my mum. What can I write?", "Je dois envoyer un SMS à ma maman. J'écris quoi ?"),
                       r("awa", "Write: « Bus late. Driver says wait 1h. »", "Écris : « Car en retard. Le chauffeur dit d'attendre 1 h. »"),
                       r("modou", "And at the end?", "Et à la fin ?"),
                       r("awa", "« C U l8r! » It means: see you later!", "« C U l8r! » Ça veut dire : à plus tard !")],
         "gainde": "C U l8r ? Ce sont des lettres et des chiffres mélangés ! Comment on écrit un SMS ?"},
        [q("Pourquoi Modou écrit un SMS ?", ["Le car est en retard.", "Il a faim.", "Il est malade."], 0, 1),
         q("« C U l8r! » veut dire…", ["À plus tard !", "Bonne nuit !", "Merci !"], 0, 3)],
        [choix("J'écris un SMS à Modou : le car est en retard. J'écris laquelle ?",
               ["Dear Mister Modou, I am writing to tell you that the bus is late.", "Bus late. C U l8r!"], 1,
               aides("Un SMS, c'est long ou c'est court ?", 1, "Écoute ce qu'Awa dit d'écrire :",
                     "Moi, j'écris : « Bus late. C U soon! »",
                     "« Dear Mister Modou, I am writing… », c'est pour une lettre au directeur ! Un SMS, c'est court.")),
         ordre("« Says driver 1h wait. » C'est ça ?", ["wait", "says", "1h", "Driver"], "Driver says wait 1h", "Driver says wait 1h.",
               aides("Dans le SMS d'Awa, qui parle en premier ?", 1, "Écoute Awa :",
                     "Moi, j'écris : « Teacher says wait 10 min. »",
                     "Qui (Driver) + says (dit) + quoi (wait 1h).")),
         trou("À la fin du SMS : « C U ___! » Il me manque un mot !", "C U", "!", ["l8r", "later"], "C U l8r!",
              aides("Écoute la fin d'Awa. « C U »… et ensuite ?", 3, "Écoute Awa :",
                    "Moi, j'écris : « C U l8r! »", "« l8r », c'est « later » : plus tard. Écris : l8r.")),
         libre("J'écris à Modou : « Je suis en retard. À plus ! » J'écris une page entière ? Aide-moi : court !",
               ["late", "c u|cu|see you|cya|l8r|later|soon"],
               aides("Comment finit le SMS de Modou ?", 3, "Écoute Awa :",
                     "Moi, j'écris : « Bus late. C U l8r! »",
                     "Écris : « I'm late. C U l8r! »"))],
        [tour("modou", "Where R U? (SMS)", "Tu es où ? (SMS)", [],
              "At the beach. C U l8r!", "OK! C U!"),
         tour("awa", "Bus late? (SMS)", "Le car est en retard ? (SMS)", [],
              "Yes. Driver says wait 1h. C U l8r!", "OK. I'm waiting. C U!")],
        ["Bus late.", "Driver says wait 1h.", "C U l8r! = See you later!", "R U = are you"],
    ),
]

unite3 = unite(
    "4e-u3", "Public places",
    "Perdu en ville : écris ou joue un petit dialogue. Une personne demande son chemin, l'autre lui montre.",
    u3,
    lignes=[
        ("Demander et montrer le chemin", "How can I get to the hospital? · Go straight on, then turn left."),
        ("Dire ce qu'on doit faire, ce qui est interdit", "You must… · You mustn't… · No smoking."),
        ("Proposer une idée", "Let's… · Why don't we…? · Shall we…?"),
        ("Demander poliment", "Sit down, please. · Don't run!"),
        ("Répéter ce qu'on a dit", "He said the bus was late. · She told us to wait."),
        ("Écrire un SMS", "Bus late. · Driver says wait 1h. · C U l8r!"),
    ],
    mots=[
        ("hospital", "hôpital", "opitaal"),
        ("bank", "banque", "bànk"),
        ("pharmacy", "pharmacie", "farmasi"),
        ("bus station", "gare routière", "garaas"),
        ("left", "gauche", "càmmoñ"),
        ("right", "droite", "ndijoor"),
        ("to turn", "tourner", "jàdd"),
        ("to wait", "attendre", "xaar"),
        ("Sit down!", "Assieds-toi !", "Toogal !"),
        ("Don't run!", "Ne cours pas !", "Bul daw !"),
    ],
    pieges=[
        "Go straight on = va tout droit. Turn left = tourne à gauche, turn right = à droite.",
        "You mustn't = c'est interdit. Ce n'est pas « tu n'es pas obligé ».",
        "She told us to wait. Pas « She said us to wait ».",
        "Shall we go? Pas « Shall we to go? ».",
    ],
    exercices=[
        ex("Tu demandes le chemin de l'hôpital, poliment :",
           ["Hospital, where?", "Excuse me, how can I get to the hospital?", "Go to the hospital!", "Hospital, now!"], 1,
           "« Excuse me, how can I get to… ? » est poli."),
        ex("« Turn left » veut dire :", ["tourne à droite", "tourne à gauche", "va tout droit", "arrête-toi"], 1,
           "Left = gauche. Right = droite."),
        ex("« You mustn't swim here. » veut dire :",
           ["Tu dois nager ici.", "Il ne faut pas nager ici.", "Tu peux nager ici.", "Tu nages bien ici."], 1,
           "« Mustn't » = il ne faut pas. C'est interdit."),
        ex("Le panneau « Interdit de fumer » dit :", ["No smoking", "Smoking no", "Don't smoking", "Not smoke"], 0,
           "Sur un panneau : « No » + le mot en -ing."),
        ex("Tu proposes d'aller à la plage : « ____ we go to the beach? »", ["Shall", "Must", "Did", "Are"], 0,
           "« Shall we… ? » = On… ? C'est une idée."),
        ex("« Why don't we play football? » veut dire :",
           ["Pourquoi tu ne joues jamais au foot ?", "Et si on jouait au foot ?", "On ne joue pas au foot.", "Qui joue au foot ?"], 1,
           "« Why don't we… ? » sert à proposer une idée."),
        ex("Tu demandes poliment à un ami de s'asseoir :", ["Sit down, please.", "SIT!", "You sit, now!", "Down, sit."], 0,
           "Avec « please », c'est poli."),
        ex("Le chauffeur a dit : « The bus is late. » Tu répètes :",
           ["He said the bus was late.", "He said me the bus late.", "He told the bus was late.", "He say bus late."], 0,
           "On dit « He said… » : il a dit que…"),
        ex("« She told us to wait. » veut dire :",
           ["Elle nous a dit d'attendre.", "Elle nous attend.", "Elle a attendu.", "Elle nous a dit au revoir."], 0,
           "« Told us to… » = nous a dit de…"),
        ex("Dans un SMS, « C U l8r! » veut dire :", ["See you later!", "Call you later!", "Come up later!", "Cut your letter!"], 0,
           "C = see, U = you, l8r = later."),
    ],
)

UNITES = [unite1, unite2, unite3]

# ======================= HISTOIRES : LA PIROGUE DE KAYAR =======================

EPISODES = [
    episode("Gaïndé Gaïndé, né un mardi", "4e-u1-m2", [
        case("plage", [perso("modou", 0.05, 90), perso("gainde", 0.55, 100, "saute")],
             [bulle("Kayar! I live with my uncle here for the holidays.", "Kayar ! Je vis ici chez mon oncle pendant les vacances.", 0.02, 0.04),
              bulle("Hello, sea! I'm Gaïndé. I was born in Niokolo-Koba!", "Bonjour, la mer ! Je suis Gaïndé. Je suis né à Niokolo-Koba ! (il parle à la mer)", 0.4, 0.34)]),
        case("plage", [perso("kocc", 0.05, 100), perso("gainde", 0.6, 95)],
             [bulle("Surname?", "Ton nom de famille ?", 0.03, 0.04),
              bulle("Gaïndé.", "Gaïndé.", 0.55, 0.22),
              bulle("First name?", "Ton prénom ?", 0.03, 0.36),
              bulle("Gaïndé!", "Gaïndé !", 0.55, 0.5)]),
        case("plage", [perso("kocc", 0.05, 100), perso("gainde", 0.6, 95, "balance")],
             [bulle("Gaïndé Gaïndé?! OK… Date of birth?", "Gaïndé Gaïndé ?! D'accord… Ta date de naissance ?", 0.03, 0.04),
              bulle("I was born… on a Tuesday!", "Je suis né… un mardi ! (il est très fier)", 0.45, 0.34)]),
        case("plage", [perso("kocc", 0.02, 95), perso("gainde", 0.35, 95), perso("pirogue", 0.6, 110, "tangue")],
             [bulle("Could you spell that?", "Tu peux l'épeler ?", 0.02, 0.04),
              bulle("T-U-E… Hmm. Could you spell that, pirogue?", "T-U-E… Hmm. Tu peux l'épeler, la pirogue ? (il demande à la pirogue)", 0.25, 0.26),
              bulle("SPLASH!", "PLOUF ! (une vague mouille Gaïndé)", 0.6, 0.5)]),
    ], ["I was born in…", "I live with…", "Surname?", "First name?", "Date of birth?", "Could you spell that?"]),

    episode("La photo de famille… de Gaïndé", "4e-u1-m4", [
        case("plage", [perso("modou", 0.05, 95), perso("awa", 0.6, 90)],
             [bulle("This is my family. My grandfather has got five children.", "Voici ma famille. Mon grand-père a cinq enfants.", 0.02, 0.04),
              bulle("And your aunt Fatou?", "Et ta tante Fatou ?", 0.5, 0.3),
              bulle("She's married to my uncle Ibou.", "Elle est mariée à mon oncle Ibou.", 0.02, 0.48)]),
        case("plage", [perso("awa", 0.05, 90), perso("gainde", 0.55, 105, "saute")],
             [bulle("Family photo! One, two, three…", "Photo de famille ! Un, deux, trois…", 0.02, 0.04),
              bulle("Me too! Me too!", "Moi aussi ! Moi aussi ! (il saute devant l'appareil)", 0.45, 0.32)]),
        case("plage", [perso("awa", 0.05, 90), perso("gainde", 0.55, 100, "danse")],
             [bulle("In this picture, I can see… a lion.", "Sur cette photo, je vois… un lion.", 0.02, 0.04),
              bulle("On the left: me! In the middle: me! On the right: me!", "À gauche : moi ! Au milieu : moi ! À droite : moi !", 0.35, 0.34)]),
        case("plage", [perso("kocc", 0.02, 95), perso("gainde", 0.35, 95), perso("modou", 0.65, 90)],
             [bulle("Hmm… Where is Modou's family?", "Hmm… Où est la famille de Modou ?", 0.02, 0.04),
              bulle("In the background! Behind my tail.", "Au fond ! Derrière ma queue.", 0.3, 0.3),
              bulle("My grandfather is… a very small dot!", "Mon grand-père, c'est… un tout petit point !", 0.5, 0.5)]),
    ], ["My grandfather has got five children.", "She's married to…", "In this picture, I can see…", "On the left", "In the background"]),

    episode("Trois conseils et un poisson", "4e-u2-m2", [
        case("mer", [perso("gainde", 0.1, 100, "tangue"), perso("awa", 0.6, 90)],
             [bulle("I feel sick… very, very sick.", "Je me sens mal… très, très mal.", 0.03, 0.04),
              bulle("Oh, poor you!", "Oh, mon pauvre !", 0.5, 0.32)]),
        case("mer", [perso("modou", 0.05, 90), perso("gainde", 0.55, 100, "balance")],
             [bulle("You should look at the sky.", "Tu devrais regarder le ciel.", 0.02, 0.04),
              bulle("The sky? OK… Oops!", "Le ciel ? D'accord… Oups ! (il regarde en l'air et tombe sur le dos)", 0.4, 0.34)]),
        case("mer", [perso("kocc", 0.05, 95), perso("gainde", 0.4, 95), perso("poisson", 0.7, 70, "saute")],
             [bulle("You'd better sit down.", "Tu ferais mieux de t'asseoir.", 0.02, 0.04),
              bulle("OK!", "D'accord ! (il s'assoit sur un poisson)", 0.35, 0.3),
              bulle("Ouch!", "Aïe !", 0.6, 0.48)]),
        case("mer", [perso("awa", 0.02, 90), perso("gainde", 0.35, 100, "tangue"), perso("poisson", 0.68, 75, "saute")],
             [bulle("If I were you, I'd drink some water.", "À ta place, je boirais un peu d'eau.", 0.02, 0.04),
              bulle("Bleurgh!", "Beurk ! (il a bu l'eau de la mer)", 0.32, 0.3),
              bulle("I'm sorry to hear that. I hope you feel better!", "Je suis désolé. J'espère que tu vas aller mieux ! (c'est le poisson qui le console)", 0.45, 0.5)]),
    ], ["Poor you!", "I'm sorry to hear that.", "I hope you feel better.", "You should…", "You'd better…", "If I were you…"]),

    episode("Gaïndé, la grosse sardine", "4e-u2-m4", [
        case("plage", [perso("modou", 0.05, 90), perso("gainde", 0.55, 110, "balance")],
             [bulle("Gaïndé! Where are the sardines for the fishing?", "Gaïndé ! Où sont les sardines pour la pêche ?", 0.02, 0.04),
              bulle("Hmm…", "Hmm… (il a un ventre énorme)", 0.5, 0.36)]),
        case("plage", [perso("awa", 0.05, 90), perso("gainde", 0.55, 110)],
             [bulle("You ate them?! You shouldn't have done that!", "Tu les as mangées ?! Tu n'aurais pas dû faire ça !", 0.02, 0.04),
              bulle("I'm sorry… I regret eating ten sardines.", "Pardon… Je regrette d'avoir mangé dix sardines.", 0.42, 0.34)]),
        case("plage", [perso("kocc", 0.05, 95), perso("gainde", 0.55, 110)],
             [bulle("Ten?! Why didn't you eat bread?", "Dix ?! Pourquoi tu n'as pas mangé de pain ?", 0.02, 0.04),
              bulle("I ate the bread too…", "J'ai mangé le pain aussi…", 0.48, 0.36)]),
        case("mer", [perso("gainde", 0.1, 100, "tangue"), perso("poisson", 0.5, 75, "saute"), perso("poisson", 0.72, 70, "saute")],
             [bulle("Hello, fish! I'm sorry I didn't bring sardines…", "Bonjour, les poissons ! Désolé, je n'ai pas apporté de sardines… (il se penche au bord de la pirogue)", 0.02, 0.04),
              bulle("Yum! A big sardine!", "Miam ! Une grosse sardine ! (les poissons regardent Gaïndé)", 0.45, 0.34),
              bulle("I regret everything!", "Je regrette tout !", 0.02, 0.5)]),
    ], ["You shouldn't have done that!", "Why didn't you…?", "I'm sorry I didn't…", "I regret…"]),

    episode("Gaïndé préfère tout", "4e-u2-m5", [
        case("maison", [perso("doudou", 0.05, 95), perso("gainde", 0.55, 100)],
             [bulle("Thiof or yaboye, Gaïndé?", "Thiof ou yaboye, Gaïndé ?", 0.02, 0.04),
              bulle("I prefer thiof to yaboye. Thank you!", "Je préfère le thiof au yaboye. Merci !", 0.45, 0.32)]),
        case("maison", [perso("modou", 0.05, 90), perso("gainde", 0.55, 105, "saute")],
             [bulle("And sardines?", "Et des sardines ?", 0.02, 0.04),
              bulle("Hmm… I'd rather eat thiof AND yaboye AND sardines!", "Hmm… Je préfère manger du thiof ET du yaboye ET des sardines ! (il prend tout le plat)", 0.35, 0.3)]),
        case("maison", [perso("awa", 0.05, 90), perso("gainde", 0.55, 115, "balance")],
             [bulle("Gaïndé! And the rice?", "Gaïndé ! Et le riz ?", 0.02, 0.04),
              bulle("I prefer fish to rice!", "Je préfère le poisson au riz !", 0.45, 0.34)]),
        case("plage", [perso("gainde", 0.1, 120, "immobile"), perso("poisson", 0.6, 75, "saute")],
             [bulle("Ooh… I regret eating all the fish…", "Ooh… Je regrette d'avoir mangé tout le poisson… (il ne peut plus bouger)", 0.03, 0.04),
              bulle("And we prefer lions… far from the sea!", "Et nous, on préfère les lions… loin de la mer !", 0.4, 0.38)]),
    ], ["I prefer thiof to yaboye.", "I'd rather eat…", "I regret…"]),

    episode("Le panneau de Gaïndé", "4e-u3-m2", [
        case("marche", [perso("gainde", 0.05, 100), perso("doudou", 0.6, 95)],
             [bulle("Hey, you! Beach! Where?", "Hé, toi ! Plage ! Où ?", 0.02, 0.04),
              bulle("Hmm…?", "Hmm… ? (Doudou lève un sourcil)", 0.55, 0.32)]),
        case("marche", [perso("gainde", 0.05, 100), perso("doudou", 0.6, 95)],
             [bulle("Sorry! Excuse me, Sir. How can I get to the beach?", "Pardon ! Excusez-moi, Monsieur. Comment je peux aller à la plage ?", 0.02, 0.04),
              bulle("Go straight on, then turn left.", "Va tout droit, puis tourne à gauche.", 0.45, 0.36)]),
        case("marche", [perso("gainde", 0.1, 95, "saute"), perso("bouc", 0.55, 85)],
             [bulle("Straight on… then turn… right!", "Tout droit… puis je tourne… à droite ! (il se trompe)", 0.02, 0.04),
              bulle("Bêêê! You mustn't come here!", "Bêêê ! Tu ne dois pas venir ici ! (c'est le parc des chèvres)", 0.42, 0.34)]),
        case("plage", [perso("kocc", 0.05, 95), perso("gainde", 0.55, 100, "danse")],
             [bulle("Here you are! You must swim with us, Gaïndé!", "Te voilà ! Tu dois nager avec nous, Gaïndé !", 0.02, 0.04),
              bulle("Sorry! Look at the sign: I mustn't swim!", "Désolé ! Regarde le panneau : je ne dois pas nager ! (il déteste l'eau, il est tout content)", 0.42, 0.28),
              bulle("Gaïndé… it says « No smoking ».", "Gaïndé… c'est écrit « Interdit de fumer ».", 0.02, 0.5)]),
    ], ["How can I get to…?", "Go straight on, then turn left.", "You must…", "You mustn't…", "No smoking."]),

    episode("Assis, Gaïndé !", "4e-u3-m4", [
        case("plage", [perso("modou", 0.02, 90), perso("awa", 0.35, 90), perso("gainde", 0.65, 90)],
             [bulle("Let's go fishing!", "Allons pêcher !", 0.02, 0.04),
              bulle("Why don't we take the pirogue?", "Et si on prenait la pirogue ?", 0.3, 0.26),
              bulle("Shall we… stay here?", "Et si on… restait ici ? (il a peur de l'eau)", 0.5, 0.48)]),
        case("mer", [perso("kocc", 0.05, 95), perso("gainde", 0.5, 100, "saute")],
             [bulle("Don't run on the pirogue, Gaïndé!", "Ne cours pas sur la pirogue, Gaïndé !", 0.02, 0.04),
              bulle("OK! I don't run… I jump!", "D'accord ! Je ne cours pas… je saute ! (la pirogue tangue très fort)", 0.42, 0.34)]),
        case("mer", [perso("kocc", 0.1, 95, "tangue"), perso("gainde", 0.45, 100)],
             [bulle("Sit down, please!", "Assieds-toi, s'il te plaît !", 0.02, 0.04),
              bulle("Yes, Sir!", "Oui, Monsieur ! (il s'assoit… sur Kocc Barma)", 0.45, 0.3),
              bulle("Not on me!", "Pas sur moi !", 0.05, 0.5)]),
        case("mer", [perso("gainde", 0.05, 95), perso("kocc", 0.35, 90, "immobile"), perso("poisson", 0.68, 75, "saute")],
             [bulle("Shall we go fishing now?", "On va pêcher, maintenant ?", 0.02, 0.04),
              bulle("Yes… let's…", "Oui… allons-y… (Kocc Barma est tout aplati)", 0.3, 0.3),
              bulle("Why don't we swim away? Quick!", "Et si on partait à la nage ? Vite ! (les poissons s'en vont)", 0.48, 0.5)]),
    ], ["Let's…", "Why don't we…?", "Shall we…?", "Sit down, please.", "Don't run!"]),

    episode("C U l8r, Kocc Barma !", "4e-u3-m6", [
        case("marche", [perso("modou", 0.05, 90), perso("gainde", 0.55, 95)],
             [bulle("The driver said the bus was late.", "Le chauffeur a dit que le car était en retard.", 0.02, 0.04),
              bulle("Late? How late?", "En retard ? Combien de temps ?", 0.5, 0.28),
              bulle("He told us to wait one hour.", "Il nous a dit d'attendre une heure.", 0.02, 0.48)]),
        case("marche", [perso("modou", 0.05, 90), perso("gainde", 0.55, 95, "balance")],
             [bulle("Gaïndé, text my mum, please!", "Gaïndé, envoie un SMS à ma maman, s'il te plaît !", 0.02, 0.04),
              bulle("« Dear Madam, good morning! My name is Gaïndé. I was born in… »", "« Chère Madame, bonjour ! Je m'appelle Gaïndé. Je suis né à… » (il écrit, il écrit…)", 0.35, 0.28),
              bulle("No! Short! « Bus late. C U l8r! »", "Non ! Court ! « Car en retard. À plus ! »", 0.02, 0.5)]),
        case("marche", [perso("gainde", 0.1, 95), perso("kocc", 0.6, 95)],
             [bulle("« Bus late. Driver says wait 1h. C U l8r! » Send!", "« Car en retard. Le chauffeur dit d'attendre 1 h. À plus ! » J'envoie !", 0.02, 0.04),
              bulle("Bip bip! Oh, a message!", "Bip bip ! Oh, un message ! (le téléphone de Kocc Barma sonne)", 0.45, 0.36)]),
        case("marche", [perso("kocc", 0.05, 95), perso("gainde", 0.4, 95, "saute"), perso("modou", 0.7, 90)],
             [bulle("Gaïndé… you sent it to ME!", "Gaïndé… tu me l'as envoyé à MOI !", 0.02, 0.04),
              bulle("Oh! OK… C U l8r, Kocc Barma!", "Oh ! D'accord… À plus, Kocc Barma ! (il est juste à côté de lui)", 0.32, 0.3),
              bulle("Oh no…", "Oh non…", 0.6, 0.5)]),
    ], ["He said the bus was late.", "He told us to wait.", "Bus late.", "Driver says wait 1h.", "C U l8r!"]),
]
