"""Parcours d'anglais de 5e, unités 4 à 6 (saison « Les vacances au village », pendant le séjour)."""
from jang_lib import *  # noqa: F401,F403

NIVEAU = "5e"

# ======================= UNITÉ 4 : BIGGER, BETTER, THE BEST =======================

u4 = [
    mission(
        "5e-u4-m1", "Le village ou la ville ?", "comparer deux choses (plus grand que…)",
        ["Dakar is bigger than Louga.", "The village is quieter than Dakar.", "smaller than", "older than"],
        {"consigne": "Le village de grand-mère. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🏡", "🌳", "🐐", "🐓"],
         "liste": [
             mot("village", True, "Oui ! « Village », c'est le village de grand-mère."),
             mot("house", True, "Oui ! « House », c'est la maison."),
             mot("tree", True, "Oui ! « Tree », c'est l'arbre."),
             mot("goat", True, "Oui ! « Goat », c'est la chèvre."),
             mot("chicken", True, "Oui ! « Chicken », c'est la poule."),
             mot("building", False, "« Building », c'est un grand immeuble. On en voit en ville, pas au village. Regarde encore !"),
             mot("sea", False, "« Sea », c'est la mer. Il n'y a pas de mer ici. Regarde encore !"),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Dakar is bigger than the village.", "Dakar est plus grand que le village."),
                       r("awa", "Yes, but the village is quieter than Dakar.", "Oui, mais le village est plus calme que Dakar."),
                       r("modou", "And the mangoes are cheaper here!", "Et les mangues sont moins chères ici !")],
         "gainde": "Plus grand, plus calme… Et moi, je suis plus grand que le bouc ?"},
        [q("Qu'est-ce qui est plus grand ?", ["Dakar", "le village", "la chèvre"], 0, 0),
         q("Pour Awa, le village est…", ["plus calme que Dakar", "plus bruyant que Dakar", "plus grand que Dakar"], 0, 1)],
        [choix("Je veux dire que Dakar est plus grand que Louga. Je dis laquelle ?",
               ["Dakar is more big than Louga.", "Dakar is bigger than Louga."], 1,
               aides("Modou dit « more big » ? Ou un seul mot ?", 0, "Écoute Modou :",
                     "Moi, je dis : « Dakar is bigger than Louga. »",
                     "Avec un mot court, on ajoute « -er » : big → bigger. « Than », c'est « que ».")),
         ordre("« The village is quieter Dakar than. » C'est bien ça ?",
               ["quieter", "village", "Dakar", "is", "than", "The"], "The village is quieter than Dakar",
               "The village is quieter than Dakar.",
               aides("Où Awa met-elle le petit mot « than » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « The village is quieter than Dakar. »",
                     "D'abord « quieter » (plus calme), puis « than » (que), puis « Dakar ».")),
         trou("Je veux dire « plus petit ». « A goat is ___ than a lion. » Je mets « more small » ?",
              "A goat is", "than a lion.", ["smaller"], "A goat is smaller than a lion.",
              aides("Petit, c'est « small ». Et « plus petit » ?", 0, "Écoute comment Modou dit « plus grand » :",
                    "Moi, je dis : big → bigger. Et small → ?", "Plus petit, c'est « smaller ». Écris : smaller.")),
         libre("Je veux dire que grand-mère est plus vieille que maman. Comment je dis ?", ["older than"],
               aides("Vieux, c'est « old ». Alors, « plus vieux » ?", 0, "Écoute comment Modou compare :",
                     "Moi, je dis : « Grandma is older than Mum. »",
                     "Old → older, puis « than ». Écris : « Grandma is older than Mum. »"))],
        [tour("modou", "Compare Dakar and your village, please!", "Compare Dakar et ton village, s'il te plaît !",
              ["bigger|smaller|quieter|noisier|older|cheaper|better|more beautiful|more expensive"],
              "Dakar is bigger than my village.", "Yes! And the village is quieter!"),
         tour("awa", "A lion and a goat: which is faster?", "Un lion et une chèvre : lequel est plus rapide ?",
              ["faster|lion"], "A lion is faster than a goat.", "Ha ha! Yes, Gaïndé is very fast!")],
        ["bigger than", "smaller than", "older than", "quieter than"],
    ),
    mission(
        "5e-u4-m2", "Le plus grand baobab", "dire le plus grand, le meilleur…",
        ["It's the biggest tree in the village!", "It's the oldest tree.", "He's the best!"],
        {"consigne": "Sous le baobab. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🌳", "🧒", "🐐", "☀️"],
         "liste": [
             mot("baobab", True, "Oui ! « Baobab », c'est le grand arbre du village."),
             mot("tree", True, "Oui ! « Tree », c'est l'arbre."),
             mot("children", True, "Oui ! « Children », ce sont les enfants."),
             mot("goat", True, "Oui ! « Goat », c'est la chèvre."),
             mot("sun", True, "Oui ! « Sun », c'est le soleil."),
             mot("boat", False, "« Boat », c'est le bateau. Il n'y a pas d'eau ici. Regarde encore !"),
             mot("snow", False, "« Snow », c'est la neige. Il fait chaud au village ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Look! It's the biggest tree in the village!", "Regarde ! C'est le plus grand arbre du village !"),
                       r("modou", "It's the oldest tree too.", "C'est aussi le plus vieil arbre."),
                       r("awa", "And its fruit is the best!", "Et son fruit est le meilleur ! (le pain de singe)")],
         "gainde": "Le plus grand… le meilleur… Et moi ? Je suis le plus beau lion du monde !"},
        [q("Le baobab est…", ["le plus grand arbre du village", "le plus petit arbre du village", "un arbre de Dakar"], 0, 0),
         q("Pour Awa, le fruit du baobab est…", ["le meilleur", "le pire", "le plus cher"], 0, 2)],
        [choix("Je veux dire que c'est le plus grand arbre. Je dis laquelle ?",
               ["It's the most big tree.", "It's the biggest tree."], 1,
               aides("Awa dit « most big » ? Ou un seul mot ?", 0, "Écoute Awa :",
                     "Moi, je dis : « It's the biggest tree in the village! »",
                     "Pour dire « le plus… » avec un mot court : the + mot + « -est ». Big → the biggest.")),
         ordre("« It's the tree oldest in the village. » C'est ça ?",
               ["tree", "the", "village", "It's", "oldest", "in", "the"], "Its the oldest tree in the village",
               "It's the oldest tree in the village.",
               aides("« Oldest » vient avant ou après « tree » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « It's the oldest tree in the village. »",
                     "D'abord « the oldest » (le plus vieux), puis « tree » (arbre).")),
         trou("Le fruit est très, très bon. « It's the ___! » Je dis « the goodest » ?", "It's the", "!",
              ["best"], "It's the best!",
              aides("Qu'est-ce qu'Awa dit du fruit ?", 2, "Écoute Awa :",
                    "Moi, je dis : « Its fruit is the best! »",
                    "Good → better → the best. C'est un mot spécial. Écris : best.")),
         libre("Je veux dire que Modou est le plus rapide. Comment je dis ?", ["fastest"],
               aides("Rapide, c'est « fast ». Alors, « le plus rapide » ?", 0, "Écoute comment Awa dit « le plus grand » :",
                     "Moi, je dis : « Modou is the fastest! »",
                     "Fast → the fastest. Écris : « Modou is the fastest! »"))],
        [tour("awa", "What is the biggest town in Senegal?", "Quelle est la plus grande ville du Sénégal ?",
              ["dakar"], "Dakar is the biggest town in Senegal.", "Yes! Dakar is the biggest!"),
         tour("modou", "Who is the best football player in your class?", "Qui est le meilleur joueur de foot de ta classe ?",
              ["best"], "Ibrahima is the best!", "Ha ha! No, I'm the best!")],
        ["the biggest", "the oldest", "the fastest", "the best"],
    ),
    mission(
        "5e-u4-m3", "Le portrait de grand-mère", "bien décrire une personne",
        ["She's old but strong.", "She has got white hair.", "She always wears a blue boubou."],
        {"consigne": "Chez grand-mère. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["👵", "👓", "🧣", "🪑"],
         "liste": [
             mot("grandmother", True, "Oui ! « Grandmother », c'est la grand-mère d'Awa."),
             mot("glasses", True, "Oui ! « Glasses », ce sont les lunettes."),
             mot("scarf", True, "Oui ! « Scarf », c'est le foulard."),
             mot("chair", True, "Oui ! « Chair », c'est la chaise."),
             mot("beard", False, "« Beard », c'est la barbe. Grand-mère n'a pas de barbe ! Regarde encore."),
             mot("hat", False, "« Hat », c'est un chapeau. Grand-mère porte un foulard, pas un chapeau. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "My grandma is old but strong.", "Ma grand-mère est vieille mais forte."),
                       r("awa", "She has got white hair and big glasses.", "Elle a les cheveux blancs et de grandes lunettes."),
                       r("modou", "She always wears a blue boubou!", "Elle porte toujours un boubou bleu !")],
         "gainde": "Je dessine grand-mère ! Vieille… forte… Je lui dessine des muscles ?"},
        [q("Grand-mère est…", ["vieille mais forte", "jeune et petite", "vieille et fatiguée"], 0, 0),
         q("Elle porte toujours…", ["un boubou bleu", "un chapeau rouge", "un pantalon"], 0, 2)],
        [choix("Je veux dire que grand-mère a les cheveux blancs. Je dis laquelle ?",
               ["She has got white hairs.", "She has got white hair."], 1,
               aides("Awa dit « hair » ou « hairs » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « She has got white hair. »",
                     "En anglais, les cheveux, c'est « hair », sans « s ».")),
         ordre("« She wears always a blue boubou. » C'est ça ?",
               ["wears", "a", "always", "She", "boubou", "blue"], "She always wears a blue boubou",
               "She always wears a blue boubou.",
               aides("Où Modou met-il le mot « always » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « She always wears a blue boubou. »",
                     "« Always » (toujours) vient avant « wears » (porte).")),
         trou("« She's old ___ strong. » Il me manque un petit mot !", "She's old", "strong.",
              ["but", "and"], "She's old but strong.",
              aides("Quel petit mot Awa dit-elle entre « old » et « strong » ?", 0, "Écoute Awa :",
                    "Moi, je dis : « She's old but strong. »", "« But », c'est « mais ». Écris : but.")),
         libre("Grand-mère a de grandes lunettes. Comment je le dis ?", ["has got|has|wears", "glasses"],
               aides("Comment Awa parle-t-elle des lunettes ?", 1, "Écoute Awa :",
                     "Moi, je dis : « She has got big glasses. »",
                     "« Glasses », ce sont les lunettes. Écris : « She has got big glasses. »"))],
        [tour("awa", "Describe your grandma or your grandpa!", "Décris ta grand-mère ou ton grand-père !",
              ["has got|has|wears|is|shes|hes"], "She's old but strong. She has got white hair.",
              "Lovely! Say hello from me!")],
        ["She's old but strong.", "She has got white hair.", "She always wears…", "glasses"],
    ),
    mission(
        "5e-u4-m4", "Moi aussi !", "dire que je suis d'accord",
        ["I agree.", "You're right.", "Me too!", "So do I."],
        {"consigne": "Le repas chez grand-mère. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🍲", "🍚", "🐟", "🥄"],
         "liste": [
             mot("bowl", True, "Oui ! « Bowl », c'est le grand bol, le plat."),
             mot("rice", True, "Oui ! « Rice », c'est le riz."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("spoon", True, "Oui ! « Spoon », c'est la cuillère."),
             mot("pizza", False, "« Pizza », c'est une pizza. Grand-mère a fait du thiéboudienne ! Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. Il n'y a pas de gâteau dans le plat. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Grandma's thieboudienne is the best!", "Le thiéboudienne de grand-mère est le meilleur !"),
                       r("awa", "I agree! You're right.", "Je suis d'accord ! Tu as raison."),
                       r("modou", "I love fish!", "J'adore le poisson !"),
                       r("awa", "So do I!", "Moi aussi !")],
         "gainde": "En français, on dit « je suis d'accord ». Alors en anglais, c'est « I am agree » ?"},
        [q("Pour Modou, le thiéboudienne de grand-mère est…", ["le meilleur", "le pire", "trop salé"], 0, 0),
         q("« So do I » veut dire…", ["Moi aussi", "Moi non", "Je ne sais pas"], 0, 3)],
        [choix("Je suis d'accord avec Modou. Je dis laquelle ?", ["I am agree.", "I agree."], 1,
               aides("Écoute bien Awa. Elle dit « I am agree » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « I agree! »",
                     "En anglais, on dit seulement « I agree ». Pas de « am ».")),
         ordre("« Right you're! I agree. » C'est ça ?", ["right", "I", "You're", "agree"], "Youre right I agree",
               "You're right! I agree.",
               aides("Quels mots Awa dit-elle après « I agree » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « You're right! I agree. »",
                     "« You're right », c'est « tu as raison ». « I agree », c'est « je suis d'accord ».")),
         trou("Modou dit « I love fish! ». Moi aussi ! « So ___ I! »", "So", "I!", ["do"], "So do I!",
              aides("Qu'est-ce qu'Awa répond à Modou ?", 3, "Écoute Awa :",
                    "Moi, je dis : « So do I! »", "« So do I », c'est « moi aussi ». Écris : do.")),
         libre("Awa dit « I love mangoes! ». Moi aussi ! Comment je dis ?", ["too|so do i"],
               aides("Il y a aussi une façon très courte de dire « moi aussi ». Tu la connais ?", 3,
                     "Écoute Awa. Elle dit « So do I ». Il y a plus court :",
                     "Moi, je dis : « Me too! »",
                     "« Me too », c'est « moi aussi », comme « So do I ». Écris : « Me too! »"))],
        [tour("awa", "Grandma's thieboudienne is the best!", "Le thiéboudienne de grand-mère est le meilleur !",
              ["agree|right|yes|too|so do i"], "I agree! You're right.", "Yes! Let's eat!"),
         tour("modou", "I love football!", "J'adore le foot !", ["too|so do i|agree"], "Me too!",
              "Great! Let's play after lunch!")],
        ["I agree.", "You're right.", "Me too!", "So do I!"],
    ),
]

unite4 = unite(
    "5e-u4", "Bigger, better, the best",
    "Mon village et la ville : compare deux endroits en 5 phrases.",
    u4,
    lignes=[
        ("Comparer deux choses", "Dakar is bigger than Louga. · The village is quieter than Dakar."),
        ("Dire le plus…, le meilleur", "It's the biggest tree in the village! · He's the best!"),
        ("Décrire une personne", "She's old but strong. · She has got white hair. · She always wears a boubou."),
        ("Dire que je suis d'accord", "I agree. · You're right. · Me too! · So do I."),
    ],
    mots=[
        ("big", "grand, gros", "rëy"),
        ("small", "petit", "tuuti"),
        ("old", "vieux, âgé", "mag"),
        ("young", "jeune", "ndaw"),
        ("beautiful", "beau, belle", "rafet"),
        ("fast", "rapide", "gaaw"),
        ("expensive", "cher", "seer"),
        ("cheap", "pas cher", "yomb"),
        ("grandmother", "grand-mère", "maam"),
        ("tree", "arbre", "garab"),
        ("village", "village", "dëkk"),
    ],
    pieges=[
        "Dakar is bigger than Louga. Pas « more big than ».",
        "I agree. Pas « I am agree ».",
        "She has got white hair. Pas « white hairs ».",
    ],
    exercices=[
        ex("Dakar est plus grand que Louga :", ["Dakar is more big than Louga.", "Dakar is bigger than Louga.",
                                                "Dakar is big than Louga.", "Dakar is biggest Louga."], 1,
           "Mot court : big → bigger, puis « than »."),
        ex("Complète : « The village is quieter ____ Dakar. »", ["that", "than", "then", "as"], 1,
           "Pour comparer, « que » se dit « than »."),
        ex("C'est le plus grand arbre du village :", ["It's the bigger tree in the village.", "It's the biggest tree in the village.",
                                                      "It's the most big tree in the village.", "It's biggest the tree in the village."], 1,
           "Le plus grand : the biggest."),
        ex("Good → better → ?", ["the goodest", "the best", "the better", "the most good"], 1,
           "Good, better, the best : ce sont des mots spéciaux."),
        ex("Grand-mère a les cheveux blancs :", ["She has got white hairs.", "She has got white hair.",
                                                 "She have got white hair.", "She is white hair."], 1,
           "Les cheveux : hair, sans « s »."),
        ex("Elle porte toujours un boubou :", ["She wears always a boubou.", "She always wears a boubou.",
                                               "Always she wear a boubou.", "She always wear a boubou."], 1,
           "« Always » vient avant « wears »."),
        ex("« She's old but strong. » « But » veut dire :", ["et", "mais", "très", "aussi"], 1,
           "But = mais."),
        ex("Ton ami dit « I love mangoes! ». Toi aussi. Tu dis :", ["Me too!", "Me also!", "I too!", "So I do!"], 0,
           "Moi aussi : Me too! ou So do I!"),
        ex("Tu es d'accord. Tu dis :", ["I am agree.", "I agree.", "I'm agree.", "I agreed you."], 1,
           "On dit « I agree », sans « am »."),
        ex("« You're right » veut dire :", ["Tu as raison.", "Tu es à droite.", "Tu écris.", "Tu es en retard."], 0,
           "You're right = tu as raison."),
    ],
)

# ======================= UNITÉ 5 : HOW DO YOU FEEL? =======================

u5 = [
    mission(
        "5e-u5-m1", "Gaïndé est triste", "dire comment je me sens",
        ["How do you feel?", "I feel sad.", "I'm happy.", "I'm tired.", "I'm scared."],
        {"consigne": "La nuit au village. Quels mots vont avec l'image ?", "fond": "nuit",
         "objets": ["🌙", "⭐", "🦉", "🔦"],
         "liste": [
             mot("moon", True, "Oui ! « Moon », c'est la lune."),
             mot("stars", True, "Oui ! « Stars », ce sont les étoiles."),
             mot("owl", True, "Oui ! « Owl », c'est le hibou. Hou hou !"),
             mot("torch", True, "Oui ! « Torch », c'est la lampe de poche."),
             mot("sun", False, "« Sun », c'est le soleil. C'est la nuit ! Regarde encore."),
             mot("beach", False, "« Beach », c'est la plage. On est au village. Regarde encore !"),
         ]},
        {"fond": "nuit", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "How do you feel, Modou?", "Comment tu te sens, Modou ?"),
                       r("modou", "I feel tired. And I'm scared!", "Je me sens fatigué. Et j'ai peur !"),
                       r("awa", "Scared? It's an owl! I'm happy here.", "Peur ? C'est un hibou ! Moi, je suis contente ici.")],
         "gainde": "Moi, je suis triste : il n'y a pas de foot à la télé ce soir ! Comment je le dis ?"},
        [q("Modou se sent…", ["fatigué", "content", "en colère"], 0, 1),
         q("Awa est…", ["contente", "triste", "fatiguée"], 0, 2)],
        [choix("J'ai peur du hibou ! Je dis laquelle ?", ["I have fear!", "I'm scared!"], 1,
               aides("Modou a peur. Il dit « I have… » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I'm scared! »",
                     "En anglais, on « est » peur : I'm scared = j'ai peur.")),
         ordre("« I me feel sad. » C'est ça ?", ["sad", "feel", "I"], "I feel sad", "I feel sad.",
               aides("Modou dit « I feel… ». Tu entends un « me » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I feel tired. » Et triste ?",
                     "« I feel », c'est « je me sens ». Pas de « me » en anglais.")),
         trou("Il est tard, je veux dormir. « I'm ___. »", "I'm", ".", ["tired", "sleepy"], "I'm tired.",
              aides("Comment Modou dit-il qu'il est fatigué ?", 1, "Écoute Modou :",
                    "Moi, je dis : « I'm tired. »", "Fatigué, c'est « tired ». Écris : tired.")),
         libre("Je suis triste : pas de foot ce soir ! Comment je dis ?", ["sad"],
               aides("Triste, en anglais, c'est un petit mot. Tu t'en souviens ?", 1, "Écoute comment Modou dit ce qu'il sent :",
                     "Moi, je dis : « I feel sad. »",
                     "Triste, c'est « sad ». Écris : « I'm sad. » ou « I feel sad. »"))],
        [tour("awa", "How do you feel today?", "Comment tu te sens aujourd'hui ?",
              ["happy|sad|tired|scared|angry|bored|excited|worried|fine|good|ok|great"],
              "I feel happy!", "Me too! I'm happy too!"),
         tour("modou", "Look! A big snake! How do you feel?", "Regarde ! Un gros serpent ! Tu te sens comment ?",
              ["scared|worried|afraid|happy|fine|ok"], "I'm scared!", "Ha ha! It's not a snake! It's a stick!")],
        ["How do you feel?", "I feel sad.", "I'm happy.", "I'm tired.", "I'm scared."],
    ),
    mission(
        "5e-u5-m2", "Au poste de santé", "dire où j'ai mal",
        ["What's wrong?", "I've got a headache.", "My stomach hurts.", "I've got a fever."],
        {"consigne": "Au poste de santé du village. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🏥", "💊", "🛏️", "💧"],
         "liste": [
             mot("health post", True, "Oui ! « Health post », c'est le poste de santé."),
             mot("medicine", True, "Oui ! « Medicine », c'est le médicament."),
             mot("bed", True, "Oui ! « Bed », c'est le lit."),
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("ball", False, "« Ball », c'est le ballon. On ne joue pas au poste de santé ! Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. Il n'y a pas de gâteau ici. Regarde encore !"),
         ]},
        {"fond": "cour", "persos": ["kocc", "modou", "gainde"],
         "repliques": [r("kocc", "Hello, Modou. What's wrong?", "Bonjour, Modou. Qu'est-ce qui ne va pas ?"),
                       r("modou", "I've got a headache.", "J'ai mal à la tête."),
                       r("kocc", "And your stomach?", "Et ton ventre ?"),
                       r("modou", "My stomach hurts too. I ate ten mangoes!", "J'ai mal au ventre aussi. J'ai mangé dix mangues !")],
         "gainde": "Kocc Barma aide au poste de santé ! Dix mangues ? Moi, j'en ai mangé vingt… Aïe, mon ventre !"},
        [q("Qu'est-ce que Modou dit d'abord ?", ["J'ai mal à la tête.", "J'ai peur.", "J'ai faim."], 0, 1),
         q("Pourquoi Modou a mal au ventre ?", ["Il a mangé dix mangues.", "Il a couru.", "Il a bu du bissap."], 0, 3)],
        [choix("J'ai mal à la tête. Je dis laquelle ?", ["I have bad at my head.", "I've got a headache."], 1,
               aides("Modou dit « bad » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « I've got a headache. »",
                     "Mal à la tête, c'est « a headache » : head (tête) + ache (mal).")),
         ordre("« My hurts stomach. » C'est ça ?", ["hurts", "stomach", "My"], "My stomach hurts", "My stomach hurts.",
               aides("Quel mot Modou dit-il juste après « My » ?", 3, "Écoute Modou :",
                     "Moi, je dis : « My stomach hurts. »",
                     "My stomach (mon ventre) + hurts (fait mal).")),
         trou("J'ai de la fièvre. « I've got a ___. »", "I've got a", ".", ["fever", "temperature"], "I've got a fever.",
              aides("« Fièvre » ressemble au mot anglais. Tu devines ?", -1, "",
                    "Moi, je dis : « I've got a fever. »", "Fièvre, c'est « fever ». Écris : fever.")),
         libre("J'ai mangé vingt mangues. J'ai mal au ventre ! Comment je dis ?", ["stomach|stomachache|tummy"],
               aides("Comment Modou parle-t-il de son ventre ?", 3, "Écoute Modou :",
                     "Moi, je dis : « My stomach hurts. »",
                     "Ventre, c'est « stomach ». Écris : « My stomach hurts. »"))],
        [tour("kocc", "Hello! What's wrong?", "Bonjour ! Qu'est-ce qui ne va pas ?",
              ["headache|stomach|stomachache|fever|cough|cold|hurts|hurt|ache|tired"],
              "I've got a headache.", "Oh dear! Sit down, please.")],
        ["What's wrong?", "I've got a headache.", "My stomach hurts.", "I've got a fever."],
    ),
    mission(
        "5e-u5-m3", "Le conseil de l'infirmière", "comprendre le conseil de l'infirmière",
        ["You should rest.", "Drink a lot of water.", "You shouldn't eat ten mangoes!"],
        {"consigne": "Au poste de santé. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["💧", "🛏️", "💊", "😴"],
         "liste": [
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("bed", True, "Oui ! « Bed », c'est le lit."),
             mot("medicine", True, "Oui ! « Medicine », c'est le médicament."),
             mot("sleep", True, "Oui ! « Sleep », c'est dormir."),
             mot("football", False, "« Football », c'est le foot. Quand on est malade, on ne joue pas ! Regarde encore."),
             mot("cake", False, "« Cake », c'est le gâteau. Tu vois un gâteau ? Non ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["kocc", "modou", "gainde"],
         "repliques": [r("kocc", "The nurse says: you should rest today.", "L'infirmière dit : tu devrais te reposer aujourd'hui."),
                       r("kocc", "Drink a lot of water.", "Bois beaucoup d'eau."),
                       r("modou", "And mangoes?", "Et les mangues ?"),
                       r("kocc", "You shouldn't eat ten mangoes!", "Tu ne devrais pas manger dix mangues !")],
         "gainde": "« Rest »… c'est le reste ? Il faut manger le reste du riz ? Miam !"},
        [q("L'infirmière dit « You should rest ». Modou doit…", ["se reposer", "courir", "manger le reste"], 0, 0),
         q("Modou doit boire beaucoup…", ["d'eau", "de bissap", "de lait"], 0, 1)],
        [choix("Je redis le conseil à Modou. Je dis laquelle ?", ["You should to rest.", "You should rest."], 1,
               aides("Kocc Barma dit « should to » ?", 0, "Écoute le conseil :",
                     "Moi, je dis : « You should rest. »",
                     "Après « should », pas de « to ». You should rest = tu devrais te reposer.")),
         ordre("« Drink of water a lot. » C'est ça ?", ["of", "a", "water", "Drink", "lot"], "Drink a lot of water",
               "Drink a lot of water.",
               aides("Qu'est-ce que Kocc Barma dit juste après « Drink » ?", 1, "Écoute Kocc Barma :",
                     "Moi, je dis : « Drink a lot of water. »",
                     "Drink (bois) + a lot of (beaucoup de) + water (eau).")),
         trou("Je veux dire « tu ne devrais pas ». « You ___ eat ten mangoes! »", "You", "eat ten mangoes!",
              ["shouldn't", "shouldnt", "should not"], "You shouldn't eat ten mangoes!",
              aides("Qu'est-ce que Kocc Barma dit à la fin ?", 3, "Écoute Kocc Barma :",
                    "Moi, je dis : « You shouldn't eat ten mangoes! »",
                    "« Shouldn't », c'est « tu ne devrais pas ». Écris : shouldn't.")),
         libre("Modou est fatigué. Je lui redis le conseil de l'infirmière. Comment je dis ?", ["rest|sleep"],
               aides("Quel est le premier conseil de l'infirmière ?", 0, "Écoute Kocc Barma :",
                     "Moi, je dis : « You should rest. »",
                     "Rest = se reposer. Écris : « You should rest. »"))],
        [tour("kocc", "You've got a fever. What should you do?", "Tu as de la fièvre. Qu'est-ce que tu dois faire ?",
              ["rest|water|sleep|medicine"], "I should rest and drink a lot of water.", "Yes! Very good!"),
         tour("modou", "I'm very tired. What should I do?", "Je suis très fatigué. Je dois faire quoi ?",
              ["rest|sleep"], "You should rest.", "OK! Thank you!")],
        ["You should rest.", "Drink a lot of water.", "You shouldn't…", "medicine"],
    ),
    mission(
        "5e-u5-m4", "Je sais nager !", "dire ce que je sais faire ou pas",
        ["I can swim.", "I can't ride a bike.", "Can you swim?"],
        {"consigne": "Au bord de l'eau. Quels mots vont avec l'image ?", "fond": "mer",
         "objets": ["🌊", "🏊", "🛶", "🐟"],
         "liste": [
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("swim", True, "Oui ! « Swim », c'est nager."),
             mot("boat", True, "Oui ! « Boat », c'est la pirogue, le bateau."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("bike", False, "« Bike », c'est le vélo. On ne roule pas dans l'eau ! Regarde encore."),
             mot("car", False, "« Car », c'est la voiture. Tu vois une voiture ? Non ! Regarde encore."),
         ]},
        {"fond": "mer", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Can you swim, Awa?", "Tu sais nager, Awa ?"),
                       r("awa", "Yes, I can swim! And you?", "Oui, je sais nager ! Et toi ?"),
                       r("modou", "I can swim, but I can't ride a bike.", "Je sais nager, mais je ne sais pas faire du vélo.")],
         "gainde": "Moi, je sais rugir. Je sais manger. Mais nager… les lions n'aiment pas l'eau !"},
        [q("Awa sait nager ?", ["Oui", "Non"], 0, 1),
         q("Modou ne sait pas…", ["faire du vélo", "nager", "danser"], 0, 2)],
        [choix("Je veux dire « je sais nager ». Je dis laquelle ?", ["I know swim.", "I can swim."], 1,
               aides("Awa dit « I know » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « I can swim. »",
                     "Pour dire « je sais faire », on dit « I can ». I can swim = je sais nager.")),
         ordre("« Can swim you? » C'est ça ?", ["swim", "you", "Can"], "Can you swim", "Can you swim?",
               aides("Qu'est-ce que Modou demande à Awa ?", 0, "Écoute Modou :",
                     "Moi, je demande : « Can you swim? »",
                     "Can (sais-) + you (tu) + swim (nager) ?")),
         trou("Je ne sais pas faire du vélo. « I ___ ride a bike. »", "I", "ride a bike.",
              ["can't", "cant", "cannot", "can not"], "I can't ride a bike.",
              aides("Comment Modou dit-il ce qu'il ne sait pas faire ?", 2, "Écoute Modou :",
                    "Moi, je dis : « I can't ride a bike. »",
                    "« Can't », c'est « je ne sais pas ». Écris : can't.")),
         libre("Je veux dire que je ne sais pas nager. Comment je dis ?", ["cant|cannot|can not", "swim"],
               aides("Comment Modou dit-il « je ne sais pas » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « I can't swim. »",
                     "Can = je sais. Can't = je ne sais pas. Écris : « I can't swim. »"))],
        [tour("awa", "Can you swim?", "Tu sais nager ?", ["yes|no|can|cant"], "Yes, I can!",
              "Great! Let's go to the river!"),
         tour("modou", "What can you do? Tell me!", "Qu'est-ce que tu sais faire ? Dis-moi !", ["can|cant|cannot"],
              "I can dance and I can play football.", "Cool! I can play football too!")],
        ["I can swim.", "I can't ride a bike.", "Can you swim?"],
    ),
    mission(
        "5e-u5-m5", "Je peux sortir ?", "demander la permission",
        ["Can I go out, please?", "Yes, you can.", "No, you can't."],
        {"consigne": "Le soir, chez grand-mère. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🚪", "🍚", "🌙", "🏠"],
         "liste": [
             mot("door", True, "Oui ! « Door », c'est la porte."),
             mot("rice", True, "Oui ! « Rice », c'est le riz du dîner."),
             mot("moon", True, "Oui ! « Moon », c'est la lune. C'est le soir."),
             mot("house", True, "Oui ! « House », c'est la maison de grand-mère."),
             mot("school", False, "« School », c'est l'école. C'est les vacances ! Regarde encore."),
             mot("sea", False, "« Sea », c'est la mer. On est à la maison. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["awa", "kocc", "modou"],
         "repliques": [r("awa", "Can I go out, please?", "Je peux sortir, s'il vous plaît ?"),
                       r("kocc", "Yes, you can.", "Oui, tu peux."),
                       r("modou", "Can I go out too, please?", "Je peux sortir aussi, s'il vous plaît ?"),
                       r("kocc", "No, you can't. Eat your rice first!", "Non, tu ne peux pas. Mange d'abord ton riz !")],
         "gainde": "Grand-mère dort, Kocc Barma garde la maison. Ils demandent avant de sortir ? Moi, je sors par la fenêtre !"},
        [q("Kocc Barma dit oui à…", ["Awa", "Modou", "Gaïndé"], 0, 1),
         q("Pourquoi Modou ne peut pas sortir ?", ["Il doit manger son riz.", "Il est malade.", "Il pleut."], 0, 3)],
        [choix("Je veux sortir. Je demande à Kocc Barma. Je dis laquelle ?",
               ["I can go out, please?", "Can I go out, please?"], 1,
               aides("Awa commence par « I can » ou par « Can I » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Can I go out, please? »",
                     "Pour demander, on commence par « Can I… ? » : est-ce que je peux… ?")),
         ordre("« Go out can I, please? » C'est ça ?", ["please", "out", "I", "go", "Can"], "Can I go out please",
               "Can I go out, please?",
               aides("Quel mot Awa dit-elle en premier ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Can I go out, please? »",
                     "Can I (je peux) + go out (sortir) + please (s'il te plaît).")),
         trou("Modou veut sortir. Kocc Barma dit non : « No, you ___. »", "No, you", ".",
              ["can't", "cant", "cannot", "can not"], "No, you can't.",
              aides("Qu'est-ce que Kocc Barma répond à Modou ?", 3, "Écoute Kocc Barma :",
                    "Moi, je dis : « No, you can't. »", "« You can't », c'est « tu ne peux pas ». Écris : can't.")),
         libre("J'ai soif. Je demande si je peux boire de l'eau. Comment je dis ?", ["can i", "water"],
               aides("Comment Awa commence-t-elle sa question ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Can I drink some water, please? »",
                     "Can I… ? = je peux… ? Écris : « Can I drink some water, please? »"))],
        [tour("kocc", "Yes? What do you want?", "Oui ? Tu veux quoi ? (Demande si tu peux sortir.)", ["can i"],
              "Can I go out, please?", "Yes, you can. Come back before dinner!"),
         tour("modou", "Can I play with your ball?", "Je peux jouer avec ton ballon ?", ["yes|no|can|cant"],
              "Yes, you can!", "Thank you! Let's play!")],
        ["Can I go out, please?", "Yes, you can.", "No, you can't."],
    ),
]

unite5 = unite(
    "5e-u5", "How do you feel?",
    "Chez l'infirmière : écris un petit dialogue entre un malade et l'infirmière.",
    u5,
    lignes=[
        ("Dire comment je me sens", "How do you feel? · I feel sad. · I'm happy / tired / scared."),
        ("Dire où j'ai mal", "What's wrong? · I've got a headache. · My stomach hurts. · I've got a fever."),
        ("Comprendre un conseil", "You should rest. · Drink a lot of water. · You shouldn't…"),
        ("Dire ce que je sais faire", "I can swim. · I can't ride a bike. · Can you swim?"),
        ("Demander la permission", "Can I go out, please? — Yes, you can. / No, you can't."),
    ],
    mots=[
        ("happy", "content", "bég"),
        ("sad", "triste", "tiis"),
        ("tired", "fatigué", "sonn"),
        ("scared", "avoir peur", "ragal"),
        ("angry", "en colère", "mer"),
        ("headache", "mal de tête", "metitu bopp"),
        ("stomach", "ventre", "biir"),
        ("medicine", "médicament", "garab"),
        ("rest", "se reposer", "noppalu"),
        ("swim", "nager", "féey"),
        ("water", "eau", "ndox"),
    ],
    pieges=[
        "I'm scared. Pas « I have fear ».",
        "I've got a headache. Pas « I have bad at my head ».",
        "I can swim. Pas « I know swim ».",
    ],
    exercices=[
        ex("Tu as peur. Tu dis :", ["I have fear.", "I'm scared.", "I'm fear.", "I scared."], 1,
           "Avoir peur : I'm scared."),
        ex("« I feel tired » veut dire :", ["Je me sens fatigué.", "J'ai faim.", "Je suis content.", "J'ai froid."], 0,
           "I feel = je me sens. Tired = fatigué."),
        ex("Tu as mal à la tête. Tu dis :", ["I've got a headache.", "I have bad at my head.", "My head is bad.", "I've got a head."], 0,
           "Mal à la tête : a headache."),
        ex("Complète : « My stomach ____. »", ["hurts", "hurt me", "is bad to", "pains me"], 0,
           "My stomach hurts = j'ai mal au ventre."),
        ex("L'infirmière dit « You should rest ». Tu dois :", ["te reposer", "courir", "manger le reste", "aller à l'école"], 0,
           "Rest = se reposer."),
        ex("« Drink a lot of water » veut dire :", ["Bois beaucoup d'eau.", "Bois un peu d'eau.", "Ne bois pas d'eau.", "Achète de l'eau."], 0,
           "A lot of = beaucoup de."),
        ex("Tu sais nager. Tu dis :", ["I know swim.", "I can swim.", "I can to swim.", "I swim can."], 1,
           "Je sais nager : I can swim."),
        ex("Tu ne sais pas faire du vélo :", ["I can't ride a bike.", "I don't can ride a bike.", "I not can ride a bike.",
                                              "I can ride not a bike."], 0,
           "Je ne sais pas : I can't."),
        ex("Tu veux sortir. Tu demandes :", ["I can go out?", "Can I go out, please?", "Go out, please!", "I go out, OK?"], 1,
           "Pour demander : Can I… ? et « please »."),
        ex("Ta maman dit non. Elle dit :", ["No, you can't.", "No, you don't.", "No, I can't.", "No, you aren't."], 0,
           "Non, tu ne peux pas : No, you can't."),
    ],
)

# ======================= UNITÉ 6 : KEEP IN TOUCH =======================

u6 = [
    mission(
        "5e-u6-m1", "Le SMS de Modou", "écrire un SMS",
        ["Hi! How r u?", "I'm fine, thx!", "C U soon!"],
        {"consigne": "Awa a un message. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["📱", "💬", "😀"],
         "liste": [
             mot("phone", True, "Oui ! « Phone », c'est le téléphone."),
             mot("message", True, "Oui ! « Message », c'est le message, le SMS."),
             mot("smile", True, "Oui ! « Smile », c'est le sourire."),
             mot("girl", True, "Oui ! « Girl », c'est une fille. C'est Awa."),
             mot("letter", False, "« Letter », c'est une lettre sur du papier. Ici, c'est un téléphone ! Regarde encore."),
             mot("stamp", False, "« Stamp », c'est le timbre. Pas de timbre pour un SMS ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Hi Awa! How r u?", "Salut Awa ! Ça va ? (SMS de Modou, rentré à Dakar)"),
                       r("awa", "I'm fine, thx! And u?", "Ça va, merci ! Et toi ?"),
                       r("modou", "Fine! C U soon!", "Ça va ! À bientôt !")],
         "gainde": "« r », « u », « C U »… Ils ont oublié des lettres ? Le téléphone est cassé ?"},
        [q("« How r u? » veut dire…", ["Ça va ?", "Tu es où ?", "Tu as quel âge ?"], 0, 0),
         q("« C U soon! » veut dire…", ["À bientôt !", "Ça va !", "Merci !"], 0, 2)],
        [choix("En français, j'écris « Slt ! Cv ? ». En anglais, je tape laquelle ?", ["Slt! Cv?", "Hi! How r u?"], 1,
               aides("Modou écrit son SMS en français ou en anglais ?", 0, "Écoute le SMS de Modou :",
                     "Moi, j'écris : « Hi! How r u? »",
                     "En SMS, « r » = are et « u » = you. How r u? = How are you?")),
         ordre("« Soon C U! » C'est ça ?", ["soon", "U", "C"], "C U soon", "C U soon!",
               aides("Comment Modou finit-il son SMS ?", 2, "Écoute Modou :",
                     "Moi, j'écris : « C U soon! »",
                     "C U = see you (on se voit). Soon = bientôt.")),
         trou("Je veux écrire « merci » en court. « I'm fine, ___! »", "I'm fine,", "!",
              ["thx", "thanks", "thank you", "thank u", "ty"], "I'm fine, thx!",
              aides("Comment Awa écrit-elle « merci » ?", 1, "Écoute la réponse d'Awa :",
                    "Moi, j'écris : « I'm fine, thx! »",
                    "« Thx », c'est « thanks » (merci) en SMS. Écris : thx.")),
         libre("J'écris à Awa « Salut ! Ça va ? » en SMS anglais. Comment j'écris ?",
               ["hi|hello|hey", "how r u|how are you|how are u|how r you"],
               aides("Comment Modou commence-t-il son SMS ?", 0, "Écoute Modou :",
                     "Moi, j'écris : « Hi Awa! How r u? »",
                     "Hi = salut. How r u? = ça va ? Écris : « Hi Awa! How r u? »"))],
        [tour("modou", "Hi! How r u? :)", "Salut ! Ça va ? :)", ["fine|good|ok|great|gr8"],
              "I'm fine, thx! And u?", "Gr8! C U soon!"),
         tour("awa", "Bye! C U soon!", "Salut ! À bientôt !", ["bye|c u|cu|see you|see u"], "Bye! C U soon!", "C U! :)")],
        ["How r u?", "thx", "C U soon!", "u = you"],
    ),
    mission(
        "5e-u6-m2", "Une lettre pour Awa", "écrire une lettre à un ami",
        ["Dear Awa,", "I hope you are well.", "See you soon!", "Love, Fatou"],
        {"consigne": "Une lettre arrive au village. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["✉️", "📝", "🖊️"],
         "liste": [
             mot("letter", True, "Oui ! « Letter », c'est la lettre."),
             mot("envelope", True, "Oui ! « Envelope », c'est l'enveloppe."),
             mot("paper", True, "Oui ! « Paper », c'est le papier."),
             mot("pen", True, "Oui ! « Pen », c'est le stylo."),
             mot("phone", False, "« Phone », c'est le téléphone. Ici, c'est une lettre sur du papier ! Regarde encore."),
             mot("computer", False, "« Computer », c'est l'ordinateur. Tu en vois un ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["kocc", "awa", "gainde"],
         "repliques": [r("kocc", "Awa, a letter for you!", "Awa, une lettre pour toi !"),
                       r("awa", "It's from Fatou! « Dear Awa, I hope you are well. »",
                         "C'est de Fatou ! « Chère Awa, j'espère que tu vas bien. »"),
                       r("awa", "« See you soon! Love, Fatou. »", "« À bientôt ! Bisous, Fatou. »")],
         "gainde": "« Dear » ? Mais « cher », c'est « expensive » ! Elle a coûté cher, cette lettre ?"},
        [q("La lettre commence par…", ["Dear Awa,", "Hi! How r u?", "Good morning, Sir!"], 0, 1),
         q("« Love, Fatou », c'est…", ["la fin de la lettre", "le début de la lettre", "l'adresse"], 0, 2)],
        [choix("Je commence ma lettre à Awa. J'écris laquelle ?", ["Expensive Awa,", "Dear Awa,"], 1,
               aides("Comment commence la lettre de Fatou ?", 1, "Écoute Awa :",
                     "Moi, j'écris : « Dear Awa, »",
                     "Dans une lettre, « cher » se dit « dear ». « Expensive », c'est cher pour un prix !")),
         ordre("« I hope you go well. » Comme en français ? Non… Aide-moi !",
               ["well", "hope", "are", "I", "you"], "I hope you are well", "I hope you are well.",
               aides("Fatou écrit « you go well » ?", 1, "Écoute la lettre :",
                     "Moi, j'écris : « I hope you are well. »",
                     "En anglais, on « est » bien : you are well = tu vas bien.")),
         trou("Je finis ma lettre. « ___, Gaïndé » J'écris « Kisses » ?", "", ", Gaïndé",
              ["love", "best wishes"], "Love, Gaïndé",
              aides("Comment Fatou finit-elle sa lettre ?", 2, "Écoute la fin :",
                    "Fatou écrit : « Love, Fatou. »",
                    "À un ami, on finit par « Love » (bisous). Écris : Love.")),
         libre("J'écris à Modou : « Cher Modou, j'espère que tu vas bien. » Comment j'écris ?", ["dear", "hope"],
               aides("Comment commence la lettre de Fatou ?", 1, "Écoute Awa :",
                     "Moi, j'écris : « Dear Modou, I hope you are well. »",
                     "Dear = cher. I hope = j'espère. Écris : « Dear Modou, I hope you are well. »"))],
        [tour("awa", "Write a letter to me! The start and the end.", "Écris-moi une lettre ! Le début et la fin.",
              ["dear", "love|best wishes|see you|bye"],
              "Dear Awa, I hope you are well. See you soon! Love, Gaïndé", "Thank you! What a nice letter!")],
        ["Dear…,", "I hope you are well.", "See you soon!", "Love,", "Best wishes,"],
    ),
    mission(
        "5e-u6-m3", "Il fait chaud, n'est-ce pas ?", "demander « n'est-ce pas ? »",
        ["It's hot today, isn't it?", "You're coming, aren't you?", "Yes, it is."],
        {"consigne": "Il fait très chaud au village. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["☀️", "🥵", "🌳", "💧"],
         "liste": [
             mot("sun", True, "Oui ! « Sun », c'est le soleil."),
             mot("hot", True, "Oui ! « Hot », c'est chaud. Il fait très chaud !"),
             mot("tree", True, "Oui ! « Tree », c'est l'arbre. On se met à l'ombre."),
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("rain", False, "« Rain », c'est la pluie. Il ne pleut pas aujourd'hui ! Regarde encore."),
             mot("cold", False, "« Cold », c'est froid. Il fait chaud ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "doudou", "gainde"],
         "repliques": [r("awa", "It's hot today, isn't it?", "Il fait chaud aujourd'hui, n'est-ce pas ?"),
                       r("doudou", "Yes, it is! Very hot!", "Oh oui ! Très chaud !"),
                       r("doudou", "You're coming to the party, aren't you?", "Tu viens à la fête, n'est-ce pas ?"),
                       r("awa", "Yes, of course!", "Oui, bien sûr !")],
         "gainde": "Moi, je dis juste « It's hot, no? ». C'est pareil, non ?"},
        [q("Awa dit qu'il fait…", ["chaud", "froid", "nuit"], 0, 0),
         q("Doudou demande si Awa vient…", ["à la fête", "au marché", "à l'école"], 0, 2)],
        [choix("Il fait chaud. Je veux que Doudou soit d'accord. Je dis laquelle ?",
               ["It's hot today, no?", "It's hot today, isn't it?"], 1,
               aides("Comment Awa finit-elle sa phrase ?", 0, "Écoute Awa :",
                     "Moi, je dis : « It's hot today, isn't it? »",
                     "« Isn't it? », c'est « n'est-ce pas ? ». « No? », ça ne va pas.")),
         ordre("« You're coming, isn't it? » Non… Aide-moi !", ["you", "coming", "aren't", "You're"],
               "Youre coming arent you", "You're coming, aren't you?",
               aides("Doudou dit « isn't it » ou « aren't you » ?", 2, "Écoute Doudou :",
                     "Moi, je dis : « You're coming, aren't you? »",
                     "Avec « You're », on finit par « aren't you? ».")),
         trou("« It's hot, ___ it? » Il me manque un mot !", "It's hot,", "it?", ["isn't", "isnt", "is not"],
              "It's hot, isn't it?",
              aides("Qu'est-ce qu'Awa dit après « today » ?", 0, "Écoute Awa :",
                    "Moi, je dis : « It's hot today, isn't it? »",
                    "Avec « It's », on finit par « isn't it? ». Écris : isn't.")),
         libre("Il fait beau aujourd'hui. Je veux qu'Awa soit d'accord. Comment je dis ?", ["isnt it"],
               aides("Comment Awa finit-elle sa phrase sur la chaleur ?", 0, "Écoute Awa :",
                     "Moi, je dis : « It's sunny today, isn't it? »",
                     "Il fait beau = It's sunny. Écris : « It's sunny today, isn't it? »"))],
        [tour("doudou", "It's very hot today, isn't it?", "Il fait très chaud aujourd'hui, n'est-ce pas ?",
              ["yes|no"], "Yes, it is!", "Let's drink some bissap!"),
         tour("awa", "You like thieboudienne, don't you?", "Tu aimes le thiéboudienne, n'est-ce pas ?",
              ["yes|no"], "Yes, I do!", "Me too! Grandma's is the best!")],
        ["It's hot today, isn't it?", "You're coming, aren't you?", "Yes, it is."],
    ),
    mission(
        "5e-u6-m4", "La fête de fin de vacances", "inviter un ami, dire oui ou non",
        ["Would you like to come?", "Yes, I'd love to!", "Sorry, I can't."],
        {"consigne": "On prépare la fête. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🎉", "🥁", "🎂", "🎁"],
         "liste": [
             mot("party", True, "Oui ! « Party », c'est la fête."),
             mot("music", True, "Oui ! « Music », c'est la musique."),
             mot("drum", True, "Oui ! « Drum », c'est le tambour, le tama de Doudou."),
             mot("cake", True, "Oui ! « Cake », c'est le gâteau."),
             mot("present", True, "Oui ! « Present », c'est le cadeau."),
             mot("homework", False, "« Homework », ce sont les devoirs. Pas de devoirs à la fête ! Regarde encore."),
             mot("rain", False, "« Rain », c'est la pluie. Il fait beau ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "doudou", "kocc"],
         "repliques": [r("awa", "We have a party tonight. Would you like to come?", "On fait une fête ce soir. Tu veux venir ?"),
                       r("doudou", "Yes, I'd love to! I can bring my tama.", "Oui, avec plaisir ! Je peux apporter mon tama."),
                       r("awa", "Kocc Barma, would you like to come?", "Kocc Barma, vous voulez venir ?"),
                       r("kocc", "Sorry, I can't. I'm at the health post.", "Désolé, je ne peux pas. Je suis au poste de santé.")],
         "gainde": "Une fête ?! Personne ne m'invite… mais je viens quand même !"},
        [q("Doudou répond…", ["Oui, avec plaisir !", "Non, désolé.", "Je ne sais pas."], 0, 1),
         q("Pourquoi Kocc Barma ne vient pas ?", ["Il est au poste de santé.", "Il est malade.", "Il dort."], 0, 3)],
        [choix("J'invite Awa à la fête. Je dis laquelle ?",
               ["You want come to the party?", "Would you like to come to the party?"], 1,
               aides("Comment Awa invite-t-elle Doudou ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Would you like to come? »",
                     "« Would you like to… ? », c'est la façon polie d'inviter.")),
         ordre("« Yes, I'd love! » Il manque un mot, non ? Remets tout dans l'ordre.",
               ["love", "Yes", "to", "I'd"], "Yes Id love to", "Yes, I'd love to!",
               aides("Écoute bien la fin de la réponse de Doudou.", 1, "Écoute Doudou :",
                     "Moi, je dis : « Yes, I'd love to! »",
                     "On finit par « to » : I'd love to = avec plaisir.")),
         trou("Je ne peux pas venir. « Sorry, I ___. »", "Sorry, I", ".", ["can't", "cant", "cannot", "can not"],
              "Sorry, I can't.",
              aides("Qu'est-ce que Kocc Barma répond à Awa ?", 3, "Écoute Kocc Barma :",
                    "Moi, je dis : « Sorry, I can't. »",
                    "« Sorry » = désolé. « I can't » = je ne peux pas. Écris : can't.")),
         libre("J'invite Modou à ma fête. Comment je dis ?", ["would you like"],
               aides("Comment Awa commence-t-elle son invitation ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Would you like to come to my party? »",
                     "Would you like to come? = tu veux venir ? Écris : « Would you like to come to my party? »"))],
        [tour("awa", "Would you like to come to my party?", "Tu veux venir à ma fête ?",
              ["love to|yes|sorry|cant|cannot|no"], "Yes, I'd love to!", "Great! See you tonight!"),
         tour("doudou", "Invite me to your party!", "Invite-moi à ta fête !", ["would you like"],
              "Would you like to come to my party?", "Yes, I'd love to! I can bring my tama!")],
        ["Would you like to come?", "Yes, I'd love to!", "Sorry, I can't.", "party"],
    ),
]

unite6 = unite(
    "5e-u6", "Keep in touch",
    "Ma lettre : écris une lettre ou un SMS pour inviter un ami.",
    u6,
    lignes=[
        ("Écrire un SMS", "Hi! How r u? · I'm fine, thx! · C U soon!"),
        ("Écrire une lettre", "Dear Awa, · I hope you are well. · Love, Fatou"),
        ("Demander « n'est-ce pas ? »", "It's hot today, isn't it? · You're coming, aren't you?"),
        ("Inviter, dire oui ou non", "Would you like to come? — Yes, I'd love to! / Sorry, I can't."),
    ],
    mots=[
        ("friend", "ami(e)", "xarit"),
        ("letter", "lettre", "bataaxal"),
        ("party", "fête", "xew"),
        ("guest", "invité", "gan"),
        ("song", "chanson", "woy"),
        ("hot", "chaud", "tàng"),
        ("come", "venir", "ñëw"),
        ("invite", "inviter", "woo"),
        ("love", "amour", "mbëggeel"),
        ("thank you", "merci", "jërëjëf"),
    ],
    pieges=[
        "Dear Awa = Chère Awa. Pas « Expensive Awa ».",
        "I hope you are well. Pas « I hope you go well ».",
        "Yes, I'd love to! N'oublie pas « to » à la fin.",
    ],
    exercices=[
        ex("« How r u? » veut dire :", ["How are you?", "Where are you?", "Who are you?", "How old are you?"], 0,
           "En SMS : r = are, u = you."),
        ex("« C U soon! » veut dire :", ["À bientôt !", "Ça va ?", "Merci !", "Bonne nuit !"], 0,
           "C U soon = see you soon = à bientôt."),
        ex("Tu commences une lettre à Awa :", ["Expensive Awa,", "Dear Awa,", "Hello Madam Awa,", "Love Awa,"], 1,
           "Dans une lettre : Dear… (cher, chère)."),
        ex("« J'espère que tu vas bien » :", ["I hope you go well.", "I hope you are well.", "I hope you well.",
                                              "I hope are you well."], 1,
           "Aller bien : to be well. I hope you are well."),
        ex("Tu finis une lettre à un ami :", ["Love, Fatou", "Dear, Fatou", "Hello, Fatou", "Good morning, Fatou"], 0,
           "À la fin : Love, … ou Best wishes, …"),
        ex("Complète : « It's hot today, ____ it? »", ["isn't", "aren't", "is", "don't"], 0,
           "It's… isn't it?"),
        ex("Complète : « You're coming, ____ you? »", ["isn't", "aren't", "are", "don't"], 1,
           "You're… aren't you?"),
        ex("Tu invites un ami poliment :", ["Would you like to come?", "You come?", "Come, you!", "Do you like come?"], 0,
           "Pour inviter : Would you like to come?"),
        ex("Tu dis oui à l'invitation :", ["Yes, I'd love to!", "Yes, I'd love!", "Yes, I would love!", "Yes, I'd like!"], 0,
           "Avec plaisir : Yes, I'd love to! (avec « to »)."),
        ex("Tu ne peux pas venir. Tu dis :", ["Sorry, I can't.", "Sorry, I don't.", "Sorry, I'm not.", "Sorry, you can't."], 0,
           "Désolé, je ne peux pas : Sorry, I can't."),
    ],
)

UNITES = [unite4, unite5, unite6]

# ======================= LES ÉPISODES (pendant le séjour au village) =======================

EPISODES = [
    episode("Plus grand que le bouc ?", "5e-u4-m2", [
        case("cour", [perso("gainde", 0.05, 100, "saute"), perso("bouc", 0.55, 85)], [
            bulle("I'm bigger than the goat!", "Je suis plus grand que le bouc !", 0.02, 0.04),
            bulle("Bêêê!", "Bêêê ! (le bouc se lève sur ses pattes de derrière : il est plus grand que Gaïndé)", 0.45, 0.32)]),
        case("cour", [perso("gainde", 0.05, 95), perso("modou", 0.6, 95)], [
            bulle("Hmm… OK. I'm faster than Modou!", "Hmm… D'accord. Je suis plus rapide que Modou !", 0.02, 0.04),
            bulle("No! I'm faster than you!", "Non ! Je suis plus rapide que toi !", 0.5, 0.32)]),
        case("terrain", [perso("modou", 0.05, 95, "saute"), perso("gainde", 0.6, 95, "tangue")], [
            bulle("I'm the fastest!", "Je suis le plus rapide !", 0.02, 0.04),
            bulle("Ouch!", "Aïe ! (Gaïndé court en regardant derrière lui… et fonce dans le baobab)", 0.5, 0.3)]),
        case("cour", [perso("awa", 0.05, 95), perso("gainde", 0.55, 100, "balance")], [
            bulle("Ha ha! The baobab is bigger than you!", "Ha ha ! Le baobab est plus grand que toi !", 0.02, 0.04),
            bulle("Yes… but its fruit is the best!", "Oui… mais son fruit est le meilleur ! (un fruit du baobab lui tombe sur la tête. Il le mange, tout content.)", 0.4, 0.34)]),
    ], ["bigger than", "faster than", "the fastest", "the best"]),

    episode("Grand-mère, la lutteuse", "5e-u4-m4", [
        case("maison", [perso("awa", 0.05, 95), perso("gainde", 0.55, 95)], [
            bulle("Grandma is old but strong.", "Grand-mère est vieille mais forte.", 0.02, 0.04),
            bulle("Old… but strong. OK!", "Vieille… mais forte. D'accord ! (il prend un crayon et dessine)", 0.45, 0.32)]),
        case("maison", [perso("gainde", 0.05, 100, "saute"), perso("awa", 0.6, 95)], [
            bulle("Look! She has got white hair and big glasses!", "Regarde ! Elle a les cheveux blancs et de grandes lunettes ! (sur le dessin, grand-mère a aussi des bras de lutteur)", 0.02, 0.04),
            bulle("Gaïndé!!!", "Gaïndé !!!", 0.55, 0.36)]),
        case("maison", [perso("modou", 0.05, 95, "danse"), perso("gainde", 0.55, 95)], [
            bulle("Ha ha! I agree! She's very strong!", "Ha ha ! Je suis d'accord ! Elle est très forte !", 0.02, 0.04),
            bulle("You're right!", "Tu as raison !", 0.5, 0.34)]),
        case("cour", [perso("awa", 0.05, 95), perso("gainde", 0.5, 100, "saute")], [
            bulle("You're right, Gaïndé. She's old but strong!", "Tu as raison, Gaïndé. Elle est vieille mais forte ! (grand-mère adore le dessin : elle soulève Gaïndé d'une seule main)", 0.02, 0.04),
            bulle("I agree… Help!", "Je suis d'accord… Au secours ! (il est tout en haut, dans les airs)", 0.45, 0.3)]),
    ], ["She's old but strong.", "She has got white hair.", "I agree!", "You're right!"]),

    episode("Gaïndé est très, très malade", "5e-u5-m2", [
        case("maison", [perso("awa", 0.05, 95), perso("gainde", 0.55, 95)], [
            bulle("Gaïndé, help Grandma, please!", "Gaïndé, aide grand-mère, s'il te plaît ! (il faut piler le mil)", 0.02, 0.04),
            bulle("Oh… I'm tired.", "Oh… je suis fatigué. (il se couche par terre)", 0.5, 0.34)]),
        case("maison", [perso("awa", 0.05, 95), perso("gainde", 0.55, 100, "balance")], [
            bulle("What's wrong? How do you feel?", "Qu'est-ce qui ne va pas ? Comment tu te sens ?", 0.02, 0.04),
            bulle("I've got a headache! And a fever! And my stomach hurts!", "J'ai mal à la tête ! Et de la fièvre ! Et j'ai mal au ventre ! (il met un bonnet, une écharpe et trois couvertures… alors qu'il fait 40 degrés)", 0.35, 0.3)]),
        case("maison", [perso("awa", 0.05, 95), perso("modou", 0.6, 95)], [
            bulle("OK. No thieboudienne for Gaïndé today…", "D'accord. Pas de thiéboudienne pour Gaïndé aujourd'hui…", 0.02, 0.04),
            bulle("Ha ha!", "Ha ha ! (Modou a compris le plan d'Awa)", 0.55, 0.34)]),
        case("maison", [perso("gainde", 0.3, 110, "saute")], [
            bulle("Thieboudienne?! I'm happy! I'm fine!", "Thiéboudienne ?! Je suis content ! Je vais bien ! (il pile tout le mil en trois secondes et court à table)", 0.05, 0.05)]),
    ], ["I'm tired.", "What's wrong?", "I've got a headache.", "My stomach hurts.", "I'm happy!"]),

    episode("Gaïndé sait nager… ou pas", "5e-u5-m4", [
        case("mer", [perso("gainde", 0.05, 100, "saute"), perso("awa", 0.6, 95)], [
            bulle("Look! I can swim!", "Regarde ! Je sais nager !", 0.02, 0.04),
            bulle("Gaïndé, you can't swim!", "Gaïndé, tu ne sais pas nager !", 0.5, 0.34)]),
        case("mer", [perso("kocc", 0.05, 95), perso("gainde", 0.55, 100, "saute")], [
            bulle("You shouldn't swim here, Gaïndé!", "Tu ne devrais pas nager ici, Gaïndé !", 0.02, 0.04),
            bulle("I can! I can!", "Je sais ! Je sais ! (il saute dans l'eau : PLOUF !)", 0.5, 0.32)]),
        case("mer", [perso("gainde", 0.1, 100, "tangue"), perso("awa", 0.6, 95)], [
            bulle("Help! I can't swim!", "Au secours ! Je ne sais pas nager !", 0.02, 0.04),
            bulle("Gaïndé… stand up!", "Gaïndé… lève-toi ! (l'eau lui arrive aux genoux)", 0.5, 0.34)]),
        case("mer", [perso("kocc", 0.05, 95), perso("gainde", 0.4, 100), perso("poisson", 0.72, 60, "saute")], [
            bulle("You should rest now.", "Tu devrais te reposer, maintenant.", 0.02, 0.04),
            bulle("I drank a lot of water…", "J'ai bu beaucoup d'eau…", 0.3, 0.3),
            bulle("Blub!", "Blub ! (un petit poisson sort de la bouche de Gaïndé)", 0.62, 0.08)]),
    ], ["I can swim!", "I can't swim!", "You shouldn't…", "You should rest."]),

    episode("Gaïndé demande la permission pour tout", "5e-u5-m5", [
        case("maison", [perso("gainde", 0.05, 95), perso("kocc", 0.6, 95)], [
            bulle("Can I sit down, please?", "Je peux m'asseoir, s'il vous plaît ?", 0.02, 0.04),
            bulle("Yes, you can.", "Oui, tu peux.", 0.55, 0.34)]),
        case("maison", [perso("gainde", 0.05, 95, "balance"), perso("kocc", 0.6, 95)], [
            bulle("Can I open my book, please? Can I close my book, please?", "Je peux ouvrir mon livre, s'il vous plaît ? Je peux fermer mon livre, s'il vous plaît ?", 0.02, 0.04),
            bulle("Yes… you can.", "Oui… tu peux. (une heure plus tard, Kocc Barma est très fatigué)", 0.5, 0.36)]),
        case("maison", [perso("gainde", 0.05, 100, "saute"), perso("kocc", 0.6, 95, "saute")], [
            bulle("Can I eat, please?", "Je peux manger, s'il vous plaît ?", 0.02, 0.04),
            bulle("YES! YOU CAN!", "OUI ! TU PEUX ! (Kocc Barma n'en peut plus)", 0.5, 0.32)]),
        case("maison", [perso("modou", 0.05, 95), perso("kocc", 0.35, 95), perso("gainde", 0.68, 105, "immobile")], [
            bulle("Can I eat too, please?", "Je peux manger aussi, s'il vous plaît ?", 0.02, 0.04),
            bulle("Hmm… No, you can't.", "Hmm… Non, tu ne peux pas. (le plat est vide : Gaïndé a tout mangé)", 0.3, 0.32),
            bulle("Zzz…", "Zzz… (Gaïndé dort, le ventre tout rond)", 0.62, 0.1)]),
    ], ["Can I…, please?", "Yes, you can.", "No, you can't."]),

    episode("Le SMS le plus long du monde", "5e-u6-m2", [
        case("maison", [perso("gainde", 0.05, 95), perso("awa", 0.6, 95)], [
            bulle("Dear Modou, I hope you are well…", "Cher Modou, j'espère que tu vas bien… (il tape un SMS avec une seule griffe)", 0.02, 0.04),
            bulle("Gaïndé! Write: Hi! How r u?", "Gaïndé ! C'est un SMS ! Écris : Salut ! Ça va ?", 0.45, 0.34)]),
        case("maison", [perso("gainde", 0.3, 100, "balance")], [
            bulle("I hope your mum is well. I hope your goat is well. I hope your ball is well… Love, Gaïndé.", "J'espère que ta maman va bien. J'espère que ta chèvre va bien. J'espère que ton ballon va bien… Bisous, Gaïndé. (trois heures plus tard…)", 0.03, 0.05)]),
        case("terrain", [perso("modou", 0.3, 100, "tangue")], [
            bulle("Gaïndé?! R u OK?", "Gaïndé ?! Ça va ?? (le téléphone de Modou reçoit 200 SMS. Il chauffe, il fume !)", 0.05, 0.05)]),
        case("maison", [perso("gainde", 0.05, 95), perso("awa", 0.6, 95, "saute")], [
            bulle("He writes: R u OK? Hmm… Dear Modou, I hope you are well…", "Il écrit : Ça va ? Hmm… Cher Modou, j'espère que tu vas bien… (il recommence !)", 0.02, 0.04),
            bulle("Nooo!", "Nooon !", 0.6, 0.36)]),
    ], ["Dear Modou,", "I hope you are well.", "Love, Gaïndé", "Hi! How r u?"]),

    episode("Le retour… avec deux invités", "5e-u6-m4", [
        case("cour", [perso("doudou", 0.02, 95, "danse"), perso("gainde", 0.35, 100, "danse2"), perso("awa", 0.68, 95)], [
            bulle("It's a great party, isn't it?", "C'est une super fête, n'est-ce pas ?", 0.5, 0.04),
            bulle("Yes, it is!", "Oh oui ! (Doudou joue du tama, tout le village danse)", 0.28, 0.36)]),
        case("cour", [perso("gainde", 0.05, 95), perso("bouc", 0.45, 80), perso("mouton", 0.72, 80)], [
            bulle("Would you like to come to Dakar with me?", "Vous voulez venir à Dakar avec moi ?", 0.02, 0.04),
            bulle("Bêêê!", "Bêêê ! (ça veut dire : « Yes, I'd love to! »)", 0.38, 0.36),
            bulle("Mêêê!", "Mêêê ! (moi aussi !)", 0.62, 0.14)]),
        case("nuit", [perso("awa", 0.05, 95), perso("gainde", 0.55, 95, "immobile")], [
            bulle("We're going home tomorrow, aren't we?", "On rentre demain, n'est-ce pas ?", 0.02, 0.04),
            bulle("Yes… I'm sad.", "Oui… je suis triste. (grand-mère lui donne un sac de mangues et un bisou sur la crinière. Il pleure un peu.)", 0.45, 0.34)]),
        case("classe", [perso("kocc", 0.05, 95), perso("gainde", 0.55, 100, "tangue")], [
            bulle("Hello, Gaïndé! You're happy, aren't you?", "Bonjour, Gaïndé ! Tu es content, n'est-ce pas ? (c'est la rentrée)", 0.02, 0.04),
            bulle("Yes! But sorry, I can't sit down…", "Oui ! Mais désolé, je ne peux pas m'asseoir… (son gros sac bouge tout seul)", 0.42, 0.34)]),
        case("classe", [perso("gainde", 0.05, 95, "saute"), perso("bouc", 0.45, 80, "saute"), perso("mouton", 0.72, 80, "danse")], [
            bulle("Kocc Barma, would you like to meet my friends?", "Kocc Barma, vous voulez rencontrer mes amis ? (le bouc et le mouton sortent du sac)", 0.02, 0.04),
            bulle("Bêêê!", "Bêêê !", 0.4, 0.38),
            bulle("Mêêê!", "Mêêê ! (toute la classe éclate de rire)", 0.62, 0.14)]),
    ], ["isn't it?", "aren't you?", "Would you like to come?", "Yes, I'd love to!", "Sorry, I can't."]),
]
