"""Parcours d'anglais de 5e, unités 1 à 3."""
from jang_lib import *  # noqa: F401,F403

NIVEAU = "5e"

# ======================= UNITÉ 1 : MY BIG FAMILY =======================

u1 = [
    mission(
        "5e-u1-m1", "Toute la famille à la gare routière", "parler de toute ma famille (cousins, oncles…)",
        ["She's my cousin.", "He's my uncle's son."],
        {"consigne": "À la gare routière du village. Quels mots vont avec l'image ?", "fond": "marche",
         "objets": ["🚌", "🧳", "👵🏾", "👨‍👩‍👧‍👦"],
         "liste": [
             mot("bus", True, "Oui ! « Bus », c'est le car. Il arrive au village."),
             mot("suitcase", True, "Oui ! « Suitcase », c'est la valise d'Awa."),
             mot("grandmother", True, "Oui ! « Grandmother », c'est la grand-mère. Elle attend Awa."),
             mot("family", True, "Oui ! « Family », c'est la famille. Toute la famille est là !"),
             mot("cousin", True, "Oui ! « Cousin », c'est le cousin ou la cousine. Il y en a plein ici !"),
             mot("plane", False, "« Plane », c'est l'avion. Il n'y a pas d'avion à la gare routière. Regarde encore !"),
             mot("teacher", False, "« Teacher », c'est le prof. C'est les vacances : pas d'école ! Regarde encore."),
             mot("snow", False, "« Snow », c'est la neige. Il fait chaud au village ! Regarde encore."),
         ]},
        {"fond": "marche", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Look! She's my cousin, Fatou.", "Regarde ! C'est ma cousine, Fatou."),
                       r("modou", "And the tall boy? Who is he?", "Et le grand garçon ? C'est qui ?"),
                       r("awa", "He's my uncle's son. He's my cousin too!", "C'est le fils de mon oncle. C'est mon cousin aussi !")],
         "gainde": "Le fils de son oncle, c'est son cousin ? Et le fils de son cousin, c'est quoi ? Ma tête tourne !"},
        [q("Fatou, c'est qui ?", ["la tante d'Awa", "la cousine d'Awa", "la sœur d'Awa"], 1, 0),
         q("« My uncle's son », c'est…", ["le fils de mon oncle", "mon oncle", "mon fils"], 0, 2)],
        [choix("Je veux dire : « C'est le fils de mon oncle. » Je dis laquelle ?",
               ["He's the son of the uncle of me.", "He's my uncle's son."], 1,
               aides("Awa a dit « my uncle… », et après ?", 2, "Écoute Awa :",
                     "Moi, je dis : « She's my aunt's daughter. »",
                     "En anglais, on dit d'abord à qui : my uncle's son = le fils de mon oncle.")),
         ordre("« Cousin my she's. » C'est bien ça ?", ["cousin", "She's", "my"], "Shes my cousin",
               "She's my cousin.",
               aides("Quel mot Awa dit-elle en premier ?", 0, "Écoute Awa :",
                     "Moi, je dis : « She's my cousin. »",
                     "She's (c'est elle) + my cousin (ma cousine).")),
         trou("« He's my uncle's ___. » (le fils) Il me manque un mot !", "He's my uncle's", ".", ["son"],
              "He's my uncle's son.",
              aides("Comment dit-on « fils » ?", 2, "Écoute Awa :",
                    "Moi, je dis : « He's my uncle's son. »", "« Fils », c'est « son ». Écris : son.")),
         libre("Fatou est ma cousine. Dis-le à Modou !", ["cousin"],
               aides("Comment Awa présente-t-elle Fatou ?", 0, "Écoute Awa :",
                     "Moi, je dis : « She's my cousin. »", "Cousine = cousin. Écris : « She's my cousin. »"))],
        [tour("awa", "Who is he? (le fils de ton oncle)", "C'est qui ? (le fils de ton oncle)",
              ["uncles son|cousin"], "He's my uncle's son.", "Oh, he's your cousin! Nice!"),
         tour("modou", "Who is she? (la fille de ta tante)", "C'est qui ? (la fille de ta tante)",
              ["aunts daughter|cousin"], "She's my cousin.", "Hello, cousin!")],
        ["She's my cousin.", "He's my uncle's son.", "uncle · aunt", "nephew · niece", "grandson · granddaughter"],
    ),
    mission(
        "5e-u1-m2", "Je te présente…", "présenter un ami à un adulte",
        ["Let me introduce my cousin.", "Pleased to meet you."],
        {"consigne": "Dans la cour de grand-mère. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🌳", "🫖", "🪑", "🐐"],
         "liste": [
             mot("tree", True, "Oui ! « Tree », c'est l'arbre de la cour."),
             mot("teapot", True, "Oui ! « Teapot », c'est la théière, pour l'attaya."),
             mot("chair", True, "Oui ! « Chair », c'est la chaise."),
             mot("goat", True, "Oui ! « Goat », c'est la chèvre de grand-mère."),
             mot("boat", False, "« Boat », c'est le bateau. Il n'y a pas d'eau dans la cour ! Regarde encore."),
             mot("board", False, "« Board », c'est le tableau de la classe. On est en vacances ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "kocc", "modou"],
         "repliques": [r("awa", "Good afternoon, Kocc Barma! Let me introduce my friend Modou.",
                         "Bonjour, Kocc Barma ! Je vous présente mon ami Modou."),
                       r("kocc", "Pleased to meet you, Modou.", "Enchanté, Modou."),
                       r("modou", "Pleased to meet you too, Sir.", "Enchanté aussi, Monsieur.")],
         "gainde": "« Let me introduce »… C'est poli, ça ! Moi aussi, je veux présenter mes amis !"},
        [q("Awa présente Modou à qui ?", ["à Kocc Barma", "à sa cousine", "à Gaïndé"], 0, 0),
         q("« Pleased to meet you », ça veut dire…", ["Au revoir", "Bon appétit", "Enchanté"], 2, 1)],
        [choix("Je présente Modou à Kocc Barma. Je dis laquelle ?",
               ["Let me introduce my friend Modou.", "I present you my friend Modou."], 0,
               aides("Comment Awa commence-t-elle sa phrase ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Let me introduce my cousin. »",
                     "« Je te présente », en anglais, c'est « Let me introduce ». Pas « I present you ».")),
         ordre("« Meet pleased you to. » C'est bien ça ?", ["to", "Pleased", "you", "meet"], "Pleased to meet you",
               "Pleased to meet you.",
               aides("Quel mot Kocc Barma dit-il en premier ?", 1, "Écoute Kocc Barma :",
                     "Moi, je dis : « Pleased to meet you. »",
                     "Pleased (content) + to meet you (de te rencontrer).")),
         trou("« Let me ___ my cousin. » Il me manque un mot !", "Let me", "my cousin.", ["introduce"],
              "Let me introduce my cousin.",
              aides("Quel mot Awa dit-elle après « Let me » ?", 0, "Écoute Awa :",
                    "Moi, je dis : « Let me introduce my friend. »", "« Présenter », c'est « introduce ». Écris : introduce.")),
         libre("Je veux présenter mon cousin Ali à Kocc Barma. Comment je dis ?",
               ["introduce|this is|meet", "ali|cousin"],
               aides("Qu'est-ce qu'Awa dit pour présenter Modou ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Let me introduce my cousin Ali. »",
                     "Écris : « Let me introduce my cousin Ali. »"))],
        [tour("kocc", "Good afternoon! Who is this? (ton amie Awa)", "Bonjour ! C'est qui ? (ton amie Awa)",
              ["introduce|this is|meet"], "Let me introduce my friend Awa.", "Pleased to meet you, Awa!"),
         tour("doudou", "Hello! I'm Doudou, the griot of the village.", "Bonjour ! Je suis Doudou, le griot du village.",
              ["pleased to meet you|nice to meet you"], "Pleased to meet you, Doudou.", "Pleased to meet you too!")],
        ["Let me introduce my cousin.", "Pleased to meet you.", "Pleased to meet you too."],
    ),
    mission(
        "5e-u1-m3", "Qui aime quoi ?", "dire ce que j'aime faire et ce que je n'aime pas",
        ["I love dancing.", "I hate cooking.", "I don't mind…"],
        {"consigne": "Le soir, au village. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🥁", "💃🏾", "🍲", "📖"],
         "liste": [
             mot("drum", True, "Oui ! « Drum », c'est le tambour. C'est le tama de Doudou."),
             mot("dancing", True, "Oui ! « Dancing », c'est danser. Awa danse !"),
             mot("cooking", True, "Oui ! « Cooking », c'est faire la cuisine. Regarde la marmite."),
             mot("reading", True, "Oui ! « Reading », c'est lire. Il y a un livre."),
             mot("sleeping", False, "« Sleeping », c'est dormir. Personne ne dort : il y a la fête ! Regarde encore."),
             mot("driving", False, "« Driving », c'est conduire. Il n'y a pas de voiture ici. Regarde encore !"),
         ]},
        {"fond": "cour", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "I love dancing!", "J'adore danser !"),
                       r("awa", "But I hate cooking.", "Mais je déteste faire la cuisine."),
                       r("modou", "I don't mind cooking. I love eating!", "Ça m'est égal de faire la cuisine. J'adore manger !")],
         "gainde": "Awa adore danser. Modou adore manger. Et moi ? J'adore… tout !"},
        [q("Qu'est-ce qu'Awa déteste ?", ["danser", "faire la cuisine", "manger"], 1, 1),
         q("Modou dit « I don't mind cooking ». Ça veut dire…",
           ["Ça lui est égal de faire la cuisine.", "Il déteste la cuisine.", "Il ne sait pas cuisiner."], 0, 2)],
        [choix("Je veux dire : « J'aime beaucoup danser. » Je dis laquelle ?",
               ["I like very much dancing.", "I love dancing."], 1,
               aides("Comment Awa dit-elle qu'elle aime beaucoup danser ?", 0, "Écoute Awa :",
                     "Moi, je dis : « I love reading. »",
                     "« J'aime beaucoup », c'est « I love » : un seul mot, au début.")),
         ordre("« Cooking hate I. » C'est bien ça ?", ["cooking", "I", "hate"], "I hate cooking", "I hate cooking.",
               aides("Quel mot Awa dit-elle en premier ?", 1, "Écoute Awa :",
                     "Moi, je dis : « I hate cooking. »", "I (je) + hate (déteste) + cooking (faire la cuisine).")),
         trou("Ça m'est égal de faire la cuisine : « I don't ___ cooking. »", "I don't", "cooking.", ["mind"],
              "I don't mind cooking.",
              aides("Qu'est-ce que Modou dit après « I don't » ?", 2, "Écoute Modou :",
                    "Moi, je dis : « I don't mind cooking. »", "« Ça m'est égal », c'est « I don't mind ». Écris : mind.")),
         libre("Dis que tu adores chanter.", ["love|like", "singing|sing"],
               aides("Comment Awa dit-elle « J'adore danser » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « I love singing. »", "Chanter = singing. Écris : « I love singing. »"))],
        [tour("modou", "What do you love doing?", "Qu'est-ce que tu adores faire ?",
              ["love|like|enjoy"], "I love dancing!", "Cool! I love eating!"),
         tour("awa", "Do you like cooking?", "Tu aimes faire la cuisine ?",
              ["love|like|hate|mind|yes|no"], "I don't mind cooking.", "Ha ha! Me, I hate cooking!")],
        ["I love dancing.", "I hate cooking.", "I don't mind cooking.", "singing · reading · swimming"],
    ),
    mission(
        "5e-u1-m4", "Les talents du village", "dire ce que je fais bien et ce que je fais mal",
        ["He's good at drawing.", "I'm bad at maths."],
        {"consigne": "La lutte au village ! Quels mots vont avec l'image ?", "fond": "terrain",
         "objets": ["🤼", "🥁", "🎨", "⚽"],
         "liste": [
             mot("wrestling", True, "Oui ! « Wrestling », c'est la lutte. Les lutteurs sont là."),
             mot("drum", True, "Oui ! « Drum », c'est le tambour pour la lutte."),
             mot("drawing", True, "Oui ! « Drawing », c'est le dessin. Regarde la peinture."),
             mot("football", True, "Oui ! « Football », c'est le foot. Voilà le ballon !"),
             mot("swimming", False, "« Swimming », c'est nager. Il n'y a pas d'eau sur le terrain. Regarde encore !"),
             mot("cooking", False, "« Cooking », c'est faire la cuisine. Il n'y a pas de marmite ici. Regarde encore."),
         ]},
        {"fond": "terrain", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "My cousin is good at wrestling!", "Mon cousin est fort à la lutte !"),
                       r("modou", "And you, Awa?", "Et toi, Awa ?"),
                       r("awa", "I'm good at drawing. But I'm bad at swimming.", "Je suis forte en dessin. Mais je suis nulle en natation."),
                       r("modou", "Me, I'm bad at maths. But I'm good at football!", "Moi, je suis nul en maths. Mais je suis fort au foot !")],
         "gainde": "Fort à la lutte… nul en maths… Et moi, je suis fort à quoi ? À rugir ?"},
        [q("Awa est forte en…", ["dessin", "natation", "maths"], 0, 2),
         q("« I'm bad at maths », ça veut dire…", ["J'adore les maths.", "Je fais des maths.", "Je suis nul en maths."], 2, 3)],
        [choix("Je veux dire : « Je suis fort à la lutte. » Je dis laquelle ?",
               ["I'm good at wrestling.", "I'm strong in wrestling."], 0,
               aides("Comment Awa parle-t-elle de son cousin ?", 0, "Écoute Awa :",
                     "Moi, je dis : « I'm good at reading. »",
                     "« Fort en », c'est « good at ». Pas « strong in ».")),
         ordre("« At bad I'm maths. » C'est bien ça ?", ["maths", "at", "I'm", "bad"], "Im bad at maths",
               "I'm bad at maths.",
               aides("Quel mot Modou dit-il juste après « I'm » ?", 3, "Écoute Modou :",
                     "Moi, je dis : « I'm bad at maths. »", "I'm (je suis) + bad at (nul en) + maths.")),
         trou("« He's good ___ drawing. » Il me manque un petit mot !", "He's good", "drawing.", ["at"],
              "He's good at drawing.",
              aides("Quel petit mot Awa dit-elle après « good » ?", 2, "Écoute Awa :",
                    "Moi, je dis : « I'm good at drawing. »", "Après « good », on dit « at ». Écris : at.")),
         libre("Dis une chose que tu fais bien.", ["good at"],
               aides("Comment Modou dit-il qu'il est fort au foot ?", 3, "Écoute Modou :",
                     "Moi, je dis : « I'm good at reading. »", "Écris : « I'm good at… » et ton talent."))],
        [tour("kocc", "What are you good at?", "Tu es fort en quoi ?", ["good at"], "I'm good at football.",
              "Very good!"),
         tour("awa", "And what are you bad at?", "Et tu es nul en quoi ?", ["bad at|not good at"],
              "I'm bad at singing.", "Ha ha! Me too!")],
        ["He's good at drawing.", "I'm bad at maths.", "wrestling · drawing · swimming"],
    ),
]

unite1 = unite(
    "5e-u1", "My big family",
    "Ma grande famille : présente 4 personnes de ta famille et dis ce qu'elles font bien.",
    u1,
    lignes=[
        ("Parler de ma famille", "She's my cousin. · He's my uncle's son."),
        ("Présenter un ami à un adulte", "Let me introduce my cousin. · Pleased to meet you."),
        ("Dire ce que j'aime ou pas", "I love dancing. · I hate cooking. · I don't mind…"),
        ("Dire ce que je fais bien ou mal", "He's good at drawing. · I'm bad at maths."),
    ],
    mots=[
        ("family", "famille", "njaboot"),
        ("grandmother", "grand-mère", "maam"),
        ("grandson", "petit-fils", "sët"),
        ("son", "fils", "doom ju góor"),
        ("uncle", "oncle (frère de la maman)", "nijaay"),
        ("friend", "ami(e)", "xarit"),
        ("dancing", "danser", "fecc"),
        ("singing", "chanter", "woy"),
        ("swimming", "nager", "féey"),
        ("wrestling", "la lutte", "làmb"),
        ("cooking", "faire la cuisine", "togg"),
    ],
    pieges=[
        "Let me introduce my friend. Pas « I present you my friend ».",
        "I'm good at maths. Pas « I'm strong in maths ».",
        "I love dancing. Pas « I like very much dancing ».",
    ],
    exercices=[
        ex("C'est le fils de ton oncle. Tu dis :", ["He's my uncle's son.", "He's my son's uncle.",
           "He's the son of the uncle of me.", "He's my uncle son's."], 0,
           "On dit d'abord à qui : my uncle's son = le fils de mon oncle."),
        ex("La fille de ta tante, c'est ta…", ["cousin", "nephew", "uncle", "grandson"], 0,
           "Cousin = cousin ou cousine."),
        ex("Tu présentes ton ami à Kocc Barma :", ["Let me introduce my friend.", "I present you my friend.",
           "Look my friend.", "My friend is introduce."], 0,
           "Pour présenter quelqu'un : « Let me introduce… »."),
        ex("Kocc Barma te dit « Pleased to meet you. » Tu réponds :", ["Pleased to meet you too.", "Goodbye!",
           "I'm bad at maths.", "I hate cooking."], 0, "On répond : « Pleased to meet you too. » (Enchanté aussi.)"),
        ex("« I hate cooking » veut dire :", ["Je déteste faire la cuisine.", "J'adore faire la cuisine.",
           "Je fais la cuisine.", "Ça m'est égal de faire la cuisine."], 0, "Hate = détester."),
        ex("Ça t'est égal de lire. Tu dis :", ["I don't mind reading.", "I hate reading.",
           "I love reading.", "I'm good at reading."], 0, "« I don't mind » = ça m'est égal."),
        ex("Complète : « I love ______. »", ["dancing", "dance at", "to dancing", "danced"], 0,
           "On dit « I love dancing »."),
        ex("Tu es forte en dessin. Tu dis :", ["I'm good at drawing.", "I'm strong in drawing.",
           "I'm bad at drawing.", "I'm good in drawing."], 0, "Fort en = good at."),
        ex("« He's bad at swimming » veut dire :", ["Il nage mal.", "Il nage bien.", "Il adore nager.",
           "Il ne nage jamais."], 0, "Bad at = nul en."),
        ex("Complète : « Modou is good ___ football. »", ["at", "in", "on", "of"], 0, "Après « good », on dit « at »."),
    ],
)

# ======================= UNITÉ 2 : FOOD AND DRINKS =======================

u2 = [
    mission(
        "5e-u2-m1", "La cuisine de grand-mère", "dire le nom des plats et des boissons",
        ["rice", "millet", "oil", "fish", "bissap"],
        {"consigne": "Dans la cuisine de grand-mère. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🍚", "🐟", "🫗", "🥤"],
         "liste": [
             mot("rice", True, "Oui ! « Rice », c'est le riz."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("oil", True, "Oui ! « Oil », c'est l'huile. Grand-mère en met dans la marmite."),
             mot("bissap", True, "Oui ! « Bissap », c'est le jus de bissap. Il est rouge."),
             mot("pizza", False, "« Pizza », c'est la pizza. Grand-mère ne fait pas de pizza ! Regarde encore."),
             mot("ice cream", False, "« Ice cream », c'est la glace. Il n'y en a pas ici. Regarde encore !"),
             mot("chips", False, "« Chips », ce sont les frites. Tu vois des frites ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Look! Rice, fish and oil.", "Regarde ! Du riz, du poisson et de l'huile."),
                       r("modou", "And this drink?", "Et cette boisson ?"),
                       r("awa", "It's bissap!", "C'est du bissap !"),
                       r("modou", "And this?", "Et ça ?"),
                       r("awa", "It's millet, for the thiakry.", "C'est du mil, pour le thiakry.")],
         "gainde": "Riz, poisson, bissap… J'ai faim ! Je veux tout goûter !"},
        [q("Quelle est la boisson ?", ["le riz", "le bissap", "le mil"], 1, 2),
         q("Le mil, c'est pour…", ["le thiakry", "le bissap", "le poisson"], 0, 4)],
        [choix("Grand-mère montre le riz. Je dis laquelle ?", ["It's a rice.", "It's rice."], 1,
               aides("Awa dit « a rice » ou juste « rice » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « It's rice. It's oil. »",
                     "Astuce : on ne compte pas le riz. On ne dit pas « a » devant « rice ».")),
         ordre("« Bissap is drink this. » C'est bien ça ?", ["is", "bissap", "drink", "This"], "This drink is bissap",
               "This drink is bissap.",
               aides("Qu'est-ce que Modou demande ?", 1, "Écoute Modou :",
                     "Moi, je dis : « This drink is bissap. »", "This drink (cette boisson) + is (est) + bissap.")),
         trou("Je montre le poisson : « It's ___. »", "It's", ".", ["fish"], "It's fish.",
              aides("Comment dit-on « poisson » ?", 0, "Écoute Awa :",
                    "Moi, je dis : « Rice, fish and oil. »", "Poisson = fish. Écris : fish.")),
         libre("Grand-mère demande ce qu'il y a dans la marmite. Il y a du riz et du poisson.", ["rice", "fish"],
               aides("Quels mots Awa dit-elle au début ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Rice and fish. »", "Riz = rice. Poisson = fish. Écris : « Rice and fish. »"))],
        [tour("awa", "What's your favourite drink?", "C'est quoi, ta boisson préférée ?",
              ["bissap|water|milk|juice|tea|attaya|bouye|coffee|lemonade|soda|coke|ginger"],
              "Bissap!", "Me too! It's very good!"),
         tour("modou", "What's your favourite food?", "C'est quoi, ton plat préféré ?", [],
              "Thieboudienne!", "Yummy!")],
        ["rice", "fish", "oil", "millet", "bissap", "drink"],
    ),
    mission(
        "5e-u2-m2", "Les nombres du marché", "dire les grands nombres, les prix, les années",
        ["It costs 12 500 francs.", "In 2024."],
        {"consigne": "Au marché du village. Quels mots vont avec l'image ?", "fond": "marche",
         "objets": ["💰", "🛍️", "🧅", "🐟"],
         "liste": [
             mot("money", True, "Oui ! « Money », c'est l'argent."),
             mot("bag", True, "Oui ! « Bag », c'est le sac."),
             mot("onions", True, "Oui ! « Onions », ce sont les oignons."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("bed", False, "« Bed », c'est le lit. On ne dort pas au marché ! Regarde encore."),
             mot("ticket", False, "« Ticket », c'est le billet pour le car. On est au marché. Regarde encore !"),
         ]},
        {"fond": "marche", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "How much is this bag of rice?", "Combien coûte ce sac de riz ?"),
                       r("modou", "It costs twelve thousand five hundred francs.", "Il coûte douze mille cinq cents francs."),
                       r("awa", "Wow! In 2020, it cost ten thousand francs!", "Waouh ! En 2020, il coûtait dix mille francs !")],
         "gainde": "Douze mille cinq cents ! Je n'ai pas assez de griffes pour compter ça !"},
        [q("Le sac de riz coûte…", ["10 000 francs", "2 500 francs", "12 500 francs"], 2, 1),
         q("Combien coûtait le riz en 2020 ?", ["10 000 francs", "12 500 francs", "20 000 francs"], 0, 2)],
        [choix("Je veux dire le prix du riz. Je dis laquelle ?",
               ["It costs 12 500 francs.", "It makes 12 500 francs."], 0,
               aides("Quel mot Modou dit-il avant le prix ?", 1, "Écoute Modou :",
                     "Moi, je dis : « It costs five thousand francs. »",
                     "« Ça coûte », c'est « It costs ». Pas « It makes ».")),
         ordre("« Francs costs it thousand five. » C'est bien ça ?", ["costs", "francs", "It", "five", "thousand"],
               "It costs five thousand francs", "It costs five thousand francs.",
               aides("Quels mots Modou dit-il en premier ?", 1, "Écoute Modou :",
                     "Moi, je dis : « It costs five thousand francs. »",
                     "It costs (ça coûte) + five thousand (cinq mille) + francs.")),
         trou("Je veux dire « En 2024 » : « In twenty twenty-___. »", "In twenty twenty-", ".",
              ["four", "4"], "In twenty twenty-four.",
              aides("On coupe 2024 en deux : 20 et 24. Comment dit-on 24 ?", -1, "",
                    "Moi, je dis : « In twenty twenty. » (2020)", "24 = twenty-four. Écris : four.")),
         libre("Le poisson coûte 2 000 francs. Dis-le.", ["costs|cost|its|is", "2000|2 000|two thousand"],
               aides("Comment Modou dit-il le prix du riz ?", 1, "Écoute Modou :",
                     "Moi, je dis : « It costs two thousand francs. »",
                     "Mille = thousand. Écris : « It costs two thousand francs. »"))],
        [tour("modou", "How much is a bag of rice? (12 500 francs)", "Combien coûte un sac de riz ? (12 500 francs)",
              ["12500|12 500|twelve thousand"], "It costs twelve thousand five hundred francs.", "Wow! That's a lot!"),
         tour("awa", "I was born in 2014. And you?", "Je suis née en 2014. Et toi ?",
              ["2008|2009|2010|2011|2012|2013|2014|2015|2016|two thousand|twenty"],
              "I was born in 2013.", "Cool!")],
        ["It costs 12 500 francs.", "one hundred · one thousand", "In 2024."],
    ),
    mission(
        "5e-u2-m3", "Combien de poissons ?", "demander combien",
        ["How many fish?", "How much rice?"],
        {"consigne": "Sur la plage, les pêcheurs arrivent. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🛶", "🐟", "🧺", "🌊"],
         "liste": [
             mot("boat", True, "Oui ! « Boat », c'est le bateau. Ici, c'est la pirogue."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("basket", True, "Oui ! « Basket », c'est le panier pour les poissons."),
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("bread", False, "« Bread », c'est le pain. On ne pêche pas de pain ! Regarde encore."),
             mot("goat", False, "« Goat », c'est la chèvre. Il n'y a pas de chèvre sur la plage. Regarde encore !"),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Grandma needs fish. How many fish?", "Grand-mère a besoin de poisson. Combien de poissons ?"),
                       r("modou", "Ten fish!", "Dix poissons !"),
                       r("awa", "And how much rice?", "Et combien de riz ?"),
                       r("modou", "Two kilos.", "Deux kilos.")],
         "gainde": "How many ? How much ? C'est pareil, non ? Je vais tout mélanger…"},
        [q("Combien de poissons faut-il ?", ["deux", "dix", "douze"], 1, 1),
         q("« How much rice? » veut dire…", ["Combien de riz ?", "Combien de poissons ?", "C'est quoi, le riz ?"], 0, 2)],
        [choix("Je veux savoir combien de mangues il faut. Je dis laquelle ?",
               ["How much mangoes?", "How many mangoes?"], 1,
               aides("On peut compter les mangues : une, deux, trois… Awa a dit quoi pour les poissons ?", 0, "Écoute Awa :",
                     "Moi, je dis : « How many onions? »",
                     "Astuce : on compte (1, 2, 3) → how many. On ne compte pas (le riz, l'eau) → how much.")),
         ordre("« Rice how much? » C'est bien ça ?", ["much", "rice", "How"], "How much rice", "How much rice?",
               aides("Quel mot Awa dit-elle en premier ?", 2, "Écoute Awa :",
                     "Moi, je dis : « How much rice? »", "How much (combien de) + rice (riz).")),
         trou("Je veux savoir combien d'oignons : « How ___ onions? »", "How", "onions?", ["many"], "How many onions?",
              aides("On peut compter les oignons ?", 0, "Écoute Awa :",
                    "Moi, je dis : « How many fish? »", "On compte les oignons : how many. Écris : many.")),
         libre("Demande combien d'eau il faut.", ["how much", "water"],
               aides("L'eau, on peut la compter : une, deux, trois ?", 2, "Écoute Awa pour le riz :",
                     "Moi, je dis : « How much rice? »", "On ne compte pas l'eau. Écris : « How much water? »"))],
        [tour("kocc", "Ask me: combien de poissons ?", "Demande-moi : combien de poissons ?", ["how many", "fish"],
              "How many fish?", "Five big fish!"),
         tour("awa", "Ask me: combien de sucre ?", "Demande-moi : combien de sucre ?", ["how much", "sugar"],
              "How much sugar?", "A lot! I love sugar!")],
        ["How many fish?", "How much rice?", "How many onions?", "How much water?"],
    ),
    mission(
        "5e-u2-m4", "Un peu, beaucoup", "dire un peu, beaucoup",
        ["some bread", "a lot of water", "a few onions", "a little salt"],
        {"consigne": "Grand-mère fait la cuisine. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🍞", "🧂", "🧅", "💧"],
         "liste": [
             mot("bread", True, "Oui ! « Bread », c'est le pain."),
             mot("salt", True, "Oui ! « Salt », c'est le sel."),
             mot("onions", True, "Oui ! « Onions », ce sont les oignons."),
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("sand", False, "« Sand », c'est le sable. On ne met pas de sable dans la marmite ! Regarde encore."),
             mot("sugar", False, "« Sugar », c'est le sucre. Il n'y en a pas sur l'image. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "We need a lot of water.", "Il nous faut beaucoup d'eau."),
                       r("modou", "And salt?", "Et du sel ?"),
                       r("awa", "A little salt. And a few onions.", "Un peu de sel. Et quelques oignons."),
                       r("modou", "And some bread for me!", "Et du pain pour moi !")],
         "gainde": "Un peu de sel, beaucoup d'eau… Et beaucoup, beaucoup de pain pour moi !"},
        [q("Combien de sel faut-il ?", ["beaucoup", "un peu", "pas du tout"], 1, 2),
         q("« A lot of water », c'est…", ["beaucoup d'eau", "un peu d'eau", "une bouteille d'eau"], 0, 0)],
        [choix("Je veux un peu de sel. Je dis laquelle ?", ["A little salt, please.", "A few salt, please."], 0,
               aides("Comment Awa demande-t-elle le sel ?", 2, "Écoute Awa :",
                     "Moi, je dis : « A little salt. A little oil. »",
                     "Astuce : on compte les oignons → a few onions. On ne compte pas le sel → a little salt.")),
         ordre("« Water lot a of. » C'est bien ça ?", ["of", "water", "a", "lot"], "a lot of water", "A lot of water.",
               aides("Qu'est-ce qu'Awa dit au début ?", 0, "Écoute Awa :",
                     "Moi, je dis : « A lot of water. »", "A lot of (beaucoup de) + water (eau).")),
         trou("Je veux quelques oignons : « A ___ onions, please. »", "A", "onions, please.", ["few"],
              "A few onions, please.",
              aides("Comment Awa dit-elle « quelques oignons » ?", 2, "Écoute Awa :",
                    "Moi, je dis : « A few onions. »", "Quelques = a few. Écris : few.")),
         libre("Dis : il faut beaucoup de riz.", ["a lot of|lots of|much", "rice"],
               aides("Comment Awa dit-elle « beaucoup d'eau » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « We need a lot of rice. »", "Beaucoup de = a lot of. Écris : « A lot of rice. »"))],
        [tour("awa", "How much water do you drink every day?", "Tu bois combien d'eau chaque jour ?",
              ["a lot|a little|lots|much|litre|litres|bottle|bottles|glass|glasses"],
              "I drink a lot of water.", "Very good! Water is good for you."),
         tour("modou", "Do you want some bread?", "Tu veux du pain ?", ["yes|no|please|thanks|thank"],
              "Yes, please! A little bread.", "Here you are!")],
        ["some bread", "a lot of water", "a few onions", "a little salt", "a bottle of water"],
    ),
    mission(
        "5e-u2-m5", "Gaïndé pose trop de questions", "poser des questions (qui ? où ? quand ?)",
        ["What…?", "Where…?", "When…?", "Who…?", "How often…?"],
        {"consigne": "Dans la cour. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["❓", "👵🏾", "🛍️", "🕕"],
         "liste": [
             mot("question", True, "Oui ! « Question », c'est une question. Gaïndé en a plein !"),
             mot("grandmother", True, "Oui ! « Grandmother », c'est la grand-mère."),
             mot("bag", True, "Oui ! « Bag », c'est le sac pour le marché."),
             mot("clock", True, "Oui ! « Clock », c'est l'horloge. Il est 6 h."),
             mot("answer", False, "« Answer », c'est la réponse. Ici, on ne voit que des questions ! Regarde encore."),
             mot("crocodile", False, "« Crocodile », c'est le crocodile. Il n'y en a pas dans la cour, heureusement ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Where is your grandmother?", "Où est ta grand-mère ?"),
                       r("awa", "At the market.", "Au marché."),
                       r("modou", "When does she come back?", "Elle revient quand ?"),
                       r("awa", "At six. She goes to the market every day!", "À six heures. Elle va au marché tous les jours !")],
         "gainde": "Où ? Quand ? Qui ? Quoi ? Moi aussi, j'ai mille questions !"},
        [q("Où est la grand-mère ?", ["à la plage", "à l'école", "au marché"], 2, 1),
         q("« When does she come back? » veut dire…", ["Elle revient quand ?", "Elle est où ?", "C'est qui ?"], 0, 2)],
        [choix("Je veux savoir où est grand-mère. Je dis laquelle ?", ["Where grandma is?", "Where is grandma?"], 1,
               aides("Comment Modou pose-t-il la question ?", 0, "Écoute Modou :",
                     "Moi, je dis : « Where is the market? »",
                     "Dans une question, on dit « Where is… ? » : « is » vient tout de suite après « Where ».")),
         ordre("« Often how you go do to the market? » C'est bien ça ?",
               ["market", "How", "do", "to", "often", "the", "you", "go"], "How often do you go to the market",
               "How often do you go to the market?",
               aides("« Tous les combien », c'est « How often ». Par quoi commence la question ?", -1, "",
                     "Moi, je dis : « How often do you go to the sea? »",
                     "How often (tous les combien) + do you go (vas-tu) + to the market.")),
         trou("Je veux savoir qui est ce garçon : « ___ is he? »", "", "is he?", ["who"], "Who is he?",
              aides("Quel mot veut dire « qui » ?", -1, "",
                    "Moi, je dis : « Who is she? — She's my cousin. »", "Qui = who. Écris : who.")),
         libre("Demande à Awa quand elle rentre à Dakar.", ["when", "dakar"],
               aides("Comment Modou demande-t-il « quand » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « When do you go back to Dakar? »", "Quand = when. Écris : « When do you go back to Dakar? »"))],
        [tour("doudou", "Ask me a question! (où j'habite)", "Pose-moi une question ! (où j'habite)", ["where"],
              "Where do you live?", "I live in the village, near the big baobab!"),
         tour("kocc", "Ask me: tous les combien je vais à la mer ?", "Demande-moi : tous les combien je vais à la mer ?",
              ["how often"], "How often do you go to the sea?", "Every Sunday!")],
        ["What…?", "Where is…?", "When…?", "Who is…?", "How often…?"],
    ),
    mission(
        "5e-u2-m6", "La recette du thiéboudienne", "dire avec quoi on fait un plat",
        ["It's made with rice and fish.", "It's cooked in a big pot."],
        {"consigne": "Grand-mère fait le thiéboudienne. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🍲", "🐟", "🍚", "🥕"],
         "liste": [
             mot("pot", True, "Oui ! « Pot », c'est la marmite. Elle est grande !"),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("rice", True, "Oui ! « Rice », c'est le riz."),
             mot("carrot", True, "Oui ! « Carrot », c'est la carotte."),
             mot("chocolate", False, "« Chocolate », c'est le chocolat. Pas de chocolat dans le thiéboudienne ! Regarde encore."),
             mot("bread", False, "« Bread », c'est le pain. Il n'y a pas de pain sur l'image. Regarde encore !"),
         ]},
        {"fond": "maison", "persos": ["kocc", "awa", "gainde"],
         "repliques": [r("kocc", "What is thieboudienne made with?", "Le thiéboudienne, c'est fait avec quoi ?"),
                       r("awa", "It's made with rice and fish.", "C'est fait avec du riz et du poisson."),
                       r("kocc", "And how is it cooked?", "Et comment on le cuit ?"),
                       r("awa", "It's cooked in a big pot.", "On le cuit dans une grande marmite.")],
         "gainde": "Riz, poisson, grande marmite… Je peux me cacher dans la marmite pour goûter ?"},
        [q("Le thiéboudienne est fait avec…", ["du riz et du poisson", "du mil et du lait", "du pain et du sel"], 0, 1),
         q("On le cuit où ?", ["dans la mer", "dans une grande marmite", "dans un sac"], 1, 3)],
        [choix("Je veux dire : « C'est fait avec du riz et du poisson. » Je dis laquelle ?",
               ["It's made with rice and fish.", "It's done with rice and fish."], 0,
               aides("Quel mot Awa dit-elle après « It's » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Thiakry is made with millet. »",
                     "Pour un plat, « c'est fait avec », c'est « It's made with ». Pas « done with ».")),
         ordre("« Pot cooked in big a it's. » C'est bien ça ?", ["cooked", "pot", "It's", "a", "in", "big"],
               "Its cooked in a big pot", "It's cooked in a big pot.",
               aides("Qu'est-ce qu'Awa dit à la fin ?", 3, "Écoute Awa :",
                     "Moi, je dis : « It's cooked in a big pot. »",
                     "It's cooked (on le cuit) + in a big pot (dans une grande marmite).")),
         trou("« Thiakry is made ___ millet and milk. » Il me manque un petit mot !", "Thiakry is made",
              "millet and milk.", ["with", "from", "of"], "Thiakry is made with millet and milk.",
              aides("Quel petit mot Awa dit-elle après « made » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « It's made with rice and fish. »", "Fait avec = made with. Écris : with.")),
         libre("Dis : le yassa est fait avec du poisson et des oignons.",
               ["made with|made from|made of", "onion|onions"],
               aides("Comment Awa dit-elle avec quoi on fait le thiéboudienne ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Yassa is made with fish and onions. »",
                     "Écris : « Yassa is made with fish and onions. »"))],
        [tour("awa", "What is your favourite dish made with?", "Ton plat préféré, il est fait avec quoi ?",
              ["with|from|made of"], "It's made with rice and fish.", "Yummy! I love it!")],
        ["It's made with rice and fish.", "It's cooked in a big pot.", "pot"],
    ),
]

unite2 = unite(
    "5e-u2", "Food and drinks",
    "Mon plat préféré : présente un plat et dis comment on le fait.",
    u2,
    lignes=[
        ("Dire le nom des plats et des boissons", "rice · millet · oil · fish · bissap"),
        ("Dire les prix et les années", "It costs 12 500 francs. · In 2024."),
        ("Demander combien", "How many fish? · How much rice?"),
        ("Dire un peu, beaucoup", "some bread · a lot of water · a few onions · a little salt"),
        ("Poser des questions", "What…? · Where…? · When…? · Who…? · How often…?"),
        ("Dire avec quoi on fait un plat", "It's made with rice and fish. · It's cooked in a big pot."),
    ],
    mots=[
        ("rice", "riz", "ceeb"),
        ("fish", "poisson", "jën"),
        ("millet", "mil", "dugub"),
        ("oil", "huile", "diw"),
        ("water", "eau", "ndox"),
        ("salt", "sel", "xorom"),
        ("onion", "oignon", "soble"),
        ("bread", "pain", "mburu"),
        ("money", "argent", "xaalis"),
        ("one thousand", "mille", "junni"),
        ("Who?", "Qui ?", "Kan ?"),
        ("Where?", "Où ?", "Fan ?"),
    ],
    pieges=[
        "It costs 1 000 francs. Pas « It makes 1 000 francs ».",
        "How many onions? (on les compte) · How much rice? (on ne compte pas le riz).",
        "A little salt. Pas « a few salt ».",
    ],
    exercices=[
        ex("« Bissap », c'est…", ["une boisson", "un poisson", "un plat de riz", "un fruit"], 0,
           "Le bissap est une boisson rouge."),
        ex("Le poisson coûte 1 500 francs. Tu dis :", ["It costs one thousand five hundred francs.",
           "It makes one thousand five hundred francs.", "It costs fifteen francs.", "It is cost fifteen hundred."], 0,
           "« Ça coûte » = It costs."),
        ex("Comment dit-on 2024 ?", ["twenty twenty-four", "two zero two four", "twenty hundred twenty-four",
           "two thousand and forty-two"], 0, "On coupe en deux : 20 + 24 → twenty twenty-four."),
        ex("Tu veux savoir combien de poissons il y a :", ["How many fish?", "How much fish are?",
           "How many rice?", "What fish?"], 0, "On compte les poissons : How many fish?"),
        ex("Complète : « How ______ water? »", ["much", "many", "few", "often"], 0,
           "On ne compte pas l'eau : How much water?"),
        ex("Tu veux un peu de sel :", ["A little salt, please.", "A few salt, please.", "A lot of salt, please.",
           "Many salt, please."], 0, "Un peu de sel = a little salt."),
        ex("« A few onions » veut dire :", ["quelques oignons", "beaucoup d'oignons", "pas d'oignons",
           "un oignon"], 0, "A few = quelques."),
        ex("Tu veux savoir où est Awa :", ["Where is Awa?", "When is Awa?", "Who is Awa?", "Where Awa is?"], 0,
           "Where = où. On dit « Where is… ? »."),
        ex("« How often do you go to the market? » veut dire :", ["Tu vas au marché tous les combien ?",
           "Tu vas au marché quand ?", "Tu vas au marché avec qui ?", "Tu vas au marché comment ?"], 0,
           "How often = tous les combien."),
        ex("Le thiakry est fait avec du mil et du lait :", ["It's made with millet and milk.",
           "It's done with millet and milk.", "It makes millet and milk.", "It's cooked millet with milk."], 0,
           "Fait avec = made with."),
    ],
)

# ======================= UNITÉ 3 : LAST HOLIDAYS =======================

u3 = [
    mission(
        "5e-u3-m1", "Qu'as-tu fait hier ?", "raconter ce que j'ai fait",
        ["Yesterday, I went to the river.", "I saw a crocodile!"],
        {"consigne": "La photo d'Awa, hier, au bord de l'eau. Quels mots vont avec l'image ?", "fond": "mer",
         "objets": ["🐊", "🛶", "🌳", "🐟"],
         "liste": [
             mot("crocodile", True, "Oui ! « Crocodile », c'est le crocodile. Attention !"),
             mot("boat", True, "Oui ! « Boat », c'est le bateau, la pirogue."),
             mot("tree", True, "Oui ! « Tree », c'est l'arbre au bord de l'eau."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("camel", False, "« Camel », c'est le chameau. Il vit dans le désert, pas dans l'eau ! Regarde encore."),
             mot("school", False, "« School », c'est l'école. C'est les vacances ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "What did you do yesterday?", "Qu'est-ce que tu as fait hier ?"),
                       r("awa", "Yesterday, I went to the river.", "Hier, je suis allée au fleuve."),
                       r("modou", "Wow! What did you see?", "Waouh ! Qu'est-ce que tu as vu ?"),
                       r("awa", "I saw a crocodile!", "J'ai vu un crocodile !")],
         "gainde": "Un crocodile ?! Moi, hier, j'ai vu… mon lit. Et ma gamelle."},
        [q("Où Awa est-elle allée hier ?", ["au fleuve", "au marché", "à l'école"], 0, 1),
         q("Qu'est-ce qu'Awa a vu ?", ["un lion", "un poisson", "un crocodile"], 2, 3)],
        [choix("Je veux dire : « Hier, je suis allé au fleuve. » Je dis laquelle ?",
               ["Yesterday, I have gone to the river.", "Yesterday, I went to the river."], 1,
               aides("Écoute bien le mot qu'Awa dit après « I ».", 1, "Écoute Awa :",
                     "Moi, je dis : « Yesterday, I went to the market. »",
                     "Pour hier, « je suis allé », c'est « I went ». Un seul mot !")),
         ordre("« Crocodile saw I a! » C'est bien ça ?", ["a", "saw", "crocodile", "I"], "I saw a crocodile",
               "I saw a crocodile!",
               aides("Quel mot Awa dit-elle en premier ?", 3, "Écoute Awa :",
                     "Moi, je dis : « I saw a crocodile! »", "I (je) + saw (ai vu) + a crocodile.")),
         trou("« Yesterday, I ___ to the market. » (je suis allé)", "Yesterday, I", "to the market.", ["went"],
              "Yesterday, I went to the market.",
              aides("Comment Awa dit-elle « je suis allée » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « Yesterday, I went to the river. »", "Je suis allé = I went. Écris : went.")),
         libre("Dis : hier, je suis allé à la plage.", ["went", "beach|sea"],
               aides("Comment Awa dit-elle « Hier, je suis allée au fleuve » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Yesterday, I went to the river. »",
                     "Plage = beach. Écris : « Yesterday, I went to the beach. »"))],
        [tour("modou", "What did you do yesterday?", "Qu'est-ce que tu as fait hier ?",
              ["went|saw|played|ate|watched|helped|visited|did|was|stayed|slept|read|cooked|swam|danced"],
              "Yesterday, I went to the market.", "Cool! I played football!")],
        ["Yesterday, I went to…", "I saw…", "What did you do yesterday?"],
    ),
    mission(
        "5e-u3-m2", "Le journal de vacances d'Awa", "dire le jour et l'heure d'une chose passée",
        ["On Monday the 3rd of August", "at half past eight"],
        {"consigne": "Awa écrit son journal. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["📔", "✏️", "📅", "🕣"],
         "liste": [
             mot("diary", True, "Oui ! « Diary », c'est le journal d'Awa. Elle écrit dedans."),
             mot("pencil", True, "Oui ! « Pencil », c'est le crayon."),
             mot("calendar", True, "Oui ! « Calendar », c'est le calendrier, avec les jours."),
             mot("clock", True, "Oui ! « Clock », c'est l'horloge. Il est huit heures et demie."),
             mot("ball", False, "« Ball », c'est le ballon. Awa écrit, elle ne joue pas ! Regarde encore."),
             mot("phone", False, "« Phone », c'est le téléphone. Tu vois un téléphone ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "When did you see the crocodile?", "Tu as vu le crocodile quand ?"),
                       r("awa", "On Monday the 3rd of August.", "Le lundi 3 août."),
                       r("modou", "At what time?", "À quelle heure ?"),
                       r("awa", "At half past eight.", "À huit heures et demie.")],
         "gainde": "Lundi, août, huit heures et demie… Awa sait tout ! Moi, je ne sais même pas quel jour on est."},
        [q("Awa a vu le crocodile quel jour ?", ["le lundi 3 août", "le mardi 8 août", "le lundi 8 mars"], 0, 1),
         q("À quelle heure ?", ["8 h", "8 h 30", "3 h 30"], 1, 3)],
        [choix("Je veux dire : « À huit heures et demie. » Je dis laquelle ?",
               ["At half past eight.", "At eight and half."], 0,
               aides("Awa dit d'abord « half » ou « eight » ?", 3, "Écoute Awa :",
                     "Moi, je dis : « At half past nine. » (9 h 30)",
                     "En anglais, on dit la demie d'abord : half past eight = 8 h 30.")),
         ordre("« August the 3rd of on Monday. » C'est bien ça ?", ["the", "Monday", "of", "3rd", "On", "August"],
               "On Monday the 3rd of August", "On Monday the 3rd of August.",
               aides("Quel petit mot Awa dit-elle en premier ?", 1, "Écoute Awa :",
                     "Moi, je dis : « On Friday the 7th of August. »",
                     "On + le jour (Monday) + the 3rd (le 3) + of August (août).")),
         trou("9 h 30 : « At half ___ nine. »", "At half", "nine.", ["past"], "At half past nine.",
              aides("Quel mot Awa dit-elle entre « half » et « eight » ?", 3, "Écoute Awa :",
                    "Moi, je dis : « At half past eight. »", "Écris : past.")),
         libre("Dis : le samedi 5 août.", ["saturday", "5th|fifth|5"],
               aides("Comment Awa dit-elle « le lundi 3 août » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « On Monday the 3rd of August. »",
                     "Samedi = Saturday. Le 5 = the 5th. Écris : « On Saturday the 5th of August. »"))],
        [tour("kocc", "When did you arrive in the village?", "Tu es arrivé au village quand ?",
              ["monday|tuesday|wednesday|thursday|friday|saturday|sunday|january|february|march|april|may|june|july"
               "|august|september|october|november|december|yesterday|last"],
              "On Sunday the 2nd of August.", "Welcome to the village!")],
        ["On Monday the 3rd of August", "at half past eight", "Monday · Tuesday · Wednesday…"],
    ),
    mission(
        "5e-u3-m3", "Gaïndé n'a jamais vu la mer", "dire ce que j'ai déjà fait, ou jamais fait",
        ["Have you ever been to the sea?", "I've never…"],
        {"consigne": "Une photo de la mer. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🌊", "🐚", "☀️", "🛶"],
         "liste": [
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("shell", True, "Oui ! « Shell », c'est le coquillage."),
             mot("sun", True, "Oui ! « Sun », c'est le soleil."),
             mot("beach", True, "Oui ! « Beach », c'est la plage."),
             mot("bush", False, "« Bush », c'est la brousse. Ici, il y a du sable et de l'eau. Regarde encore !"),
             mot("river", False, "« River », c'est le fleuve. Ici, c'est beaucoup plus grand : c'est la mer ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Have you ever been to Saint-Louis?", "Tu es déjà allée à Saint-Louis ?"),
                       r("awa", "Yes, I have! And you?", "Oui ! Et toi ?"),
                       r("modou", "No, I've never been to Saint-Louis.", "Non, je ne suis jamais allé à Saint-Louis.")],
         "gainde": "Moi, je ne suis jamais allé… à la mer. Chut ! C'est un secret de lion."},
        [q("Awa est déjà allée à Saint-Louis ?", ["Non", "Oui"], 1, 1),
         q("« I've never been », ça veut dire…", ["Je ne suis jamais allé", "Je suis déjà allé", "Je vais aller"], 0, 2)],
        [choix("Je veux demander : « Tu es déjà allé à la mer ? » Je dis laquelle ?",
               ["Are you already gone to the sea?", "Have you ever been to the sea?"], 1,
               aides("Comment Modou commence-t-il sa question ?", 0, "Écoute Modou :",
                     "Moi, je dis : « Have you ever been to Dakar? »",
                     "« Tu es déjà allé… ? », c'est « Have you ever been to… ? ».")),
         ordre("« Never I've been Saint-Louis to. » C'est bien ça ?", ["been", "to", "I've", "Saint-Louis", "never"],
               "Ive never been to Saint-Louis", "I've never been to Saint-Louis.",
               aides("Qu'est-ce que Modou dit après « No » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « I've never been to Paris. »",
                     "I've never been (je ne suis jamais allé) + to Saint-Louis.")),
         trou("« Have you ___ been to Dakar? » (déjà)", "Have you", "been to Dakar?", ["ever"],
              "Have you ever been to Dakar?",
              aides("Quel mot Modou dit-il après « Have you » ?", 0, "Écoute Modou :",
                    "Moi, je dis : « Have you ever been to the sea? »", "Déjà = ever. Écris : ever.")),
         libre("Dis que tu n'es jamais allé à Paris.", ["never", "paris"],
               aides("Comment Modou dit-il qu'il n'est jamais allé à Saint-Louis ?", 2, "Écoute Modou :",
                     "Moi, je dis : « I've never been to Paris. »", "Jamais = never. Écris : « I've never been to Paris. »"))],
        [tour("modou", "Have you ever been to the sea?", "Tu es déjà allé à la mer ?", ["yes|no|never"],
              "Yes, I have!", "Gaïndé has never been to the sea! Ha ha!"),
         tour("awa", "Have you ever eaten thiakry?", "Tu as déjà mangé du thiakry ?", ["yes|no|never"],
              "Yes, I have. I love it!", "Me too! Grandma's thiakry is the best!")],
        ["Have you ever been to the sea?", "Yes, I have.", "I've never been to…"],
    ),
    mission(
        "5e-u3-m4", "Il vient d'arriver !", "dire ce qui s'est passé à l'instant",
        ["I've just arrived.", "She has just eaten."],
        {"consigne": "Modou arrive en retard. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🏃🏾", "🍽️", "🧳", "⏰"],
         "liste": [
             mot("plate", True, "Oui ! « Plate », c'est l'assiette. Elle est vide !"),
             mot("suitcase", True, "Oui ! « Suitcase », c'est la valise de Modou."),
             mot("clock", True, "Oui ! « Clock », c'est le réveil. Modou est en retard !"),
             mot("boy", True, "Oui ! « Boy », c'est le garçon. C'est Modou, il court."),
             mot("bed", False, "« Bed », c'est le lit. Modou ne dort pas, il court ! Regarde encore."),
             mot("rain", False, "« Rain », c'est la pluie. Il fait beau ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Hello! I've just arrived!", "Bonjour ! Je viens d'arriver !"),
                       r("awa", "Oh no, Modou! We have just eaten!", "Oh non, Modou ! On vient de manger !"),
                       r("modou", "What? And grandma?", "Quoi ? Et grand-mère ?"),
                       r("awa", "She has just eaten too!", "Elle vient de manger aussi !")],
         "gainde": "Modou vient d'arriver… et il n'y a plus rien ! Moi, je viens de manger sa part. Chut !"},
        [q("Qu'est-ce que Modou vient de faire ?", ["arriver", "manger", "dormir"], 0, 0),
         q("« We have just eaten » veut dire…", ["On va manger.", "On vient de manger.", "On a faim."], 1, 1)],
        [choix("Je veux dire : « Je viens d'arriver ! » Je dis laquelle ?",
               ["I've just arrived!", "I come to arrive!"], 0,
               aides("Écoute Modou. Il dit « come » ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I've just eaten. »",
                     "« Je viens de… », c'est « I've just… ». Pas « I come to… ».")),
         ordre("« Eaten just has she. » C'est bien ça ?", ["just", "She", "eaten", "has"], "She has just eaten",
               "She has just eaten.",
               aides("Quel mot Awa dit-elle en premier ?", 3, "Écoute Awa :",
                     "Moi, je dis : « She has just eaten. »", "She has just (elle vient de) + eaten (manger).")),
         trou("« I've ___ arrived! » (je viens d'arriver)", "I've", "arrived!", ["just"], "I've just arrived!",
              aides("Quel mot Modou dit-il entre « I've » et « arrived » ?", 0, "Écoute Modou :",
                    "Moi, je dis : « I've just arrived. »", "« Je viens de », c'est « I've just ». Écris : just.")),
         libre("Dis : je viens de manger.", ["just", "eaten|ate|finished"],
               aides("Comment Awa dit-elle « On vient de manger » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « I've just eaten. »", "Écris : « I've just eaten. »"))],
        [tour("modou", "Hey! Where are you? (tu viens d'arriver)", "Hé ! Tu es où ? (tu viens d'arriver)", ["just"],
              "I've just arrived!", "Great! Come and eat!"),
         tour("awa", "Are you hungry? (tu viens de manger)", "Tu as faim ? (tu viens de manger)", ["just"],
              "No, thanks. I've just eaten.", "OK! More for Gaïndé!")],
        ["I've just arrived.", "I've just eaten.", "She has just eaten."],
    ),
    mission(
        "5e-u3-m5", "Il était une fois au village", "raconter une histoire",
        ["Once upon a time…", "One day…", "In the end…"],
        {"consigne": "Le soir, Doudou raconte une histoire. Quels mots vont avec l'image ?", "fond": "nuit",
         "objets": ["🌙", "🔥", "🥁", "⭐"],
         "liste": [
             mot("moon", True, "Oui ! « Moon », c'est la lune."),
             mot("fire", True, "Oui ! « Fire », c'est le feu. On s'assoit autour."),
             mot("drum", True, "Oui ! « Drum », c'est le tama de Doudou."),
             mot("stars", True, "Oui ! « Stars », ce sont les étoiles."),
             mot("sun", False, "« Sun », c'est le soleil. Il fait nuit ! Regarde encore."),
             mot("board", False, "« Board », c'est le tableau de la classe. On est au village, la nuit ! Regarde encore."),
         ]},
        {"fond": "nuit", "persos": ["doudou", "awa", "gainde"],
         "repliques": [r("doudou", "Once upon a time, there was a lion in the village.", "Il était une fois un lion au village."),
                       r("awa", "And then?", "Et après ?"),
                       r("doudou", "One day, the lion went to school.", "Un jour, le lion est allé à l'école."),
                       r("doudou", "In the end, he spoke English!", "À la fin, il parlait anglais !")],
         "gainde": "Un lion qui va à l'école et qui parle anglais ? Hé ! C'est mon histoire !"},
        [q("« Once upon a time » veut dire…", ["Il était une fois", "Un jour", "À la fin"], 0, 0),
         q("À la fin, le lion…", ["mangeait tout", "dormait", "parlait anglais"], 2, 3)],
        [choix("Je commence une histoire. Je dis laquelle ?",
               ["It was one time a lion…", "Once upon a time, there was a lion…"], 1,
               aides("Comment Doudou commence-t-il son histoire ?", 0, "Écoute Doudou :",
                     "Moi, je commence : « Once upon a time, there was a goat… »",
                     "En wolof, on dit « Léeboon ! ». En anglais : « Once upon a time… ».")),
         ordre("« Day one the lion went to school. » C'est bien ça ?",
               ["went", "One", "the", "school", "day", "lion", "to"], "One day the lion went to school",
               "One day, the lion went to school.",
               aides("Quels mots Doudou dit-il en premier ?", 2, "Écoute Doudou :",
                     "Moi, je dis : « One day, the goat went to the market. »",
                     "One day (un jour) + the lion went (le lion est allé) + to school.")),
         trou("« In the ___, he spoke English! » (à la fin)", "In the", ", he spoke English!", ["end"],
              "In the end, he spoke English!",
              aides("Comment Doudou finit-il son histoire ?", 3, "Écoute Doudou :",
                    "Moi, je finis : « In the end, everybody was happy. »", "Fin = end. Écris : end.")),
         libre("Commence une histoire, comme Doudou.", ["once upon a time"],
               aides("Qu'est-ce que Doudou dit tout au début ?", 0, "Écoute Doudou :",
                     "Moi, je dis : « Once upon a time, there was a baobab… »",
                     "Écris : « Once upon a time… » et la suite."))],
        [tour("doudou", "Now it's your turn! Begin a story!", "À toi ! Commence une histoire !",
              ["once upon a time|one day"], "Once upon a time, there was a big baobab.", "Wonderful! And then?"),
         tour("doudou", "How does your story finish?", "Comment ton histoire finit ?", ["in the end|at the end"],
              "In the end, everybody was happy.", "Bravo! What a story!")],
        ["Once upon a time…", "One day…", "And then…", "In the end…"],
    ),
]

unite3 = unite(
    "5e-u3", "Last holidays",
    "Mes dernières vacances : raconte 3 moments de tes vacances.",
    u3,
    lignes=[
        ("Raconter ce que j'ai fait", "Yesterday, I went to the river. · I saw a crocodile!"),
        ("Dire le jour et l'heure", "On Monday the 3rd of August, at half past eight."),
        ("Dire ce que j'ai déjà fait, ou jamais", "Have you ever been to the sea? · I've never…"),
        ("Dire ce qui vient de se passer", "I've just arrived. · She has just eaten."),
        ("Raconter une histoire", "Once upon a time… · One day… · In the end…"),
    ],
    mots=[
        ("yesterday", "hier", "démb"),
        ("river", "fleuve", "dex"),
        ("sea", "mer", "géej"),
        ("bush", "brousse", "àll"),
        ("village", "village", "dëkk"),
        ("crocodile", "crocodile", "jasig"),
        ("travel", "voyager", "tukki"),
        ("help", "aider", "dimbali"),
        ("story", "conte, histoire", "léeb"),
        ("Monday", "lundi", "altine"),
        ("never", "jamais", "mukk"),
    ],
    pieges=[
        "Yesterday, I went to the river. Pas « Yesterday, I have gone ».",
        "At half past eight (8 h 30). Pas « at eight and half ».",
        "I've just arrived (je viens d'arriver). Pas « I come to arrive ».",
    ],
    exercices=[
        ex("Hier, tu es allé au marché. Tu dis :", ["Yesterday, I went to the market.",
           "Yesterday, I have gone to the market.", "Yesterday, I go to the market.", "Tomorrow, I went to the market."], 0,
           "Pour hier : I went."),
        ex("« I saw a crocodile! » veut dire :", ["J'ai vu un crocodile !", "Je vois un crocodile !",
           "J'ai peur du crocodile !", "J'ai mangé un crocodile !"], 0, "Saw = j'ai vu."),
        ex("Comment dit-on 8 h 30 ?", ["at half past eight", "at eight and half", "at half eight past",
           "at eight half"], 0, "Half past eight = 8 h 30."),
        ex("Le lundi 3 août :", ["On Monday the 3rd of August", "In Monday 3 August", "At Monday the 3 August",
           "Monday on the 3rd August of"], 0, "On + le jour + the 3rd of August."),
        ex("Tu demandes à Modou s'il est déjà allé à Dakar :", ["Have you ever been to Dakar?",
           "Are you already gone to Dakar?", "Did you ever go Dakar?", "Have you ever went to Dakar?"], 0,
           "Déjà allé… ? = Have you ever been to… ?"),
        ex("« I've never been to Paris » veut dire :", ["Je ne suis jamais allé à Paris.",
           "Je suis déjà allé à Paris.", "Je vais aller à Paris.", "J'habite à Paris."], 0, "Never = jamais."),
        ex("Tu viens d'arriver. Tu dis :", ["I've just arrived.", "I come to arrive.", "I'm just arrive.",
           "I arrive just."], 0, "Je viens de… = I've just…"),
        ex("Complète : « She has ______ eaten. » (elle vient de manger)", ["just", "never", "ever", "yesterday"], 0,
           "Just = à l'instant."),
        ex("Pour commencer une histoire, on dit :", ["Once upon a time…", "In the end…", "See you tomorrow!",
           "Good night!"], 0, "Once upon a time = il était une fois."),
        ex("« In the end » veut dire :", ["À la fin", "Au début", "Un jour", "Hier"], 0,
           "In the end = à la fin de l'histoire."),
    ],
)



def _varie(u, places=(1, 0, 2, 3, 1, 2, 0, 3, 2, 1)):
    """Place la bonne réponse des exercices à des endroits différents (écrite en premier ci-dessus)."""
    for x, p in zip(u["exercices"], places):
        o = x["options"]
        bonne = o[x["reponse"]]
        autres = [y for i, y in enumerate(o) if i != x["reponse"]]
        autres.insert(p, bonne)
        x["options"], x["reponse"] = autres, p
    return u


UNITES = [_varie(unite1), _varie(unite2), _varie(unite3)]

# ======================= HISTOIRES : LES VACANCES AU VILLAGE =======================

EPISODES = [
    episode("Mon cousin le mouton", "5e-u1-m2", [
        case("marche", [perso("awa", 0.05, 90), perso("gainde", 0.5, 100, "saute")], [
            bulle("Gaïndé, this is my village!", "Gaïndé, voici mon village !", 0.02, 0.05),
            bulle("Wow! Hello, family!", "Waouh ! Bonjour, la famille ! (il saute du car avec la valise sur la tête)", 0.4, 0.35),
        ]),
        case("cour", [perso("awa", 0.02, 90), perso("mouton", 0.35, 90), perso("gainde", 0.62, 95)], [
            bulle("Look! He's my uncle's son.", "Regarde ! C'est le fils de mon oncle. (elle montre un garçon, derrière le mouton)", 0.02, 0.05),
            bulle("Your uncle's son? Pleased to meet you, cousin!", "Le fils de ton oncle ? Enchanté, cousin ! (il serre la patte… du mouton)", 0.4, 0.3),
        ]),
        case("cour", [perso("mouton", 0.1, 90), perso("gainde", 0.45, 95, "danse"), perso("awa", 0.75, 85)], [
            bulle("Bêêê!", "Bêêê !", 0.02, 0.1),
            bulle("Gaïndé! No!", "Gaïndé ! Non !", 0.55, 0.05),
            bulle("Shh! He's my cousin now.", "Chut ! C'est mon cousin, maintenant. (il fait un câlin au mouton)", 0.3, 0.4),
        ]),
        case("cour", [perso("gainde", 0.02, 95), perso("mouton", 0.32, 90), perso("kocc", 0.62, 100)], [
            bulle("Kocc Barma! Let me introduce my cousin!", "Kocc Barma ! Je vous présente mon cousin !", 0.02, 0.05),
            bulle("Pleased to meet… Hey! My book!", "Enchanté… Hé ! Mon livre ! (le mouton mange le livre bleu de Kocc Barma)", 0.45, 0.35),
        ]),
    ], ["He's my uncle's son.", "Let me introduce…", "Pleased to meet you."]),

    episode("Gaïndé est fort en tout", "5e-u1-m4", [
        case("nuit", [perso("doudou", 0.05, 95, "balance"), perso("gainde", 0.55, 100)], [
            bulle("Who is good at singing?", "Qui est fort en chant ?", 0.02, 0.05),
            bulle("Me! I love singing!", "Moi ! J'adore chanter !", 0.45, 0.3),
        ]),
        case("nuit", [perso("gainde", 0.1, 105, "saute"), perso("awa", 0.6, 90)], [
            bulle("GRRRAAAOOO!", "GRRRAAAOOO ! (il chante… tous les chiens du village se cachent)", 0.02, 0.05),
            bulle("Hmm… You are bad at singing.", "Hmm… Tu es nul en chant.", 0.45, 0.35),
        ]),
        case("terrain", [perso("modou", 0.05, 90), perso("gainde", 0.5, 100, "tangue")], [
            bulle("Are you good at wrestling?", "Tu es fort à la lutte ?", 0.02, 0.05),
            bulle("I'm VERY good at wrestling!", "Je suis TRÈS fort à la lutte ! (il tombe tout seul dans le sable, avant le combat)", 0.4, 0.3),
        ]),
        case("maison", [perso("awa", 0.05, 90), perso("gainde", 0.5, 105, "danse")], [
            bulle("Gaïndé, what are you good at?", "Gaïndé, tu es fort en quoi ?", 0.02, 0.05),
            bulle("I'm good at eating! I love eating!", "Je suis fort pour manger ! J'adore manger ! (il a la tête dans le grand bol de grand-mère)", 0.35, 0.35),
        ]),
    ], ["I love singing!", "Are you good at…?", "I'm good at…", "You are bad at…"]),

    episode("Le poisson qui coûte mille francs", "5e-u2-m2", [
        case("marche", [perso("modou", 0.05, 90), perso("gainde", 0.5, 100, "saute")], [
            bulle("Grandma wants fish, rice and oil.", "Grand-mère veut du poisson, du riz et de l'huile.", 0.02, 0.05),
            bulle("Fish! I love fish!", "Du poisson ! J'adore le poisson !", 0.45, 0.35),
        ]),
        case("marche", [perso("gainde", 0.05, 95), perso("poisson", 0.4, 70), perso("doudou", 0.65, 95)], [
            bulle("How much is this fish?", "Combien coûte ce poisson ?", 0.02, 0.05),
            bulle("It costs one thousand francs.", "Il coûte mille francs.", 0.45, 0.3),
        ]),
        case("marche", [perso("gainde", 0.1, 100), perso("poisson", 0.5, 70, "saute")], [
            bulle("Hello, fish! You cost one thousand francs!", "Bonjour, poisson ! Tu coûtes mille francs ! (le poisson est vivant et lui fait un clin d'œil)", 0.02, 0.05),
            bulle("Bloub!", "Bloub !", 0.5, 0.35),
        ]),
        case("maison", [perso("awa", 0.05, 90), perso("gainde", 0.35, 95), perso("poisson", 0.68, 70, "danse")], [
            bulle("Gaïndé! Where is the fish?", "Gaïndé ! Où est le poisson ?", 0.02, 0.05),
            bulle("He's in the bissap!", "Il est dans le bissap ! (le poisson nage, tout content, dans la bassine de bissap de grand-mère)", 0.35, 0.35),
        ]),
    ], ["fish · rice · oil · bissap", "It costs one thousand francs."]),

    episode("Un peu de sel… beaucoup de sel", "5e-u2-m4", [
        case("maison", [perso("awa", 0.05, 90), perso("gainde", 0.5, 100)], [
            bulle("Gaïndé, a little salt, please. And a few onions.", "Gaïndé, un peu de sel, s'il te plaît. Et quelques oignons.", 0.02, 0.05),
            bulle("OK!", "D'accord !", 0.55, 0.35),
        ]),
        case("maison", [perso("gainde", 0.3, 105, "danse")], [
            bulle("A little salt… a lot of salt… a LOT of salt!", "Un peu de sel… beaucoup de sel… BEAUCOUP de sel ! (il vide tout le paquet dans la marmite)", 0.02, 0.05),
            bulle("And a few onions… twenty onions!", "Et quelques oignons… vingt oignons !", 0.3, 0.4),
        ]),
        case("maison", [perso("kocc", 0.05, 95), perso("gainde", 0.4, 95), perso("modou", 0.68, 90, "saute")], [
            bulle("Hmm… How much salt?", "Hmm… Combien de sel ?", 0.02, 0.05),
            bulle("A lot of salt!", "Beaucoup de sel !", 0.3, 0.35),
            bulle("Water! A lot of water!", "De l'eau ! Beaucoup d'eau !", 0.55, 0.05),
        ]),
        case("mer", [perso("kocc", 0.1, 95, "tangue"), perso("modou", 0.5, 90, "tangue")], [
            bulle("Water! A lot of water!", "De l'eau ! Beaucoup d'eau ! (ils courent boire… dans la mer)", 0.02, 0.05),
            bulle("Pfff! A lot of salt!", "Pfff ! Beaucoup de sel ! (l'eau de mer, c'est salé !)", 0.45, 0.35),
        ]),
    ], ["How much salt?", "a little salt", "a lot of water", "a few onions"]),

    episode("Où est mon thiéboudienne ?", "5e-u2-m6", [
        case("maison", [perso("gainde", 0.05, 100, "saute"), perso("awa", 0.55, 90)], [
            bulle("What's this? Who cooks it? When do we eat?", "C'est quoi ? Qui le cuisine ? On mange quand ?", 0.02, 0.05),
            bulle("It's thieboudienne. Grandma cooks it.", "C'est du thiéboudienne. Grand-mère le cuisine.", 0.4, 0.35),
        ]),
        case("maison", [perso("gainde", 0.05, 100, "saute"), perso("awa", 0.55, 90)], [
            bulle("What is it made with? Where is the fish? How often do we eat it?", "C'est fait avec quoi ? Où est le poisson ? On en mange tous les combien ?", 0.02, 0.05),
            bulle("It's made with rice and fish. It's cooked in a big pot.", "C'est fait avec du riz et du poisson. On le cuit dans une grande marmite.", 0.35, 0.38),
        ]),
        case("cour", [perso("kocc", 0.05, 95), perso("gainde", 0.5, 100, "saute")], [
            bulle("Gaïndé! A lot of questions!", "Gaïndé ! Beaucoup de questions !", 0.02, 0.05),
            bulle("Who are you? Where do you live? When…", "Qui êtes-vous ? Où habitez-vous ? Quand… (il pose des questions à Kocc Barma, qu'il connaît très bien)", 0.35, 0.35),
        ]),
        case("maison", [perso("gainde", 0.05, 95), perso("modou", 0.5, 110, "balance")], [
            bulle("Where is my thieboudienne?!", "Où est mon thiéboudienne ?!", 0.02, 0.05),
            bulle("Here! It's made with rice and fish. Very good!", "Ici ! C'est fait avec du riz et du poisson. Très bon ! (Modou tape sur son gros ventre : il a tout mangé)", 0.4, 0.35),
        ]),
    ], ["What…? Who…? Where…? When…? How often…?", "It's made with rice and fish.", "It's cooked in a big pot."]),

    episode("Cent crocodiles", "5e-u3-m2", [
        case("cour", [perso("gainde", 0.1, 100, "saute"), perso("modou", 0.6, 90)], [
            bulle("Yesterday, I went to the river!", "Hier, je suis allé au fleuve !", 0.02, 0.05),
            bulle("And?", "Et alors ?", 0.6, 0.1),
            bulle("I saw a crocodile!", "J'ai vu un crocodile !", 0.15, 0.4),
        ]),
        case("cour", [perso("awa", 0.05, 90), perso("gainde", 0.5, 100)], [
            bulle("When?", "Quand ?", 0.02, 0.05),
            bulle("On Monday… at half past eight… no, at half past nine!", "Lundi… à huit heures et demie… non, à neuf heures et demie !", 0.3, 0.35),
        ]),
        case("cour", [perso("gainde", 0.1, 105, "danse"), perso("modou", 0.6, 90)], [
            bulle("I saw ten crocodiles! A hundred crocodiles!", "J'ai vu dix crocodiles ! Cent crocodiles !", 0.02, 0.05),
            bulle("Wow!", "Waouh !", 0.6, 0.35),
        ]),
        case("cour", [perso("kocc", 0.05, 100), perso("gainde", 0.55, 95, "immobile")], [
            bulle("On Monday, at half past eight, I went to the river too.", "Lundi, à huit heures et demie, je suis allé au fleuve, moi aussi.", 0.02, 0.05),
            bulle("I saw a lion… and an old tree.", "J'ai vu un lion… et un vieux tronc d'arbre. (le « crocodile » de Gaïndé, c'était un tronc d'arbre ! Et Gaïndé a couru très vite…)", 0.02, 0.3),
            bulle("Hmm…", "Hmm… (Gaïndé devient tout rouge)", 0.55, 0.1),
        ]),
    ], ["Yesterday, I went to…", "I saw…", "On Monday", "at half past eight"]),

    episode("Gaïndé vient d'arriver… dans la mer", "5e-u3-m4", [
        case("maison", [perso("modou", 0.05, 90), perso("gainde", 0.55, 95)], [
            bulle("Gaïndé, have you ever been to the sea?", "Gaïndé, tu es déjà allé à la mer ?", 0.02, 0.05),
            bulle("No… I've never been to the sea.", "Non… Je ne suis jamais allé à la mer.", 0.4, 0.35),
        ]),
        case("plage", [perso("gainde", 0.15, 100, "saute"), perso("awa", 0.65, 85)], [
            bulle("The sea! I've just arrived!", "La mer ! Je viens d'arriver ! (il court tout droit vers l'eau)", 0.02, 0.05),
            bulle("Gaïndé! No!", "Gaïndé ! Non !", 0.55, 0.3),
        ]),
        case("mer", [perso("gainde", 0.2, 95, "tangue"), perso("poisson", 0.6, 70, "saute")], [
            bulle("Hello! Have you ever been to the sea?", "Bonjour ! Tu es déjà allé à la mer ?", 0.5, 0.05),
            bulle("Yes… I've just arrived… in the sea!", "Oui… Je viens d'arriver… dans la mer ! (une grosse vague vient de le mouiller)", 0.02, 0.35),
        ]),
        case("plage", [perso("gainde", 0.05, 100, "immobile"), perso("poisson", 0.13, 55), perso("kocc", 0.6, 95)], [
            bulle("Gaïndé! A fish has just arrived… on your head!", "Gaïndé ! Un poisson vient d'arriver… sur ta tête ! (le poisson est assis sur sa crinière, comme un chapeau)", 0.35, 0.05),
            bulle("Hello!", "Bonjour !", 0.05, 0.4),
        ]),
    ], ["Have you ever been to the sea?", "I've never been to…", "I've just arrived!"]),

    episode("L'histoire sans fin", "5e-u3-m5", [
        case("nuit", [perso("doudou", 0.05, 95), perso("gainde", 0.5, 100, "saute")], [
            bulle("Gaïndé, tell a story!", "Gaïndé, raconte une histoire !", 0.02, 0.05),
            bulle("Once upon a time, there was a lion. A very big lion!", "Il était une fois un lion. Un très grand lion !", 0.35, 0.35),
        ]),
        case("nuit", [perso("gainde", 0.3, 105, "danse")], [
            bulle("One day, the lion went to the river. One day, he went to the sea. One day…", "Un jour, le lion est allé au fleuve. Un jour, il est allé à la mer. Un jour…", 0.02, 0.05),
        ]),
        case("nuit", [perso("awa", 0.02, 85), perso("gainde", 0.35, 95, "danse"), perso("modou", 0.68, 85, "immobile")], [
            bulle("And in the end?", "Et à la fin ?", 0.02, 0.05),
            bulle("One day… one day… one day…", "Un jour… un jour… un jour…", 0.3, 0.35),
            bulle("Zzz…", "Zzz… (Modou dort, la tête sur le tama de Doudou)", 0.6, 0.1),
        ]),
        case("cour", [perso("kocc", 0.05, 95), perso("gainde", 0.55, 95, "danse")], [
            bulle("Good morning, Gaïndé!", "Bonjour, Gaïndé ! (c'est le matin : tout le village dort encore)", 0.02, 0.05),
            bulle("…and in the end, the lion said: good morning!", "…et à la fin, le lion a dit : bonjour ! (il a raconté toute la nuit)", 0.3, 0.35),
        ]),
    ], ["Once upon a time…", "One day…", "In the end…"]),
]
