"""Parcours d'anglais de 6e, unités 5 et 6 (avec leurs épisodes, fin de la saison)."""
from jang_lib import *  # noqa: F401,F403

NIVEAU = "6e"

# ======================= UNITÉ 5 : AT THE MARKET =======================

u5 = [
    mission(
        "6e-u5-m1", "Panique au marché : les mangues ont disparu", "dire le nom des fruits et des légumes",
        ["It's a mango.", "They're onions.", "They're tomatoes."],
        {"consigne": "Au marché. Quels mots vont avec l'image ?", "fond": "marche", "objets": ["🥭", "🧅", "🍅", "🍌"],
         "liste": [
             mot("mango", True, "Oui ! « Mango », c'est la mangue. Elle est jaune et verte."),
             mot("onions", True, "Oui ! « Onions », ce sont les oignons."),
             mot("tomatoes", True, "Oui ! « Tomatoes », ce sont les tomates. Elles sont rouges."),
             mot("bananas", True, "Oui ! « Bananas », ce sont les bananes."),
             mot("market", True, "Oui ! « Market », c'est le marché."),
             mot("potatoes", False, "« Potatoes », ce sont les pommes de terre. Je n'en vois pas ici. Regarde encore !"),
             mot("rice", False, "« Rice », c'est le riz. Il n'y a pas de riz sur l'image. Regarde encore !"),
             mot("pen", False, "« Pen », c'est le stylo. On n'est pas en classe ! Regarde encore."),
         ]},
        {"fond": "marche", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "What's this, Awa?", "Qu'est-ce que c'est, Awa ?"),
                       r("awa", "It's a mango.", "C'est une mangue."),
                       r("modou", "And these?", "Et ceux-là ?"),
                       r("awa", "They're onions.", "Ce sont des oignons.")],
         "gainde": "Une mango, des onions… Hmm, et où sont passées toutes les mangues ? (il a la bouche pleine)"},
        [q("Awa montre un fruit. C'est…", ["une mangue", "une banane", "un oignon"], 0, 1),
         q("« They're onions » veut dire…", ["Ce sont des oignons.", "C'est un oignon.", "J'aime les oignons."], 0, 3)],
        [choix("Je montre une mangue. Je dis laquelle ?", ["It's an onion.", "It's a mango."], 1,
               aides("Comment Awa appelle-t-elle la mangue ?", 1, "Écoute Awa :",
                     "Moi, je montre une mangue et je dis : « It's a mango. »",
                     "« Mango », c'est la mangue. « Onion », c'est l'oignon.")),
         ordre("« Red tomatoes they're » ? C'est bien ça ?", ["tomatoes", "They're", "red"], "They're red tomatoes",
               "They're red tomatoes.",
               aides("Awa a dit « They're onions ». Quel mot vient en premier ?", 3, "Écoute Awa :",
                     "Moi, je dis : « They're red tomatoes. »", "They're (ce sont) + red (rouges) + tomatoes (tomates).")),
         trou("Il y a trois bananes. « They're ___. »", "They're", ".", ["bananas", "banana"], "They're bananas.",
              aides("Il y a une banane ou plusieurs bananes ?", 3, "Écoute comment Awa parle des oignons :",
                    "Moi, je dis : « They're onions. » Et pour les bananes ?",
                    "Plusieurs bananes = bananas. Écris : bananas.")),
         libre("Je montre des tomates. Dis-moi ce que c'est.", ["tomatoes|tomato|tomatos"],
               aides("Il y a une tomate ou plusieurs ?", 3, "Écoute Awa : « They're onions. »",
                     "Pour plusieurs choses, on dit « They're… ».", "Écris : « They're tomatoes. »"))],
        [tour("awa", "What's this? (une mangue)", "Qu'est-ce que c'est ? (une mangue)", ["mango"],
              "It's a mango.", "Yes! I like mangoes!"),
         tour("modou", "And these? (des oignons)", "Et ça ? (des oignons)", ["onions|onion"],
              "They're onions.", "Very good!")],
        ["It's a mango.", "They're onions.", "banana", "tomato", "onion"],
    ),
    mission(
        "6e-u5-m2", "Les grands nombres", "compter jusqu'à 10 000",
        ["one hundred", "one thousand", "ten thousand"],
        {"consigne": "Au marché, on compte l'argent. Quels mots vont avec l'image ?", "fond": "marche",
         "objets": ["💰", "🪙", "🔢"],
         "liste": [
             mot("money", True, "Oui ! « Money », c'est l'argent."),
             mot("coins", True, "Oui ! « Coins », ce sont les pièces."),
             mot("numbers", True, "Oui ! « Numbers », ce sont les nombres : 1, 2, 3…"),
             mot("market", True, "Oui ! « Market », c'est le marché."),
             mot("letters", False, "« Letters », ce sont les lettres : A, B, C. Ici, on voit des nombres ! Regarde encore."),
             mot("ball", False, "« Ball », c'est le ballon. On ne joue pas au marché ! Regarde encore."),
         ]},
        {"fond": "marche", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "One hundred, two hundred, three hundred…", "Cent, deux cents, trois cents…"),
                       r("awa", "Look! It's one thousand!", "Regarde ! Ça fait mille !"),
                       r("modou", "And this is ten thousand!", "Et ça, c'est dix mille ! (un gros billet)")],
         "gainde": "Moi, je sais compter jusqu'à vingt. Après vingt, il y a quoi ? Cent ? Mille ? Dix mille ?!"},
        [q("« One thousand », c'est…", ["100", "1 000", "10 000"], 1, 1),
         q("Modou montre un gros billet. C'est…", ["cent", "mille", "dix mille"], 2, 2)],
        [choix("1 000, c'est « one hundred » ? Je dis lequel ?", ["one hundred", "one thousand"], 1,
               aides("Modou compte : cent, deux cents… Et après, Awa dit quoi ?", 1, "Écoute Awa :",
                     "Moi, je compte : one hundred (100)… one thousand (1 000).",
                     "« Hundred », c'est cent. « Thousand », c'est mille.")),
         ordre("« Thousand ten francs » ? C'est ça ?", ["thousand", "francs", "ten"], "ten thousand francs",
               "ten thousand francs",
               aides("En français, on dit « dix mille ». Et en anglais, quel mot vient en premier ?", 2, "Écoute Modou :",
                     "Moi, je dis : « ten thousand francs ».", "Ten (dix) + thousand (mille) + francs.")),
         trou("500, c'est « five ___ ». Il me manque un mot !", "five", "", ["hundred"], "five hundred",
              aides("100, c'est « one hundred ». Et 500 ?", 0, "Écoute Modou compter :",
                    "Moi, je compte : one hundred, two hundred… five hundred.",
                    "Cent = hundred. Écris : hundred.")),
         libre("Écris 2 000 en anglais, en lettres.", ["two thousand"],
               aides("1 000, c'est « one thousand ». Et 2 000 ?", 1, "Écoute Awa :",
                     "Moi, je dis : one thousand, two thousand, three thousand…", "Écris : « two thousand »."))],
        [tour("modou", "Count with me! One hundred, two hundred…", "Compte avec moi ! Cent, deux cents…",
              ["three hundred"], "Three hundred, four hundred!", "Great! You can count!"),
         tour("awa", "Is it one thousand or ten thousand? (10 000)", "C'est mille ou dix mille ? (10 000)",
              ["ten thousand"], "It's ten thousand.", "Yes! Well done!")],
        ["one hundred", "one thousand", "ten thousand", "franc"],
    ),
    mission(
        "6e-u5-m3", "Combien ça coûte ?", "demander le prix",
        ["How much is it?", "It's 2 500 francs."],
        {"consigne": "Au marché. Quels mots vont avec l'image ?", "fond": "marche", "objets": ["🍌", "🏷️", "🧺", "💰"],
         "liste": [
             mot("price", True, "Oui ! « Price », c'est le prix. Il est écrit sur l'étiquette."),
             mot("money", True, "Oui ! « Money », c'est l'argent."),
             mot("basket", True, "Oui ! « Basket », c'est le panier."),
             mot("bananas", True, "Oui ! « Bananas », ce sont les bananes."),
             mot("fish", False, "« Fish », c'est le poisson. On le vend plus loin, pas ici. Regarde encore !"),
             mot("shoes", False, "« Shoes », ce sont les chaussures. Tu en vois ? Non ! Regarde encore."),
         ]},
        {"fond": "marche", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "How much is it, Modou?", "C'est combien, Modou ? (Modou aide sa maman au marché)"),
                       r("modou", "It's two hundred francs.", "C'est deux cents francs."),
                       r("awa", "And the big basket?", "Et le grand panier ?"),
                       r("modou", "It's two thousand five hundred francs!", "C'est deux mille cinq cents francs !")],
         "gainde": "Combien ça coûte, un lionceau ? Euh… non ! Je ne suis pas à vendre !"},
        [q("Comment Awa demande le prix ?", ["How much is it?", "How old are you?", "What's this?"], 0, 0),
         q("Le grand panier coûte…", ["200 francs", "2 500 francs", "25 francs"], 1, 3)],
        [choix("Je veux le prix de la mangue. Je dis laquelle ?", ["How old is it?", "How much is it?"], 1,
               aides("Tu veux l'âge de la mangue ou son prix ?", 0, "Écoute Awa :",
                     "Moi, au marché, je dis : « How much is it? »",
                     "« How old », c'est pour l'âge. « How much », c'est pour le prix.")),
         ordre("« Much how it is? » C'est ça ?", ["much", "is", "How", "it"], "How much is it", "How much is it?",
               aides("Quel mot Awa dit-elle en premier ?", 0, "Écoute Awa :",
                     "Moi, je demande : « How much is it? »", "How much (combien) + is it (c'est).")),
         trou("C'est 500 francs : « It's five hundred ___. »", "It's five hundred", ".", ["francs", "franc", "cfa"],
              "It's five hundred francs.",
              aides("Quel mot Modou dit-il après le nombre ?", 1, "Écoute Modou :",
                    "Moi, je dis : « It's two hundred francs. »", "Au Sénégal, on paie en francs. Écris : francs.")),
         libre("Demande le prix du panier.", ["how much"],
               aides("Comment Awa demande-t-elle le prix ?", 0, "Écoute Awa :",
                     "Moi, je dis : « How much is it? »",
                     "En wolof, on dit « Ñaata la ? ». Écris : « How much is it? »"))],
        [tour("modou", "Hello! Mangoes, bananas, onions…", "Bonjour ! Mangues, bananes, oignons…", ["how much"],
              "How much is it?", "It's three hundred francs."),
         tour("awa", "How much is your pen? (100 francs)", "Ton stylo coûte combien ? (100 francs)",
              ["hundred|100"], "It's one hundred francs.", "OK, thank you!")],
        ["How much is it?", "It's 2 500 francs.", "price", "money"],
    ),
    mission(
        "6e-u5-m4", "Gaïndé fait les courses", "acheter avec politesse",
        ["I'd like a kilo of onions, please.", "Here you are.", "Thank you!"],
        {"consigne": "Au marché. Quels mots vont avec l'image ?", "fond": "marche", "objets": ["🧅", "⚖️", "🛍️"],
         "liste": [
             mot("onions", True, "Oui ! « Onions », ce sont les oignons."),
             mot("scales", True, "Oui ! « Scales », c'est la balance. On pèse les oignons."),
             mot("kilo", True, "Oui ! « Kilo », c'est le kilo. La balance pèse un kilo d'oignons."),
             mot("bag", True, "Oui ! « Bag », c'est le sac pour les courses."),
             mot("mangoes", False, "« Mangoes », ce sont les mangues. Il n'y a pas de mangues ici. Regarde encore !"),
             mot("pencil", False, "« Pencil », c'est le crayon. On fait les courses, pas les devoirs ! Regarde encore."),
         ]},
        {"fond": "marche", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Good morning! I'd like a kilo of onions, please.",
                         "Bonjour ! Je voudrais un kilo d'oignons, s'il te plaît."),
                       r("modou", "Here you are.", "Voilà. (il donne le sac)"),
                       r("awa", "Thank you!", "Merci !")],
         "gainde": "Awa dit « please » et elle a ses oignons. Moi, je dis « Donne ! » et le vendeur se sauve. Pourquoi ?"},
        [q("Que veut Awa ?", ["un kilo d'oignons", "un kilo de mangues", "un sac"], 0, 0),
         q("Modou donne le sac. Il dit…", ["Here you are.", "How much is it?", "Thank you!"], 0, 1)],
        [choix("Je veux des oignons. Je dis laquelle ?", ["Give me onions!", "I'd like a kilo of onions, please."], 1,
               aides("Comment Awa demande-t-elle, avec politesse ?", 0, "Écoute Awa :",
                     "Moi, je dis : « I'd like a kilo of onions, please. »",
                     "« I'd like », c'est « je voudrais ». C'est poli. « Give me! », ce n'est pas poli.")),
         ordre("« Like I'd a kilo of onions » ? C'est ça ?", ["like", "a", "of", "I'd", "onions", "kilo"],
               "I'd like a kilo of onions", "I'd like a kilo of onions, please.",
               aides("Quel mot Awa dit-elle juste après « Good morning » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « I'd like a kilo of onions, please. »",
                     "I'd like (je voudrais) + a kilo (un kilo) + of onions (d'oignons).")),
         trou("Je suis le vendeur. Je donne le sac. « Here ___ are. »", "Here", "are.", ["you"], "Here you are.",
              aides("Qu'est-ce que Modou dit quand il donne le sac ?", 1, "Écoute Modou :",
                    "Moi, je donne un livre et je dis : « Here you are. »", "« Here you are », c'est « voilà ». Écris : you.")),
         libre("Demande un kilo de tomates, poliment.", ["kilo", "tomatoes|tomato|tomatos", "please"],
               aides("Comment Awa a-t-elle demandé les oignons ?", 0, "Écoute Awa :",
                     "Awa dit : « I'd like a kilo of onions, please. » Et pour les tomates ?",
                     "Écris : « I'd like a kilo of tomatoes, please. »"))],
        [tour("modou", "Good morning! What would you like?", "Bonjour ! Qu'est-ce que tu voudrais ?",
              ["like|please"], "I'd like a kilo of onions, please.", "Here you are!"),
         tour("awa", "I'd like a mango, please.", "Je voudrais une mangue, s'il te plaît. (tu es le vendeur)",
              ["here"], "Here you are!", "Thank you!")],
        ["I'd like…, please.", "a kilo of onions", "Here you are.", "Thank you!"],
    ),
    mission(
        "6e-u5-m5", "Le repas de famille", "demander à manger ou à boire",
        ["Can I have some water, please?", "Can I have some rice, please?", "Here you are."],
        {"consigne": "C'est l'heure du repas. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🍚", "🐟", "💧", "🧃"],
         "liste": [
             mot("rice", True, "Oui ! « Rice », c'est le riz. C'est le thiéboudienne !"),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("water", True, "Oui ! « Water », c'est l'eau."),
             mot("juice", True, "Oui ! « Juice », c'est le jus. Ici, un jus de bissap."),
             mot("milk", False, "« Milk », c'est le lait. Il n'y a pas de lait sur l'image. Regarde encore !"),
             mot("bread", False, "« Bread », c'est le pain. Pas de pain à midi ici ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Can I have some water, please?", "Je peux avoir de l'eau, s'il te plaît ?"),
                       r("awa", "Here you are.", "Tiens."),
                       r("awa", "Can I have some fish, please?", "Je peux avoir du poisson, s'il te plaît ?"),
                       r("modou", "Yes! Here you are.", "Oui ! Tiens.")],
         "gainde": "Du riz, du poisson… J'ai faim, moi aussi ! Comment je demande ?"},
        [q("Que demande Modou ?", ["de l'eau", "du riz", "du lait"], 0, 0),
         q("« Can I have…? » veut dire…", ["Je peux avoir… ?", "J'aime…", "Où est… ?"], 0, 2)],
        [choix("J'ai soif. Je dis laquelle ?", ["Can I have some fish, please?", "Can I have some water, please?"], 1,
               aides("Quand on a soif, on veut du poisson ou de l'eau ?", 0, "Écoute Modou :",
                     "Moi, quand j'ai soif, je dis : « Can I have some water, please? »",
                     "« Water », c'est l'eau. « Fish », c'est le poisson.")),
         ordre("« Have I can some rice? » C'est ça ?", ["have", "some", "Can", "rice", "I"], "Can I have some rice",
               "Can I have some rice, please?",
               aides("Quel mot Modou dit-il en premier ?", 0, "Écoute Modou :",
                     "Moi, je dis : « Can I have some rice, please? »",
                     "Can I have (je peux avoir) + some rice (du riz).")),
         trou("« Can I have some ___, please? » (du jus)", "Can I have some", ", please?", ["juice"],
              "Can I have some juice, please?",
              aides("Comment dit-on « jus » ? Regarde l'image du début.", 0, "Écoute comment Modou demande :",
                    "Moi, je dis : « Can I have some water, please? » Et pour le jus ?",
                    "Jus = juice. Écris : juice.")),
         libre("Demande du pain, poliment.", ["can i have|could i have|id like|i would like", "bread"],
               aides("Comment Modou a-t-il demandé de l'eau ?", 0, "Écoute Modou :",
                     "Modou dit : « Can I have some water, please? » Et pour le pain ?",
                     "Pain = bread. Écris : « Can I have some bread, please? »"))],
        [tour("awa", "Rice? Fish? Water? Juice?", "Du riz ? Du poisson ? De l'eau ? Du jus ?",
              ["can i have|could i have|id like|please"], "Can I have some rice, please?", "Here you are!")],
        ["Can I have some water, please?", "Can I have some rice, please?", "Here you are.", "rice", "fish", "juice"],
    ),
]

unite5 = unite(
    "6e-u5", "At the market",
    "Au marché : joue la scène avec un ami. L'un vend, l'autre achète.",
    u5,
    lignes=[
        ("Dire le nom des fruits et des légumes", "It's a mango. · They're onions."),
        ("Compter jusqu'à 10 000", "one hundred · one thousand · ten thousand"),
        ("Demander le prix", "How much is it? — It's 2 500 francs."),
        ("Acheter avec politesse", "I'd like a kilo of onions, please. · Here you are. · Thank you!"),
        ("Demander à manger ou à boire", "Can I have some water, please? — Here you are."),
    ],
    mots=[
        ("mango", "mangue", "mango"),
        ("onion", "oignon", "soble"),
        ("tomato", "tomate", "tamaate"),
        ("rice", "riz", "ceeb"),
        ("fish", "poisson", "jën"),
        ("water", "eau", "ndox"),
        ("bread", "pain", "mburu"),
        ("milk", "lait", "meew"),
        ("money", "argent", "xaalis"),
        ("price", "prix", "njëg"),
        ("one hundred", "cent", "téeméer"),
        ("one thousand", "mille", "junni"),
    ],
    pieges=[
        "How much is it? = c'est combien ? Pas « How many is it? ».",
        "I'd like = je voudrais. I like = j'aime. Au marché, on dit « I'd like ».",
        "Une seule chose : It's a mango. Plusieurs : They're onions.",
    ],
    exercices=[
        ex("Tu montres une seule mangue. Tu dis :", ["They're a mango.", "It's a mango.", "It's mangoes.", "They mango."], 1,
           "Une seule chose : « It's a… ». Plusieurs : « They're… »."),
        ex("Tu montres des oignons. Tu dis :", ["It's onions.", "They're onions.", "They onion.", "It's an onions."], 1,
           "Plusieurs oignons : « They're onions. »"),
        ex("1 000, en anglais, c'est :", ["one hundred", "one thousand", "ten thousand", "ten hundred"], 1,
           "Hundred = cent. Thousand = mille."),
        ex("« Ten thousand », c'est :", ["100", "1 000", "10 000", "110"], 2, "Ten (dix) + thousand (mille) = 10 000."),
        ex("Pour demander le prix, tu dis :", ["How old is it?", "How much is it?", "What's this?", "Where is it?"], 1,
           "« How much is it? » = c'est combien ?"),
        ex("« It's two thousand five hundred francs. » C'est :", ["250 francs", "2 050 francs", "2 500 francs", "25 000 francs"], 2,
           "Two thousand (2 000) + five hundred (500) = 2 500."),
        ex("Tu veux des oignons. Tu dis, poliment :",
           ["Give me onions!", "I'd like a kilo of onions, please.", "I like onions.", "Onions, now!"], 1,
           "« I'd like…, please » = je voudrais…, s'il te plaît."),
        ex("Le vendeur te donne le sac. Il dit :", ["Here you are.", "How much is it?", "I'm fine.", "Goodbye!"], 0,
           "« Here you are » = voilà, tiens."),
        ex("Tu as soif. Tu dis :", ["Can I have some rice, please?", "Can I have some water, please?",
                                    "Can I have some bread, please?", "Can I have some fish, please?"], 1,
           "Water = l'eau."),
        ex("Complète : « Can I ____ some juice, please? »", ["have", "has", "am", "like"], 0,
           "« Can I have…? » = je peux avoir… ?"),
    ],
)

# ======================= UNITÉ 6 : MY VILLAGE, MY TOWN =======================

u6 = [
    mission(
        "6e-u6-m1", "Le village de grand-mère", "parler de mon village ou de mon quartier",
        ["There is a big tree.", "There are many houses."],
        {"consigne": "Au village de la grand-mère d'Awa. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🌳", "🏠", "🕌", "🐐"],
         "liste": [
             mot("tree", True, "Oui ! « Tree », c'est l'arbre. Il est très grand."),
             mot("houses", True, "Oui ! « Houses », ce sont les maisons."),
             mot("mosque", True, "Oui ! « Mosque », c'est la mosquée."),
             mot("goat", True, "Oui ! « Goat », c'est la chèvre."),
             mot("village", True, "Oui ! « Village », c'est le village. Comme en français !"),
             mot("sea", False, "« Sea », c'est la mer. Le village de grand-mère est loin de la mer. Regarde encore !"),
             mot("plane", False, "« Plane », c'est l'avion. Tu vois un avion ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "This is my grandma's village.", "C'est le village de ma grand-mère."),
                       r("awa", "There is a big tree.", "Il y a un grand arbre."),
                       r("modou", "And there are many houses!", "Et il y a beaucoup de maisons !"),
                       r("awa", "There is a mosque, too.", "Il y a aussi une mosquée.")],
         "gainde": "Il y a un arbre, il y a des maisons… Et il y a des lions, dans ce village ?"},
        [q("« There is a big tree » veut dire…", ["Il y a un grand arbre.", "C'est mon arbre.", "L'arbre est petit."], 0, 1),
         q("Au village, il y a beaucoup de…", ["maisons", "mosquées", "lions"], 0, 2)],
        [choix("Au village, il y a un grand arbre. Je dis laquelle ?", ["There is a big house.", "There is a big tree."], 1,
               aides("Comment dit-on « arbre » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « There is a big tree. »", "« Tree », c'est l'arbre. « House », c'est la maison.")),
         ordre("« Many there are houses » ? C'est ça ?", ["are", "houses", "There", "many"], "There are many houses",
               "There are many houses.",
               aides("Quels mots Modou dit-il en premier, après « And » ?", 2, "Écoute Modou :",
                     "Moi, je dis : « There are many houses. »",
                     "There are (il y a) + many (beaucoup de) + houses (maisons).")),
         trou("« There ___ a mosque. » Il me manque un mot !", "There", "a mosque.", ["is"], "There is a mosque.",
              aides("Il y a une mosquée. Awa dit « There… » quoi ?", 3, "Écoute Awa :",
                    "Moi, je dis : « There is a big tree. »", "Pour une seule chose : « There is ». Écris : is.")),
         libre("Dis une chose de ton village ou de ton quartier. Commence par « There is » ou « There are ».",
               ["there is|there are|theres"],
               aides("Qu'est-ce qu'il y a dans ton village ou ton quartier ? Un arbre ? Un marché ?", 1, "Écoute Awa :",
                     "Moi, je dis : « There is a market. There are many shops. »",
                     "En wolof : « Am na garab gu mag » = « There is a big tree »."))],
        [tour("modou", "What is there in your village?", "Qu'est-ce qu'il y a dans ton village ?",
              ["there is|there are|theres"], "There is a big tree.", "Cool! I like your village!"),
         tour("awa", "In my village, there is a well. And in your village?", "Dans mon village, il y a un puits. Et dans ton village ?",
              ["there is|there are|theres"], "There are many houses.", "Nice!")],
        ["There is a big tree.", "There are many houses.", "village", "house", "mosque"],
    ),
    mission(
        "6e-u6-m2", "Le match de foot de Modou", "dire ce que les gens font en ce moment",
        ["Look! Modou is playing football.", "Doudou is singing."],
        {"consigne": "Sur le terrain. Quels mots vont avec l'image ?", "fond": "terrain", "objets": ["⚽", "🥅", "👟", "📣"],
         "liste": [
             mot("ball", True, "Oui ! « Ball », c'est le ballon."),
             mot("goal", True, "Oui ! « Goal », c'est le but."),
             mot("football", True, "Oui ! « Football », c'est le foot."),
             mot("shoes", True, "Oui ! « Shoes », ce sont les chaussures."),
             mot("bed", False, "« Bed », c'est le lit. On ne dort pas sur le terrain ! Regarde encore."),
             mot("book", False, "« Book », c'est le livre. On ne lit pas pendant le match ! Regarde encore."),
         ]},
        {"fond": "terrain", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Look! Modou is playing football.", "Regarde ! Modou joue au foot."),
                       r("modou", "Goal! I'm running!", "But ! Je cours !"),
                       r("awa", "And Gaïndé is sleeping!", "Et Gaïndé dort !")],
         "gainde": "Je ne dors pas ! Je… je regarde le match avec les yeux fermés !"},
        [q("Que fait Modou en ce moment ?", ["Il joue au foot.", "Il dort.", "Il chante."], 0, 0),
         q("Et Gaïndé ?", ["Il court.", "Il dort.", "Il mange."], 1, 2)],
        [choix("Modou court avec le ballon. Je dis laquelle ?", ["Modou is sleeping.", "Modou is playing football."], 1,
               aides("Modou dort ou il joue ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Look! Modou is playing football. »",
                     "« Playing », c'est en train de jouer. « Sleeping », c'est en train de dormir.")),
         ordre("« Playing is Modou football » ? C'est ça ?", ["is", "football", "Modou", "playing"],
               "Modou is playing football", "Look! Modou is playing football.",
               aides("Quel mot Awa dit-elle juste après « Look! » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Modou is playing football. »",
                     "Modou + is playing (est en train de jouer) + football.")),
         trou("Doudou chante en ce moment : « Doudou is ___. »", "Doudou is", ".", ["singing"], "Doudou is singing.",
              aides("Awa dit « playing », « sleeping ». Pour chanter, c'est… ?", 2, "Écoute la fin du mot :",
                    "Moi, je dis : « Doudou is singing. »", "Chanter = sing. En ce moment = singing. Écris : singing.")),
         libre("Awa fait la cuisine. Dis ce qu'elle fait en ce moment.", ["cooking"],
               aides("Qu'est-ce qu'Awa fait ? Elle joue ? Elle cuisine ?", 0, "Écoute comment Awa parle de Modou :",
                     "Moi, je dis : « Look! Awa is cooking. »", "Écris : « Awa is cooking. »"))],
        [tour("awa", "Look at Modou! What is he doing?", "Regarde Modou ! Qu'est-ce qu'il fait ?",
              ["playing|running"], "He's playing football.", "Yes! Go, Modou!")],
        ["Look! Modou is playing football.", "playing", "singing", "cooking", "sleeping"],
    ),
    mission(
        "6e-u6-m3", "Doudou et son tama", "dire ce que je vais faire",
        ["Tomorrow, I'm going to play the tama.", "I'm going to dance."],
        {"consigne": "Doudou et sa musique. Quels mots vont avec l'image ?", "fond": "cour", "objets": ["🥁", "🎶", "💃"],
         "liste": [
             mot("drum", True, "Oui ! « Drum », c'est le tambour. Le tama de Doudou est un petit tambour."),
             mot("music", True, "Oui ! « Music », c'est la musique."),
             mot("song", True, "Oui ! « Song », c'est la chanson."),
             mot("dance", True, "Oui ! « Dance », c'est danser."),
             mot("piano", False, "« Piano », c'est le piano. C'est grand, avec des touches. Tu en vois ? Non ! Regarde encore."),
             mot("guitar", False, "« Guitar », c'est la guitare. Doudou joue du tama, pas de la guitare ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "doudou", "gainde"],
         "repliques": [r("awa", "What are you going to do tomorrow, Doudou?", "Qu'est-ce que tu vas faire demain, Doudou ?"),
                       r("doudou", "Tomorrow, I'm going to play the tama.", "Demain, je vais jouer du tama."),
                       r("awa", "Cool! I'm going to dance!", "Super ! Moi, je vais danser !")],
         "gainde": "Demain ? Moi, demain, je vais… manger ! Et dormir ! Comment je le dis ?"},
        [q("Que va faire Doudou demain ?", ["jouer du tama", "jouer au foot", "dormir"], 0, 1),
         q("« I'm going to dance » veut dire…", ["Je vais danser.", "Je danse.", "J'aime danser."], 0, 2)],
        [choix("Demain, je vais chanter à la fête. Je dis laquelle ?",
               ["Tomorrow, I'm going to sleep.", "Tomorrow, I'm going to sing."], 1,
               aides("Tu vas dormir ou chanter à la fête ?", 1, "Écoute comment Doudou parle de demain :",
                     "Moi, je dis : « Tomorrow, I'm going to sing. »",
                     "« Sing », c'est chanter. « Sleep », c'est dormir.")),
         ordre("« Going I'm to play the tama » ? C'est ça ?", ["to", "I'm", "the", "going", "play", "tama"],
               "I'm going to play the tama", "Tomorrow, I'm going to play the tama.",
               aides("Quel mot Doudou dit-il juste après « Tomorrow » ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « I'm going to play the tama. »",
                     "I'm going to (je vais) + play the tama (jouer du tama).")),
         trou("« Tomorrow, I'm ___ to dance. » Il me manque un mot !", "Tomorrow, I'm", "to dance.", ["going"],
              "Tomorrow, I'm going to dance.",
              aides("Awa dit « I'm… to dance ». Quel mot est au milieu ?", 2, "Écoute Awa :",
                    "Moi, je dis : « I'm going to dance. »", "« I'm going to », c'est « je vais ». Écris : going.")),
         libre("Dis ce que tu vas faire demain.", ["going to|gonna"],
               aides("Demain, tu vas jouer ? Lire ? Aller au marché ?", 1, "Écoute Doudou :",
                     "Moi, je dis : « Tomorrow, I'm going to read a book. »",
                     "Commence par : « Tomorrow, I'm going to… »"))],
        [tour("doudou", "What are you going to do tomorrow?", "Qu'est-ce que tu vas faire demain ?",
              ["going to|gonna"], "Tomorrow, I'm going to play football.", "Great! See you tomorrow!")],
        ["Tomorrow, I'm going to play the tama.", "I'm going to dance.", "tomorrow"],
    ),
    mission(
        "6e-u6-m4", "Le SMS de Gaïndé", "écrire un SMS",
        ["Hi! C U 2morrow! Thx!", "pls", "2day"],
        {"consigne": "Awa écrit à Modou. Quels mots vont avec l'image ?", "fond": "maison", "objets": ["📱", "💬", "😀"],
         "liste": [
             mot("phone", True, "Oui ! « Phone », c'est le téléphone."),
             mot("message", True, "Oui ! « Message », c'est le message. Comme en français !"),
             mot("screen", True, "Oui ! « Screen », c'est l'écran du téléphone."),
             mot("smile", True, "Oui ! « Smile », c'est le sourire. Regarde le petit visage."),
             mot("letter", False, "« Letter », c'est une lettre, avec une enveloppe et un timbre. Ici, c'est un SMS ! Regarde encore."),
             mot("radio", False, "« Radio », c'est la radio. Tu vois une radio ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Hi Modou! C U 2morrow! Thx!", "Salut Modou ! À demain ! Merci ! (Awa lit son SMS)"),
                       r("modou", "C U? What's this?", "C U ? C'est quoi ?"),
                       r("awa", "C U is see you. 2morrow is tomorrow.", "C U, c'est « see you ». 2morrow, c'est « tomorrow »."),
                       r("modou", "Cool! Thx!", "Cool ! Merci !")],
         "gainde": "C U ? 2morrow ? Ce sont des maths ou de l'anglais ?"},
        [q("Dans un SMS, « C U » veut dire…", ["see you (à plus)", "thank you (merci)", "hello (bonjour)"], 0, 2),
         q("Dans un SMS, « Thx », c'est…", ["thanks (merci)", "tomorrow (demain)", "please (s'il te plaît)"], 0, 3)],
        [choix("Je veux écrire « À demain » dans un SMS. J'écris laquelle ?", ["C U 2day!", "C U 2morrow!"], 1,
               aides("Demain, en anglais, c'est « today » ou « tomorrow » ?", 2, "Écoute Awa :",
                     "Moi, j'écris : « C U 2morrow! »", "« 2day » = today (aujourd'hui). « 2morrow » = tomorrow (demain).")),
         ordre("« 2morrow U C » ? C'est ça ?", ["2morrow", "U", "C"], "C U 2morrow", "C U 2morrow!",
               aides("« C U », c'est « see you ». Quelle lettre vient en premier ?", 0, "Écoute le SMS d'Awa :",
                     "Moi, j'écris : « C U 2morrow! »", "C U (see you) + 2morrow (tomorrow) = à demain.")),
         trou("Je dis merci en SMS, en tout petit : « ___! »", "", "!", ["thx", "thanks", "thank you", "thks", "tnx", "ty"],
              "Thx!",
              aides("Comment Awa écrit-elle « merci » à la fin de son SMS ?", 0, "Écoute Awa :",
                    "Moi, j'écris : « Thx! »", "« Thx », c'est « thanks » en SMS. Écris : thx.")),
         libre("Écris un SMS à Awa : dis salut et à demain.", ["hi|hello|hey", "2morrow|tomorrow|2moro|tmrw|tmr"],
               aides("Comment Awa commence-t-elle son SMS ? Et comment dit-elle « à demain » ?", 0, "Écoute Awa :",
                     "Moi, j'écris : « Hi Modou! C U 2morrow! »", "Écris : « Hi Awa! C U 2morrow! »"))],
        [tour("modou", "(SMS) Hi! Football 2day?", "(SMS) Salut ! Foot aujourd'hui ?",
              ["yes|ok|okay|no|thx|thanks|cool|c u|see you"], "Yes! C U 2day! Thx!", "Cool! C U!")],
        ["C U = see you", "2morrow = tomorrow", "2day = today", "thx = thanks", "pls = please"],
    ),
    mission(
        "6e-u6-m5", "Ma journée au village", "raconter ma journée",
        ["First, I get up.", "Then, I go to the well.", "After that, I eat rice.", "Finally, I sleep."],
        {"consigne": "Une journée au village. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🌅", "🐐", "🍚", "🌙"],
         "liste": [
             mot("morning", True, "Oui ! « Morning », c'est le matin. Le soleil se lève."),
             mot("goat", True, "Oui ! « Goat », c'est la chèvre."),
             mot("rice", True, "Oui ! « Rice », c'est le riz du repas."),
             mot("moon", True, "Oui ! « Moon », c'est la lune, le soir."),
             mot("snow", False, "« Snow », c'est la neige. Il ne neige jamais au village ! Regarde encore."),
             mot("plane", False, "« Plane », c'est l'avion. Tu vois un avion ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "First, I get up and I wash.", "D'abord, je me lève et je me lave."),
                       r("awa", "Then, I go to the well.", "Ensuite, je vais au puits."),
                       r("awa", "After that, I eat rice with grandma.", "Après ça, je mange du riz avec grand-mère."),
                       r("awa", "Finally, I sleep under the big tree!", "Enfin, je dors sous le grand arbre !")],
         "gainde": "Moi, ma journée : d'abord, je mange. Ensuite, je mange. Enfin… je mange !"},
        [q("Que fait Awa en premier ?", ["Elle se lève.", "Elle mange du riz.", "Elle dort."], 0, 0),
         q("« Finally » veut dire…", ["enfin", "d'abord", "ensuite"], 0, 3)],
        [choix("Je commence à raconter ma journée. Je dis laquelle ?", ["Finally, I get up.", "First, I get up."], 1,
               aides("Comment Awa commence-t-elle son histoire ?", 0, "Écoute Awa :",
                     "Moi, je commence : « First, I get up. »", "« First », c'est d'abord. « Finally », c'est enfin.")),
         ordre("« That after, I eat rice » ? C'est ça ?", ["that", "After", "I", "rice", "eat"], "After that I eat rice",
               "After that, I eat rice.",
               aides("Quel mot Awa dit-elle en premier, avant « that » ?", 2, "Écoute Awa :",
                     "Moi, je dis : « After that, I eat rice. »", "After that (après ça) + I eat rice (je mange du riz).")),
         trou("« ___, I go to the well. » (ensuite)", "", ", I go to the well.", ["then", "next"],
              "Then, I go to the well.",
              aides("Comment dit-on « ensuite » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « Then, I go to the well. »", "Ensuite = then. Écris : then.")),
         libre("Raconte la fin de ta journée. Commence par « Finally ».", ["finally"],
               aides("Le soir, qu'est-ce que tu fais à la fin ?", 3, "Écoute Awa :",
                     "Moi, je dis : « Finally, I sleep. »", "Écris : « Finally, I sleep. »"))],
        [tour("kocc", "Tell me about your day. What do you do first?", "Raconte-moi ta journée. Que fais-tu d'abord ?",
              ["first"], "First, I get up at six.", "Very good! And then?"),
         tour("kocc", "And then?", "Et ensuite ?", ["then|after that|finally|next"],
              "Then, I go to school.", "Well done! You can tell a story!")],
        ["First…", "Then…", "After that…", "Finally…"],
    ),
]

unite6 = unite(
    "6e-u6", "My village, my town",
    "Mon village : décris ton village ou ton quartier en 5 phrases.",
    u6,
    lignes=[
        ("Parler de mon village", "There is a big tree. · There are many houses."),
        ("Dire ce que les gens font en ce moment", "Look! Modou is playing football."),
        ("Dire ce que je vais faire", "Tomorrow, I'm going to play the tama."),
        ("Écrire un SMS", "Hi! · C U 2morrow! · Thx! · pls · 2day"),
        ("Raconter ma journée", "First… · Then… · After that… · Finally…"),
    ],
    mots=[
        ("village", "village", "dëkk"),
        ("house", "maison", "kër"),
        ("tree", "arbre", "garab"),
        ("mosque", "mosquée", "jumaa"),
        ("well", "puits", "teen"),
        ("market", "marché", "marse"),
        ("road", "route", "yoon"),
        ("field", "champ", "tool"),
        ("shop", "boutique", "bitig"),
        ("tomorrow", "demain", "suba"),
    ],
    pieges=[
        "There are many houses (plusieurs). Pas « There is many houses ».",
        "Modou is playing (en ce moment). Pas « Modou playing ».",
        "C U, 2morrow, thx : seulement dans les SMS, pas dans un devoir !",
    ],
    exercices=[
        ex("Au village, il y a un grand arbre :", ["There is a big tree.", "There are a big tree.", "It is tree big.", "There big tree."], 0,
           "Pour une seule chose : « There is… »."),
        ex("Il y a beaucoup de maisons :", ["There is many houses.", "There are many houses.", "There many houses.", "It's many house."], 1,
           "Pour plusieurs choses : « There are… »."),
        ex("Modou joue au foot en ce moment :", ["Modou play football.", "Modou is playing football.",
                                                 "Modou playing football.", "Modou is play football."], 1,
           "En ce moment : « is playing »."),
        ex("« Doudou is singing. » veut dire :", ["Doudou chante, en ce moment.", "Doudou va chanter.",
                                                  "Doudou aime chanter.", "Doudou ne chante pas."], 0,
           "« is singing » = il est en train de chanter."),
        ex("Demain, je vais jouer du tama :", ["Tomorrow, I play the tama.", "Tomorrow, I'm going to play the tama.",
                                               "Tomorrow, I going play the tama.", "Tomorrow, I'm play the tama."], 1,
           "« I'm going to… » = je vais…"),
        ex("« I'm going to dance. » veut dire :", ["Je danse.", "Je vais danser.", "J'aime danser.", "Je ne danse pas."], 1,
           "« I'm going to » = je vais."),
        ex("Dans un SMS, « C U 2morrow! » veut dire :", ["À demain !", "Merci !", "S'il te plaît !", "Bonjour !"], 0,
           "C U = see you. 2morrow = tomorrow."),
        ex("Dans un SMS, « Thx » veut dire :", ["merci", "s'il te plaît", "demain", "aujourd'hui"], 0,
           "Thx = thanks = merci. Pls = please."),
        ex("Pour commencer à raconter ta journée, tu dis :", ["Finally…", "First…", "After that…", "Tomorrow…"], 1,
           "First = d'abord. On commence par « First »."),
        ex("« Ensuite, je vais au marché. »", ["Then, I go to the market.", "First, I go to the market.",
                                              "Finally, I go to the market.", "Tomorrow, I go to the market."], 0,
           "Then = ensuite."),
    ],
)

UNITES = [unite5, unite6]

# ======================= LES ÉPISODES =======================

EPISODES = [
    episode("Le voleur de mangues", "6e-u5-m2", [
        case("marche", [perso("awa", 0.05, 95), perso("gainde", 0.6, 95)], [
            bulle("They're onions. They're tomatoes…", "Ce sont des oignons. Ce sont des tomates…", 0.03, 0.04),
            bulle("But… where are the mangoes?!", "Mais… où sont les mangues ?! (la table des mangues est vide)", 0.03, 0.3)]),
        case("marche", [perso("modou", 0.05, 95), perso("gainde", 0.55, 110)], [
            bulle("Gaïndé! What's this?", "Gaïndé ! Qu'est-ce que c'est ? (il montre le ventre tout rond de Gaïndé)", 0.03, 0.04),
            bulle("It's… a ball!", "C'est… un ballon !", 0.5, 0.32)]),
        case("marche", [perso("modou", 0.05, 90), perso("gainde", 0.55, 110, "balance")], [
            bulle("One hundred… two hundred… one thousand!", "Cent… deux cents… mille ! (Modou compte les noyaux autour de Gaïndé)", 0.02, 0.04),
            bulle("Hmm… one thousand and one!", "Hmm… mille et un ! (il mange encore une mangue, cachée dans sa crinière)", 0.45, 0.34)]),
        case("marche", [perso("kocc", 0.02, 95), perso("gainde", 0.35, 95), perso("bouc", 0.68, 80)], [
            bulle("Gaïndé! The mangoes?", "Gaïndé ! Les mangues ?", 0.02, 0.03),
            bulle("It's the goat!", "C'est le bouc ! (une mangue tombe de sa crinière… plouf)", 0.3, 0.32),
            bulle("Bêêê!", "Bêêê ! (le bouc n'est pas content)", 0.62, 0.08)]),
    ], ["It's a mango.", "They're onions.", "What's this?", "one hundred", "one thousand"]),

    episode("Un kilo de… lions ?", "6e-u5-m4", [
        case("marche", [perso("gainde", 0.05, 95, "saute"), perso("modou", 0.6, 95)], [
            bulle("Good morning! I'd like a kilo of… lions, please!", "Bonjour ! Je voudrais un kilo de… lions, s'il te plaît !", 0.03, 0.04),
            bulle("Lions?!", "Des lions ?! (Modou tremble derrière ses légumes)", 0.55, 0.3)]),
        case("marche", [perso("gainde", 0.05, 95), perso("modou", 0.6, 95)], [
            bulle("No! No! Onions! A kilo of onions, please.", "Non ! Non ! Des oignons ! Un kilo d'oignons, s'il te plaît.", 0.03, 0.04),
            bulle("Ah! Here you are.", "Ah ! Voilà.", 0.55, 0.32)]),
        case("marche", [perso("gainde", 0.05, 95), perso("modou", 0.6, 95)], [
            bulle("How much is it?", "C'est combien ?", 0.03, 0.04),
            bulle("It's five hundred francs.", "C'est cinq cents francs. (Gaïndé fouille dans sa crinière : un noyau de mangue, une plume, un caillou…)", 0.5, 0.32)]),
        case("marche", [perso("gainde", 0.02, 95, "saute"), perso("modou", 0.35, 90), perso("kocc", 0.68, 95)], [
            bulle("Here you are! It's a pen.", "Voilà ! C'est un stylo. (il paie avec un stylo)", 0.02, 0.03),
            bulle("Hmm… OK! Thank you!", "Hmm… D'accord ! Merci !", 0.3, 0.34),
            bulle("My pen?!", "Mon stylo ?! (Kocc Barma fouille ses poches)", 0.6, 0.06)]),
    ], ["I'd like a kilo of onions, please.", "Here you are.", "How much is it?", "It's five hundred francs.", "Thank you!"]),

    episode("Encore, s'il te plaît !", "6e-u5-m5", [
        case("maison", [perso("awa", 0.05, 95), perso("gainde", 0.6, 95)], [
            bulle("Can I have some rice, please?", "Je peux avoir du riz, s'il te plaît ?", 0.5, 0.04),
            bulle("Here you are.", "Tiens.", 0.03, 0.3)]),
        case("maison", [perso("modou", 0.05, 95), perso("gainde", 0.6, 105)], [
            bulle("Can I have some fish, please?", "Je peux avoir du poisson, s'il te plaît ?", 0.5, 0.04),
            bulle("Here you are.", "Tiens. (Gaïndé mange le poisson… et l'assiette avec)", 0.03, 0.3)]),
        case("maison", [perso("awa", 0.05, 95), perso("gainde", 0.6, 105)], [
            bulle("Can I have some water, please?", "Je peux avoir de l'eau, s'il te plaît ?", 0.5, 0.04),
            bulle("Here you are!", "Tiens ! (Awa lui verse tout le seau sur la tête. Splash !)", 0.03, 0.3)]),
        case("maison", [perso("gainde", 0.02, 100), perso("mouton", 0.4, 85, "saute"), perso("awa", 0.7, 90)], [
            bulle("Can I have some… please?", "Je peux avoir un peu de… (il regarde le mouton et se lèche les babines) …s'il te plaît ?", 0.02, 0.03),
            bulle("Bêêê!!!", "Bêêê !!! (le mouton s'enfuit en courant)", 0.38, 0.32),
            bulle("No, Gaïndé!", "Non, Gaïndé !", 0.62, 0.06)]),
    ], ["Can I have some rice, please?", "Can I have some water, please?", "Here you are."]),

    episode("Un ballon dans l'arbre", "6e-u6-m2", [
        case("maison", [perso("awa", 0.05, 95), perso("gainde", 0.6, 95, "saute")], [
            bulle("This is my grandma's village. There is a big tree.", "C'est le village de ma grand-mère. Il y a un grand arbre.", 0.03, 0.04),
            bulle("There are many houses!", "Il y a beaucoup de maisons !", 0.5, 0.34)]),
        case("terrain", [perso("modou", 0.05, 95), perso("bouc", 0.6, 85, "danse")], [
            bulle("Look! The goat is playing football!", "Regarde ! Le bouc joue au foot !", 0.03, 0.04),
            bulle("Bêêê!", "Bêêê ! (le bouc dribble très bien)", 0.58, 0.3)]),
        case("terrain", [perso("gainde", 0.3, 105, "saute")], [
            bulle("I'm playing football too!", "Moi aussi, je joue au foot ! (il tire très fort… le ballon monte, monte…)", 0.05, 0.05)]),
        case("maison", [perso("awa", 0.02, 90), perso("modou", 0.35, 90), perso("gainde", 0.68, 90, "balance")], [
            bulle("Where is the ball?", "Où est le ballon ?", 0.02, 0.03),
            bulle("There is a ball in the big tree… and there is a lion!", "Il y a un ballon dans le grand arbre… et il y a un lion !", 0.3, 0.34),
            bulle("Hello!", "Coucou ! (Gaïndé est coincé tout en haut de l'arbre, le ballon sur la tête)", 0.6, 0.06)]),
    ], ["There is a big tree.", "There are many houses.", "Look! The goat is playing football!", "I'm playing football."]),

    episode("Le SMS de la nuit", "6e-u6-m4", [
        case("nuit", [perso("gainde", 0.35, 105)], [
            bulle("Hi Doudou! 2morrow, I'm going to play the tama! C U!", "Salut Doudou ! Demain, je vais jouer du tama ! À plus ! (Gaïndé écrit un SMS, la langue entre les dents)", 0.05, 0.05)]),
        case("nuit", [perso("kocc", 0.35, 105)], [
            bulle("Hi Doudou? I'm not Doudou!", "« Salut Doudou » ? Je ne suis pas Doudou ! (Kocc Barma lit le SMS dans son lit, avec un bonnet de nuit)", 0.05, 0.05)]),
        case("cour", [perso("gainde", 0.05, 100, "saute"), perso("awa", 0.6, 90)], [
            bulle("BOOM! BOOM! I'm playing the tama!", "BOUM ! BOUM ! Je joue du tama !", 0.03, 0.04),
            bulle("Pls, Gaïndé! Pls!", "S'il te plaît, Gaïndé ! S'il te plaît ! (elle se bouche les oreilles)", 0.5, 0.32)]),
        case("cour", [perso("modou", 0.05, 95), perso("gainde", 0.6, 95)], [
            bulle("Gaïndé! It's not a tama! It's my ball!", "Gaïndé ! Ce n'est pas un tama ! C'est mon ballon ! (le ballon se dégonfle : pfffff…)", 0.03, 0.04),
            bulle("Oh… Thx?", "Oh… Merci ?", 0.55, 0.34)]),
    ], ["Tomorrow, I'm going to play the tama.", "C U!", "2morrow", "Thx!", "Pls!"]),

    episode("Le premier rugissement", "6e-u6-m5", [
        case("classe", [perso("kocc", 0.05, 100), perso("gainde", 0.6, 95)], [
            bulle("Gaïndé, tell us about your day!", "Gaïndé, raconte-nous ta journée ! (c'est le dernier jour de l'année)", 0.03, 0.04),
            bulle("First, I get up…", "D'abord, je me lève… (il bâille si fort qu'on voit toutes ses dents)", 0.5, 0.34)]),
        case("classe", [perso("gainde", 0.05, 95), perso("modou", 0.6, 95, "danse")], [
            bulle("Then, I eat. After that, I eat. Then… I eat!", "Ensuite, je mange. Après ça, je mange. Ensuite… je mange !", 0.03, 0.04),
            bulle("Ha ha! And finally?", "Ha ha ! Et enfin ?", 0.55, 0.34)]),
        case("classe", [perso("gainde", 0.3, 110)], [
            bulle("Finally… I speak English!", "Enfin… je parle anglais ! (il gonfle sa poitrine et prend une grande respiration…)", 0.05, 0.05)]),
        case("classe", [perso("gainde", 0.05, 115, "saute"), perso("kocc", 0.6, 100)], [
            bulle("ROAR!", "ROAAAR ! (son premier vrai rugissement… en anglais !)", 0.05, 0.04),
            bulle("Hmm… very good, Gaïndé.", "Hmm… très bien, Gaïndé. (les quatre touffes de Kocc Barma sont toutes droites, ses lunettes sont sur sa tête)", 0.45, 0.34)]),
        case("cour", [perso("awa", 0.02, 90), perso("gainde", 0.35, 100, "danse"), perso("doudou", 0.68, 90, "saute")], [
            bulle("Your first roar in English! Well done, Gaïndé!", "Ton premier rugissement en anglais ! Bravo, Gaïndé !", 0.02, 0.03),
            bulle("Thx! And finally… ROAR!", "Merci ! Et enfin… ROAR ! (Doudou joue du tama, tout le monde danse. Le tama de Doudou s'envole. Fin de la saison !)", 0.3, 0.34)]),
    ], ["First…", "Then…", "After that…", "Finally…"]),
]
