"""Parcours d'anglais de 6e, unités 3 et 4 (avec leurs épisodes)."""
from jang_lib import *  # noqa: F401,F403

NIVEAU = "6e"

JOURS = "monday|tuesday|wednesday|thursday|friday|saturday|sunday"
MOIS = "january|february|march|april|may|june|july|august|september|october|november|december"
HEURES = "one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|1|2|3|4|5|6|7|8|9|10|11|12"

# ======================= UNITÉ 3 : MY FAMILY =======================

u3 = [
    mission(
        "6e-u3-m1", "La photo de famille de Modou", "parler de ma famille",
        ["This is my mother.", "This is my father.", "I've got two sisters."],
        {"consigne": "La photo de famille de Modou. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🖼️", "👩", "👨", "👧", "👶"],
         "liste": [
             mot("mother", True, "Oui ! « Mother », c'est la mère. C'est la maman de Modou."),
             mot("father", True, "Oui ! « Father », c'est le père. C'est le papa de Modou."),
             mot("sister", True, "Oui ! « Sister », c'est la sœur. Voilà la petite sœur."),
             mot("baby", True, "Oui ! « Baby », c'est le bébé de la famille."),
             mot("photo", True, "Oui ! « Photo », c'est la photo. Comme en français !"),
             mot("teacher", False, "« Teacher », c'est le prof. Kocc Barma n'est pas sur la photo ! Regarde encore."),
             mot("goat", False, "« Goat », c'est la chèvre. Elle n'est pas dans la famille ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Look! This is my family.", "Regarde ! C'est ma famille."),
                       r("modou", "This is my mother, and this is my father.", "Ça, c'est ma mère, et ça, c'est mon père."),
                       r("modou", "I've got two sisters and one brother.", "J'ai deux sœurs et un frère."),
                       r("awa", "Wow! A big family!", "Waouh ! Une grande famille !")],
         "gainde": "Une mère, un père, deux sœurs… Et ma famille de lions, je la montre comment ?"},
        [q("Modou montre qui en premier ?", ["sa mère", "son prof", "son chat"], 0, 1),
         q("Modou a combien de sœurs ?", ["une", "deux", "trois"], 1, 2)],
        [choix("Je montre la maman de Modou sur la photo. Je dis « This is my father » ?",
               ["This is my father.", "This is my mother."], 1,
               aides("La maman, c'est une femme. Quel mot Modou dit-il pour sa maman ?", 1, "Écoute Modou :",
                     "Moi, je dis : « This is my mother. »", "Mother = la mère. Father = le père.")),
         ordre("« Got I've two sisters. » C'est bien ça ?", ["two", "I've", "sisters", "got"], "I've got two sisters",
               "I've got two sisters.",
               aides("Quel mot Modou dit-il en premier ?", 2, "Écoute Modou :",
                     "Moi, je dis : « I've got two brothers. »", "I've got (j'ai) + two sisters (deux sœurs).")),
         trou("Je montre mon papa : « This is my ___. »", "This is my", ".", ["father", "dad"], "This is my father.",
              aides("Comment Modou dit-il « mon père » ?", 1, "Écoute Modou :",
                    "Moi, je dis : « This is my father. »", "Le père = father. Écris : father.")),
         libre("Je montre le frère de Modou sur la photo. Comment je dis « C'est mon frère » ?",
               ["this is my|thats my|its my", "brother"],
               aides("Modou dit « This is my… ». Et « frère », c'est quoi ?", 2, "Écoute Modou :",
                     "Moi, je dis : « This is my sister. »", "Frère = brother. Écris : « This is my brother. »"))],
        [tour("awa", "Have you got brothers or sisters?", "Tu as des frères ou des sœurs ?",
              ["brother|brothers|sister|sisters|no"], "I've got two sisters.", "Nice! I've got one brother."),
         tour("gainde", "Who is this on your photo? (ta maman)", "C'est qui, sur ta photo ? (ta maman)",
              ["mother|mum|mom|mummy"], "This is my mother.", "Oh! Good morning, Madam!")],
        ["This is my family.", "This is my mother.", "This is my father.", "I've got two sisters.", "brother"],
    ),
    mission(
        "6e-u3-m2", "Il est comment ?", "dire comment est une personne (grand, petit…)",
        ["He's tall.", "She's short.", "She has got long hair."],
        {"consigne": "Devant l'école. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["🧍‍♂️", "👧", "💇‍♀️"],
         "liste": [
             mot("tall", True, "Oui ! « Tall », c'est grand. Le grand garçon, là."),
             mot("short", True, "Oui ! « Short », c'est petit. La petite fille, là."),
             mot("hair", True, "Oui ! « Hair », ce sont les cheveux."),
             mot("long", True, "Oui ! « Long », c'est long. Elle a les cheveux longs."),
             mot("boy", True, "Oui ! « Boy », c'est un garçon."),
             mot("hat", False, "« Hat », c'est le chapeau. Personne n'a de chapeau ici ! Regarde encore."),
             mot("old", False, "« Old », c'est vieux. Tu vois un grand-père ? Non ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Look! My brother Ibou is here.", "Regarde ! Mon frère Ibou est là."),
                       r("awa", "He's tall. He has got short hair.", "Il est grand. Il a les cheveux courts."),
                       r("modou", "And your sister?", "Et ta sœur ?"),
                       r("awa", "She's short. She has got long hair.", "Elle est petite. Elle a les cheveux longs.")],
         "gainde": "Grand, petit, cheveux longs… Et moi ? Moi, j'ai une crinière !"},
        [q("Le frère d'Awa est…", ["grand", "petit", "vieux"], 0, 1),
         q("La sœur d'Awa a…", ["les cheveux longs", "les cheveux courts", "un chapeau"], 0, 3)],
        [choix("Ibou est très grand. Je dis « He's short » ?", ["He's short.", "He's tall."], 1,
               aides("Grand, c'est « tall » ou « short » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Modou is tall. »", "Tall = grand. Short = petit.")),
         ordre("« Long has she got hair. » C'est bien ça ?", ["hair", "has", "She", "long", "got"],
               "She has got long hair", "She has got long hair.",
               aides("Quel mot Awa dit-elle en premier ?", 3, "Écoute Awa :",
                     "Moi, je dis : « He has got short hair. »",
                     "She has got (elle a) + long hair (les cheveux longs). La taille vient avant « hair ».")),
         trou("Le frère de Modou est petit : « He's ___. »", "He's", ".", ["short", "small"], "He's short.",
              aides("Comment Awa dit-elle que sa sœur est petite ?", 3, "Écoute Awa :",
                    "Moi, je dis : « She's short. »", "Petit = short. Écris : short.")),
         libre("Modou a les cheveux courts. Comment je le dis ?", ["short hair"],
               aides("Comment Awa parle-t-elle des cheveux d'Ibou ?", 1, "Écoute Awa :",
                     "Moi, je dis : « Awa has got long hair. »", "Écris : « He has got short hair. »"))],
        [tour("modou", "Is your best friend tall or short?", "Ton meilleur ami est grand ou petit ?",
              ["tall|short|small|big"], "He's tall.", "Like me! I'm tall too!"),
         tour("awa", "Has your mum got long hair or short hair?", "Ta maman a les cheveux longs ou courts ?",
              ["long|short"], "She has got long hair.", "Like my mum!")],
        ["He's tall.", "She's short.", "She has got long hair.", "short hair"],
    ),
    mission(
        "6e-u3-m3", "Gentil ou grognon ?", "dire si une personne est gentille, drôle…",
        ["He's kind.", "She's funny.", "He's nice."],
        {"consigne": "Regarde les visages. Quels mots vont avec l'image ?", "fond": "cour",
         "objets": ["😄", "🤗", "😂"],
         "liste": [
             mot("happy", True, "Oui ! « Happy », c'est content. Ce visage sourit."),
             mot("funny", True, "Oui ! « Funny », c'est drôle. Celui-là rit très fort !"),
             mot("kind", True, "Oui ! « Kind », c'est gentil. Ce visage fait un câlin."),
             mot("nice", True, "Oui ! « Nice », c'est sympa."),
             mot("hungry", False, "« Hungry », c'est « j'ai faim ». Personne ne mange ici ! Regarde encore."),
             mot("tired", False, "« Tired », c'est fatigué. Personne ne dort ici ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Kocc Barma is kind.", "Kocc Barma est gentil."),
                       r("modou", "Yes, he's very kind. And Doudou is funny!", "Oui, il est très gentil. Et Doudou est drôle !"),
                       r("awa", "Ha ha! Yes, he's very funny.", "Ha ha ! Oui, il est très drôle."),
                       r("modou", "And my sister is nice.", "Et ma sœur est sympa.")],
         "gainde": "Gentil, drôle, sympa… Et moi, je suis comment ? Terrible et féroce ?"},
        [q("Comment est Kocc Barma ?", ["gentil", "drôle", "grand"], 0, 0),
         q("Doudou est…", ["drôle", "méchant", "petit"], 0, 1)],
        [choix("Doudou fait rire toute la classe. Je dis « Doudou is kind » ?", ["Doudou is kind.", "Doudou is funny."], 1,
               aides("Il fait rire. C'est « gentil » ou « drôle » ?", 1, "Écoute Modou :",
                     "Moi, je dis : « Modou is funny. »", "Funny = drôle. Kind = gentil.")),
         ordre("« Kind is Kocc Barma. » C'est bien ça ?", ["kind", "Kocc", "is", "Barma"], "Kocc Barma is kind",
               "Kocc Barma is kind.",
               aides("Awa dit d'abord le nom ou « kind » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « Awa is kind. »", "D'abord la personne, puis « is », puis « kind ».")),
         trou("Awa m'aide tout le temps : « She's ___. »", "She's", ".", ["kind", "nice"], "She's kind.",
              aides("Quelqu'un qui aide, il est comment ?", 0, "Écoute Awa :",
                    "Moi, je dis : « Kocc Barma is kind. »", "Gentil = kind. Écris : kind.")),
         libre("Mon ami me fait toujours rire. Comment je le dis ?", ["funny"],
               aides("Comment Modou parle-t-il de Doudou ?", 1, "Écoute Modou :",
                     "Moi, je dis : « Doudou is funny. »", "Écris : « He's funny. »"))],
        [tour("awa", "Is your best friend kind or funny?", "Ton meilleur ami est gentil ou drôle ?",
              ["kind|funny|nice"], "She's funny!", "Cool! Doudou is funny too!"),
         tour("gainde", "And me? Am I kind?", "Et moi ? Je suis gentil ?", ["kind|nice|funny"],
              "Yes, you are kind!", "Thank you! You are kind too!")],
        ["He's kind.", "She's funny.", "He's nice.", "very"],
    ),
    mission(
        "6e-u3-m4", "Gaïndé dessine son corps", "dire le nom des parties du corps",
        ["This is my head.", "I've got big eyes!"],
        {"consigne": "Quels mots vont avec l'image ?", "fond": "classe", "objets": ["👀", "👂", "👃", "✋"],
         "liste": [
             mot("eyes", True, "Oui ! « Eyes », ce sont les yeux."),
             mot("ear", True, "Oui ! « Ear », c'est l'oreille."),
             mot("nose", True, "Oui ! « Nose », c'est le nez."),
             mot("hand", True, "Oui ! « Hand », c'est la main."),
             mot("mouth", False, "« Mouth », c'est la bouche. Tu vois une bouche ? Non ! Regarde encore."),
             mot("foot", False, "« Foot », c'est le pied. Il n'y a pas de pied ici ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "This is my head.", "Ça, c'est ma tête."),
                       r("awa", "This is my nose, and this is my mouth.", "Ça, c'est mon nez, et ça, c'est ma bouche."),
                       r("modou", "Ha ha! You've got big eyes!", "Ha ha ! Tu as de grands yeux !"),
                       r("awa", "Yes! I've got big eyes and small ears.", "Oui ! J'ai de grands yeux et de petites oreilles.")],
         "gainde": "Une tête, un nez, des yeux… Moi aussi, je veux dessiner ma tête. Avec ma crinière !"},
        [q("Qu'est-ce qu'Awa montre en premier ?", ["sa tête", "son pied", "sa main"], 0, 0),
         q("Les yeux d'Awa sont…", ["grands", "petits", "fermés"], 0, 2)],
        [choix("Je touche mon nez. Je dis « This is my ear » ?", ["This is my ear.", "This is my nose."], 1,
               aides("Le nez, c'est « ear » ou « nose » ?", 1, "Écoute Awa :",
                     "Moi, je touche mon nez et je dis : « This is my nose. »", "Nose = le nez. Ear = l'oreille.")),
         ordre("« Big I've eyes got! » C'est bien ça ?", ["eyes", "got", "big", "I've"], "I've got big eyes",
               "I've got big eyes!",
               aides("Quel mot Awa dit-elle en premier, après « Yes » ?", 3, "Écoute Awa :",
                     "Moi, je dis : « I've got big ears! »", "I've got (j'ai) + big eyes (de grands yeux).")),
         trou("Je montre ma tête : « This is my ___. »", "This is my", ".", ["head"], "This is my head.",
              aides("Comment Awa dit-elle « ma tête » ?", 0, "Écoute Awa :",
                    "Moi, je dis : « This is my head. »", "La tête = head. Écris : head.")),
         libre("Je montre ma main. Comment je dis « C'est ma main » ?", ["hand"],
               aides("Awa dit « This is my… » puis la partie du corps. Et « main » ?", 0, "Écoute Awa :",
                     "Moi, je dis : « This is my head. »", "Main = hand. Écris : « This is my hand. »"))],
        [tour("kocc", "Touch your nose! What's this?", "Touche ton nez ! Qu'est-ce que c'est ?", ["nose"],
              "This is my nose.", "Very good!"),
         tour("modou", "Have you got big eyes or small eyes?", "Tu as de grands yeux ou de petits yeux ?",
              ["big|small"], "I've got big eyes.", "Me too!")],
        ["This is my head.", "I've got big eyes!", "nose", "ears", "hand"],
    ),
    mission(
        "6e-u3-m5", "Que font tes parents ?", "dire le travail d'une personne",
        ["What does your father do?", "He's a fisherman.", "She's a nurse."],
        {"consigne": "Sur la plage. Quels mots vont avec l'image ?", "fond": "plage",
         "objets": ["🛶", "🐟", "🌊", "🎣"],
         "liste": [
             mot("fisherman", True, "Oui ! « Fisherman », c'est le pêcheur. Il revient de la mer."),
             mot("boat", True, "Oui ! « Boat », c'est le bateau. Ici, c'est une pirogue."),
             mot("fish", True, "Oui ! « Fish », c'est le poisson."),
             mot("sea", True, "Oui ! « Sea », c'est la mer."),
             mot("nurse", False, "« Nurse », c'est l'infirmière. Elle travaille à l'hôpital, pas sur la plage ! Regarde encore."),
             mot("tailor", False, "« Tailor », c'est le tailleur, il coud les habits. Tu vois une machine à coudre ? Non ! Regarde encore."),
         ]},
        {"fond": "plage", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "What does your father do, Modou?", "Que fait ton père, Modou ?"),
                       r("modou", "He's a fisherman. And your father?", "Il est pêcheur. Et ton père ?"),
                       r("awa", "He's a driver. And my mother is a nurse.", "Il est chauffeur. Et ma mère est infirmière.")],
         "gainde": "Pêcheur, chauffeur, infirmière… Et mon papa lion, il fait quoi ? Il dort sous un arbre !"},
        [q("Le père de Modou est…", ["pêcheur", "chauffeur", "prof"], 0, 1),
         q("La mère d'Awa est…", ["infirmière", "couturière", "commerçante"], 0, 2)],
        [choix("Le papa de Modou va pêcher en mer. Je dis « He's a driver » ?", ["He's a fisherman.", "He's a driver."], 0,
               aides("Celui qui pêche des poissons, c'est quel mot ?", 1, "Écoute Modou :",
                     "Moi, je dis : « My uncle is a fisherman. »", "Fisherman = pêcheur. Driver = chauffeur.")),
         ordre("« Your does what father do? » C'est bien ça ?", ["does", "What", "do", "your", "father"],
               "What does your father do", "What does your father do?",
               aides("Quel mot Awa dit-elle en premier ?", 0, "Écoute Awa :",
                     "Moi, je demande : « What does your mother do? »",
                     "What does… do ? = Que fait… ? Le mot « father » est au milieu.")),
         trou("Ma maman soigne les malades à l'hôpital : « She's a ___. »", "She's a", ".", ["nurse", "doctor"],
              "She's a nurse.",
              aides("Comment Awa dit-elle le travail de sa mère ?", 2, "Écoute Awa :",
                    "Moi, je dis : « My sister is a nurse. »", "Infirmière = nurse. Écris : nurse.")),
         libre("Le papa d'Awa conduit un car rapide. Comment je dis son travail ?", ["driver"],
               aides("Comment Awa dit-elle le travail de son père ?", 2, "Écoute Awa :",
                     "Moi, je dis : « He's a fisherman. »", "Chauffeur = driver. Écris : « He's a driver. »"))],
        [tour("awa", "What does your father do?", "Que fait ton père ?",
              ["hes|he is|is a|is an|teacher|doctor|farmer|fisherman|trader|driver|tailor|nurse"],
              "He's a trader.", "Oh, nice!"),
         tour("gainde", "And your mother? What does she do?", "Et ta mère ? Que fait-elle ?",
              ["shes|she is|is a|is an|teacher|doctor|farmer|trader|driver|tailor|nurse"],
              "She's a tailor.", "Wow! Can she make a boubou for a lion?")],
        ["What does your father do?", "He's a fisherman.", "She's a nurse.", "driver", "teacher"],
    ),
]

unite3 = unite(
    "6e-u3", "My family", "Ma famille : présente 3 personnes de ta famille.", u3,
    lignes=[
        ("Parler de ma famille", "This is my mother. · I've got two sisters."),
        ("Dire comment est une personne", "He's tall. · She's short. · She has got long hair."),
        ("Dire si une personne est gentille, drôle", "He's kind. · She's funny. · He's nice."),
        ("Les parties du corps", "This is my head. · I've got big eyes!"),
        ("Dire le travail", "What does your father do? — He's a fisherman."),
    ],
    mots=[
        ("family", "famille", "njaboot"),
        ("mother", "mère", "yaay"),
        ("father", "père", "baay"),
        ("tall", "grand", "gudd"),
        ("small", "petit", "tuuti"),
        ("hair", "cheveux", "kawar"),
        ("kind", "gentil", "baax"),
        ("head", "tête", "bopp"),
        ("eyes", "yeux", "bët"),
        ("ear", "oreille", "nopp"),
        ("hand", "main", "loxo"),
    ],
    pieges=[
        "She has got long hair. Pas « She has the hair long ». Et « hair » sans s !",
        "He's a fisherman (avec « a »). Pas « He's fisherman ».",
        "He pour un homme ou un garçon, she pour une femme ou une fille.",
    ],
    exercices=[
        ex("Tu montres ta mère sur la photo. Tu dis :", ["This is my father.", "This is my mother.", "This is my sister.", "This is my brother."], 1,
           "Mother = mère. Father = père."),
        ex("Tu as deux sœurs. Tu dis :", ["I've got two brothers.", "I've got two sisters.", "I'm two sisters.", "I've two got sisters."], 1,
           "I've got = j'ai. Sisters = sœurs."),
        ex("Ton frère est grand. Tu dis :", ["He's short.", "He's tall.", "She's tall.", "He's small."], 1,
           "Tall = grand. « He » pour un garçon."),
        ex("Elle a les cheveux longs :", ["She has got long hair.", "She has got long hairs.", "She has the hair long.", "He has got long hair."], 0,
           "On dit « long hair », sans s. « She » pour une fille."),
        ex("« She's funny » veut dire :", ["Elle est drôle.", "Elle est gentille.", "Elle est grande.", "Elle est petite."], 0,
           "Funny = drôle."),
        ex("Complète : « Kocc Barma is very ____. » (gentil)", ["kind", "tall", "head", "nurse"], 0,
           "Kind = gentil."),
        ex("Tu touches ta tête. Tu dis :", ["This is my hand.", "This is my head.", "This is my nose.", "This is my ear."], 1,
           "Head = tête. Hand = main."),
        ex("« I've got big eyes! » veut dire :", ["J'ai de grands yeux !", "J'ai de grandes oreilles !", "J'ai une grande bouche !", "J'ai de grandes mains !"], 0,
           "Eyes = yeux. Ears = oreilles."),
        ex("Tu veux savoir le travail du papa de ton ami :", ["What does your father do?", "Where is your father?", "How old is your father?", "Whose father is it?"], 0,
           "« What does your father do? » = Que fait ton père ?"),
        ex("Son père va pêcher en mer :", ["He's a driver.", "He's a fisherman.", "He's fisherman.", "He's a nurse."], 1,
           "Fisherman = pêcheur. N'oublie pas « a »."),
    ],
)

# ======================= UNITÉ 4 : MY DAY =======================

u4 = [
    mission(
        "6e-u4-m1", "En retard ! Gaïndé a trop dormi", "dire l'heure",
        ["What time is it?", "It's seven o'clock.", "It's half past seven."],
        {"consigne": "C'est le matin, chez Modou. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["⏰", "🛏️", "☀️"],
         "liste": [
             mot("clock", True, "Oui ! « Clock », c'est le réveil. Il sonne !"),
             mot("bed", True, "Oui ! « Bed », c'est le lit."),
             mot("sun", True, "Oui ! « Sun », c'est le soleil. Il est déjà levé."),
             mot("morning", True, "Oui ! « Morning », c'est le matin."),
             mot("night", False, "« Night », c'est la nuit. Mais le soleil est là ! Regarde encore."),
             mot("school", False, "« School », c'est l'école. On n'est pas encore à l'école, on est au lit ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["awa", "modou", "gainde"],
         "repliques": [r("awa", "Modou! What time is it?", "Modou ! Quelle heure est-il ?"),
                       r("modou", "It's half past seven!", "Il est sept heures et demie !"),
                       r("awa", "Half past seven? We're late!", "Sept heures et demie ? On est en retard !"),
                       r("modou", "School is at eight o'clock. Run!", "L'école, c'est à huit heures. Cours !")],
         "gainde": "Sept heures et demie ? Moi, je dors jusqu'à midi… C'est grave ?"},
        [q("Quelle heure est-il ?", ["7 h 30", "7 h", "8 h"], 0, 1),
         q("L'école commence à…", ["8 h", "7 h 30", "9 h"], 0, 3)],
        [choix("Le réveil dit 7 h pile. Je dis « It's half past seven » ?", ["It's seven o'clock.", "It's half past seven."], 0,
               aides("7 h pile, c'est « o'clock » ou « half past » ?", 3, "Écoute Modou :",
                     "Moi, à 8 h pile, je dis : « It's eight o'clock. »",
                     "O'clock = l'heure pile. Half past = et demie.")),
         ordre("« Is time what it? » C'est bien ça ?", ["time", "it", "What", "is"], "What time is it",
               "What time is it?",
               aides("Quel mot Awa dit-elle en premier ?", 0, "Écoute Awa :",
                     "Moi, je demande : « What time is it? »", "What time (quelle heure) + is it (est-il).")),
         trou("Il est 8 h 30 : « It's half past ___. »", "It's half past", ".", ["eight", "8"], "It's half past eight.",
              aides("Comment Modou dit-il 7 h 30 ?", 1, "Écoute Modou :",
                    "Moi, à 6 h 30, je dis : « It's half past six. »", "8 = eight. Écris : eight.")),
         libre("Le réveil dit 6 h pile. Quelle heure est-il ?", ["six|6"],
               aides("L'heure pile, on dit « o'clock ». Et 6, c'est quoi ?", 3, "Écoute Modou :",
                     "Moi, je dis : « It's seven o'clock. »", "Écris : « It's six o'clock. »"))],
        [tour("kocc", "What time is it? (il est 10 h)", "Quelle heure est-il ? (il est 10 h)", ["ten|10"],
              "It's ten o'clock.", "Thank you!"),
         tour("modou", "What time is it now? (il est 7 h 30)", "Quelle heure est-il ? (il est 7 h 30)",
              ["half past seven|7 30|seven thirty"], "It's half past seven.", "Oh no! I'm late!")],
        ["What time is it?", "It's seven o'clock.", "It's half past seven.", "clock"],
    ),
    mission(
        "6e-u4-m2", "Quel jour sommes-nous ?", "dire le jour et le mois",
        ["What day is it today?", "It's Monday.", "It's October."],
        {"consigne": "En classe. Quels mots vont avec l'image ?", "fond": "classe", "objets": ["📅", "🧑‍🏫", "📝"],
         "liste": [
             mot("calendar", True, "Oui ! « Calendar », c'est le calendrier."),
             mot("teacher", True, "Oui ! « Teacher », c'est le prof, Kocc Barma."),
             mot("board", True, "Oui ! « Board », c'est le tableau. Le jour est écrit dessus."),
             mot("Monday", True, "Oui ! « Monday », c'est lundi. C'est écrit au tableau."),
             mot("moon", False, "« Moon », c'est la lune. Ça ressemble à « Monday », mais on ne voit pas la lune ! Regarde encore."),
             mot("bed", False, "« Bed », c'est le lit. Pas de lit en classe ! Regarde encore."),
         ]},
        {"fond": "classe", "persos": ["kocc", "awa", "gainde"],
         "repliques": [r("kocc", "What day is it today?", "On est quel jour, aujourd'hui ?"),
                       r("awa", "It's Monday!", "On est lundi !"),
                       r("kocc", "Good! And what month is it?", "Bien ! Et on est en quel mois ?"),
                       r("awa", "It's October.", "On est en octobre.")],
         "gainde": "Lundi ? Octobre ? Moi, je croyais que tous les jours, c'était dimanche !"},
        [q("On est quel jour ?", ["lundi", "mardi", "dimanche"], 0, 1),
         q("On est en quel mois ?", ["octobre", "mai", "juin"], 0, 3)],
        [choix("Aujourd'hui, c'est lundi. Je dis « It's Sunday » ?", ["It's Sunday.", "It's Monday."], 1,
               aides("Lundi, c'est « Monday » ou « Sunday » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « It's Monday! »", "Monday = lundi. Sunday = dimanche.")),
         ordre("« Day what is it today? » C'est bien ça ?", ["is", "today", "What", "it", "day"],
               "What day is it today", "What day is it today?",
               aides("Quel mot Kocc Barma dit-il en premier ?", 0, "Écoute Kocc Barma :",
                     "Moi, je demande : « What day is it today? »", "What day (quel jour) + is it + today (aujourd'hui).")),
         trou("Après lundi, c'est mardi : « It's ___. »", "It's", ".", ["tuesday"], "It's Tuesday.",
              aides("Monday, puis… ? Tu connais le jour d'après ?", -1, "",
                    "Moi, je compte : Monday, Tuesday, Wednesday…", "Mardi = Tuesday. Écris : Tuesday.")),
         libre("Aujourd'hui, c'est vendredi. Comment je le dis ?", ["friday"],
               aides("Comment Awa dit-elle « lundi » ?", 1, "Écoute Awa :",
                     "Moi, je dis : « It's Monday. »", "Vendredi = Friday. Écris : « It's Friday. »"))],
        [tour("kocc", "What day is it today?", "On est quel jour, aujourd'hui ?", [JOURS], "It's Wednesday.",
              "Thank you!"),
         tour("awa", "And what month is it?", "Et on est en quel mois ?", [MOIS], "It's October.", "Great! Thank you!")],
        ["What day is it today?", "It's Monday.", "Monday… Sunday", "January… December"],
    ),
    mission(
        "6e-u4-m3", "L'anniversaire d'Awa", "dire une date",
        ["When is your birthday?", "It's on the fifth of May."],
        {"consigne": "C'est une fête ! Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["🎂", "🎁", "🎈", "📅"],
         "liste": [
             mot("cake", True, "Oui ! « Cake », c'est le gâteau."),
             mot("present", True, "Oui ! « Present », c'est le cadeau."),
             mot("balloons", True, "Oui ! « Balloons », ce sont les ballons."),
             mot("calendar", True, "Oui ! « Calendar », c'est le calendrier, avec la date."),
             mot("goat", False, "« Goat », c'est la chèvre. Elle n'est pas invitée à la fête ! Regarde encore."),
             mot("snow", False, "« Snow », c'est la neige. Pas de neige au Sénégal ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "When is your birthday, Awa?", "C'est quand, ton anniversaire, Awa ?"),
                       r("awa", "It's on the fifth of May.", "C'est le 5 mai."),
                       r("modou", "My birthday is on the tenth of June!", "Mon anniversaire, c'est le 10 juin !")],
         "gainde": "Le 5 mai ? Et mon anniversaire à moi, c'est quand ? Tous les jours, j'espère !"},
        [q("L'anniversaire d'Awa, c'est le…", ["5 mai", "10 juin", "5 juin"], 0, 1),
         q("Et l'anniversaire de Modou ?", ["10 juin", "5 mai", "1er juin"], 0, 2)],
        [choix("Mon anniversaire, c'est le 3 mars. Je dis « the three of March » ?",
               ["It's on the third of March.", "It's on the three of March."], 0,
               aides("Pour une date, on dit « five » ou « fifth » ? Écoute bien.", 1, "Écoute Awa :",
                     "Moi, je dis : « It's on the first of April. »",
                     "Pour une date, on dit « first, second, third… », comme pour le rang.")),
         ordre("« Your when birthday is? » C'est bien ça ?", ["birthday", "When", "your", "is"],
               "When is your birthday", "When is your birthday?",
               aides("Quel mot Modou dit-il en premier ?", 0, "Écoute Modou :",
                     "Moi, je demande : « When is your birthday? »", "When (quand) + is + your birthday (ton anniversaire).")),
         trou("Le 5 mai : « It's on the fifth of ___. »", "It's on the fifth of", ".", ["may"], "It's on the fifth of May.",
              aides("Comment Awa dit-elle « mai » ?", 1, "Écoute Awa :",
                    "Moi, je dis : « It's on the fifth of May. »", "Mai = May. Écris : May.")),
         libre("Pour le jeu, ton anniversaire, c'est le 1er janvier. Dis-le !", ["first|1st|1", "january"],
               aides("Le 1er, c'est « the first ». Et janvier ?", 1, "Écoute la phrase d'Awa :",
                     "Moi, je dis : « It's on the fifth of May. »", "Écris : « It's on the first of January. »"))],
        [tour("awa", "When is your birthday?", "C'est quand, ton anniversaire ?", [MOIS],
              "It's on the ninth of April.", "Happy birthday soon!"),
         tour("gainde", "When is Awa's birthday?", "C'est quand, l'anniversaire d'Awa ?", ["fifth|5th|5", "may"],
              "It's on the fifth of May.", "Thank you! I've got a present for her: a big fish!")],
        ["When is your birthday?", "It's on the fifth of May.", "Happy birthday!"],
    ),
    mission(
        "6e-u4-m4", "Une journée avec Modou", "dire ce que je fais tous les jours",
        ["I get up at six.", "I go to school at seven."],
        {"consigne": "Le matin, chez Modou. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["⏰", "🍞", "🎒", "🚿"],
         "liste": [
             mot("clock", True, "Oui ! « Clock », c'est le réveil."),
             mot("bread", True, "Oui ! « Bread », c'est le pain du petit-déjeuner."),
             mot("bag", True, "Oui ! « Bag », c'est le sac pour l'école."),
             mot("water", True, "Oui ! « Water », c'est l'eau pour se laver."),
             mot("moon", False, "« Moon », c'est la lune. C'est le matin ! Regarde encore."),
             mot("ball", False, "« Ball », c'est le ballon. Pas de foot le matin, Modou se prépare ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "I get up at six.", "Je me lève à six heures."),
                       r("modou", "I wash, and I eat bread.", "Je me lave, et je mange du pain."),
                       r("modou", "I go to school at seven.", "Je vais à l'école à sept heures."),
                       r("awa", "At seven? But you are late every day!", "À sept heures ? Mais tu es en retard tous les jours !")],
         "gainde": "Il se lève à six heures ? Moi, à six heures, je dors… et à sept heures aussi."},
        [q("Modou se lève à…", ["6 h", "7 h", "8 h"], 0, 0),
         q("Modou va à l'école à…", ["7 h", "6 h", "midi"], 0, 2)],
        [choix("Je me lève à 6 h. Je dis « I sleep at six » ?", ["I sleep at six.", "I get up at six."], 1,
               aides("Se lever, c'est « sleep » ou « get up » ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I get up at five. »", "Get up = se lever. Sleep = dormir.")),
         ordre("« School I to go at seven. » C'est bien ça ?", ["go", "seven", "I", "school", "at", "to"],
               "I go to school at seven", "I go to school at seven.",
               aides("Modou dit d'abord « I go »… et ensuite ?", 2, "Écoute Modou :",
                     "Moi, je dis : « I go to school at eight. »",
                     "I go (je vais) + to school (à l'école) + at seven (à sept heures).")),
         trou("« I ___ up at six. » Il me manque un mot !", "I", "up at six.", ["get"], "I get up at six.",
              aides("Comment Modou dit-il qu'il se lève ?", 0, "Écoute Modou :",
                    "Moi, je dis : « I get up at five. »", "Se lever = get up. Écris : get.")),
         libre("Le soir, je mange à 8 h. Comment je le dis ?", ["eat", "eight|8"],
               aides("Modou dit « I eat bread ». Et pour l'heure, on dit « at… ».", 1, "Écoute Modou :",
                     "Moi, je dis : « I get up at six. »", "Écris : « I eat at eight. »"))],
        [tour("modou", "What time do you get up?", "Tu te lèves à quelle heure ?", [HEURES],
              "I get up at six.", "Wow! I get up at seven… and I'm late!"),
         tour("awa", "What time do you go to school?", "Tu vas à l'école à quelle heure ?", [HEURES],
              "I go to school at seven.", "Me too!")],
        ["I get up at six.", "I go to school at seven.", "wash", "eat", "sleep"],
    ),
    mission(
        "6e-u4-m5", "J'aime, j'aime pas", "dire ce que j'aime et ce que je n'aime pas",
        ["I like football.", "I don't like rice."],
        {"consigne": "Quels mots vont avec l'image ?", "fond": "maison", "objets": ["⚽", "🍚", "🥭", "🎵"],
         "liste": [
             mot("football", True, "Oui ! « Football », c'est le foot. Comme en français !"),
             mot("rice", True, "Oui ! « Rice », c'est le riz."),
             mot("mango", True, "Oui ! « Mango », c'est la mangue."),
             mot("music", True, "Oui ! « Music », c'est la musique."),
             mot("orange", False, "« Orange », c'est l'orange. Ici, le fruit jaune, c'est une mangue ! Regarde encore."),
             mot("bus", False, "« Bus », c'est le car. Tu vois un car ? Non ! Regarde encore."),
         ]},
        {"fond": "cour", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "I like football!", "J'aime le foot !"),
                       r("awa", "I don't like football. I like music.", "Je n'aime pas le foot. J'aime la musique."),
                       r("awa", "And I don't like rice.", "Et je n'aime pas le riz."),
                       r("modou", "What?! You don't like rice?!", "Quoi ?! Tu n'aimes pas le riz ?!")],
         "gainde": "Elle n'aime pas le riz ?! Moi, j'aime tout. Surtout la viande…"},
        [q("Qu'est-ce qu'Awa aime ?", ["la musique", "le foot", "le riz"], 0, 1),
         q("Pourquoi Modou crie « What?! » ?", ["Awa n'aime pas le riz.", "Awa aime le foot.", "Awa est en retard."], 0, 3)],
        [choix("J'adore les mangues ! Je dis « I don't like mangoes » ?", ["I don't like mangoes.", "I like mangoes."], 1,
               aides("Tu les aimes. Tu dis « like » ou « don't like » ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I like music. »", "I like = j'aime. I don't like = je n'aime pas.")),
         ordre("« Like don't I rice. » C'est bien ça ?", ["like", "rice", "I", "don't"], "I don't like rice",
               "I don't like rice.",
               aides("Awa dit d'abord « I »… et ensuite ?", 2, "Écoute Awa :",
                     "Moi, je dis : « I don't like rain. »", "I + don't (ne… pas) + like (aime) + rice (le riz).")),
         trou("Je n'aime pas la pluie : « I ___ like rain. »", "I", "like rain.", ["don't", "dont", "do not"],
              "I don't like rain.",
              aides("Comment Awa dit-elle qu'elle n'aime pas le foot ?", 1, "Écoute Awa :",
                    "Moi, je dis : « I don't like football. »", "Pour « je n'aime pas » : I don't like. Écris : don't.")),
         libre("J'aime le foot. Comment je le dis ?", ["like", "football"],
               aides("Comment Modou dit-il qu'il aime le foot ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I like music. »", "Écris : « I like football. »"))],
        [tour("awa", "I like music. And you? What do you like?", "J'aime la musique. Et toi ? Qu'est-ce que tu aimes ?",
              ["like|love"], "I like football.", "Cool!"),
         tour("modou", "Do you like rice?", "Tu aimes le riz ?", ["yes|no|like"], "Yes! I like rice!",
              "Me too! Ceebu jën!")],
        ["I like football.", "I don't like rice.", "music", "mango"],
    ),
    mission(
        "6e-u4-m6", "Gaïndé essaie les habits de Modou", "dire ce que je porte",
        ["I'm wearing a blue shirt.", "I'm wearing a red cap."],
        {"consigne": "Les habits de Modou. Quels mots vont avec l'image ?", "fond": "maison",
         "objets": ["👕", "👖", "👟", "🧢"],
         "liste": [
             mot("shirt", True, "Oui ! « Shirt », c'est la chemise."),
             mot("trousers", True, "Oui ! « Trousers », c'est le pantalon."),
             mot("shoes", True, "Oui ! « Shoes », ce sont les chaussures."),
             mot("cap", True, "Oui ! « Cap », c'est la casquette."),
             mot("hat", False, "« Hat », c'est le chapeau. Ici, c'est une casquette : « cap » ! Regarde encore."),
             mot("dress", False, "« Dress », c'est la robe. Tu vois une robe ? Non ! Regarde encore."),
         ]},
        {"fond": "maison", "persos": ["modou", "awa", "gainde"],
         "repliques": [r("modou", "Look! I'm wearing a blue shirt and a red cap.", "Regarde ! Je porte une chemise bleue et une casquette rouge."),
                       r("awa", "Nice! I'm wearing a green dress.", "Joli ! Moi, je porte une robe verte."),
                       r("awa", "And yellow sandals!", "Et des sandales jaunes !")],
         "gainde": "Une chemise, une casquette… Moi, je ne porte rien ! Je veux essayer les habits de Modou !"},
        [q("Modou porte une chemise…", ["bleue", "rouge", "verte"], 0, 0),
         q("Awa porte…", ["une robe verte", "une chemise bleue", "une casquette rouge"], 0, 1)],
        [choix("Je mets le pantalon de Modou. Je dis « I'm wearing a cap » ?", ["I'm wearing a cap.", "I'm wearing trousers."], 1,
               aides("Le pantalon, c'est « cap » ou « trousers » ?", -1, "",
                     "Moi, je dis : « I'm wearing trousers. »", "Trousers = pantalon. Cap = casquette.")),
         ordre("« Wearing I'm shirt a blue. » C'est bien ça ?", ["a", "shirt", "I'm", "blue", "wearing"],
               "I'm wearing a blue shirt", "I'm wearing a blue shirt.",
               aides("Modou dit d'abord « I'm wearing »… et la couleur, elle vient où ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I'm wearing a red shirt. »",
                     "I'm wearing (je porte) + a blue shirt. La couleur vient avant l'habit.")),
         trou("« I'm ___ a red cap. » Il me manque un mot !", "I'm", "a red cap.", ["wearing"], "I'm wearing a red cap.",
              aides("Quel mot Modou dit-il après « I'm » ?", 0, "Écoute Modou :",
                    "Moi, je dis : « I'm wearing a boubou. »", "Je porte = I'm wearing. Écris : wearing.")),
         libre("Je porte des chaussures noires. Comment je le dis ?", ["wearing", "black shoes"],
               aides("Comment Modou commence-t-il sa phrase ?", 0, "Écoute Modou :",
                     "Moi, je dis : « I'm wearing a blue shirt. »", "Écris : « I'm wearing black shoes. »"))],
        [tour("awa", "What are you wearing today?", "Qu'est-ce que tu portes aujourd'hui ?",
              ["wearing|shirt|t shirt|dress|trousers|shoes|sandals|boubou|cap|skirt|uniform"],
              "I'm wearing a white shirt.", "Very nice!")],
        ["I'm wearing a blue shirt.", "trousers", "dress", "shoes", "cap"],
    ),
]

unite4 = unite(
    "6e-u4", "My day", "Ma journée : raconte ta journée en 5 phrases.", u4,
    lignes=[
        ("Dire l'heure", "What time is it? — It's seven o'clock. · It's half past seven."),
        ("Dire le jour et le mois", "What day is it today? — It's Monday. · It's October."),
        ("Dire une date", "When is your birthday? — It's on the fifth of May."),
        ("Dire ce que je fais tous les jours", "I get up at six. · I go to school at seven."),
        ("Dire ce que j'aime", "I like football. · I don't like rice."),
        ("Dire ce que je porte", "I'm wearing a blue shirt."),
    ],
    mots=[
        ("today", "aujourd'hui", "tey"),
        ("day", "jour", "bés"),
        ("month", "mois", "weer"),
        ("time", "heure", "waxtu"),
        ("Monday", "lundi", "altine"),
        ("get up", "se lever", "jóg"),
        ("eat", "manger", "lekk"),
        ("sleep", "dormir", "nelaw"),
        ("rice", "riz", "ceeb"),
        ("shirt", "chemise", "simis"),
        ("trousers", "pantalon", "tubay"),
        ("shoes", "chaussures", "dàll"),
    ],
    pieges=[
        "7 h 30 = It's half past seven. Pas « It's seven and half ».",
        "Le 5 mai = the fifth of May. Pas « the five of May ».",
        "a blue shirt : la couleur avant l'habit. Pas « a shirt blue ».",
    ],
    exercices=[
        ex("Il est 7 h 30. Tu dis :", ["It's seven o'clock.", "It's half past seven.", "It's seven and half.", "It's half past six."], 1,
           "Half past seven = sept heures et demie."),
        ex("Il est 9 h pile. Tu dis :", ["It's nine o'clock.", "It's half past nine.", "It's o'clock nine.", "It's ten o'clock."], 0,
           "O'clock = l'heure pile. On le met après le nombre."),
        ex("« What day is it today? » veut dire :", ["On est quel jour, aujourd'hui ?", "Quelle heure est-il ?", "C'est quand, ton anniversaire ?", "Tu portes quoi ?"], 0,
           "Day = jour. Today = aujourd'hui."),
        ex("Le jour après Monday, c'est :", ["Sunday", "Tuesday", "Friday", "Thursday"], 1,
           "Monday, Tuesday, Wednesday… Tuesday = mardi."),
        ex("Ton anniversaire, c'est le 5 mai :", ["It's on the five of May.", "It's on the fifth of May.", "It's in the fifth May.", "It's May five."], 1,
           "Pour une date : the fifth of May."),
        ex("Complète : « ____ is your birthday? »", ["When", "What", "Where", "Whose"], 0,
           "When = quand."),
        ex("Tu te lèves à 6 h. Tu dis :", ["I get up at six.", "I go to school at six.", "I sleep at six.", "I eat at six."], 0,
           "Get up = se lever."),
        ex("Tu n'aimes pas le riz. Tu dis :", ["I like rice.", "I don't like rice.", "I not like rice.", "I no like rice."], 1,
           "Pour « je n'aime pas » : I don't like."),
        ex("Tu portes une chemise bleue :", ["I'm wearing a shirt blue.", "I'm wearing a blue shirt.", "I wearing a blue shirt.", "I'm wear a blue shirt."], 1,
           "I'm wearing + la couleur + l'habit."),
        ex("« Trousers », c'est :", ["un pantalon", "une robe", "des chaussures", "une casquette"], 0,
           "Trousers = pantalon. Dress = robe."),
    ],
)

UNITES = [unite3, unite4]

# ======================= LES ÉPISODES =======================

EPISODES = [
    # ---- Unité 3 ----
    episode("Le frère de Gaïndé a une barbe", "6e-u3-m2", [
        case("maison", [perso("modou", 0.05, 95), perso("gainde", 0.6, 95)], [
            bulle("Look! This is my mother. I've got two sisters.",
                  "Regarde ! Ça, c'est ma mère. J'ai deux sœurs. (Modou montre sa photo de famille)", 0.03, 0.04),
            bulle("Wow! A big family!", "Waouh ! Une grande famille !", 0.6, 0.4),
        ]),
        case("cour", [perso("gainde", 0.05, 95, "saute"), perso("bouc", 0.55, 90)], [
            bulle("I've got a big family too! This is my brother!",
                  "Moi aussi, j'ai une grande famille ! Ça, c'est mon frère ! (il montre le bouc de la cour)", 0.03, 0.04),
            bulle("Bêêê!", "Bêêê !", 0.6, 0.35),
        ]),
        case("cour", [perso("gainde", 0.05, 95), perso("bouc", 0.55, 90)], [
            bulle("He's short. He has got long hair… like me!",
                  "Il est petit. Il a les poils longs… comme moi ! (le bouc a une longue barbe, Gaïndé a sa crinière)", 0.03, 0.04),
            bulle("Bêêê!", "Bêêê ! (le bouc mange la crinière de Gaïndé)", 0.6, 0.4),
        ]),
        case("cour", [perso("modou", 0.02, 90, "danse"), perso("gainde", 0.35, 90), perso("mouton", 0.65, 90)], [
            bulle("Ha ha! And this is your sister?", "Ha ha ! Et ça, c'est ta sœur ?", 0.02, 0.04),
            bulle("Yes! She's tall. She has got short hair!",
                  "Oui ! Elle est grande. Elle a les poils courts ! (il fait un câlin au mouton)", 0.3, 0.32),
            bulle("Mêêê!", "Mêêê ! (le mouton s'enfuit en courant)", 0.6, 0.06),
        ]),
    ], ["This is my mother.", "I've got two sisters.", "This is my brother!", "He's short.", "She's tall.", "long hair"]),

    episode("Le portrait de Kocc Barma", "6e-u3-m4", [
        case("classe", [perso("gainde", 0.4, 105, "saute")], [
            bulle("This is Kocc Barma! He's very kind.",
                  "Ça, c'est Kocc Barma ! Il est très gentil. (Gaïndé dessine le prof au tableau, avec la craie dans la bouche)", 0.05, 0.05),
        ]),
        case("classe", [perso("gainde", 0.05, 95), perso("awa", 0.6, 95)], [
            bulle("He has got big eyes… and big ears!", "Il a de grands yeux… et de grandes oreilles !", 0.03, 0.04),
            bulle("Big ears?!", "De grandes oreilles ?! (sur le dessin, les oreilles sont grandes comme des éventails)", 0.55, 0.4),
        ]),
        case("classe", [perso("gainde", 0.05, 95), perso("modou", 0.6, 95, "danse")], [
            bulle("And he has got a small nose and a big mouth!", "Et il a un petit nez et une grande bouche !", 0.03, 0.04),
            bulle("Ha ha ha! He's funny!", "Ha ha ha ! Il est drôle ! (Modou tombe de sa chaise)", 0.55, 0.4),
        ]),
        case("classe", [perso("kocc", 0.05, 100), perso("gainde", 0.6, 90, "balance")], [
            bulle("Hmm… I've got big ears, Gaïndé?", "Hmm… J'ai de grandes oreilles, Gaïndé ? (Kocc Barma est juste derrière lui)", 0.03, 0.04),
            bulle("Er… You are kind! You are very, very kind, Sir!",
                  "Euh… Vous êtes gentil ! Très, très gentil, Monsieur ! (il efface le dessin avec sa queue… et se met de la craie partout)", 0.4, 0.4),
        ]),
    ], ["He's kind.", "He's funny!", "This is my head.", "big eyes", "big ears", "a small nose"]),

    episode("Gaïndé, pêcheur de poissons", "6e-u3-m5", [
        case("plage", [perso("awa", 0.05, 95), perso("gainde", 0.6, 95)], [
            bulle("My father is a driver. What does your father do, Gaïndé?",
                  "Mon père est chauffeur. Que fait ton père, Gaïndé ?", 0.03, 0.04),
            bulle("He's a… fisherman!", "Il est… pêcheur ! (il n'en sait rien du tout)", 0.55, 0.4),
        ]),
        case("mer", [perso("gainde", 0.15, 95, "saute"), perso("poisson", 0.6, 70)], [
            bulle("Look! I'm a fisherman too!",
                  "Regarde ! Moi aussi, je suis pêcheur ! (il saute dans la mer pour attraper un poisson avec la bouche)", 0.03, 0.04),
            bulle("Blub!", "Blub !", 0.6, 0.35),
        ]),
        case("plage", [perso("modou", 0.05, 95), perso("gainde", 0.55, 95, "balance")], [
            bulle("Gaïndé! Are you a fisherman?", "Gaïndé ! Tu es pêcheur ?", 0.03, 0.04),
            bulle("No… I'm a fish!", "Non… je suis un poisson ! (il est tout mouillé, avec des algues sur la tête)", 0.5, 0.4),
        ]),
        case("plage", [perso("awa", 0.02, 90), perso("gainde", 0.35, 90), perso("poisson", 0.68, 70, "saute")], [
            bulle("Ha ha! And what does the fish do?", "Ha ha ! Et le poisson, il fait quoi ?", 0.02, 0.04),
            bulle("He's a teacher!", "Il est prof ! (le poisson porte les lunettes de Kocc Barma)", 0.32, 0.38),
        ]),
    ], ["What does your father do?", "He's a fisherman.", "He's a driver.", "He's a teacher!"]),

    # ---- Unité 4 ----
    episode("Bonjour… à trois heures du matin", "6e-u4-m2", [
        case("nuit", [perso("gainde", 0.4, 105, "saute")], [
            bulle("It's seven o'clock! School! School!",
                  "Il est sept heures ! L'école ! L'école ! (il prend la lune pour le soleil)", 0.05, 0.05),
        ]),
        case("nuit", [perso("kocc", 0.05, 100), perso("gainde", 0.6, 95)], [
            bulle("Gaïndé?! What time is it?!", "Gaïndé ?! Quelle heure est-il ?! (Kocc Barma est en pyjama, avec une lampe)", 0.03, 0.04),
            bulle("It's half past seven, Sir! Good morning!", "Il est sept heures et demie, Monsieur ! Bonjour !", 0.5, 0.4),
        ]),
        case("nuit", [perso("kocc", 0.05, 100), perso("gainde", 0.6, 95, "balance")], [
            bulle("No! It's three o'clock! It's night!", "Non ! Il est trois heures ! C'est la nuit !", 0.03, 0.04),
            bulle("Oh… Good night, Sir.", "Oh… Bonne nuit, Monsieur.", 0.55, 0.4),
        ]),
        case("classe", [perso("kocc", 0.02, 90), perso("gainde", 0.35, 90, "immobile"), perso("modou", 0.68, 90, "danse")], [
            bulle("Gaïndé! What day is it today?", "Gaïndé ! On est quel jour, aujourd'hui ?", 0.02, 0.04),
            bulle("Zzz… It's Sunday…", "Zzz… C'est dimanche… (il dort sur sa table)", 0.32, 0.38),
            bulle("Ha ha! No! It's Monday!", "Ha ha ! Non ! On est lundi !", 0.6, 0.06),
        ]),
    ], ["What time is it?", "It's seven o'clock.", "It's half past seven.", "What day is it today?", "It's Monday."]),

    episode("Joyeux anniversaire… trop tôt !", "6e-u4-m4", [
        case("cour", [perso("gainde", 0.05, 95), perso("awa", 0.6, 95)], [
            bulle("When is your birthday, Awa?", "C'est quand, ton anniversaire, Awa ?", 0.03, 0.04),
            bulle("It's on the fifth of May.", "C'est le 5 mai.", 0.55, 0.4),
        ]),
        case("maison", [perso("gainde", 0.05, 95, "danse"), perso("awa", 0.6, 95)], [
            bulle("Happy birthday, Awa!", "Joyeux anniversaire, Awa ! (le lendemain, il arrive chez Awa avec un gâteau)", 0.03, 0.04),
            bulle("Gaïndé! What time is it?!", "Gaïndé ! Quelle heure est-il ?! (Awa est encore au lit)", 0.55, 0.3),
            bulle("It's six o'clock! I get up at six!", "Il est six heures ! Je me lève à six heures !", 0.03, 0.55),
        ]),
        case("maison", [perso("awa", 0.05, 95), perso("gainde", 0.6, 95, "balance")], [
            bulle("My birthday is on the fifth of May! Today is the fifth of March!",
                  "Mon anniversaire, c'est le 5 mai ! Aujourd'hui, c'est le 5 mars !", 0.03, 0.04),
            bulle("Oh…", "Oh… (il mange le gâteau tout seul, pour se consoler)", 0.6, 0.45),
        ]),
        case("maison", [perso("gainde", 0.02, 90, "danse"), perso("doudou", 0.35, 90, "danse2"), perso("awa", 0.68, 90)], [
            bulle("It's six o'clock! Happy birthday, Awa!",
                  "Il est six heures ! Joyeux anniversaire, Awa ! (le jour d'après, il revient… avec Doudou et son tama)", 0.02, 0.04),
            bulle("Gaïndé! It's the sixth of March!", "Gaïndé ! On est le 6 mars !", 0.55, 0.4),
        ]),
    ], ["When is your birthday?", "It's on the fifth of May.", "What time is it?", "It's six o'clock!", "I get up at six!"]),

    episode("Gaïndé, roi de la mode", "6e-u4-m6", [
        case("maison", [perso("modou", 0.05, 95), perso("gainde", 0.6, 95)], [
            bulle("I like my blue shirt. I don't like my red cap.",
                  "J'aime ma chemise bleue. Je n'aime pas ma casquette rouge.", 0.03, 0.04),
            bulle("I like caps!", "Moi, j'aime les casquettes !", 0.6, 0.4),
        ]),
        case("maison", [perso("gainde", 0.05, 95, "danse"), perso("awa", 0.6, 95)], [
            bulle("Look! I'm wearing trousers!",
                  "Regarde ! Je porte un pantalon ! (le pantalon est sur sa tête, la casquette sur sa queue)", 0.03, 0.04),
            bulle("Gaïndé! The trousers… on your head?!", "Gaïndé ! Le pantalon… sur ta tête ?!", 0.5, 0.4),
        ]),
        case("maison", [perso("modou", 0.05, 95), perso("gainde", 0.6, 95, "saute")], [
            bulle("And my shoes?!", "Et mes chaussures ?!", 0.03, 0.04),
            bulle("I'm wearing your shoes… on my ears!", "Je porte tes chaussures… sur mes oreilles !", 0.45, 0.4),
        ]),
        case("cour", [perso("kocc", 0.05, 95), perso("gainde", 0.55, 100, "danse")], [
            bulle("Gaïndé! My boubou!", "Gaïndé ! Mon boubou ! (Kocc Barma est enroulé dans un pagne)", 0.03, 0.04),
            bulle("I don't like trousers. I like boubous!",
                  "Je n'aime pas les pantalons. J'aime les boubous ! (il porte le boubou violet de Kocc Barma, beaucoup trop grand)", 0.4, 0.4),
        ]),
    ], ["I like…", "I don't like…", "I'm wearing trousers!", "shoes", "cap", "boubou"]),
]
